### ISSUE TITLE
Can we reuse the JDT

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#1]
There has been recent advances in tweaking the JDT framework so that extensions for java-like languages are easier to make.

see

     http://bugs.eclipse.org/36939 

     http://contraptionsforprogramming.blogspot.com/2009/02/jdt-wont-do-that.html (and follow up posts) 

     http://www.cs.pdx.edu/~pq/papers/pq-emh-ab-eTX-2004-FINAL.pdf 

     http://www.slideshare.net/guest9ff00/aspects-every-where?type=powerpoint 

potentially, this could provide full integration into existing views and with features as auto completion.

This is probably very difficult, could be a topic of a masters thesis.

**Comment by tthuem** [comment]
Interesting, but there are many topics with more interesting scientific contributions.
