### ISSUE TITLE
FeatureIDE views seem to perform calculations even if invisible

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#100]
Statistics, collaboration diagram, outline, and feature model edits should only be updated when they are visible. I noticed several jobs of invisble views during changes of source code.

**Comment by tthuem** [comment]
Seems to be related to #70.

**Comment by Kogoro** [comment]
In my tests with the latest nightly build, the views got only updated by changing the model.xml and when they are open (not necessarily in focus). You can see them in the progress tab then. When editing source code, only the workspace is rebuild.

**Comment by tthuem** [comment]
Done by Team 2.
