### ISSUE TITLE
Different calculations-Tag in Written XML Model

### ISSUE THREAD

**Issue by coemgen1992** [FeatureIDE/FeatureIDE#1001]
#### Prerequisitives
* **Eclipse Version:**  `4.14.0.I20191210-0610`
* **FeatureIDE-Version:**  `3.6.2 FeatureIDE Library`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `13.0.2`
* **FeatureIDE Composer:** `Library used`
* **Git branch/Commit-ID:**  `release3.6`
* **Java compiler used to build the FeatureIDE plugin:** `OpenJDK 1.8.0_242`

### Issue description
I build the FeatureIDE Library (version 3.6.2) to read and write XML feature models. I use the FeatureModelManager class, which provides the needed functionality.

In my first tries, I read and wrote the same model. I used a provided example XML model (enclosed in the attached .zip) with an older version of the XML Tags. 

After reading the model, I wrote it again to the hard drive, and there were some differences in the resulting XML compared to the original one. Besides some problems caused by the older XML version, the calculations-Tag is not read and written correctly.

In the attached .zip, I provide you with the classes I wrote for reading and writing the XML file, the model I used, and a document showing the differences between the original and the created version of the XML.

[Read_Write_Issue.zip](https://github.com/FeatureIDE/FeatureIDE/files/4449224/Read_Write_Issue.zip)

**Comment by Subaro** [comment]
@coemgen1992 Hi, I just looked into your code. The changed model is actually correct. 

First, the feature `GPL`  that was changed from group type `Alternative` to `And` has only one child. Group types only work for features with at least two children. For consistency, we change the group type of all features with less than two children into `And` group.

Second, we recently changed the handling of calculation properties for the feature model. We introduced default values and therefore the calculation tag was removed. Instead, the calculation (if the default behavior is not wanted) is stored in the properties of the model as shown in an example below:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<featureModel>
	<properties>
		<calculations key="calculatefeatures" value="true"/>
		<calculations key="calculateconstraints" value="false"/>
		<calculations key="runcalculationsautomatically" value="false"/>
	</properties>
	<struct>
		<and abstract="true" mandatory="true" name="Root">
			<feature name="Base"/>
		</and>
	</struct>
</featureModel>
```
The example above would not execute automatic calculations. But when a calculation is triggered manually only defects for features would be calculated.

Hope I could help :)
