### ISSUE TITLE
SXFMFormat bug with group cardinality

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#1009]
#### Prerequisitives
* **Eclipse Version:**  2020-03
* **FeatureIDE-Version:**  3.6.2
* **Git branch/Commit-ID:**  develop

### Issue description
Imagine that you have this fm in SXFM format. There is a group cardinality where 3 was used instead of *
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<feature_model name="FeatureIDE model">
    <feature_tree>
:r FM(FM)
	:g [1,3]
		: A(A)
		: B(B)
		: C(C)
</feature_tree>
    <constraints>
</constraints>
</feature_model>
```

When you export as FeatureIDE xml format  you obtain the result below. First it will be better if no constraint is created as 3 is the number of features in the group (An OR relation will be better). There is some code about this check in SXFMFormat but it seems to fail. Second, the exported FM is not correct as there is an error saying that in the constraint it appears a new FM_1 that does not exist.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<featureModel>
	<struct>
		<and mandatory="true" name="FM">
			<feature name="A"/>
			<feature name="B"/>
			<feature name="C"/>
		</and>
	</struct>
	<constraints>
		<rule>
			<conj>
				<disj>
					<not>
						<var>FM_1</var>
					</not>
					<var>A</var>
					<var>B</var>
					<var>C</var>
				</disj>
			</conj>
		</rule>
	</constraints>
</featureModel>
```

**Comment by jabiercoding** [comment]
This code in the SXFMFormat in (line 602) method handleArbitrayCardinality can do it to fix this case
```
if ((start == 1) && (end == f)) {
     feat.getStructure().setOr();
} else {
```
however any other cardinality seems to fail with this non-existent feature in the constraint. It will be nice to fix it or at least to throw a UnsupportedModelException until fixed.

Also notice the code in the method buildFeatureTree and the use of Character
```
} else if ((lineText.contains("[")) && (lineText.contains("]"))) {
	final int index = lineText.indexOf('[');
	final int start = Character.getNumericValue(lineText.charAt(index + 1));
	final int end = Character.getNumericValue(lineText.charAt(index + 3));
```
This means that it will work only when start and end numbers have just one digit. For example [1,20], with the current code, will get start 1 but end 2 instead of 20

**Comment by tthuem** [comment]
Thanks for your report, we will have a look soon.

**Comment by Subaro** [comment]
Fixed both problems, PR is #1058

**Comment by jabiercoding** [comment]
By looking at the changes in the code in commit f1b3ad6, I am not sure but maybe something like [2,*]   will go through Integer.parseInt and it will get a NumberFormatException.

**Comment by Subaro** [comment]
Thanks, I will take a look at it again

**Comment by Subaro** [comment]
@jabiercoding Hi, I just pushed another fix that should fix the remaining problems. I identified that our transformation of the group cardinalities into propositional logic used some old local code. That code was removed and replaced by our modern transformation. I also added more cases for cardinalities. I think I tested all cases and they seem to work as expected. If you encounter any further problem please feel free to write them.

**Comment by jabiercoding** [comment]
I tried the initial example with [1,3] [1,*] [2,3] and [2,*] and it works 👍

**Comment by tthuem** [comment]
@jabiercoding Thanks for your feedback!
