### ISSUE TITLE
Storing feature models slow if there are several configurations

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#1011]
For a project with about 50 configurations, storing the feature model becomes too slow to work with FeatureIDE. This problem has been experienced with v3.6.2 and was not an issue with v3.5.5.

**Comment by SundermannC** [comment]
#1036 vastly improves the performance when working with feature project that contain a high number of configurations. Seems to be at least as fast as v3.5.5 now.
