### ISSUE TITLE
The columns of the attributes view are too narrow

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#1013]
Right now, columns such as value are to small to read the text. While users can adapt the width of columns, the width restores once Eclipse is restarted. Either we should have a good default behavior or restore the width settings of the user on restarts.

**Comment by Subaro** [comment]
Our normal behavior should always set the width of the cells to the value required to see all text. I will look into it right away.

**Comment by Subaro** [comment]
Introduce the following behavior:

Initial situation (feature Sandwich selected):
![grafik](https://user-images.githubusercontent.com/6231523/82206975-aa9dc880-98f8-11ea-920d-706641c3dc5e.png)

Changing the value of the `StringAttribute0` to `AAAAAAAAAAAA AAAAAAAAAAAA`:
![grafik](https://user-images.githubusercontent.com/6231523/82207075-c7d29700-98f8-11ea-848d-fafa5ab97135.png)

Selecting feature Cheese:
![grafik](https://user-images.githubusercontent.com/6231523/82207115-d751e000-98f8-11ea-94f2-c08c89729076.png)

Selecting feature Sandwich again:
![grafik](https://user-images.githubusercontent.com/6231523/82207153-e9338300-98f8-11ea-9dfd-a4b4396633b9.png)

**Comment by Subaro** [comment]
Fix (pull request) awaits review #1029

**Comment by f105** [comment]
Thank you, Subaro, this is much better now. However, I often enter long strings as values (up to 200 characters). If this attribute is the only (or first) attribute of a feature, the input field is still very narrow.

![image](https://user-images.githubusercontent.com/64901027/88556335-6e819500-d018-11ea-9c5b-4f13ff77564a.png)

![image](https://user-images.githubusercontent.com/64901027/88555956-f915c480-d017-11ea-9900-1e3ce7386865.png)

A longer initial width of the value column, which makes better use of the width of the feature attributes view, would be helpful.
Or even better (but maybe difficult?): Let the column grow wider during the typing.

**Comment by Subaro** [comment]
Thank you very much for your feedback.

I think a higher initial size for the column should not be a problem. Growing the column is not impossible but would require a hacky approach as eclipse does not support this behavior out of the box. So I think we go with the first idea.

**Comment by Subaro** [comment]
Increased the size of the attribute value column.
