### ISSUE TITLE
Horizontal layout incorrectly displays or and alternative features

### ISSUE THREAD

**Issue by szschaler** [FeatureIDE/FeatureIDE#1015]
#### Prerequisitives
* **Eclipse Version:**  `Version: 2019-06 (4.12.0), Build id: 20190614-1200`
* **FeatureIDE-Version:**  ` 3.3.2.201709130400`
* **Operating system:** `Win10`
* **Java runtime used to run eclipse:** `openjdk 13.0.1 2019-10-15; OpenJDK Runtime Environment (build 13.0.1+9); OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)`

### Issue description
In horizontal layout, the arcs for or and alternative features is so small that it is essentially not visible. As a result, it is impossible to recognise those features. I believe this is related to Issue #187, which seems to already provide a first idea for a fix, too.

**Comment by Subaro** [comment]
It is possible to change the size of the arcs. Will be further discussed in our meeting.

### Horizontal (Central) Layout:

(Option A)<img width="227" alt="25_h" src="https://user-images.githubusercontent.com/6231523/81502958-99d5cd00-92d0-11ea-966c-94ee1f190c61.png">( Option B)<img width="227" alt="30_h" src="https://user-images.githubusercontent.com/6231523/81502960-9cd0bd80-92d0-11ea-8f0e-fe248b52c7a4.png">

------------------

(Option C)<img width="227" alt="35_h" src="https://user-images.githubusercontent.com/6231523/81502963-9e9a8100-92d0-11ea-8573-17a678fceafe.png">(Option D)<img width="227" alt="40_h" src="https://user-images.githubusercontent.com/6231523/81502966-a0644480-92d0-11ea-870f-538d3d694fbd.png">

--------------------------------

### Vertical (Left-To-Right):
( Option A)
<img width="285" alt="25_v" src="https://user-images.githubusercontent.com/6231523/81503031-f3d69280-92d0-11ea-8972-f00f5b38f799.png">

----------------------------------------------------------------------------------------------

( Option B)
<img width="283" alt="30_v" src="https://user-images.githubusercontent.com/6231523/81503032-f638ec80-92d0-11ea-865b-fa9e9143ce5d.png">

----------------------------------------------------------------------------------------------

( Option C)
<img width="277" alt="35_v" src="https://user-images.githubusercontent.com/6231523/81503094-4a43d100-92d1-11ea-9c61-d196e4f0a204.png">

----------------------------------------------------------------------------------------------

( Option D)
<img width="276" alt="40_v" src="https://user-images.githubusercontent.com/6231523/81503098-4c0d9480-92d1-11ea-815c-9b30281178db.png">

**Comment by szschaler** [comment]
Thanks. It seems that this is indeed fixed in the latest release. I had originally installed FeatureIDE from the nightly build update site, which is, confusingly, stuck in the 2017s... Once I updated to a more recent version via the Marketplace, the diagrams look much better.

**Comment by Subaro** [comment]
Is closed because it was already fixed
