### ISSUE TITLE
Team Project Summer 2020 in Ulm

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#1016]
Create wiki, unit and GUI tests (with standard and extended feature models), and screencast for all new functionality (iteratively if possible).

Part 1
* Change default with of columns in constraints view to show long descriptions (cf. https://github.com/FeatureIDE/FeatureIDE/issues/887)
* Enable sorting of constraints in constraints view (cf. https://github.com/FeatureIDE/FeatureIDE/issues/886)

Part 2
* Add a fold-able menu for creation of features and constraints
* Add button to expand sub-tree to a certain level as single-selection action (cf. https://github.com/FeatureIDE/FeatureIDE/issues/851)

Part 3
* Add a button to delete selected features by means of slicing (cf. https://github.com/FeatureIDE/FeatureIDE/issues/984 and https://github.com/FeatureIDE/FeatureIDE/issues/200)
* Add a button to select features based on search criteria (cf. https://github.com/FeatureIDE/FeatureIDE/issues/984)

**Comment by h3ssto** [comment]
All mentioned issues have been resolved.

**Comment by tthuem** [comment]
The source code during this team project has been created in the following fork: https://github.com/sjvie/FeatureIDE
