### ISSUE TITLE
Warning disappearing from feature after rename

### ISSUE THREAD

**Issue by sjvie** [FeatureIDE/FeatureIDE#1028]
#### Prerequisitives
* **Eclipse Version:**  4.13
* **Git branch/Commit-ID:** develop / 8f048b58ec9654d277f8016d5159ec849d59158c

### Issue description
When a feature is renamed, possible warnings (tested with "false-optional feature") disappear.
The warnings don't seem to appear again until the model is reopened or the constraints causing the warning are readded.

![image](https://user-images.githubusercontent.com/35612644/82043792-7cc44400-96ac-11ea-98fc-fc99ed729b99.png)

![image](https://user-images.githubusercontent.com/35612644/82043754-6fa75500-96ac-11ea-900a-fe9c4d43713c.png)

This also happens, when adding a new feature:
![image](https://user-images.githubusercontent.com/35612644/82043963-c4e36680-96ac-11ea-9d8d-fb3503e34554.png)

**Comment by h3ssto** [comment]
Possibly linked to work on #695 @Subaro ?

**Comment by Subaro** [comment]
Analysis results are cached and I think not recomputed when renaming a component. Therefore, the cached results for the renamed features need to be changed accordingly. Then the icon should be persistent.

**Comment by h3ssto** [comment]
Resolution (from 25.05.2020): Start a new analysis on feature rename.

**Comment by tthuem** [comment]
@sjvie Please note that this could be fixed based on the release branch.

**Comment by Raixxor** [comment]
This problem is easily fixable with the suggested solution of just re-analyzing after renaming, however, the bug found in #1027 then always creates a popup and becomes more apparent. #1027 should be solved before solving #1028.

**Comment by Subaro** [comment]
Issue #1027 is now fixed. The fix is pending: #1073

**Comment by tthuem** [comment]
Seems to be fixed and merged.
