### ISSUE TITLE
Constraints disappearing when selecting anything but a feature

### ISSUE THREAD

**Issue by Raixxor** [FeatureIDE/FeatureIDE#1037]
#### Prerequisitives
* **Eclipse Version:**  4.13
* **Git branch/Commit-ID:** release3.6 / ca634bc78ad35eb62f8ee7dc8a6586d4e1fbf01b

### Issue description
If a connection between features or the legend of the Feature Model in the Feature Model editor is clicked/selected all Constraints from the Constraint View are hidden. 
Clicking on anything other than features should not change what is shown in the Constraint View.

**Comment by tthuem** [comment]
Indeed, if no feature is in the selection, all constraints should be shown.
