### ISSUE TITLE
Constraint View combination of search and Feature selection not working

### ISSUE THREAD

**Issue by Raixxor** [FeatureIDE/FeatureIDE#1038]
#### Prerequisitives
* **Eclipse Version:**  4.13
* **Git branch/Commit-ID:** release3.6 / ca634bc78ad35eb62f8ee7dc8a6586d4e1fbf01b

### Issue description
If Features in the Feature Model editor are selected only the constraints that are relevant are shown. If I also search in the search box of the Constraint View while having Features selected the search checks all constraints and not only in the selected ones. 

See in the example. There are no constraints involving RushHour, but if RushHour is selected and something is searched the Constraint View displays any Constraints matching the search. 
Intended behaviour should be that the search only filters through selected Features. 

![image](https://user-images.githubusercontent.com/25290815/82806515-3a59ee80-9e86-11ea-86b7-f03e364dbb5c.png)

![image](https://user-images.githubusercontent.com/25290815/82806541-4ba2fb00-9e86-11ea-8aad-c4bbe5e2793e.png)

**Comment by tthuem** [comment]
If I remember correctly from the past team project, this behavior was on purpose. The search should always work on all constraints.

**Comment by Raixxor** [comment]
The behavior will be changed so that you can search through all constraints by not selecting a feature and then typing in the searchbar or you can search through already selected features to search only in the already selected features. 

So the example in the original post wouldn't show the constraint in the view anymore.
