### ISSUE TITLE
Product Generator not Working for FeatureHouse Examples

### ISSUE THREAD

**Issue by cleberoli** [FeatureIDE/FeatureIDE#1046]
#### Prerequisitives
* **Eclipse Version:**  `2019-12 (4.14.0)`
* **FeatureIDE-Version:**  `3.6.2`
* **Operating system:** `Windows 10 Pro`
* **Java runtime used to run eclipse:** `openjdk 13.0.1`
* **FeatureIDE Composer:** `Feature House`
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
When using the product generator option the folders generated contain only the configuration file, but none of the source code as generated when using the "set as current configuration" option.
The issue happens with both .xml and .config files as configurations, as shown in the image.

![image](https://user-images.githubusercontent.com/4074429/83170328-bfddd880-a0ea-11ea-8ed8-490c4d00060e.png)

**Comment by tthuem** [comment]
@PaulWestphal Could you please try to reproduce this with the most recent release and when this was introduced? Does this also affect other composers?

**Comment by tthuem** [comment]
@cleberoli reported to me that this was still working in v3.5.5. Still, we need to find out when this bug was introduced.

**Comment by PaulWestphal** [comment]
This bug was introduced in 3.6.0. It also affects most other composers, only preprocessor-based composers still seem to work.

**Comment by Subaro** [comment]
Fixed, PR is #1056
