### ISSUE TITLE
Configuration editor doesn't propagate selections after constraints view is closed

### ISSUE THREAD

**Issue by f105** [FeatureIDE/FeatureIDE#1049]
#### Prerequisitives
* **Eclipse Version:**  4.13 2019-09
* **FeatureIDE-Version:**  3.6.2
* **Operating system:** Windows 7 Enterprise
* **Java runtime used to run eclipse:** 1.8

### Issue description
After having closed the constraints view, the configuration editor does not propagate selections. Instead of adapting their states to the selection, checkboxes remain in the state they are.

### Steps to reproduce

1. Start FeatureIDE, launch a project. Constraints view is automatically open.
2. Create a configuration file (if not already open).
3. Close the constraints view.
4. Select a feature in the configuration editor.

**Result:** The checkbox of the selected feature is checked, but all other checkboxes remain unchanged.

**Expected Result:** The checkbox of the selected feature is checked, and this selection is propagated to all other checkboxes according to the constraints of the feature model.
 
![FIDE-Issue_AlternativeFeaturesRemainSelectableAfterOneHasBeenSelected](https://user-images.githubusercontent.com/64901027/83421619-eae06900-a417-11ea-85a2-c6b9d778603b.PNG)

**Comment by tthuem** [comment]
I tried to reproduce this with the example Elevator-Antenna-v1.4 but failed to do so.

The screenshot indicates that the feature model is not saved yet. If it is unsaved, the configuration editor will still use the last saved version. However, propagation of selections should still work (based on the old feature model version). Did the old feature model not contain the respective constraints leading to a propagation?

Other than that, we probably need more details on what has been changed in the feature diagram. Have constraints been added or removed? Is the failure reproducible with FeatureIDE example projects?

**Comment by f105** [comment]
Dear Thomas,
if you failed to reproduce, could it be another Windows problem?
In response to your 3 questions, my answer is no to all.
I took exactly the four steps that I have described.
Please watch the video in "fide.zip":
[fide.zip](https://github.com/FeatureIDE/FeatureIDE/files/4731309/fide.zip)
[model.zip](https://github.com/FeatureIDE/FeatureIDE/files/4731241/model.zip)

Thank you,
Claudia

**Comment by PaulWestphal** [comment]
I can reproduce the issue with the feature model that you provided and I'll try to fix it.

**Comment by PaulWestphal** [comment]
fixed 57b3938b337ab1254b902b1515f38a9a402d01b3
