### ISSUE TITLE
Add References to Example Projects

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#1054]
Researchers frequently use FeatureIDE examples in their evaluations. It is hard for them to find the original publication for each example. We should add READMEs to all examples that contain links to a citable reference. This also helps them to understand the origin of examples, as publications often have at least a brief discussion on the domain, applied translations, and whether they are of academic or industrial nature.

**Comment by tthuem** [comment]
In addition, we could also add a list of references that use a feature model as a benchmark.

**Comment by Subaro** [comment]
This work contains some of the smaller examples: https://www.se.cs.uni-saarland.de/theses/PeterLutzMA.pdf

**Comment by Subaro** [comment]
| Author         | Publication                                                                    | Examples Covered |
|----------------|--------------------------------------------------------------------------------|------------------|
| Sofia Ananieva | Explaining Defects and Identifying Dependencies in Interrelated Feature Models | SortingLine, PPU |

**Comment by skrieter** [comment]
Also add original feature model (e.g. dimacs files)

**Comment by tthuem** [comment]
Tobias starts, then Chico and Thomas will extend the data.
