### ISSUE TITLE
Missing visual indicator for unselectable features in the Configuration Editor on Ubuntu/Linux

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#1055]
#### Prerequisitives
* **Eclipse Version:**  `4.12`
* **FeatureIDE-Version:**  `release3.6 branch`
* **Operating system:** `Ubuntu 19.04`

### Issue description
In ubuntu, there is no visual indicator for unselectable features in the configuration editor.

In the following screenshot Alt1, Alt2, and Alt3 are part of an alternative group. As Alt1 is selected, Alt2 and Alt3 are unselectable. Thus, there should be a visual indicator (grayed out). Such an indicator is completely missing for Ubuntu. It is impossible to tell whether a feature is selectable.
![Screenshot from 2020-06-15 11-20-05](https://user-images.githubusercontent.com/24757266/84640717-5c311900-aefa-11ea-830e-22d2b87ead11.png)

EDIT:
Here is an example of a group that has two selectable features Opt1 and Opt2 and unselectable one Dead for better comparison.
![Screenshot from 2020-06-15 12-05-41](https://user-images.githubusercontent.com/24757266/84645379-c2b93580-af00-11ea-87eb-34a717bb6ce4.png)

**Comment by tthuem** [comment]
Could you please add a screenshot that also shows an unselected feature that can be selected?

**Comment by SundermannC** [comment]
That is a good point. I edited the original comment.

**Comment by tthuem** [comment]
Amazing. Not sure whether we should blame Ubuntu or Eclipse for that. Also not sure either whether we should provide a workaround for that or not. Changing the color of the feature name could work. We are already using blue and green, but probably only if features are selectable. Hence, we could use gray in this case. Let's discuss this in more detail in out jour fix.

**Comment by tthuem** [comment]
Page 67 in the FeatureIDE book already had an overview on selection states implying that this state is actually not highlighted in several operating systems:

![image](https://user-images.githubusercontent.com/5330357/84669524-3d944780-af25-11ea-990c-756e9002bdb6.png)

**Comment by ekuiter** [comment]
I can reproduce the bug on Ubuntu 20.04. Actually, the problem applies to all coloring of feature text entries - not only gray entries, also the supposedly green and blue ones (Ubuntu on the left, Windows on the right):

![grafik](https://user-images.githubusercontent.com/4258713/108409189-2d580900-7226-11eb-9408-eaf42efe7836.png)

**Comment by tthuem** [comment]
Thanks for checking. At least the highlighting with bold font does work. Maybe we could use italic font for grayed out entries then?

**Comment by ekuiter** [comment]
That would look like this:

![grafik](https://user-images.githubusercontent.com/4258713/109488970-87f32f80-7a86-11eb-80b3-3f3fbc44b2a2.png)

**Comment by tthuem** [comment]
Looks like a good workaround and should not harm usability on other operating systems. Would be good to link to that report in the code to make clear that we deal with dependencies to operating systems here.
