### ISSUE TITLE
Update ConstraintView documentation

### ISSUE THREAD

**Issue by h3ssto** [FeatureIDE/FeatureIDE#1059]
#1021 #1022 #1023 #1024 #1025 #874 #886 #887 #1037 #1038 #1039 have been fixed by the *Team Project Ulm 2020a*.
The constraint view is lacking documentation in the wiki.

Based on the existing screen cast and the changes made to fix the issues above, describe the functionality of the constraint view in a wiki page.

Wiki page: https://github.com/FeatureIDE/FeatureIDE/wiki/Constraint-View

A good orientation for such a documentation can be found for the collaboration diagram: https://github.com/FeatureIDE/FeatureIDE/wiki/Collaboration-Diagram

**Comment by tthuem** [comment]
To avoid redundant effort, it would be good if you do not yet start with this task. We are still in the process of finding the documentation of a previous team project.

**Comment by h3ssto** [comment]
Done, but forgot to close.
