### ISSUE TITLE
Product generator generates invalid and duplicate configurations.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#1066]
This bug was first reported by @Enxhi04 here:

https://stackoverflow.com/questions/61524828/product-genaration-in-featureide-does-not-generate-correct-combination-of-featur

The product generator generates the correct number of configurations, but if you look at them, they're invalid and duplicates. This bug occurs on both release3.6 and develop. 

I've re-created the project from the stackoverflow bug description and uploaded it here:

[Project_Product_Generator.zip](https://github.com/FeatureIDE/FeatureIDE/files/4878724/Project_Product_Generator.zip)

**Comment by PaulWestphal** [comment]
This was fixed by @skrieter e1c745c85e98128c2cbdcd7a3f0d0953f0fc2cd7

**Comment by antoniogarmendia** [comment]
Hello,

I would like to test this version because I get some duplicates configurations. I am using Eclipse, so I have checked the update site and it is not available. How can I test this version?

Thanks.

Kind regards,
Antonio G.

**Comment by PaulWestphal** [comment]
Hello,

this bugfix will be included in the next release.

You can also compile our most recent branch with the bugfix (https://github.com/FeatureIDE/FeatureIDE/commits/develop) yourself. How to get the source code and set up the run configuration correctly is outlined in this wiki article: 

https://github.com/FeatureIDE/FeatureIDE/wiki/Preparing-Eclipse

**Comment by antoniogarmendia** [comment]
Hello,

Thanks. I will try to build it from source code.

Kind regards,
Antonio G.
