### ISSUE TITLE
ConstraintView not updated after deletion of Constraints

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#1070]
#### Prerequisitives
* **Eclipse Version:**  `Its the published 363 repo version`
* **FeatureIDE-Version:**  `363`
* **Operating system:** `Windows 7 64`
* **Java runtime used to run eclipse:** `Build 1.8.0_161-b12`

### Issue description

1. Select a feature in the feature model editor.
2. Select two or more constraints in the Constraints View and right click => delete

**Expected Behaviour:** If deletion succeeds, UI interface feedbacks success with the constraint view updating (constraints disappearing).

**Acutal Behaviour:** After deletion no feedback is given and constraint view is not updated. In case of an error, feedback is given though.

When I edit constraints, the constraints view is updated immediately.

Hope this helps!

**Comment by h3ssto** [comment]
Issue has been fixed by the refactor merged from #1087 and can no longer be reproduced in v3.7.0 (993933c61c4d660aef9fd6f5ffa20900b5171c88).
