### ISSUE TITLE
Issues with the new universal variability language (UVL)

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#1076]
This issue encompasses multiple bugs for the currently implementation of the universal variability language (uvl) on the `masterthesis-Dominik` branch. These issues should be resolved before merging the branch into the current develop branch of FeatureIDE.

# Overview
- [x] [1]  Legend shows invalid entries, Fixed by 894ccf835babf2a34fad0e7693f87acd2f3266ac
- [x] [2] Parser does not report invalid entries in the UVL models
- [x] [3] Create feature above is not greyed out for imported subtrees, Fixed by cd5420a57dd62b285f40805ca426e242ad5743c1
- [x] [4] Right-Clicking a features does not refresh the context menu

For the description of each individual issues see below.

**Comment by Subaro** [comment]
### Issue: [1] Legend shows invalid entries

When having no visible features that are from an interface, inherited or imported the legend still shows them:
![image](https://user-images.githubusercontent.com/6231523/91662438-b8134300-eae2-11ea-893f-d3865e3edd0d.png)

Fix (894ccf835babf2a34fad0e7693f87acd2f3266ac) : I introduced specific filters that we already use for several other cases in the legend. They use only the graphically visible features and input and determine the legend entries for inherited, interfaced, and imported feature correctly.

**Comment by Subaro** [comment]
### Issue:  [2] Parser does not report invalid entries in the UVL models

The source tab should report any semantic faults in the format. The source tab editor behaves completely wrong when renaming elements of a UVL-Model. For example in the following UVL-Model we change the line 

```
OperatingSystem as os
```

into 

```
OperatingSystem as oss
```

 This results in the following UVL-Model:
```
namespace Server

imports
	OperatingSystem as oss
	submodels.FileSystem as fs

features
	Server {abstract}	
		mandatory
			fs.FileSystem
			os.OperatingSystem

		optional
			Logging

constraints
	os.Windows => fs.NTFS
	os.macOS => fs.APFS
	os.Debian => fs.EXT4
```
The source tab editor should report that the prefix `os` does not exist. I would expect that the source tab marks all invalid lines with a marker and prevents the user to switch to the feature diagram. Contrary to our expectation, no markers are created and the user can freely switch to the feature diagram. After switching to the feature diagram it seems that the constraints are not longer existent but the imported OperatingSystem is mandatory.

**Comment by Subaro** [comment]
### Issue: [3] Create feature above is not greyed out for imported subtrees

When selecting feature from imported or interfaced subtrees it is still possible to add features to the parents (CreateFeatureAbove).

![image](https://user-images.githubusercontent.com/6231523/91663035-a2078180-eae6-11ea-9ea4-61934c2a1429.png)

**Comment by Subaro** [comment]
### Issue: [4] Right-Clicking a features does not refresh the context menu

When right-clicking multiple features to perform action the context menu does not refresh leading to invalid action for "read-only" subtrees. 

For example, we open the UVL server example and right-click the feature `Logging`:

![image](https://user-images.githubusercontent.com/6231523/91663135-4093e280-eae7-11ea-8fea-a5a42a45b6cb.png)

Now, right-clicking a feature (without selecting the feature with a left-click beforehand)  from an interface should make most action of the context menu unavailable. However, the context menu does not change:
![image](https://user-images.githubusercontent.com/6231523/91663182-96688a80-eae7-11ea-88b5-4652560c3ca0.png)

When the feature from the interface is selected via left-click before right-clicking, then the correct context menu is shown:
![image](https://user-images.githubusercontent.com/6231523/91663213-cca60a00-eae7-11ea-9452-a9c3cb233a2b.png)

**Comment by h3ssto** [comment]
@SundermannC @johannesherschel Please let me know if subtask 2 is completed or if the issue needs to be reopened.

**Comment by johannesherschel** [comment]
As far as I can tell, this issue can be closed.
There are still some edge cases related to task 2, but these are covered by #1159. Also, the errors reported by the source tab do not appear at the correct source location, but this is because the UVL parser does not provide the necessary location information, and thus (as far as I can tell) requires changes to the parser in order to be improved. Perhaps this should be added as another issue.
