### ISSUE TITLE
Redo of "Create Feature Above" not working correctly

### ISSUE THREAD

**Issue by Raixxor** [FeatureIDE/FeatureIDE#1080]
#### Prerequisitives
* **Eclipse Version:**  4.13
* **Git branch/Commit-ID:** develop / a114479dc69f3f76209966d50b2175a42a2532f8

In the Feature Diagram Editor after adding a Feature with "Create Feature Above" on any Feature and then "undoing" that, the following "redo" will add the Feature above the currently selected Feature and not the in the correct location. 
Works as intended without a selection. This bug does not occur with "Create Feature Below" or "Create Sibling Feature".

**Comment by tthuem** [comment]
Thanks for the report. Could you check whether this issue is also evident on release3.6?

**Comment by PaulWestphal** [comment]
Yes, this issue was also in release3.6.
