### ISSUE TITLE
No error messages and no dirty flag for invalid configurations.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#1082]
When a configuration with invalid features (for example, if a configuration contains features that are not in the corresponding feature model) is opened in the configuration editor, there's not always a dirty flag or an error message. The mode to help you fix the configuration may not be activated.

**Comment by tthuem** [comment]
Even worse, the problem marker is also missing indicating that the configuration is invalid and when opening the editor it says "valid" while fixing the problem without any notification.
