### ISSUE TITLE
Exception upon Deleting FeatureModel Root

### ISSUE THREAD

**Issue by Raixxor** [FeatureIDE/FeatureIDE#1083]
#### Prerequisitives
* **Eclipse Version:**  4.13
* **Git branch/Commit-ID:** release3.6 / 993824d28bd1252165753485654ae81773d43502

When deleting the root of a FeatureModel multiple exceptions are thrown. 

What happens is that all branches below the root except for one are deleted. 
If there is a constraint in any of the now disappeared branches the exceptions are thrown. However, if there are only constraints in the branch that remains, no exceptions are thrown.

**Comment by tthuem** [comment]
@h3ssto Isn't this fixed?

**Comment by h3ssto** [comment]
I could not reproduce this bug with v3.6.4.

**Comment by h3ssto** [comment]
The issue is fixed by #1087.
