### ISSUE TITLE
Cannot open .jak files with Eclipse 2020-09 

### ISSUE THREAD

**Issue by boehmseb** [FeatureIDE/FeatureIDE#1085]
#### Prerequisitives
* **Eclipse Version:**  `2020-09 (4.17.0)`
* **FeatureIDE-Version:**  `3.6.3`
* **Operating system:** `Debian 10`
* **Java runtime used to run eclipse:** `openjdk 11.0.8`
* **FeatureIDE Composer:** `AHEAD`

### Issue description
When I try to open any `.jak` file, eclipse shows me the following error message:
`Plug-in de.ovgu.featureide.ui was unable to load class de.ovgu.featureide.ui.editors.JavaEditor.`
You can find the full stacktrace in this gist: [https://gist.github.com/boehmseb/e5ebbe70b217384dff37fddffe692318](https://gist.github.com/boehmseb/e5ebbe70b217384dff37fddffe692318)

**Comment by tthuem** [comment]
Thanks for the report. We'll have a look at it.

In the meantime, support for FeatureHouse is significantly better and you might want to use it instead of AHEAD for feature-oriented programming, if feasible.

**Comment by h3ssto** [comment]
Same as https://github.com/FeatureIDE/FeatureIDE/issues/1048

**Comment by h3ssto** [comment]
Closing this issue as its duplicate #1048 was fixed by #1096.
