### ISSUE TITLE
Opening large feature models slowed down by configuration map and constraints view

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#1093]
#### Prerequisitives
* **Eclipse Version:** 2019-03
* **FeatureIDE-Version:**  3.7
* **Operating system:** Windows 10

### Issue description
Closed all FeatureIDE views and all eclipse views (excluding the Package explorer), restarted Eclipse, and opened the following Linux example (not sure why there are two). I measured the time to display the feature model under different settings. Did not experience large warmup effects (i.e., opening it the second time takes about the same amount of time).

![image](https://user-images.githubusercontent.com/5330357/95967918-1f742080-0e0d-11eb-8e4c-db71b2ca3574.png)

8-10s
* without any view open
* with the Eclipse Outline
* with the Collaboration Diagram
* with Feature Model Edits (deactivated calculations)
* with FeatureIDE Outline (why is it empty? bug?)
* with FeatureIDE Statistics (nothing unfolded in view, default)

13-15s
* with the Configuration Map (interesting, as not even a single configuration exists in that example project)

more than 5min (could not wait so long)
* with the Feature Model Constraints

Workaround: Close both view when working with large feature models, if possible. (Still annoying that the constraint view is not available then.)

**Comment by PaulWestphal** [comment]
Line 108 of ConstraintViewConstraintColumnLabelProvider is where the Constraint View takes a very long time or stops working with large feature models:

https://github.com/FeatureIDE/FeatureIDE/blob/993933c61c4d660aef9fd6f5ffa20900b5171c88/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/views/constraintview/content/ConstraintViewConstraintColumnLabelProvider.java#L107-L112

 I suppose "getConstraintProperty" is a very expensive operation that should not be called like that?

**Comment by h3ssto** [comment]
> Line 108 of ConstraintViewConstraintColumnLabelProvider is where the Constraint View takes a very long time or stops working with large feature models:
> 
> https://github.com/FeatureIDE/FeatureIDE/blob/993933c61c4d660aef9fd6f5ffa20900b5171c88/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/views/constraintview/content/ConstraintViewConstraintColumnLabelProvider.java#L107-L112
> 
> I suppose "getConstraintProperty" is an expensive operation that should not be called like that?

The problem originates in the getAnalyzer() - call wich creates a new FeatureModelAnalyzer, which then starts analyses for dead and false-optional features and redundantConstraints.

**Comment by h3ssto** [comment]
Constraints View does no longer have a sizable impact on loading time (~5s both with and without CV open). Some other view however slow down the loading significantly:
* Configuration Map +5s
* FeatureIDE Statistics +10-15s
