### ISSUE TITLE
HelloWorld example with runtime variability not working

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#1094]
#### Prerequisitives
* **Eclipse Version:**  2019-03
* **FeatureIDE-Version:**  3.7.0
* **Operating system:** Win10

### Issue description

Loaded the example and the runtime.properties file is empty. Switching the current configuration is not possible and after switching it several times Eclipse freezed.

**Comment by PaulWestphal** [comment]
There is a correct runtime.properties file in the project directory, and another (empty) one in the source folder.

**Comment by PaulWestphal** [comment]
I've fixed the bug where the runtime.properties files is empty. But I've noticed another bug where the PropertyManager.java class may be empty and am currently working on a fix.

branch: [issue_1094](/FeatureIDE/FeatureIDE/tree/issue_1094)
