### ISSUE TITLE
XML Schema

### ISSUE THREAD

**Issue by 89netraM** [FeatureIDE/FeatureIDE#1097]
Can I find a schema for the XML files used to save the model and the configurations somewhere?  
I need to read them in my own program without FeatureIDE.

**Comment by tthuem** [comment]
Thanks for your interest in FeatureIDE and sorry for the late response.

We do have schemas, even though I'm not sure these 3 year old files are completely in sync with the current format: https://github.com/FeatureIDE/FeatureIDE/tree/develop/plugins/de.ovgu.featureide.fm.core/schema

Please let us know, if you find any issues.

**Comment by tthuem** [comment]
In case you are not aware, you might also delegate the parsing and feature model analysis to the FeatureIDE library, a small Java library that does not have dependencies to Eclipse: https://www.isf.cs.tu-bs.de/cms/team/thuem/papers/2017-SPLC-Krieter.pdf

**Comment by 89netraM** [comment]
Wow, all this looks great. Thank you!
