### ISSUE TITLE
FeatureIDE Library Examples for Attributes and Formats

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#1098]
### Issue description
Currently, there are no code examples on how to use different formats and/or feature attributes with the FeatureIDE core library. Two examples should be added that help developers to use both fragments. The examples should show the required setup for projects and the usage of the API.

**Comment by ekuiter** [comment]
In addition, some example on how to sample feature models with the library should be added.

**Comment by skrieter** [comment]
Done in #1335
