### ISSUE TITLE
FeatureIDE Library build error using provided command line build scripts for Ant and Maven 

### ISSUE THREAD

**Issue by coemgen1992** [FeatureIDE/FeatureIDE#1100]
#### Prerequisitives
* **Eclipse Version:**  `not used`
* **FeatureIDE-Version:**  `v3.7.0`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `not used`
* **FeatureIDE Composer:** ``
* **Git branch/Commit-ID:**  `release3.7`
* **Java compiler used to build the FeatureIDE plugin:** `OpenJDK 1.8.0_242`
* **Ant Version used to build the FeatureIDE plugin:** `1.10.5`
* **Maven Version used to build the FeatureIDE plugin:** `3.6.3`

### Issue description
After I cloned the FeatureIDE repository and checked out the `release3.7` branch, I tried to build the FeatureIDE Library using the command line. Therefore, I executed the ant script provided in the `plugins\de.ovgu.featureide.fm.core\library` folder. 

While executing the script I received the following error (same for the maven build):
```
Buildfile: **\git\FeatureIDE3.7\FeatureIDE\plugins\de.ovgu.featureide.fm.core\library\build.xml
build:
external_build:
load-custom-properties:

compile:
    [mkdir] Created dir: **\git\FeatureIDE3.7\FeatureIDE\plugins\de.ovgu.featureide.fm.core\library\bin
    [mkdir] Created dir: **\git\FeatureIDE3.7\FeatureIDE\plugins\de.ovgu.featureide.fm.core\library\jar
    [mkdir] Created dir: **\git\FeatureIDE3.7\FeatureIDE\plugins\de.ovgu.featureide.fm.core\library\jar\lib
     [copy] Copying 10 files to C:\Users\AK117831\git\FeatureIDE3.7\FeatureIDE\plugins\de.ovgu.featureide.fm.core\library\jar\lib
    [javac] Compiling 475 source files to **\git\FeatureIDE3.7\FeatureIDE\plugins\de.ovgu.featureide.fm.core\library\bin
    [javac] error: illegal argument for --class-path: Illegal char <:> at index 4: file:jakarta.jar
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8

BUILD FAILED
**\git\FeatureIDE3.7\FeatureIDE\plugins\de.ovgu.featureide.fm.core\library\build.xml:29: The following error occurred while executing this line:
**\git\FeatureIDE3.7\FeatureIDE\plugins\de.ovgu.featureide.fm.core\library\subant_build_jar.xml:71: Compile failed; see the compiler error output for details.

Total time: 2 seconds
```

Instead of building the library on my own, I used the compiled version from the release, which then worked without a problem. Nevertheless, it is an issue that should be resolved for future versions.

**Comment by tthuem** [comment]
We were able to reproduce this problem on release3.7. However, it works on release3.6.

@skrieter will revert some changes on the build script leading to this problem.

**Comment by tthuem** [comment]
We discussed to remove the experimental version of the Maven script.

**Comment by tthuem** [comment]
@skrieter It works for fm.core now, but it seems that you forgot about the attributes library.

@coemgen1992 As you only need the fm.core library, it should work for you know. Please make sure to use the ANT scripts, as Maven is not supposed to work and will be removed soon.

**Comment by tthuem** [comment]
Ant scripts for both FeatureIDE libraries work again as expected.

**Comment by coemgen1992** [comment]
> @skrieter It works for fm.core now, but it seems that you forgot about the attributes library.
> 
> @coemgen1992 As you only need the fm.core library, it should work for you know. Please make sure to use the ANT scripts, as Maven is not supposed to work and will be removed soon.

Thank you for the fix.
