### ISSUE TITLE
Drawing cross-tree constraints both below the feature model and in the constraint view is counterintuitive

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#1102]
Currently, cross-tree constraints are sometimes shown in the feature model editor ...
![grafik](https://user-images.githubusercontent.com/4258713/108357407-b010a200-71ed-11eb-8196-958b67163a66.png)
... and sometimes in the contraint view ...
![grafik](https://user-images.githubusercontent.com/4258713/108357546-dcc4b980-71ed-11eb-8669-8fcf693b42cb.png)
... depending on whether the contraint view is currently opened and visible.

However, the automatic switching does not always work as intended: For example, when minimizing and restoring the constraint view as follows ...
![grafik](https://user-images.githubusercontent.com/4258713/108360341-5e6a1680-71f1-11eb-9493-31517d8630ab.png)
![grafik](https://user-images.githubusercontent.com/4258713/108360400-76da3100-71f1-11eb-8608-64fd10bb00a2.png)
... the constraints are displayed BOTH in the feature model editor and the constraint view:
![grafik](https://user-images.githubusercontent.com/4258713/108360168-27940080-71f1-11eb-9881-f3ce759cbaf3.png)

Besides such unexpected side effects, we discussed whether this switcheroo is actually desirable/intuitive behavior.

One proposed alternative was to only use the constraint view in the future, and create a menu option (e.g., in the layout menu) for the old "display constraints in the editor" behavior (so that constraints can still be graphically exported if desired).

This would not really be a breaking change, as users are already notified about the new constraint view when they import feature models from old FeatureIDE versions.

**Comment by Rahel12342** [comment]
We discussed this and decided the following: 
Per default, the constraints are displayed beneath the feature model, without regards to the constraints view (i.e., even when the constraints view is opened the constraints will still be displayed beneath the feature model). There will be a toggle that can be activated to not display the constraints under the feature model anymore. In this case, they will not appear beneath the feature model, even though the constraint view is not focussed.
