### ISSUE TITLE
Generating metaproduct for family-based verification does not encode feature model correctly

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#1105]
If I use the FeatureIDE > FeatureHouse > Generate Meta Product menu option, the generated code seems to contain errors in the feature model encoding in the JML contracts.
For example, generating a metaproduct for the example project *IntList-FH-JML*, the following JML specification is generated:
![grafik](https://user-images.githubusercontent.com/4258713/110650780-2126f200-81bb-11eb-80c6-d594159fe6d0.png)
I am pretty sure that this should be (i.e. referencing the FeatureModel class):
```
@ requires (FM.FeatureModel.root) && (FM.FeatureModel.root || !FM.FeatureModel.base) && (FM.FeatureModel.root || !FM.FeatureModel.cons) && 
```
KeY also cannot load this metaproduct:
![grafik](https://user-images.githubusercontent.com/4258713/110651041-5c292580-81bb-11eb-9c53-33a2c3cbd7e3.png)
Am I missing something? If this is a bug, is it due to FeatureIDE or FeatureHouse (or wherever metaproduct generation is implemented?)

**Comment by tthuem** [comment]
Looks like a bug indeed. The missing prefix is most likely handled in the FeatureHouse code.

**Comment by Rahel12342** [comment]
The regex in the replace function (for replacing "feature" with "FM.FeatureModel.feature" when creating the expression) only checks for a " "or a "(" infront of a feature, not for a "!".
