### ISSUE TITLE
FeatureHouse menu throws exceptions

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#1106]
In several example projects, *FeatureIDE > FeatureHouse > Enable Fuji Type Check* throws errors:

![grafik](https://user-images.githubusercontent.com/4258713/110651671-effaf180-81bb-11eb-9514-a49b8c7eafac.png)
![grafik](https://user-images.githubusercontent.com/4258713/110651728-00ab6780-81bc-11eb-9867-640d131673ce.png)

Stack trace:
![grafik](https://user-images.githubusercontent.com/4258713/110654193-36e9e680-81be-11eb-91e4-40ee20e3833d.png)

---

Also, *FeatureIDE > FeatureHouse > Perform Feature-Based Verification with KeY* throws an error:
![grafik](https://user-images.githubusercontent.com/4258713/110651997-3fd9b880-81bc-11eb-8c4e-ed822257a9e8.png)
Why do I need Fuji to run KeY in the first place?

Stack trace:
![grafik](https://user-images.githubusercontent.com/4258713/110653904-f5f1d200-81bd-11eb-8f56-cc59aaa0d8da.png)

---

Finally, *FeatureIDE > FeatureHouse > Change the composer to AHEAD* shows the following:
![grafik](https://user-images.githubusercontent.com/4258713/110652903-140b0280-81bd-11eb-885b-bd3fe1e07aa5.png)
Besides the typos, I think a "Cancel" button should be added, otherwise the user cannot create a copy as advised in the warning.
Also, clicking OK throws another exception:
![grafik](https://user-images.githubusercontent.com/4258713/110652817-0190c900-81bd-11eb-8b52-002e73d6f1be.png)
Stack trace:
![grafik](https://user-images.githubusercontent.com/4258713/110653274-64826000-81bd-11eb-8f95-305b8a9b1ef7.png)

**Comment by tthuem** [comment]
If I remember correctly, Fuji is incompatible with newer Java versions and all code related to Fuji should be removed from FeatureIDE.

**Comment by skrieter** [comment]
Related to #936.

**Comment by ekuiter** [comment]
Fuji has been removed, but the other points have not been addressed yet.

**Comment by skrieter** [comment]
Fixed
