### ISSUE TITLE
Framework Support: PluginLoader always returns empty list

### ISSUE THREAD

**Issue by pmbittner** [FeatureIDE/FeatureIDE#1109]
#### Prerequisitives
* **Eclipse Version:**  Tested with prepackaged _Eclipse with FeatureIDE, JDT, CDT, and AJDT_ from featureide.github.io for the FeatureIDE-Versions 3.6.2 and 3.7.0.
* **FeatureIDE-Version:**  tested with 3.6.2 and 3.7.0
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** JRE 1.8 with FeatureIDE 3.6.2; JDK 16 with FeatureIDE 3.7.0
* **FeatureIDE Composer:** Framework
* **Git branch/Commit-ID:**  
* **Java compiler used to build the FeatureIDE plugin:** 

### Issue description
![FeatureIDE_Framework_bug](https://user-images.githubusercontent.com/9421337/117032811-15aaff80-ad02-11eb-82cb-9000b8c50bb3.PNG)

When using the framework support, the `PluginLoader.load(...)` method always returns an empty list. I followed the instructions from the [youtube video](https://www.youtube.com/watch?v=j_XRxowwi04) but had no success. When inspecting the generated jar files for the plugins, the jar only contained a single file but no `info.xml`. I found that the `info.xml`, of which there is one for each plugin, could not be loaded by the PluginLoader, most likely because it was not packaged into the corresponding jar file.

**Comment by pmbittner** [comment]
Having a fix until end of may would be just in time for homework assignments of the current lecture. :)

**Comment by dhohmann** [comment]
I wrote this code as a software project, so sorry for the inconvenience. I may have a few ideas, why this bug occures: I am re-using the existing project structure and behaviour of Java projects in Eclipse (source files under `src`, compiled files under `bin`). This means that I look into the `bin` folder of the feature project to collect the `.class` files.

- If the files are not compiled, i.e. when it is disabled, the files will not exist or will not be up-to-date.
- If the target of compilation process is not a folder named `bin`, the `.class` files cannot be loaded as they are not in the checked folder. (Maybe there is a possibility to access the configuration of Eclipse to get this setting?)

The bug will likely occur in the [FrameworkComposer](https://github.com/FeatureIDE/FeatureIDE/blob/0b3dc62d55f2284eb055f77f98e1b8f7e2a86011/plugins/de.ovgu.featureide.core.framework/src/de/ovgu/featureide/core/framework/FrameworkComposer.java#L81) class.

**Comment by ekuiter** [comment]
We also have upcoming assignments on this in our lecture, so +1

**Comment by tthuem** [comment]
Daniel, this is great. We've never had a former student before looking into the code again (unless we paid the students for that purpose). :)

Please keep us updated to avoid redundant work. Are you planning to work towards a pull request? If so, please make sure to use the release3.7 branch.

**Comment by dhohmann** [comment]
For the moment, I am not planning to work towards a pull request right now, but I want to provide help towards finding a solution. I am not really familiar with the current state of the project and I don't want to mess it up.

@pmbittner It would be great to know, if one of the causes, that i have written about previously, is currently the problem in your case.

**Comment by Rahel12342** [comment]
I reproduced the issue, it appears when taking an existing xml file from another FeatureIDE project and copying it, not when creating a new one or taking an example. Maybe we can talk about it later in the Meeting.

**Comment by pmbittner** [comment]
@dhohmann The built `.class` files are in the `bin` directory of the respective plugins. The `Test.java` and `Whitebread.java` in my screenshot above were compiled to `Brot-Task4/features/White/bin/de/uulm/spl/Test.class` and `Brot-Task4/features/White/bin/de/uulm/spl/Whitebread.class` according to the package `de.uulm.spl` the classes are defined in. I did not change any settings regarding the build process.

**Comment by pmbittner** [comment]
@Rahel12342 Yes, instead of editing the feature model in the diagram editor, I replaced it with an existing model by exchanging its xml description in the `Source` view:

![grafik](https://user-images.githubusercontent.com/9421337/117645271-b0845d80-b18a-11eb-8cbe-a1b66c941593.png)

**Comment by pmbittner** [comment]
Here is my project: [Brot-Task4.zip](https://github.com/FeatureIDE/FeatureIDE/files/6451394/Brot-Task4.zip)

**Comment by ekuiter** [comment]
> 
> 
> Here is my project: [Brot-Task4.zip](https://github.com/FeatureIDE/FeatureIDE/files/6451394/Brot-Task4.zip)

For me, it works once I open the configuration `default.xml` and save it (which regenerates the JARs).

**Comment by Rahel12342** [comment]
> For me, it works once I open the configuration `default.xml` and save it (which regenerates the JARs).

Same for me.

**Comment by dhohmann** [comment]
I had a similar (or maybe the same) issue while working on the programming task today. To fix it, I disabled the automatic build. Then, I built the feature projects before building the main project.

**Comment by ekuiter** [comment]
Could you try Daniel's suggestion, @pmbittner ? You can also delete the  `lib` directory and check whether the jars are actually rebuilt. Creating a new configuration, choosing some features and saving may also help. The problem could also be due to abstract features, which should not have implementations.

**Comment by ekuiter** [comment]
Here is another project from one of our students who has this problem. I am not able to re-build this at all, even with the suggestions above. (It works when run, but only because the student worked around the PluginLoader.)
Interestingly, one generated JAR (Breite8.jar) *does* have the info.xml, but not the class files. Seems that the issue does not have to do with the info.xml after all.
Is anyone able to get this project to work (and with what steps)? This could maybe give us a clue to the root issue.

[VierGewinnt-Framework.zip](https://github.com/FeatureIDE/FeatureIDE/files/6500172/VierGewinnt-Framework.zip)

**Comment by pmbittner** [comment]
> 
> 
> Could you try Daniel's suggestion, @pmbittner ? You can also delete the `lib` directory and check whether the jars are actually rebuilt. Creating a new configuration, choosing some features and saving may also help. The problem could also be due to abstract features, which should not have implementations.

1.) Disabling Automatic Build for each project (was only active for the main framework project); then building feature projects manually; then building framework project manually; then running framework project still did not make a difference.
2.) Deleting the `lib` directory; then repeating 1 does not lead to the lib directory being regenerated. The `lib` directory is just gone now.
3.) Creating a new configuration and saving it also has no effect. Repeating 1 afterwards also does not change anything. I am unsure if `Right Click on any project > Build Project` is doing anything. I don't get a response from eclipse.
4.) No, the features I am testing are not abstract (`White` and `WholeGrain`). I made the remaining features abstract, so no feature projects are generated for those which worked as expected.

![grafik](https://user-images.githubusercontent.com/9421337/118632593-ddf78980-b7d0-11eb-8dc0-294d3158e745.png)

I am not able to restore the `lib` directory again.

**Comment by pmbittner** [comment]
> 
> 
> Here is another project from one of our students who has this problem. I am not able to re-build this at all, even with the suggestions above. (It works when run, but only because the student worked around the PluginLoader.)
> Interestingly, one generated JAR (Breite8.jar) _does_ have the info.xml, but not the class files. Seems that the issue does not have to do with the info.xml after all.
> Is anyone able to get this project to work (and with what steps)? This could maybe give us a clue to the root issue.
> 
> [VierGewinnt-Framework.zip](https://github.com/FeatureIDE/FeatureIDE/files/6500172/VierGewinnt-Framework.zip)

I experienced that only the last file that was created in a feature project was put into the jar file. So at first, only the `info.xml` was in the jar file (as expected because it was the only file in that feature project). When creating a class (e.g., `Test.class` in the first screenshot I sent) then only the corresponding class file is in the jar file. When creating another class, only the class file of the newest class is in the jar file. I reproduced this together with @Rahel12342 but only on my machine.

**Comment by pmbittner** [comment]
Interestingly, a similar case seemed to be occured in `VierGewinnt-Framework.zip`. When inspecting the jars with 7zip I can only find exactly one file in each jar (either a `.class` file or the `info.xml`).

**Comment by pmbittner** [comment]
Just extracting `VierGewinnt-Framework.zip`, importing it into my workspace and running `Main::main` worked for me if this is the expected output:

![grafik](https://user-images.githubusercontent.com/9421337/118633793-22375980-b7d2-11eb-83b9-7c5fe4e6334f.png)

I did not build it though or did anything FeatureIDE-specific.

**Comment by pmbittner** [comment]
> 
> 
> > Could you try Daniel's suggestion, @pmbittner ? You can also delete the `lib` directory and check whether the jars are actually rebuilt. Creating a new configuration, choosing some features and saving may also help. The problem could also be due to abstract features, which should not have implementations.
> 
> With `eclipse4.17.0committers-featureide3.7.0-win64`:
> 
> 1.) Disabling Automatic Build for each project (was only active for the main framework project); then building feature projects manually; then building framework project manually; then running framework project still did not make a difference.
> 2.) Deleting the `lib` directory; then repeating 1 does not lead to the lib directory being regenerated. The `lib` directory is just gone now.
> 3.) Creating a new configuration and saving it also has no effect. Repeating 1 afterwards also does not change anything. I am unsure if `Right Click on any project > Build Project` is doing anything. I don't get a response from eclipse.
> 4.) No, the features I am testing are not abstract (`White` and `WholeGrain`). I made the remaining features abstract, so no feature projects are generated for those which worked as expected.
> 
> ![grafik](https://user-images.githubusercontent.com/9421337/118632593-ddf78980-b7d0-11eb-8dc0-294d3158e745.png)
> 
> I am not able to restore the `lib` directory again.

I switched from Java 16 to Java 13 now (via Eclipse.ini, you may find my ini file attached) and now rebuilding the projects worked and the `lib` and `White.jar` files are there again. Still, the PluginLoader does not find any implementations as the `White.jar` does still not contain the info.xml.

<details><summary>
<em>eclipse.ini</em></summary>
<p>

```
-startup
plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1300.v20200819-0940
-product
org.eclipse.epp.package.committers.product
-showsplash
org.eclipse.epp.package.common
--launcher.defaultAction
openFile
--launcher.defaultAction
openFile
-vm
C:\Program Files\Java\jdk-13.0.2\bin\javaw.exe
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
```
</p>
</details>

**Comment by ekuiter** [comment]
> 
> 
> Just extracting `VierGewinnt-Framework.zip`, importing it into my workspace and running `Main::main` worked for me if this is the expected output:
> 
> ![grafik](https://user-images.githubusercontent.com/9421337/118633793-22375980-b7d2-11eb-83b9-7c5fe4e6334f.png)
> 
> I did not build it though or did anything FeatureIDE-specific.

This works only because the student hard-coded a way around the PluginLoader. When using the commented-out lines, the PluginLoader.load list is also empty

**Comment by pmbittner** [comment]
> 
> 
> > Just extracting `VierGewinnt-Framework.zip`, importing it into my workspace and running `Main::main` worked for me if this is the expected output:
> > ![grafik](https://user-images.githubusercontent.com/9421337/118633793-22375980-b7d2-11eb-83b9-7c5fe4e6334f.png)
> > I did not build it though or did anything FeatureIDE-specific.
> 
> This works only because the student hard-coded a way around the PluginLoader. When using the commented-out lines, the PluginLoader.load list is also empty

Oops, now I see it. I read your comment on that but was confused that the PluginLoader is still used in that project. It wasn't obvious to me that the lists returned by the PluginLoader were discarded.

**Comment by ekuiter** [comment]
Maybe we are dealing with two different bugs?
First, updating JAR files and the classpath does not work reliably (for you, it works with Java 13 but not Java 16; for me, it mostly works for Java 11, but not for the Vier Gewinnt project).
Second, the JAR creation ( https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.core.framework/src/de/ovgu/featureide/core/framework/FrameworkJarCreator.java ) does not work reliably (for you and our student, only a single file is put into the JAR; for me and Rahel, all files are always there as soon as I regenerate the JARs).

**Comment by tthuem** [comment]
I would like to create the new release tomorrow (planned for May). Shall I wait for a fix of this issue?

From this long discussion, it is not quite clear to me whether we need a fix for students or not. If we need a fix, who can do it until when?

**Comment by pmbittner** [comment]
As this issue seems to arise only for some users (Elias' student and me), it might be ok to fix it later. Yet, it would be nice to have because I have no way of helping those students that run into this issue.

**Comment by tthuem** [comment]
Workaround: As FeatureIDE merely automates including and excluding plugins, the same can be simulated by commenting out lines that add certain plugins. That's what we did with students before we have had the framework extension.

**Comment by ekuiter** [comment]
Of our 9 students, one had this problem. For this student, we used Thomas' workaround and that was fine. So I would not consider it urgent

**Comment by Rahel12342** [comment]
For me, this appears as well when using the HelloWorld-Framework Example from the FeatureIDE Book Examples.

**Comment by haasy** [comment]
When i tried to use the Framework composer for an excercise in the lecture SPL, i also ran into this problem. Further debugging showed that in my case, the list returned by the PluginLoader was empty because the classpath did not contain the *.jar-files that constitute the features. So it seems that in my case the composer was not able to change the classpath according to the current configuration.

**Comment by ekuiter** [comment]
Has someone new information about this? Our students have reported issues with the framework support again (JARs are not generated or do not show up as references libraries).

**Comment by Rahel12342** [comment]
> I still can't reproduce this issue with the HelloWorld-Framework example on
> 
> * Linux, Java 17 OpenJDK, Eclipse 4.20, FeatureIDE-develop
> * Windows 10, JDK 16, Eclipse 4.13, FeatureIDE 3.6.2 prepackaged
> * Windows 11, Java 8 JRE, Eclipse 4.13, FeatureIDE 3.6.2 prepackaged
> 
> What about you, @Rahel12342 ?

I tried it again and cannot reproduce the issue, with Windows 10, Eclipse 4.20, FeatureIDE 3.8.1 prepackaged

**Comment by tthuem** [comment]
@pmbittner Can you still reproduce this issue?

**Comment by skrieter** [comment]
I noticed this behavior, when the info.xml was missing in some plug-ins. In this case, not all Jars where updated.
Now, FeatureIDE creates an error marker for the problematic plug-ins to show the users the problem.

**Comment by pandrow** [comment]
Unfortunately, I still encounter this issue in FeatureIDE Version 3.8.3, Eclipse Version 4.20.0 (`eclipse4.20.0committers-featureide3.8.3-win64`) as a student of the SPL lecture.

**Prerequisites:**

- **Operating System:** Windows 10 Pro (64-Bit)
- **Eclipse and FeatureIDE Version:** Eclipse 4.20.0, FeatureIDE 3.8.3
- **JDK:** JDK 11.0.12 or JDK 16

**Steps to reproduce (on a fresh install):**

- Configure Eclipse to use a specific JDK by adding the following 2 lines at the start of the `eclipse.ini` file (replace the path to your JDK accordingly):
  ```
  -vm
  C:\Program Files\Java\jdk-11.0.12\bin\javaw.exe
  ```
- Create the HelloWorld-Framework example project
- Run `HelloWorld.java`

The application terminates without any output. Debugging the application shows that the list of plugins (`messagePlugins`) returned by the `PluginLoader` in `HelloWorld.java` is empty.

In the Package Explorer, it seems that all required classes and jars are present. However, every feature directory is marked with an error marker:

![Package Explorer showing the HelloWorld-Framework example project](https://user-images.githubusercontent.com/75807465/173858652-ff2d58b7-f21a-4727-9325-af294074e1c1.png)

Following the instructions of [this screencast](https://www.youtube.com/watch?v=j_XRxowwi04) also shows similar behaviour.

It might also be worth to note that I specifically include the JDK I want to use for FeatureIDE because I have older Java versions installed on my machine that FeatureIDE would otherwise try to use on startup (resulting in an error dialog stating that Java version 11 or later is required).

However, I also encounter the issue on my other machine (laptop) without older Java versions and without specifying a specific JDK in the `eclipse.ini` file. In this case, there are no error markers like in the image above, but the PluginLoader still just returns an empty list.

**Comment by ekuiter** [comment]
I cannot reproduce (Windows 11, JDK 11.0.14), I get the expected output "Hello Beautiful World". What do these error markers say? Did you try "Project > Clean ..."?

**Comment by ekuiter** [comment]
> Workaround: As FeatureIDE merely automates including and excluding plugins, the same can be simulated by commenting out lines that add certain plugins. That's what we did with students before we have had the framework extension.

**Comment by pandrow** [comment]
The error markers show the following messages:

![error messages](https://user-images.githubusercontent.com/75807465/174066602-03e23108-adfd-4c11-b8fb-652468fb70aa.png)

However, as I said, I also encounter the issue with the empty list on my laptop without the error markers, so there might be two separate issues: On the one hand that the `PluginLoader` returns an empty list, and on the other hand that errors (as shown above) appear when specifying a Java version in the `eclipse.ini` file.

`Project > Clean...` unfortunately did not change anything.

I could work around the problem (for example the way you suggested), so fixing the issue is not urgent for me.
