### ISSUE TITLE
toString() of propositional values crashes

### ISSUE THREAD

**Issue by pmbittner** [FeatureIDE/FeatureIDE#1111]
#### Prerequisitives
* **Eclipse Version:**  none: used FeatureIDE library
* **FeatureIDE-Version:** 3.7.0
* **Operating system:** Windows 10
* **Java runtime used ~~to run eclipse~~:** openjdk-16
* **FeatureIDE Composer:** 
* **Git branch/Commit-ID:** 
* **Java compiler used to build the FeatureIDE plugin:** 

### Issue description
Each of the following statements crashes
```java
new True().toString();
new False().toString();
new And(new False(), new True()).toString();
```
The error message always is:
```
Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "children" is null
	at org.prop4j.NodeWriter.operationToString(NodeWriter.java:328)
	at org.prop4j.NodeWriter.nodeToString(NodeWriter.java:236)
	at org.prop4j.NodeWriter.nodeToString(NodeWriter.java:211)
	at org.prop4j.Node.toString(Node.java:324)
```

The bug is likely caused, because there is no case implemented for `True` and `False` in `NodeWriter::nodeToString`. Thus, `True` and `False` are interpreted as operators and passed to `Node::operationToString` which they are not.

**Comment by pmbittner** [comment]
Also, both `True::isConjunctiveNormalForm` and `False::isConjunctiveNormalForm` always return `false`, but aren't pure values a valid CNF as both represent a single clause?

**Comment by pmbittner** [comment]
And wouldn't it make sense to model both values as singletons?

**Comment by pmbittner** [comment]
Also, the `NodeReader` does not parse `1` as true, but as a Literal with feature name 1.

**Comment by pmbittner** [comment]
I encountered another unexpected issue.
When evaluating formulas with `getValue`, the user has to provide assignments for `True` and `False`.
I wrote the following method to check for a configuration being a satisfiable assignment for a given formula (`Node`):

```java
public static boolean IsSatisfyingAssignment(Configuration config, Node formula) {
    final Map<Object, Boolean> assignment = new HashMap<>();
    assignment.put(NodeCreator.varTrue, true);
    assignment.put(NodeCreator.varFalse, false);

    for (IFeature f : config.getFeatureModel().getFeatures()) {
        assignment.put(f.getName(), false);
    }

    for (IFeature f : config.getSelectedFeatures()) {
        assignment.put(f.getName(), true);
    }

    return formula.getValue(assignment);
}
```

Without adding explicit assignments for true and false (lines 3 and 4), `getValue` crashes when using true and false values in a formula.
Worse, one could even assign `false` to `NodeCreator.varTrue` and `true` to `NodeCreator.varFalse`!

**Comment by skrieter** [comment]
This manual assignment is now not necessary anymore. It is also ignored for `NodeCreator.varTrue` and `NodeCreator.varFalse`.
Both  `new Literal(NodeCreator.varTrue).getValue(new HashMap())` and `new True().getValue(new HashMap())` should now always return `true`.
