### ISSUE TITLE
Feature Name is badly readable when changing it

### ISSUE THREAD

**Issue by bjthehun** [FeatureIDE/FeatureIDE#1115]
Problem:

When I rename a feature, the text field to label it takes the size of the feature box. In the default zoom level, this hides the name partially.

![Partially hidden Feature name](https://user-images.githubusercontent.com/38729215/119152349-86675100-ba50-11eb-9faf-3d5b0011e0fe.png "Selecting the Feature \"UnitConversion\"")

The field also doesn't resize when writing the new name. This makes it difficult to write correct feature names.

![Feature name not resizing](https://user-images.githubusercontent.com/38729215/119152352-86ffe780-ba50-11eb-8df3-8ec900bca2b6.png "Typing the new Feature name \"UnitConversionLongName\"")

Steps to reproduce:

1. Open a Feature Model in FeatureIDE.
2. Select a feature and press F2 to rename it.
3. Type a new feature name.

Environment Information:

* Eclipse Version: 4.19
* FeatureIDE Version: 3.7.0
* Composer: Feature Modeling
* OS: Ubuntu 20.10
* Java Runtime: OpenJDK 64 Bit Server VM 15.0.3

**Comment by tthuem** [comment]
Could be related to zooming or scrolling, but it is unlikely that the cause is in the FeatureIDE source.

**Comment by tthuem** [comment]
Seems to be an incompatibility between GEF and Linux.
