### ISSUE TITLE
Release 3.7.0 not available via Eclipse Marketplace

### ISSUE THREAD

**Issue by JavaZauber** [FeatureIDE/FeatureIDE#1117]
### Issue description

Version 3.6.3 is distributed via the marketplace which is not the current version.
See https://marketplace.eclipse.org/content/featureide

![image](https://user-images.githubusercontent.com/6533815/120473764-a8919500-c3a7-11eb-86df-bb1351ddc441.png)
![image](https://user-images.githubusercontent.com/6533815/120473800-b47d5700-c3a7-11eb-9dcd-eac15bbeff1c.png)

**Comment by tthuem** [comment]
Sorry, this was my fault. It should be available using the Marketplace now. Thanks for the report.
