### ISSUE TITLE
Alternatives and Or-Groups with one feature are not handled correctly within the feature model.

### ISSUE THREAD

**Issue by skrieter** [FeatureIDE/FeatureIDE#1139]
#### Prerequisitives
* **FeatureIDE-Version:**  3.7.1

### Issue description
Alternatives and Or-Groups are not handled correctly within the feature model, if they contain only one feature. If an alternative or Or-group only contains one feature, the feature model pretends that is is an And-Group instead. This is done in multiple places in the source code, for instance in FeatureStructure#isAlternative and FeatureStructure#isOr and was done intentionally in order to fix #662. 
The problem is that child feature of such a group should always be mandatory, but now can be also optional which leads to invalid configurations considered to be valid.
For example, when generating all configurations for GPL, 1015 configurations are returned, which contains 55 configurations that should be invalid.

**Comment by skrieter** [comment]
Fixed.

**Comment by viceice** [comment]
Thanks for fixing, found this too long time ago in v3.5.2 but had no time to report and simply pinned working v3.3.0.

btw: using it successfully at dotnet here https://github.com/visualon/featureide.net 🙃
