### ISSUE TITLE
Dislocation of decoration boxes/features in vertical view

### ISSUE THREAD

**Issue by michaelsoft-binbows** [FeatureIDE/FeatureIDE#1151]
#### Prerequisitives
* **Eclipse Version:**  `4.17`
* **FeatureIDE-Version:**  `3.7.1`
* **Operating system:** `Debian 11, KDE Plasma 5.20.5`
* **Java runtime used to run eclipse:** `jdk-14.0.1`
* **FeatureIDE Composer:** `Extended Feature Model`
* **Java compiler used to build the FeatureIDE plugin:** `1.8`

### Issue overview (check list)
- [ ] Position of decoration boxes (№ 1)
- [ ] Dislocation of features in manual layout (№ 2)
- [ ] Mix of horizontal and vertical layout (№ 3)

### Issue description
1. Decoration boxes are not positioned correctly in manual layout (see figure 1).\
  This can be reproduced by enabling the vertical layout (Left to right (ordered)) in the feature model editor. After that, the manual layout has to be chosen. If the decoration boxes are not dislocated, one has to collapse and expand any feature to make the dislocation visible.
2. Dislocation of feature arrangement in manual layout (see figure 2).\
  a) Child feature `NewFeature4` of `Base` is placed in the top left corner.
  b) Child features of `NewFeature10` and `NewFeature12` are placed at the same spot. 
  This behaviour could as be reproduced. However, the transition of the vertical into the manual view causes this problem. Collapsing and expanding features may cause this misbehaviour.
3. Mix of horizontal and vertical layout (figure 3).\
  Reproduction is unclear. When closing the feature model editor of (1) and opening it again, this view might show up.  

Remark: No element in the feature model editor has been moved manually.

Apparently, the overall vertical view seems to be buggy in combination with the manual view.

![feature_issue1](https://user-images.githubusercontent.com/83942964/127852698-422424ca-1cdf-4b01-8f9c-031e2f56ad5b.png)
Figure 1. 

![feature_issue2](https://user-images.githubusercontent.com/83942964/127852703-04519b4b-d0cf-47e1-bb28-4524b250d3dd.png)
Figure 2.

![feature_issue3](https://user-images.githubusercontent.com/83942964/127856942-7fd442a8-53d0-4e8b-b855-c7e47d53c9d9.png)
Figure 3.

**Comment by johannesherschel** [comment]
Regarding task 2:
These issues are not specific to the vertical layout.

a) This can be reproduced with the following steps:
- Select any automatic layout
- Collapse a feature
- Save, close and reopen the model
- Select manual layout
- Expand the collapsed feature

Any feature that was collapsed is now displayed in the top left corner. Apparently the location of collapsed features is not saved. This happens for any layout, not just the vertical layout.

b) This can be reproduced with the following steps
- Select any automatic layout
- Collapse a feature
- Select a different automatic layout
- Select manual layout
- Expand the collapsed feature

Any feature that was collapsed is now displayed where it was located before it was collapsed. The collapsed features are not relocated when selecting a different automatic layout. This happens with any combination of automatic layouts.

There may also be different ways to reproduce these or similar issues.
