### ISSUE TITLE
Decoration box layout for collapsed features

### ISSUE THREAD

**Issue by michaelsoft-binbows** [FeatureIDE/FeatureIDE#1153]
#### Prerequisitives
* **Eclipse Version:**  `4.17`
* **FeatureIDE-Version:**  `3.7.1`
* **Operating system:** `Debian 11, KDE Plasma 5.20.5`
* **Java runtime used to run eclipse:** `jdk-14.0.1`
* **FeatureIDE Composer:** `Extended Feature Model`
* **Java compiler used to build the FeatureIDE plugin:** `1.8`

### Issue overview (check list)
- [ ] Blank decoration box (№ 1)
- [ ] Decoration box border (№ 2)

### Issue description
The decoration box (white box underneath or right next to the feature) indicates the number of collapsed features of that very father feature.

1. The blank decoration box (see fig. 1 & 2).\
  When creating a couple of child features and then collapsing the parent feature, sometimes a blank decoration box 

![feature_issue4](https://user-images.githubusercontent.com/83942964/127860025-c0433ab1-5e61-4ce9-a3ef-9e00bb53b04c.png)
Figure 1.

![feature_issue5](https://user-images.githubusercontent.com/83942964/127860029-fd66bc8d-ea0d-40e4-aa85-c96a7c2990d1.png)
Figure 2.

2. Border of decoration box (see fig. 3).\
  The border of the decoration boxes sometimes does not render properly. This can be reproduced by collapsing the father feature node right after the creation of the child feature node.

![feature_issue6](https://user-images.githubusercontent.com/83942964/127860033-2f6df000-94a9-4d9b-8e25-34fdfd75a195.png)
Figure 3.

**Comment by johannesherschel** [comment]
The second issue also occurs for the box in the legend, as can be seen in figure 2.
