### ISSUE TITLE
Feature names in constraints truncated when zooming the feature diagram

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#1179]
#### Prerequisitives
* **Eclipse Version:**  4.20 Committers
* **FeatureIDE-Version:**  3.7.2
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** JDK 13.0.2

### Issue description
Part of the last character missing (Zeile1 and Zeile2) or even the complete last character (Zeile3):

![image](https://user-images.githubusercontent.com/5330357/130434288-8871d50e-35da-4e8e-84e7-de5f57729ab5.png)

We have had the same problem with feature boxes in the feature diagram. It seems that the solution is needed also for constraints.

**Comment by Rahel12342** [comment]
This is already fixed in version 3.8.0 (https://github.com/FeatureIDE/FeatureIDE/pull/1128).

**Comment by tthuem** [comment]
Also in constraints?

**Comment by Rahel12342** [comment]
Yes.
