### ISSUE TITLE
Ctrl+A does not work correctly when renaming a feature

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#1195]
In the renaming mode (ie, after pressing F2), Ctrl+A selects all features instead of selecting all text in the rename popup.

Expected:

![grafik](https://user-images.githubusercontent.com/4258713/131824647-6de8324d-716a-4a73-93dc-633778be54a5.png)

Actual:

![grafik](https://user-images.githubusercontent.com/4258713/131824818-1f1f2c05-61d9-4d4d-bf5d-ea847d7ed162.png)

**Comment by johannesherschel** [comment]
There are similar issues for other actions, e.g. Undo/Redo while renaming apply to the model, and Delete (via the Edit menu, not the key) deletes the current feature instead of a character of the edited name.
