### ISSUE TITLE
Delete With Slicing creates redundant constraints

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1199]
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

Deleting features with slicing sometimes creates redundant constraints.

## Example 1:
![image](https://user-images.githubusercontent.com/84278649/133071752-149d8545-dd77-4eb9-b9ab-e21cf85d1cd5.png)
When deleting feature a with slicing, this model results:
![image](https://user-images.githubusercontent.com/84278649/133071866-14df0b08-bca3-4864-ac64-771560947826.png)
The constraint Root is of course redundant. This issue appears to be specific to UVL. Using an identical XML model results in this (correct) model:
![image](https://user-images.githubusercontent.com/84278649/133072144-6e12c835-1cc4-47d3-b7c1-2da94fe1b963.png)

## Example 2:
The UVL Server example with an added feature:
![image](https://user-images.githubusercontent.com/84278649/133072575-2a0f6529-368f-418d-8318-10f14b0b40cc.png)
Deleting the feature Windows with slicing leads to this model:
![image](https://user-images.githubusercontent.com/84278649/133072676-47d8e39d-a355-4448-af1f-b6515d6da168.png)
In this case, there are 2 redundant constraints. With the equivalent XML model, we get this result:
![image](https://user-images.githubusercontent.com/84278649/133072862-5fddddc8-e8c4-4d11-9c16-ae297324d0eb.png)
In this case, there is only 1 redundant constraint.

**Comment by skrieter** [comment]
Seems to be fixed already.
