### ISSUE TITLE
UVL: Renaming of root feature does not change namespace

### ISSUE THREAD

**Issue by michaelsoft-binbows** [FeatureIDE/FeatureIDE#1209]
#### Prerequisitives
* **Eclipse Version:**  `4.17`
* **FeatureIDE-Version:**  `3.7.1`
* **Operating system:** `Debian 11, KDE Plasma 5.20.5`
* **Java runtime used to run eclipse:** `jdk-14.0.1`
* **FeatureIDE Composer:** `Extended Feature Model`
* **Java compiler used to build the FeatureIDE plugin:** `1.8`

### UVL: Remaning of root feature does not change namespace
The `namespace` of a feature model in UVL is determined by the root feature, see in `de.ovgu.featureide.fm.core.io.uvl.UVLFeatureModelFormat` in line `327`:
```
String namespace = fm.getStructure().getRoot().getFeature().getName();
```
When renaming the root feature of a feature model in the UVL format, the namespace is not updated.

I am not sure whether this is intended or a real issue. 

In the following example, one can see that the root feature name and namespace differ.
![feature_issue12](https://user-images.githubusercontent.com/83942964/133385462-7119d03f-3b7b-4ec3-a853-c27e432191ea.png)

**Comment by Rahel12342** [comment]
Does this cause any other issues? Otherwise, the described behavior is intended and this issue could be closed.

**Comment by michaelsoft-binbows** [comment]
No, it does not cause any issues.

I just wasn’t sure whether this is intended behaviour or not.
