### ISSUE TITLE
Multi UVL: Wrong behaviour of constraints of imported models

### ISSUE THREAD

**Issue by michaelsoft-binbows** [FeatureIDE/FeatureIDE#1210]
#### Prerequisitives
* **Eclipse Version:**  `4.17`
* **FeatureIDE-Version:**  `3.7.1`
* **Operating system:** `Debian 11, KDE Plasma 5.20.5`
* **Java runtime used to run eclipse:** `jdk-14.0.1`
* **FeatureIDE Composer:** `Extended Feature Model`
* **Java compiler used to build the FeatureIDE plugin:** `1.8`

### Multi UVL: Wrong behaviour of constraints of imported models
Say, UVL model `A` imports UVL model `B`. `B` contains one or more cross tree constraints. Cf. figure 1 & 2 and 3 & 4.

However, after each saving and reopening of feature model `A`, all constraints of `B` are saved in the UVL model file of model `A`, even though they do not belong there. Is it sufficient to save all constraints in model `B`. Cf. figure 5 and 6.

_**This causes especially problems when features, for instance, are renamed. Renaming only takes place in the imported model and not in the model that imports and erroneously replicates imported constraints!** Cf. fig. 7_

![feature_issue17](https://user-images.githubusercontent.com/83942964/133432489-2c15ae8f-9939-4964-b726-d807a0398ef0.png)
Figure 1.

![feature_issue18](https://user-images.githubusercontent.com/83942964/133432472-fb622b5d-bb19-4064-a148-562c42d79b39.png)
Figure 2.

![feature_issue19](https://user-images.githubusercontent.com/83942964/133432458-0374e96a-62b1-4b46-8541-5279e39959e6.png)
Figure 3.

![feature_issue20](https://user-images.githubusercontent.com/83942964/133432449-60c6d963-4867-4fd8-8a54-6a8b30692174.png)
Figure 4.

![feature_issue21](https://user-images.githubusercontent.com/83942964/133433074-1b22e38d-6421-4786-bae3-86bb7b933961.png)
Figure 5.

![feature_issue22](https://user-images.githubusercontent.com/83942964/133433089-af2b89e0-52f7-412b-a1f1-56df2bde13c3.png)
Figure 6.

![feature_issue23](https://user-images.githubusercontent.com/83942964/133434246-24597488-9b98-439c-97dc-8b0db7c888bb.png)
Figure 7.

**Comment by michaelsoft-binbows** [comment]
Additionally, this causes parsing issuesThis causes

**Comment by Rahel12342** [comment]
Another not correct working aspect of the imported constraints is, that they are still editable in the composed model. When closing and reopening the model, the changes that were made disappeared. 
Anyway, this needs a fix that will be done together with this issue.
