### ISSUE TITLE
Error when opening extended configuration with missing features

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1215]
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

Steps to reproduce:
1. Open an extended feature model. Make sure the attributes view is opened.
2. Delete or rename a feature. Save the model.
3. Open an associated extended configuration.

This error is displayed:
![image](https://user-images.githubusercontent.com/84278649/133472336-9f83afdd-4734-4d0b-8b2d-4959475e0b2b.png)

**Comment by skrieter** [comment]
Cannot be reproduced
