### ISSUE TITLE
Missing icon for ‘Redundant Constraint’ in feature diagram

### ISSUE THREAD

**Issue by michaelsoft-binbows** [FeatureIDE/FeatureIDE#1221]
#### Prerequisitives
* **Eclipse Version:**  `2020-09 (4.17.0)`
* **FeatureIDE-Version:**  `3.8`
* **Operating system:** `Debian 11, KDE Plasma 5.20.5`
* **Java runtime used to run eclipse:** `11`
* **FeatureIDE Composer:** `Extended Feature Model)`
* **Git branch/Commit-ID:**  `release3.8`

### Issue description
The icon for redundant constraints is displayed in the legend if a redundant constraint exists. However, it is not shown in the feature diagram itself. Instead of this icon, a blue exclamation mark is shown. Cf. figure 1.

#### Steps to reporduce:
1. Create a constraint that is redundant

![feature_issue24](https://user-images.githubusercontent.com/83942964/133994544-ec7e7034-e497-4ae0-8977-21a169a991d9.png)
Figure 1.

**Comment by Rahel12342** [comment]
What would be the preferred option @tthuem ? Looking at the code, the fault is that the label from "Redundant Constraint" is set to "False Optional" which leads to the yellow icon (which is the icon of false optional). This leads to the result, that the icon in the legend should be changed. 
Anyway, it might be more intuitive to have the yellow icon at both places. So what is preferred?
