### ISSUE TITLE
Cannot choose model upon new feature model creation using the wizard

### ISSUE THREAD

**Issue by michaelsoft-binbows** [FeatureIDE/FeatureIDE#1222]
#### Prerequisitives
* **Eclipse Version:**  `2020-09 (4.17.0)`
* **FeatureIDE-Version:**  `3.8`
* **Operating system:** `Debian 11, KDE Plasma 5.20.5`
* **Java runtime used to run eclipse:** `11`
* **FeatureIDE Composer:** `Extended Feature Model)`
* **Git branch/Commit-ID:**  `release3.8`

### Issue description
Cannot create any model else than .xml by using the wizard. See figure 1, 2 and 3.

Ideally, it should be possible to choose the desired feature model format.

![feature_issue25](https://user-images.githubusercontent.com/83942964/133998385-3e1ef64e-3efd-4127-99d8-71c838fbdd70.png)
Figure 1.

![feature_issue26](https://user-images.githubusercontent.com/83942964/133998369-919b1207-0212-4601-a34e-f3c961b68fd1.png)
Figure 2.

![feature_issue27](https://user-images.githubusercontent.com/83942964/133998362-b0590e5b-18fe-42ce-a0be-bc684b173463.png)
Figure 3.

**Comment by Rahel12342** [comment]
This does work when pressing "next" at Figure 2 instead of Finish. There you can choose your format.

**Comment by Rahel12342** [comment]
Maybe a text at the bottom of the wizard (something like "To choose a different format than xml you need to press next") can be added for better usability.

**Comment by michaelsoft-binbows** [comment]
I missed the ‘Next >’ button. 

It works just fine.
