### ISSUE TITLE
Issues with the extended__ marker attribute of UVL models

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1232]
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

Changing a UVL model to extended or non-extended can lead to errors.
- [ ] [1] extended__ attribute is saved even when closing the model without saving
- [ ] [2] Broken interaction with feature movement

## [1] extended__ attribute is saved even when closing the model without saving

1. Open a UVL model.
2. Switch to the Source tab of the feature model editor and add/remove the extended__ marker attribute.
3. Switch back to the Feature Diagram tab.
4. Close the model without saving.

The addition/removal of the extended__ attribute is still saved.

## [2] Broken interaction with feature movement

Example (non-extended) UVL model:
![image](https://user-images.githubusercontent.com/84278649/134959459-78c471df-69a4-4b4e-b628-64e1317a85b3.png)

1. Move "FeatureA" below "FeatureB".
2. Switch to the Source tab of the feature model editor and add the extended__ marker attribute to make the model extended:
```
namespace Root

features
	Root {extended__}
		optional
			FeatureB	
				optional
					FeatureA
```
3. Switch back to the diagram. Move "FeatureA" back to where it was, below "Root". The resulting model looks like this:
![image](https://user-images.githubusercontent.com/84278649/134960255-a07df75b-4622-4db6-a42d-83b7de465efa.png)

The same behaviour occurs when removing the extended__ attribute from a model instead of adding it.

**Comment by skrieter** [comment]
Will be fixed in 4.0.0.: In the new library there is no distinction between extended and non-extended format.
