### ISSUE TITLE
UVL textual editor has no undo

### ISSUE THREAD

**Issue by jaqPi** [FeatureIDE/FeatureIDE#1243]
#### Prerequisitives
* **Eclipse Version:**  `2021-09 (4.21.0)`
* **FeatureIDE-Version:**  `3.8.0.202108311440`
* **Operating system:** `macOS 11.6`
* **Java runtime used to run eclipse:** `jdk-11.0.4.jdk`

### Issue description

https://user-images.githubusercontent.com/3995477/135485621-d7d0728f-a9eb-4943-8cce-b0d6f996a327.mov

**Comment by johannesherschel** [comment]
This is part of #1160.
