### ISSUE TITLE
Changes of imported models or not propagated immediately

### ISSUE THREAD

**Issue by jaqPi** [FeatureIDE/FeatureIDE#1244]
#### Prerequisitives
* **Eclipse Version:**  `2021-09 (4.21.0)`
* **FeatureIDE-Version:**  `3.8.0.202108311440`
* **Operating system:** `macOS 11.6`
* **Java runtime used to run eclipse:** `jdk-11.0.4.jdk`

### Issue description

Changes made in imported submodels are visualized immediately. Only after the importing feature model is closed and re-opened, the changes made in the imported model are displayed also in the importing feature model.

https://user-images.githubusercontent.com/3995477/135487326-2bc29a66-3847-4c2f-ac1d-b7877ed75ce4.mov

**Comment by michaelsoft-binbows** [comment]
This issue has already been fixed in #1134.
