### ISSUE TITLE
Auto Layout Constraints toggle is not saved

### ISSUE THREAD

**Issue by Rahel12342** [FeatureIDE/FeatureIDE#1245]
#### Prerequisitives
* **Eclipse Version:**  `2020-03 (4.15.0)`
* **FeatureIDE-Version:**  `3.8`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `jdk-14.0.1`
* **FeatureIDE Composer:** `Feature Modeling`

### Issue description
When activating the toggle for "Auto Layout Constraints" and reopening the feature model, the toggle is gone. It would be more intuitive if the feature model would remember this layout decision, since it also remembers "Manual Layout".

**Comment by bjthehun** [comment]
Furthermore, FeatureIDE also does not save the selected Layout type when changing it.

### Prerequisitives

* Eclipse Version: `2021-09 (4.21)`
* FeatureIDE-Version: `3.8.0`
* Operating System: `Ubuntu 21.04`
* Java Runtime used to run Eclipse: `OpenJDK 64-Bit Server VM 16.0.1`
* FeatureIDE-Composer: `Feature Modelling`

### Steps to reproduce
1. Open a Feature Model in the standard FeatureIDE Format.
2. Select a different Automatic Layout in the Layout Menu, i.e. `Left to Right (ordered)`. The Model Layout changes.
3. Close and reopen the Feature Model. The Model now does have the default Layout.

https://user-images.githubusercontent.com/38729215/135600982-50d2dd40-4a84-42d6-9803-fb5b832f202a.mp4

**Comment by Rahel12342** [comment]
For other layout types that is not completely correct. They can be saved but only if the feature model is saved which requires a change in the fm (e.g., add a child). The Auto Layout Constraints option can not be saved at all.
