### ISSUE TITLE
Imported features can be made mandatory/optional

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1298]
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

Features of imported submodels can be made mandatory/optional in the feature diagram editor of the importing model by double-clicking on the connection marker. However, the corresponding context menu action of the features is disabled.

The mandatory/optional state should not be editable in the importing model, except for the imported root feature. The context menu action should also be enabled for the imported root.

**Comment by Rahel12342** [comment]
Also, it is not possible to change the root feature of the imported model from mandatory to optional and back. This will be fixed together with this issue.
