### ISSUE TITLE
Context menu of features shows incorrect collapsed state

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1299]
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

The context menu of features in the feature diagram editor sometimes falsely displays features as collapsed/expanded.

After collapsing "Root" by double-clicking on the feature, the context menu does not mark the feature as collapsed:
![image](https://user-images.githubusercontent.com/84278649/138171228-652380e5-378e-4feb-b1ab-81f5d7c79c1e.png)

After deselecting the feature and opening the context menu again, the Collapse entry is correctly marked:
![image](https://user-images.githubusercontent.com/84278649/138171490-91862f3b-24df-419f-978b-bef675d49d8e.png)

Similar behaviour occurs when expanding the feature instead of collapsing.

**Comment by skrieter** [comment]
Reloading of context menu fixes the problem.
