### ISSUE TITLE
Context menu entries "Mandatory", "Abstract" and "Hidden" of imported features not updated

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1300]
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

The context menu entries "Mandatory", "Abstract" and "Hidden" are not updated correctly for imported features.

Example model:
![image](https://user-images.githubusercontent.com/84278649/138174971-d8ada882-d3e6-4c3b-b88c-e6b5db4ecd39.png)

After selecting FeatureA (not mandatory, not abstract, not hidden), the context menu of "submodel.Base" shows that state:
![image](https://user-images.githubusercontent.com/84278649/138175306-81f43181-1ebb-4eeb-aecf-4d67c566836c.png)

However, after selecting FeatureB (mandatory, abstract, hidden), and opening the context menu of "submodel.Base" again, the entries are marked:
![image](https://user-images.githubusercontent.com/84278649/138175526-a0557bbd-dc52-4bdc-8037-ea09ca4bfe5c.png)

**Comment by skrieter** [comment]
fixed
