### ISSUE TITLE
Incorrect drag and drop locations when moving features

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1311]
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

When using one of the layouts "Root Right (abego TreeLayout)" or "Root Bottom (abego TreeLayout)", the drag and drop functionality to move features does not work as expected. The feature has to be moved to incorrect locations in order to move it. Apparently the calculation for drag and drop in these layouts is the same as for layouts where the root feature is at the top or left.

Example of correct behaviour in "Top-Down (ordered)" layout:
![image](https://user-images.githubusercontent.com/84278649/138957966-dea597a3-c098-4225-97c2-c868654897ac.png)

Example of incorrect behaviour in "Root Right (abego TreeLayout)" layout:
![image](https://user-images.githubusercontent.com/84278649/138958269-3957acd8-5713-4684-95f8-39c8e59dcd3e.png)
![image](https://user-images.githubusercontent.com/84278649/138958394-8b9115e5-5147-4a3d-805b-375acd20fc8d.png)

**Comment by tthuem** [comment]
As a workaround the problem could be mitigated a bit by changing the default layouting algorithm (back to the previous one).

**Comment by tthuem** [comment]
Could also be related to a recent change to the layout of each single feature boxes.

**Comment by dev-andreas** [comment]
I fixed the bug.

**Comment by skrieter** [comment]
fixed in 3ecdfe4aa04edebf26d6449da1f0ef7f38f8337c
