### ISSUE TITLE
Set Name Type context menu option in wrong places

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1315]
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

The "Set Name Type" option in the context menu of composed feature models (to select how imported feature names are displayed) is available in unintuitive places. It is available at features and at the diagram itself (the diagram background), but also at the legend:
![image](https://user-images.githubusercontent.com/84278649/138972127-3f460f1f-5365-4493-8b71-1b855fc68992.png)
at feature groups:
![image](https://user-images.githubusercontent.com/84278649/138972248-131194bf-1b2f-4f89-96ad-10fa6587d69b.png)
and even at the feature connections:
![image](https://user-images.githubusercontent.com/84278649/138972329-a6722dcd-d66d-45f6-a081-2b1cd8dc79e7.png)

**Comment by Rahel12342** [comment]
The Option to set the Name Type will onyl be available when nothing is selected in the editor. 
Additionally, it will be change to a toggle: 
![image](https://user-images.githubusercontent.com/64740628/143585017-cc846e23-5485-4240-965b-d870c1282be6.png)

**Comment by tthuem** [comment]
Looks good. Could you remove the separator between show legend and show qualified names?
