### ISSUE TITLE
Product Generator allowing to create only the configurations (without derivation)

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#1325]
#### Prerequisitives
* **Git branch/Commit-ID:** devop

### Issue description
The product generator allows to use different algorithms to create the configurations and derive the variants. It will be useful to have a checkbox to say that I don't want the derivation of each variant to be performed, as I only want the xml files of the configurations.

**Comment by skrieter** [comment]
Done
