### ISSUE TITLE
Bug: Dimacs Conversion Adds Values

### ISSUE THREAD

**Issue by mue-t** [FeatureIDE/FeatureIDE#1340]
#### Prerequisitives
* **Eclipse Version:** 4.20.0
* **FeatureIDE-Version:**  3.8.1
* **Operating system:** Windows
* **Java runtime used to run eclipse:** JDK 11.0.1

Tested with both Eclipse with FeatureIDE and FeatureIDE Library.

### Issue description
When converting a dimacs file to a dimacs file or dimacs -> other -> dimacs the following happens:

## Switching Variables
Sometimes the variables and their numbers are switched. Using [berkeleydb](https://github.com/SoftVarE-Group/emse21-evaluation-sharpsat/blob/main/cnf/berkeleydb/berkeleydb.dimacs) nothing gets switched, but using [busybox](https://github.com/SoftVarE-Group/emse21-evaluation-sharpsat/blob/main/cnf/busybox/2010-05-02_14-17-07.dimacs) this happens:
```
c 6 CONFIG_FEATURE_VI_YANKMARK
c 7 CONFIG_FEATURE_SPLIT_FANCY
```
is switched to:
```
c 6 CONFIG_FEATURE_SPLIT_FANCY
c 7 CONFIG_FEATURE_VI_YANKMARK
```
The clauses switch accordingly. Converting this file again to dimacs everything gets switched to the input file again.

# Adding all variables with root

After every conversion, all variables with root are added to the file.
For [busybox](https://github.com/SoftVarE-Group/emse21-evaluation-sharpsat/blob/main/cnf/busybox/2010-05-02_14-17-07.dimacs) it looks like this:
```
73 0
73 -1 0
73 -2 0
73 -3 0
73 -4 0
73 -5 0
...
73 -72 0
73 -73 0
73 -74 0
...
```
Even if clauses with the root are present in the input file, they are added again.
If the converted file is converted again, the same lines are added again.

**Comment by skrieter** [comment]
Fixed.
