### ISSUE TITLE
Non-consistent features naming conventions between UVLParser and FeatureIDE [Linked Issue]

### ISSUE THREAD

**Issue by ErwanMeunier** [FeatureIDE/FeatureIDE#1341]
#### Prerequisitives
* **Eclipse Version:**  `2022-03 (4.23.0)`
* **FeatureIDE-Version:**  `3.8.0`
* **Operating system:** `Linux Mint 20.3 Cinnamon 5.2.7`
* **Java runtime used to run eclipse:** `OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04)`
* **FeatureIDE Composer:** `IDK`
* **Git branch/Commit-ID:**  `Master -> plugins/de.ovgu.featureide.fm.core/lib/uvl-parser.jar` (probably)
* **Java compiler used to build the FeatureIDE plugin:** `IDK`
* 
### Issue description
Please find a linked issue in following the link below:
https://github.com/neominik/uvl-parser/issues/2#issue-1203065121
I think @SundermannC should be aware of this problem.

**Comment by SundermannC** [comment]
Hi @ErwanMeunier , 
thanks a lot for the report and sorry for the late answer. We also provided an answer in the issue linked above.
The UVL parser is now developed in [this fork]( https://github.com/Universal-Variability-Language/uvl-parser) while the original repository is still based on an old version which probably causes the inconsistency .
The parser used in FeatureIDE, which allows less restrictive feature names, is based on the version of [this branch](https://github.com/Universal-Variability-Language/uvl-parser/tree/less-restrictive-ids).
