### ISSUE TITLE
Deleting multiple constraints together does not work correctly

### ISSUE THREAD

**Issue by Rahel12342** [FeatureIDE/FeatureIDE#1342]
#### Prerequisitives
* **Eclipse Version:** Prepackaged FeatureIDE3.8.1
* **FeatureIDE-Version:** 3.8.1
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** jdk-14.0.1
* **FeatureIDE Composer:** Feature Modeling

### Issue description
1. When selecting multiple constraints, the delete function does not work ca. 2 out of 3 times (In the Constraint View as well as in the Feature Diagram).
2. Sometimes when it works, trying to undo it only reconstructs one or zero constraint. When trying to undo the deletion again, an error appears (as shown in the picture).
![image](https://user-images.githubusercontent.com/64740628/165328582-1b00c906-f928-4f33-a9d6-04b0d9b9e304.png)

**Comment by skrieter** [comment]
Fixed
