### ISSUE TITLE
FeatureIDE Library Example Projects use incorrect libraries

### ISSUE THREAD

**Issue by wurstbroteater** [FeatureIDE/FeatureIDE#1375]
#### Prerequisitives
* **Eclipse Version:**  `v3.9.0`
* **FeatureIDE-Version:**  `v4.2.0`
* **Operating system:** `Windows 11`
* **Java runtime used to run eclipse:** `jdk-11.0.10.9-hotspot`

### Issue description
For all FeatureIDE Example Projects of FeatureIDE Library the used libraries are wrong or missing. For example see the attached picture. This is for ExampleProjects/FeatureIDELibrary/FeatureModelTransformation.
![ItsABugNotFeature](https://user-images.githubusercontent.com/25612993/189841545-83674d09-cf71-4a54-aaf2-3104df777070.png)

### Workaround until fixed
- Create the example project as usual
- Manually download newest FeatureIDE.jar from [github.io](https://featureide.github.io/) and uvl parser from [github repo](https://github.com/FeatureIDE/FeatureIDE/tree/9666caac13b4494bcbe773aac5c09569c24a227f/plugins/de.ovgu.featureide.fm.core/lib) 
- Copy the downloaded `.jar`s in the projects lib folder
- In Eclipse -> right click on project -> Build Path -> Configure Build Path -> Replace Missing imports

**Comment by skrieter** [comment]
Unfortunately, the library versions was not updated in the example projects. We will fix this with the next version 3.9.1.
