### ISSUE TITLE
Border is Missing for Imported Constraints in the Constraints View

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#1377]
#### Prerequisitives
* **Eclipse Version:**  `4.20.0`
* **FeatureIDE-Version:**  `3.9.0`
* **Operating system:** `Ubuntu 22.04`

### Issue description
When importing constraints from a submodel in UVL, the constraints have a blue border in the feature model editor to denote they are imported. See second constraint below:
![image](https://user-images.githubusercontent.com/24757266/190182610-e196db33-9343-47ff-b5bd-106741699744.png)
 
In the constraint view, this border (or any other visual indicator) is missing.
![image](https://user-images.githubusercontent.com/24757266/190183016-be475c2a-0a0c-4498-9c43-ca111e496fed.png)

**Comment by skrieter** [comment]
show as extra information in constraint view (new column?)

**Comment by skrieter** [comment]
Introduced new column in constraint view
