### ISSUE TITLE
UVL - After creating a model file manually, FeatureModelManager.getFeatureModelManager() is null

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#1381]
#### Prerequisitives
* **Eclipse Version:**  `4.20`
* **FeatureIDE-Version:**  `3.9`
* **Operating system:** `ubuntu 21.04`

### Issue description

After creating a file via "New File" Dialog (not via "Feature IDE" > "New Model") with UVL file ending, a NPE occurs. When editing the file via text-editor and giving it valid UVL content, the NPE still occurs and no diagram is rendered. Maybe the model creation via new file is an uncommon workflow, but I would say a NPE should not occur. 

For example see XML format on the other hand: when I create an file with XML ending, the diagramEditor seems not to be invoked, respectively not rendered, because the file is treated as normal txt file.

I think this is a minor inconvenience, mainly because Eclipse blocks my interactions with the dialog popping up after each auto-focus (and failed rendering) of the manually created UVL file.

#### How to reproduce:
1. In a new project I create a new file e.g. "test.uvl"
2. After finishing the dialog, the following prompt appears, with two different exceptions thrown.

![grafik](https://user-images.githubusercontent.com/1651709/190900662-a7027de2-d4c6-449a-a0f2-1dcaca66d314.png)

First
```
An error has occurred. See error log for more details.
Cannot invoke "de.ovgu.featureide.fm.core.io.manager.FeatureModelManager.getSnapshot()" 
  because the return value of "de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.getFeatureModelManager()" 
  is null
```

Second
```
An error has occurred. See error log for more details.
Cannot invoke "de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor.removeSelectionChangedListener(
    org.eclipse.jface.viewers.ISelectionChangedListener)" 
  because "editor.diagramEditor" is null
```

Thanks for bringing in the UVL format, so great and thank you again for the tool in general!
Best
Chris

**Comment by skrieter** [comment]
Fixed in 4aa18048712a438e7172a56733c585161aafd939
See #1406 for more information.
