### ISSUE TITLE
Creating a new Project in Eclipse

### ISSUE THREAD

**Issue by ashfaq92** [FeatureIDE/FeatureIDE#1382]
#### Prerequisitives
Eclipse Version:  `2022‑09`
* **FeatureIDE-Version:**  `3.9.0`
* **Operating system:** `MacOS Monterey 12.2.1`
* **Java runtime used to run eclipse:** `11`

### Issue description
An internal error occurred during: "Add Project". 'void org.eclipse.jdt.internal.core.JavaProject.<init>(org.eclipse.core.resources.IProject, org.eclipse.jdt.internal.core.JavaElement)'

**Comment by skrieter** [comment]
Duplicate, see  #1429.
