### ISSUE TITLE
Feature Attributes View Only Offers Conversions for Feature Models

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#1399]
#### Prerequisitives
* **Eclipse Version:**  `4.20`
* **FeatureIDE-Version:**  `3.9.0`

### Issue description
When opening the feature attributes view, while working on a regular configuration the following message is shown:

![image](https://user-images.githubusercontent.com/24757266/205050103-0bc54de5-7bb6-4094-a3c2-26956ad4b899.png)

However, the convert button opens the dialog for feature models offering only to select feature model formats in contrast to configuration formats.
![image](https://user-images.githubusercontent.com/24757266/205050340-e42bdc24-a8c5-40a6-baa6-40d8b72cf7ea.png)

**Comment by tthuem** [comment]
@SundermannC Is this critical for the next UVL tutorial or the exercises in our product-line course? If not, we can move it to a later milestone.

**Comment by skrieter** [comment]
Fixed
