### ISSUE TITLE
Diagnostics for feature dependencies

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#14]
Some diagnostics for feature dependencies would be helpful (like in guidsl). These could explain why I need to select a certain feature although I thought they were independent...

Example file attached. I thought Photo could be selected without Music or Video and it is quite difficult to debug manually.

Example:
https://faracvs.cs.uni-magdeburg.de/projects/tthuem-FeatureIDE/attachment/ticket/306/model.xml

**Comment by tthuem** [comment]
Content of the above file:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
	<featureModel>
		<struct>
			<and abstract="true" mandatory="true" name="Root">
				<feature mandatory="true" name="Base"/>
				<feature name="Favourites"/>
				<and name="Sorting">
					<feature hidden="true" name="SortMusic"/>
					<feature hidden="true" name="SortPhotos"/>
					<feature hidden="true" name="SortVideo"/>
				</and>
				<or abstract="true" name="Media">
					<feature mandatory="true" name="Photo"/>
					<feature mandatory="true" name="Music"/>
					<feature mandatory="true" name="Video"/>
				</or>
				<and abstract="true" hidden="true" mandatory="true" name="Derivatives">
					<feature name="PhotoActionBase"/>
					<feature name="Sms_Or_CapturePhoto"/>
					<feature name="Sms_Or_CaptureMedia"/>
					<and abstract="true" mandatory="true" name="MediaCombinations">
						<feature name="Music_AND_Photo"/>
						<feature name="Music_OR_Video"/>
						<and name="AtLeastTwoMediaTypes">
							<feature name="AtLeastTwoTypes_AND_Photo"/>
							<feature name="AtLeastTwoTypes_AND_Video"/>
							<feature name="AtLeastTwoTypes_AndNot_Photo"/>
							<feature name="AtLeastTwoTypes_And_Music"/>
						</and>
						<feature name="OnlyPhoto"/>
						<feature name="OnlyVideo"/>
						<feature name="OnlyMusic"/>
					</and>
					<feature name="Copy_OR_Sms"/>
				</and>
				<feature name="SmsFeature"/>
				<or name="CaptureMedia">
					<feature mandatory="true" name="CapturePhoto"/>
					<feature mandatory="true" name="CaptureVideo"/>
				</or>
				<and name="CopyMedia">
					<feature hidden="true" name="CopyMusic"/>
					<feature hidden="true" name="CopyPhoto"/>
					<feature hidden="true" name="CopyVideo"/>
				</and>
				<alt abstract="true" mandatory="true" name="ScreenSize">
					<feature mandatory="true" name="S176x205"/>
					<feature mandatory="true" name="S128x149"/>
					<feature mandatory="true" name="S132x176"/>
				</alt>
			</and>
		</struct>
		<constraints>
			<rule>
				<imp>
					<var>SmsFeature</var>
					<var>Photo</var>
				</imp>
			</rule>
			<rule>
				<eq>
					<var>Sms_Or_CapturePhoto</var>
					<disj>
						<var>SmsFeature</var>
						<var>CapturePhoto</var>
					</disj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>Sms_Or_CaptureMedia</var>
					<disj>
						<var>SmsFeature</var>
						<var>CaptureMedia</var>
					</disj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>AtLeastTwoMediaTypes</var>
					<disj>
						<conj>
							<var>Photo</var>
							<var>Video</var>
						</conj>
						<disj>
							<conj>
								<var>Photo</var>
								<var>Music</var>
							</conj>
							<conj>
								<var>Music</var>
								<var>Video</var>
							</conj>
						</disj>
					</disj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>AtLeastTwoTypes_AND_Photo</var>
					<conj>
						<var>AtLeastTwoMediaTypes</var>
						<var>Photo</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>AtLeastTwoTypes_And_Music</var>
					<conj>
						<var>AtLeastTwoMediaTypes</var>
						<var>Music</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>AtLeastTwoTypes_AND_Video</var>
					<conj>
						<var>AtLeastTwoMediaTypes</var>
						<var>Video</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>AtLeastTwoTypes_AndNot_Photo</var>
					<conj>
						<var>AtLeastTwoMediaTypes</var>
						<not>
							<var>Photo</var>
						</not>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>OnlyPhoto</var>
					<conj>
						<var>Photo</var>
						<not>
							<var>AtLeastTwoMediaTypes</var>
						</not>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>OnlyMusic</var>
					<conj>
						<var>Music</var>
						<not>
							<var>AtLeastTwoMediaTypes</var>
						</not>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>OnlyVideo</var>
					<conj>
						<var>Video</var>
						<not>
							<var>AtLeastTwoMediaTypes</var>
						</not>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>Music_AND_Photo</var>
					<conj>
						<var>Music</var>
						<var>Photo</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>SortPhotos</var>
					<conj>
						<var>Photo</var>
						<var>Sorting</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>PhotoActionBase</var>
					<conj>
						<var>Photo</var>
						<disj>
							<var>CopyMedia</var>
							<disj>
								<var>SmsFeature</var>
								<var>CapturePhoto</var>
							</disj>
						</disj>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>Music_OR_Video</var>
					<disj>
						<var>Music</var>
						<var>Video</var>
					</disj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>SortMusic</var>
					<conj>
						<var>Sorting</var>
						<var>Music</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>CopyMusic</var>
					<conj>
						<var>CopyMedia</var>
						<var>Music</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>Copy_OR_Sms</var>
					<disj>
						<var>CopyMedia</var>
						<var>SmsFeature</var>
					</disj>
				</eq>
			</rule>
			<rule>
				<imp>
					<var>CapturePhoto</var>
					<var>Photo</var>
				</imp>
			</rule>
			<rule>
				<imp>
					<var>CaptureVideo</var>
					<var>Video</var>
				</imp>
			</rule>
			<rule>
				<eq>
					<var>CopyPhoto</var>
					<conj>
						<var>CopyMedia</var>
						<var>Photo</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>SortVideo</var>
					<conj>
						<var>Sorting</var>
						<var>Video</var>
					</conj>
				</eq>
			</rule>
			<rule>
				<eq>
					<var>CopyVideo</var>
					<conj>
						<var>CopyMedia</var>
						<var>Video</var>
					</conj>
				</eq>
			</rule>
		</constraints>
		<comments/>
	</featureModel>

**Comment by tthuem** [comment]
@SofiaAnanieva It would be great if you could merge your changes with respect to the explanations soon into the development branch. We would like to create the next version in July.

We should discuss the remaining issues in the next meeting.

**Comment by tthuem** [comment]
Sebastian, due to your recent changes, the branch does not work anymore and cannot be merged. Sofia and I discussed that it is probably most efficient if you both schedule a time for pair programming to merge the branch (i.e., to make the branch work again with your restructuring).

**Comment by tthuem** [comment]
Merged. Thanks to Sebastian and Sofia!
