### ISSUE TITLE
Cant find FeatureIDE in Eclipse Marketplace

### ISSUE THREAD

**Issue by koalamitice** [FeatureIDE/FeatureIDE#1403]
#### Prerequisitives
* **Eclipse Version:**  `2022/06`
* **FeatureIDE-Version:**  `well...`
* **Operating system:** `tried seaching Marketplace in Browser, and inside Eclipse on Windows and MacOS`
* **Java runtime used to run eclipse:** ``
* **FeatureIDE Composer:** ``
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
I had to reinstall my Eclipse today and was not able to find FeatureIDE in the marketplace.
I switched to installing it over the Update Page and everything worked fine. Thought it would be a good idea to inform you, maybe its a general problem!

Cheers,
Domenik

**Comment by tthuem** [comment]
Thanks Domenik.

Right now, FeatureIDE is not compatible with recent Eclipse version, but @skrieter is working on this for the next release. Once this is fixed, FeatureIDE will be added to more recent Eclipse versions in the market place.

**Comment by skrieter** [comment]
Will be fixed for Release 3.9.2 and later.
