### ISSUE TITLE
"Export All Features Models" function only exports one model (and not all selected models)

### ISSUE THREAD

**Issue by koalamitice** [FeatureIDE/FeatureIDE#1404]
#### Prerequisitives
* **Eclipse Version:**  `2022-12`
* **FeatureIDE-Version:**  `3.9.1`
* **Operating system:** `MacOS`
* **Java runtime used to run eclipse:** `OpenJDK 18`
* **FeatureIDE Composer:** ``
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
I imported all CDL examples to my workspace and wanted to convert them to .dimacs all at once.
I selected all models then used -> right click -> FeatureIDE -> Export All Feature Models
In the context menu i selected a random folder on my Desktop and switched the format to dimacs.

Unfortunatly, the exporter only exports the first model in the list of selected model and thus only created one file called "model.xml".

The same behavior seems to be the case when selecting the FeatureIDE (.xml) export format. Probably also happens for all other selectable formats.

**Comment by tthuem** [comment]
Thanks for the report. The export was only designed for a single model so far. A batch export could, however, be done using the FeatureIDE library:

https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.examples/featureide_examples/Library/FeatureModelTransformation/src/de/ovgu/featureide/examples/transformation/FeatureModelTransformation.java

**Comment by skrieter** [comment]
Not technically a bug, but fixed anyway :)
This operation was only intended to export all model files within projects and folders, but not files directly.
Now it it supports both. So you can select any mix of projects, files, and folders.
