### ISSUE TITLE
"No format found" when loading feature model

### ISSUE THREAD

**Issue by RemiN1G** [FeatureIDE/FeatureIDE#1405]
#### Prerequisitives
* **Eclipse Version:**  `4.26.0`
* **FeatureIDE-Version:**  `3.9.1`
* **Operating system:** `Windows`
* **Java runtime used to run eclipse:** `1.8`
* **FeatureIDE Composer:** ``
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
I'm trying to import a feature model to generate random configuration from code but when i try to use the FeatureModelManager like examples: 

`final FileHandler<IFeatureModel> fileHandler = FeatureModelManager.getFileHandler(Paths.get("model.xml"));`

i got the error: 

```
ERROR: No format found for file "model.xml"!
de.ovgu.featureide.fm.core.ExtensionManager$NoSuchExtensionException: No format found for file "model.xml"!
	at de.ovgu.featureide.fm.core.io.manager.AbstractIO.getFileHandler(AbstractIO.java:113)
	at de.ovgu.featureide.fm.core.io.manager.FeatureModelManager.getFileHandler(FeatureModelManager.java:70)
	at main.Main.main(Main.java:24)
```
I also tried with models from example, i got the same.

**Comment by tthuem** [comment]
@RemiN1G Thanks for your report. I'm not sure yet if this indicates an actual error or a wrong use of the API.

Did you try our example projects for the FeatureIDE library?

https://github.com/FeatureIDE/FeatureIDE/tree/develop/plugins/de.ovgu.featureide.examples/featureide_examples/Library

For instance, this one?

https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.examples/featureide_examples/Library/FeatureModelAnalysis/src/de/ovgu/featureide/examples/featuremodelanalysis/FeatureModelAnalysis.java

All example projects an also be imported within an Eclipse with FeatureIDE installed: New > Import > Example...

**Comment by RemiN1G** [comment]
@tthuem Thanks for your reply. I found the problem with this example, i was missing the line:

`LibraryManager.registerLibrary(FMCoreLibrary.getInstance());`
