### ISSUE TITLE
Invalid Configurations UVL Model

### ISSUE THREAD

**Issue by jaqPi** [FeatureIDE/FeatureIDE#1409]
#### Prerequisitives
* **Eclipse Version:**  `2021-06 (4.20.0)`
* **FeatureIDE-Version:**  `3.9.1.202212061324`
* **Operating system:** `macOS 13.2.1`
* **Java runtime used to run eclipse:** `openjdk 19.0.2 2023-01-17`

### Issue description

**Context:** A projected containing a file named `model.uvl` (a workaround as described in #1408). The model contains 36 Features and one imported submodel.

**Goal:** I want to generate 10 valid products.

**Expected Behavior:** FeatureIDE generates 10 xml files within the products directory containing a valid configuration each.

**Observed Behavior:** 10 files have been generated. I can open them. Some configurations are valid, but not all of them. Some are invalid or not completely configured. Unfortunately, this behaviour does not always occur. From my naive point of view, it seems to somehow occur more frequently with increasing model size.

**Workaround:** Export `model.uvl` as `model.xml` within the same project. Now, generation of products results in only valid products.

**Comment by skrieter** [comment]
Related to #1183

**Comment by skrieter** [comment]
Fixed in 4aa18048712a438e7172a56733c585161aafd939
See #1406 for more information.
