### ISSUE TITLE
Improvements of Set Feature Colors Dialog

### ISSUE THREAD

**Issue by jaqPi** [FeatureIDE/FeatureIDE#1411]
#### Prerequisitives
* **Eclipse Version:**  `2021-06 (4.20.0)`
* **FeatureIDE-Version:**  `3.9.1.202212061324`
* **Operating system:** `macOS 13.2.1`
* **Java runtime used to run eclipse:** `openjdk 19.0.2 2023-01-17`

### Issue description

**Color Preview**

![grafik](https://user-images.githubusercontent.com/3995477/224665303-4ae90589-568d-4bfc-b314-fc3fdf6e4ca9.png)

A colored box beside the name of the color would provide a nice preview of the color and would support me to choose an appropriate color for my feature.

**Coloring of Current Selection and all children**

![grafik](https://user-images.githubusercontent.com/3995477/224665811-41e110fb-5456-4c11-9c1e-7825cd9b31e8.png)

Currently, I can choose between `Children (all)` and `Current Selection`. I am missing an option `Current Selection and all children`.

**Comment by Rahel12342** [comment]
The "current selection and all children" function will be added. Anyway, due to limitations of the dropdown menu, we decided that no color preview will be added.
