### ISSUE TITLE
Font Size of Product View Very Small

### ISSUE THREAD

**Issue by jaqPi** [FeatureIDE/FeatureIDE#1417]
#### Prerequisitives
* **Eclipse Version:**  `2021-06 (4.20.0)`
* **FeatureIDE-Version:**  `3.9.1.202212061324`
* **Operating system:** `macOS 13.2.1`
* **Java runtime used to run eclipse:** `openjdk 19.0.2 2023-01-17`

### Issue description

![grafik](https://user-images.githubusercontent.com/3995477/224681262-1ce0b060-ac57-4db7-a6b3-e4a83f49e477.png)

The font size of the product view is very small. It would great if I could adjust the font size to fit my needs.

In the best of all worlds this could be done via CMD + `+` or CMD + `-`. But also somewhere in the Eclipse Settings would be fine.

![grafik](https://user-images.githubusercontent.com/3995477/224682212-7db8f851-9566-4328-8e68-25422bea58b1.png)

**Comment by dev-andreas** [comment]
Font size now adapts to screen resolution. Additionally, I added cleaner color indicators in the configuration view:
![image](https://github.com/FeatureIDE/FeatureIDE/assets/66901404/a60f4060-b438-461e-9580-ed2afd12c8c8)
The font size can also be changed now:
![Untitled](https://github.com/FeatureIDE/FeatureIDE/assets/66901404/3d457bd4-8de7-4a66-a9f9-30c39ef3aac4)

**Comment by skrieter** [comment]
Fixed
