### ISSUE TITLE
Saving an Unchanged Model Moves View

### ISSUE THREAD

**Issue by jaqPi** [FeatureIDE/FeatureIDE#1418]
#### Prerequisitives
* **Eclipse Version:**  `2021-06 (4.20.0)`
* **FeatureIDE-Version:**  `3.9.1.202212061324`
* **Operating system:** `macOS 13.2.1`
* **Java runtime used to run eclipse:** `openjdk 19.0.2 2023-01-17`

### Issue description

**Context:** Graphical View of Feature Diagram.

**Goal:** I want so save my latest changes.

**Expected Behavior:** If there are no changes since the last save, nothing should happen.

**Observed Behavior:** If there are changes to persist and I hit `CMD + S`, the model is saved. Nothing else happens. Instead, if there are no unsaved changes and I use `CMD + S` the current view is shifted to a feature whose name starts with an `S`.

https://user-images.githubusercontent.com/3995477/224683542-d28e9c2d-772f-46a1-8ea3-b677c27ba417.mov

**Comment by skrieter** [comment]
fixed in 2b3a2ad3468fde0e7074d3a8716f927a51eb1183
