### ISSUE TITLE
LaTeX export improvements

### ISSUE THREAD

**Issue by araschke** [FeatureIDE/FeatureIDE#1419]
#### Prerequisitives
* **Eclipse Version:**  2021-06 (4.20.0)
* **FeatureIDE-Version:**    3.9.1.202212061324
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 17.0.6
* **FeatureIDE Composer:** 
* **Git branch/Commit-ID:**  
* **Java compiler used to build the FeatureIDE plugin:** 

### Issue description
The LaTeX-export could be improved:
- The selected layout (top-down, left-to-right, etc.) of the feature model is ignored during export (only top-down). To change the exported layout to "left-to-right", the following lines must be changed/added to the `featureDiagram/.style` in file `head.tex`:  
```
text depth = 0,         % nothing changed
parent anchor = east,   % changed
child anchor = west,    % changed
draw = drawColor,       % nothing changed
edge = {draw=drawColor},% nothing changed
grow' = east,           % changed, ' is important to reverse order!
anchor = west,          % nothing changed
l sep = 2em,            % to look nice
s sep = 1em,            % to look nice
tier/.pgfmath=level()   % necessary for level adjustments
```
- export of constraints would be nice (symbols converted to Math symbols)
- cleanup of feature names  should be included, e.g. & --> \&
- set colors are ignored 
- minHeight of nodes would be good

**Comment by dev-andreas** [comment]
LaTeX now export supports:
* constraints
* feature colors
* custom color meanings
* left-to-right layout

Additionally, features in LaTeX now have a minimum height.

**Comment by skrieter** [comment]
done
