### ISSUE TITLE
Clear Button of Search Box Unreliable

### ISSUE THREAD

**Issue by jaqPi** [FeatureIDE/FeatureIDE#1428]
#### Prerequisitives
* **Eclipse Version:**  `2021-06 (4.20.0)`
* **FeatureIDE-Version:**  `3.9.1.202212061324`
* **Operating system:** `macOS 13.3`
* **Java runtime used to run eclipse:** `openjdk 19.0.2 2023-01-17`

### Issue description

**Context:** The search box of an UVL diagram. I already entered some text.

**Goal:** I want to remove all text from the search box to start a new search.

**Expected Behavior:** Clicking the small (x) at the right end of the search box, I would expect that the search box is cleared.

**Observed Behavior:** The (x) button is unreliable. It takes several clicks to clear the search box.

See video of #1427

**Comment by Rahel12342** [comment]
For me, the (x) button works as it should (on Ubuntu), meaning it deletes the box whenever I press it on multiple tries in a UVL model.

**Comment by skrieter** [comment]
Not reproducible
