### ISSUE TITLE
'Add Project' has encountered a problem. 

### ISSUE THREAD

**Issue by stella-Lee** [FeatureIDE/FeatureIDE#1429]
#### Prerequisitives
* **Eclipse Version: 2022-06(4.24.0)
* **FeatureIDE-Version:3.9.2
* **Operating system:windows 10
* **Java runtime used to run eclipse:jdk-11.0.17
* **FeatureIDE Composer:Antenna, AHEAD
* **Git branch/Commit-ID:
* **Java compiler used to build the FeatureIDE plugin:

### Issue description
When I add an example, the following message box pops up:
![image](https://user-images.githubusercontent.com/41104669/230921577-8c72b8e0-3ce5-4b68-9cfb-d342f2a0561a.png)

And I also can see the following tool tip of "configuration" tag in the ".xml" source:
No grammar constraints (DTD or XML Schema).

**Comment by ekuiter** [comment]
I can reproduce this with "Eclipse with FeatureIDE, JDT, CDT, and AJDT" 3.9.2 on Manjaro Linux (create an empty feature modeling project):
![grafik](https://user-images.githubusercontent.com/4258713/231759084-45f33133-a8cd-47ca-8110-14154dab9777.png)

Subsequently removing the project yields:
![grafik](https://user-images.githubusercontent.com/4258713/231759513-56e3dbf8-7314-40ec-8a5c-f75b43b6db13.png)

For me, a workaround seems to be to add a project, then remove a project, then restart eclipse, and then add a project again. Somehow the error vanishes for me.

**Comment by ekuiter** [comment]
FeatureIDE 3.9.1 is not affected, so use that as a workaround.

**Comment by SundermannC** [comment]
Seems to be caused by the same incompatibility as #1430.

**Comment by skrieter** [comment]
fixed
