### ISSUE TITLE
"New FeatureIDE source file" does not work

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#1430]
#### Prerequisitives
"Eclipse with FeatureIDE, JDT, CDT, and AJDT" 3.9.2 on Manjaro Linux

### Issue description
Create an Antenna project and then a new "FeatureIDE source file" under src. This does not work:

![grafik](https://user-images.githubusercontent.com/4258713/231761299-6260aba6-4ab3-4953-ac42-90167b667b02.png)

If you create a plain text file and try to use feature completion, another exception occurs:
![grafik](https://user-images.githubusercontent.com/4258713/231763834-e24d8e55-bc89-45ee-be4b-4dbc383a3ca8.png)

I think this bug and #1429 are related.

**Comment by ekuiter** [comment]
FeatureIDE 3.9.1 is not affected, so use that as a workaround.

**Comment by skrieter** [comment]
fixed
