### ISSUE TITLE
Feature completion causes crashes

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#1431]
#### Prerequisitives
Eclipse with FeatureIDE, JDT, CDT, and AJDT 3.9.1 on Manjaro Linux

### Issue description

Create an Antenna project and a Java class, then write:

![grafik](https://user-images.githubusercontent.com/4258713/231766325-bd9d3fd1-599a-4989-8620-c210a0f4c663.png)

That is, use feature completion and press <Return> to complete to "Base". Eclipse freezes and crashes after about 2 seconds.

**Comment by skrieter** [comment]
fixed
