### ISSUE TITLE
Use UVL Conversion Strategies to Cope with Unsupported Language Levels

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#1433]
### Issue description
The integrated [UVL Parser 2.0](https://github.com/Universal-Variability-Language/uvl-parser2.0) supports conversion of unsupported language features. This would enable loading UVL models with, e.g., numeric constraints or group cardinality. Currently, FeatureIDE does not use the conversion strategies and, thus, cannot load UVL models which exceed the expressiveness of FeatureIDE.

**Comment by skrieter** [comment]
Fixed
