### ISSUE TITLE
Feature Model Constraints view dashes are interpreted as negation

### ISSUE THREAD

**Issue by mnieke** [FeatureIDE/FeatureIDE#1438]
#### Prerequisitives
* **Eclipse Version:**  2023-03
* **FeatureIDE-Version:**  3.9.3
* **Operating system:** macOS 13.4.1
* **Java runtime used to run eclipse:** --
* **FeatureIDE Composer:** --
* **Git branch/Commit-ID:**  --
* **Java compiler used to build the FeatureIDE plugin:** --

In the "Feature Model Constraints" view, dashes "-" in feature names are interpreted as negation.
![image](https://github.com/FeatureIDE/FeatureIDE/assets/5243830/ea0c925f-d252-42de-9deb-a2f9353d7b73)

**Comment by skrieter** [comment]
Fixed
