### ISSUE TITLE
Option to visualize model based on currently selected configuration

### ISSUE THREAD

**Issue by jellehierck** [FeatureIDE/FeatureIDE#1452]
#### Prerequisitives
* **Eclipse Version:** ` 4.29.0`
* **FeatureIDE-Version:**  `3.10.0` (installed via eclipse marketplace)
* **Operating system:** `Ubuntu 20.04`
* **Java runtime used to run eclipse:** `JRE 17.0.8`
* **FeatureIDE Composer:** `Feature Modeling`
* **Git branch/Commit-ID:**  -
* **Java compiler used to build the FeatureIDE plugin:** -

### Issue description
It would be nice to get an option to view a "pruned" Feature Diagram based on the currently selected configuration. 

I would like to show part of my model to collaborators based on the current configuration. The Configuration editor allows me to do so, but is not visually intuitive to collaborators, especially if they have no experience with FeatureIDE. Especially with very large feature models, this helps removing much clutter.

The options I thought of are listed below (feel free to add more ideas), and I added some examples for each in the section below:

|  Original model | Selected configuration  |
|---|---|
| ![image](https://github.com/FeatureIDE/FeatureIDE/assets/35225288/cd9d242e-73d9-4a04-8014-5d8ae6072ea7)  | ![image](https://github.com/FeatureIDE/FeatureIDE/assets/35225288/3405f2c9-51ca-4297-988c-ec04431c7f8c)   |

1. Use border styles to indicate which features are selected
   - e.g. thick borders around selected features
   - e.g. dashed borders around unselected features
   - (I did not create an example for this)
2. Use colors to indicate which features are selected in the configuration 
   - e.g. color selected features in dark blue
   - e.g. color unselected features in grey
   - probably not ideal as this could interfere with existing Feature Colors and `abstract` qualifiers
   ![image](https://github.com/FeatureIDE/FeatureIDE/assets/35225288/4a54ef12-f5ea-4f6d-bf8b-977cc8417ed5)
3. Remove all features which are not selected in the configuration
   -  probably not ideal as this would remove information about `optional` / `mandatory` features
   ![image](https://github.com/FeatureIDE/FeatureIDE/assets/35225288/42f3a5b9-2a91-4484-b765-ba45d05de897)

**Comment by dev-andreas** [comment]
I added a new tab in the configuration page called _Configuration Tree_. This tree will collapse all unselected features:
![image](https://github.com/FeatureIDE/FeatureIDE/assets/66901404/9f502f7d-af5f-475f-ab62-20178425c286)
![image](https://github.com/FeatureIDE/FeatureIDE/assets/66901404/d0e9c908-67ac-4614-ac65-a512a57db0a9)

**Comment by skrieter** [comment]
done
