### ISSUE TITLE
ConfigurationEditor does not update after feature model change

### ISSUE THREAD

**Issue by dev-andreas** [FeatureIDE/FeatureIDE#1464]
#### Prerequisitives
* **FeatureIDE-Version:**  3.10
* **Operating system:** MacOS

When changing the relationship between child and parent (_and/or/alternative, mandatory/abstract/hidden_) and when saving, the icons on the _Advanced configuration page_ are not updated accordingly.

Sound doesn't work in the web video player. You must download the video.

https://github.com/FeatureIDE/FeatureIDE/assets/66901404/4f2485ff-7917-4fac-9a1d-635fdbad6930

**Comment by skrieter** [comment]
Fixed in d523ff1e4a46a27105a7d17381770eb0a7fceed0
