### ISSUE TITLE
Add support to cancel jobs

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#148]
Currently, jobs cannot be canceled. Support to cancel jobs manually should be added where it is possible.

**Comment by kTonscheidt** [comment]
AStoppableJobs should be cancelable(de.ovgu.featureide.fm.core.job.AStoppableJob ).

**Comment by kTonscheidt** [comment]
Can this be closed? 

If the functionality of AStoppableJob does not suffice, what needs to be done?

Should all Jobs instantiated by FeatureIDE be cancelable? Do they only need to be cancelable in the code, or should the user be able to cancel them during runtime?

**Comment by tthuem** [comment]
All jobs that have a runtime of - let's say - more than 1 second should be cancellable by the user of FeatureIDE. Currently, opening large project often requires to restart Eclipse, which could be avoided.

If possible, even all jobs could be cancellable.

**Comment by pinnecke** [comment]
The following table lists jobs, that are currently not stoppable. We should discuss further steps in the meeting.

| File | Type | Name |
| ---- | ---- | ---- |
| FeatureProject | AJob | "Postprocess generated files" |
| CollaborationView | AWaitingJob | "Update Collaboration View" |
| Generator | Job | "Generator" |
| FeatureCppWrapper | UIJob | "" |
| ConstraintTextValidator | UIJob | "Checking complete." |
| ConstraintTextValidator | UIJob | "Updating results for redundancy..." |
| ConstraintTextValidator | UIJob | "Updating results for dead features..." |
| ConstraintTextValidator | UIJob | "Updating results for false optional features..." |
| ConstraintTextValidator | UIJob | "Updating results for voids model..." |
| ConstraintTextValidator | UIJob | "Updating results for satisfiable check..." |
| ConstraintTextValidator | UIJob | "Updating results tautology check..." |
| ConstraintTextValidator | UIJob | "Starting up..." |
| FeatureDiagramEditor | UIJob | "Updating feature model attributes" |
| FeatureDiagramEditor | UIJob | "Updating feature model attributes" |
| FeatureModelEditView:UIJob | "Converting Feature Models" |
| GEFImageWriter | UIJob | "Save image" |
| ViewContentProvider | UIJob | "Refresh edit view" |
| CheckBoxListener | UIJob | "Refresh export dialog" |
| CheckBoxTreeViewDialog | UIJob | "init dialog - treeviewer" |
| CollaborationView | UIJob | "Update Collaboration View" |
| ContentProvider | UIJob | "Refresh statistics view" |
| CsvExporter | UIJob | "show errordialog/show dialog" |
| CsvExporter | UIJob | "" |
| JobDoneListener | UIJob | "Refresh statistics view" |
| JobDoneListener | UIJob | "Refresh statistics view" |
| NewFeatureProjectWizard | UIJob | "Creating Android project" |
| Outline | UIJob | "Update Outline View" |
| TestRunner | UIJob | "open (file)" |
| TreeClickListener | UIJob | "resort node" |
| ConstraintTextValidator | ValidationJob | "Running additional checks..." |
| AheadWrapper | Job | "Propagate problem markers for (...)" |
| AntennaPreprocessor | Job | "Propagate problem markers for (...)" |
| AHEADToFeatureHouseConversion | Job | "Change composer." |
| FeatureHouseToAHEADConversion | Job | "Change composer." |
| FeatureCppWrapper | Job | "Propagate problem markers for (...)" |
| ErrorPropagation | Job | "Propagate problem markers for (...)" |
| FeatureHouseComposer | Job | "Call compiler" |
| Munge | Job | "Propagate syntax markers" |
| MungePreprocessor | Job | "Propagate problem markers for (...)" |
| MungePreprocessor | Job | "preprocessor annotation checking" |
| CorePlugin | Job | "Add Project" |
| FeatureProject | Job | "Load Model" |
| ProjectChangeListener | Job | "Remove project" |
| CollaborationView | AWaitingJob | "Update Collaboration View" |
| ExportCNFHandler | Job | "Export to CNF" |
| ExportDIMACSHandler | Job | "Export to DIMACS" |
| FeatureDependenciesHandler | Job | "Calculating Feature Dependencies" |
| FeatureDiagramEditor | Job | "Analyze feature model (waiting)" |
| FeatureModelEditView | Job | "Updating Feature Model Edits" |
| FeatureModelEditView | Job | "Updating Feature Model Edits" |
| FeatureModelEditView | Job | "Evaluation Test" |
| FeatureModelEditView | Job | "" |
| FeatureModelEditView | Job | "Updating Feature Model Edits" |
| ViewContentProvider | Job | "Calculate:..." |
| ViewContentProvider | Job | "Calculate:..." |
| ViewContentProvider | Job | "Calculate:..." |
| ConfigurationBuilder | Job | "" |
| CsvExporter | Job | "Export statistics into csv" |
| FeatureStatisticsView | Job | "Updating FeatureStatisticsView" |
| FeatureStatisticsView | Job | "Updating FeatureStatisticsView" |
| QuickFixMissingFeatures | Job | "Create missing configurations." |
| QuickFixMissingConfigurations | Job (Inh. from QuickFix) | "" |
| QuickFixMissingFeatures | Job (Inh. from QuickFix) | "" |

**Comment by tthuem** [comment]
In the last time, I did not experience the problem of unstoppable jobs. If it occurs again, we can reopen the issue and use the table to find the corresponding job.
