### ISSUE TITLE
Specifying Timeout for FeatureModelAnalyzer

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#1480]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.11.1`

### Issue description
When using the FeatureIDE library, the FeatureModelAnalyzer encapsulates the available analyses in FeatureIDE.
However, when using its interface it is not possible to set a timeout, neither overall nor for the single analyses. 
Since some analyses are only trivially accessible over the FeatureModelAnalyzer, it is difficult to use those with a custom timeout.
It would be helpful to have a global timeout and/or setting timeout for specific analyses when using the FeatureModelAnalyer.

**Comment by skrieter** [comment]
For most analysis methods in the FeatureModelAnalyzer there is now an overloaded method where a timeout in ms can be specified.
