### ISSUE TITLE
IFeatureModel ID after using IFeatureModel.clone()

### ISSUE THREAD

**Issue by mnieke** [FeatureIDE/FeatureIDE#1482]
#### Prerequisitives
* **Eclipse Version:**  -
* **FeatureIDE-Version:**  3.11.1
* **Operating system:** -
* **Java runtime used to run eclipse:** -
* **FeatureIDE Composer:** -
* **Git branch/Commit-ID:**  -
* **Java compiler used to build the FeatureIDE plugin:** -

Hi,
we have the following situation:
We have FeatureModel A, then call A.clone() to retrieve FeatureModel B.
Afterwards, we modify FeatureModel B.
When we tried to store both models in a HashMap, we couldn't.
The reason: both have the same "id" (as the original id is reused in the clone method / constructor).

Also, this id is used in the "equals" method -> if I compare both, the result is "true" (although I could have changed model B entirely).

-> when cloning, I would expect the clone to have a new ID.

**Comment by skrieter** [comment]
Hi @mnieke 
This is the intended behavior. Normally, we need the same ID to use the cloned model within the GUI framework.
I added a new clone method that allows you to clone a feature model with a new ID.
```
IFeatureModel#clone(boolean copyId)
```
When cloning, set this parameter to `false` (default value is `true`)
