### ISSUE TITLE
Enabling Partial Feature Project Builder for a New Composer

### ISSUE THREAD

**Issue by tsanny** [FeatureIDE/FeatureIDE#1489]
#### Prerequisitives
* **Eclipse Version:**  `2023-12 (4.30.0)`
* **FeatureIDE-Version:**  `3.11.1.202409252258`
* **Operating system:** `Windows 11`
* **Java runtime used to run eclipse:** `Java 17`
* **FeatureIDE Composer:** -
* **Git branch/Commit-ID:**  [release3.11.1](https://github.com/FeatureIDE/FeatureIDE/tree/release3.11.1)
* **Java compiler used to build the FeatureIDE plugin:** -

### Issue description

Hello FeatureIDE team.

I am currently developing a composer that has support for generating subset product lines from partial configurations. When I create a project with the composer, then try right-clicking a configuration file, the 'Use the selected Configuration to derive a Partial Feature Project' option does not appear.

As it turns out, the option appears when I manually add the composer to the file `plugins/de.ovgu.featureide.ui/plugin.xml`, similar to the implementation in commit [13e613a](https://github.com/FeatureIDE/FeatureIDE/commit/13e613a229f0f3de970e19d5d1f7a699fd80e057#diff-b169f5df527c7a0eba7ba6371b40b3e8e8c32593abbd5823cd29384836afa143R1172):

```
...
   <command
         commandId="de.ovgu.featureide.ui.commands.buildPartialProject"
         icon="icons/FeatureIconSmall.ico"
         id="de.ovgu.featureide.fm.ui.actions.buildPartialProject"
         label="Derive Partial Feature Project with this Configuration"
         style="push"
         tooltip="Use the selected Configuration to derive a Partial Feature Project">
      <visibleWhen
            checkEnabled="false">
         <with
               variable="activeMenuSelection">
            <and>
               <or>
                  ...
                  <iterate
			ifEmpty="false"
                        operator="or">
                            <test
                                args="de.ovgu.featureide.core.my.composer"
                                property="de.ovgu.featureide.fm.ui.properties.composer">
                            </test>
		  </iterate>
               </or>
            </and>
            <reference
                  definitionId="de.ovgu.featureide.fm.ui.expressions.containsOnlyConfiguration">
            </reference>
         </with>
      </visibleWhen>
   </command>
...
```

I'm wondering if it is possible to display the option without making any changes to FeatureIDE's `plugins/de.ovgu.featureide.ui/plugin.xml` file. I would highly appreciate your assistance in this matter.

Thank you in advance, FeatureIDE team.

**Comment by skrieter** [comment]
Hi @tsanny ,

thanks for the suggestion. I modified the test in the `plugin.xml` to be more generic in 9206879a6809e4665e851c530f9a8ca6eeb7d99a.

Since every composer that supports partial feature project building must implement the methods `IComposerExtensionClass#buildPartialFeatureProjectAssets` and `IComposerExtensionBase#supportsPartialFeatureProject`, the test now uses this information.
So now it suffices if your composer returns true here: `IComposerExtensionBase#supportsPartialFeatureProject`.
