### ISSUE TITLE
Create new prepackaged FeatureIDE for Linux and Mac

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#166]
For the website, we should provide a prepacked installation of FeatureIDE for Linux for a recent version of FeatureIDE (2.7.2+). Possibly for Mac, too.

**Comment by pinnecke** [comment]
We discussed that Thomas and me do this together, didn't we?

**Comment by tthuem** [comment]
Yes, we should do this right after creating the next version.

**Comment by pinnecke** [comment]
All open issues related to Milestone 2.7.4 that are assigned to me, are in review or solved. As I understood, you will create the next version and afterwards, you'll give me a best practise on how to create new versions in order to enable me to create prepackaged FeatureIDE for Linux (and Mac) for next versions.

**Comment by tthuem** [comment]
Here is what needs to be done to prepare the versions for Linux and Mac:

1. Download "Eclipse IDE for Eclipse Committers" 32bit mandatory, 64bit optional
2. Open the workspace "../workspace"
3. Install AJDT http://download.eclipse.org/tools/ajdt/44/dev/update
4. Install CDT http://download.eclipse.org/tools/cdt/releases/8.6
5. Install all features of FeatureIDE
6. Add a folder with our slides for documentation

Then, I downloaded the Eclipse platform (much smaller download) in addition and repeated all steps, with the following changes:

1.
2.
3. skip
4. skip
5. Install Feature Modeling and FeatureIDE
6.

**Comment by tthuem** [comment]
Here is what I selected for CDT and AJDT

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/14686223/091c2be2-0738-11e6-870b-7dac78a804ca.jpg)

![zwischenablage-2](https://cloud.githubusercontent.com/assets/5330357/14686227/0dc908f4-0738-11e6-8255-1f1573ffbcf6.jpg)

**Comment by tthuem** [comment]
Who can create the four versions for Mac? Who for Linux?

**Comment by tthuem** [comment]
Alexander will create the version for Linux. Who can create the version for Mac?

**Comment by pinnecke** [comment]
I will with support of Sebastian.

**Comment by pinnecke** [comment]
Feature IDE 3.0 (Mac and Linux version) is now available, see webpage.
