### ISSUE TITLE
Feature Model Layout defect

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#172]
1) The circles for alternatives are not printed correctly (See attachment 2)
2) I changed the leayout from "left to right" to "Top Down" and the ancors are on the wrong place (See attachment 1)
![drawdefect2](https://cloud.githubusercontent.com/assets/1482595/5504459/d8dcf33c-8784-11e4-8b72-0ae5cee617cf.PNG)
![drowdefects](https://cloud.githubusercontent.com/assets/1482595/5504460/d8dd3d4c-8784-11e4-9214-a59221e0f4ab.PNG)

**Comment by tthuem** [comment]
1) Is a problem of the export to vector graphics only.
2) This defect is quite old, but I was not able to deterministically reproduce this error. It does not seem to happen always, right? Do you know how to reproduce it?

**Comment by tthuem** [comment]
How can this issue be in progress if there is no assingee?

**Comment by meinicke** [comment]
"This defect is quite old, but I was not able to deterministically reproduce this error. It does not seem to happen always, right? Do you know how to reproduce it?"
I can always reproduce it. Just zoom in. Seems to only affect alternatives what is qute stange as or-groups should have a similar implementation.

The mandatory and optional dots semm always to get cut a bit.

**Comment by tthuem** [comment]
Sure that you did not mixed up your two issues?

1) Do the wrong drawings occur in both, exports and zooming? Is the image that you uploaded a screenshot or an export?
2) On my machine, changing the layout from top-bottom to left-right layout does _mostly_ work, but not always.

**Comment by meinicke** [comment]
"2) On my machine, changing the layout from top-bottom to left-right layout does mostly work, but not always."
update to the last version and check this again

**Comment by tthuem** [comment]
1) Drawing alternatives seems to work for me. Jens, can you reproduce the wrong behavior? If not, please close the issue.
2) I played around with the editor for quite some time and it did not happen anymore. I would consider this as fixed. Note, that this is also duplicate to Issue #103.

**Comment by meinicke** [comment]
just zoom in if your resolution is too high

**Comment by tthuem** [comment]
Already tried zooming, everything drawn correctly with the following configuration:

Eclipse for RCP and RAP Developers
Version: Juno Service Release 2
Build id: 20130225-0426
FeatureIDE	2.7.2.201501200400

But as it still occurs on your machine, we should investigate this (but for the next version).

**Comment by tthuem** [comment]
org.eclipse.gef 3.9.0.201212170307

**Comment by meinicke** [comment]
I have 3.9.100.201408450207

**Comment by FeatureIDE** [comment]
fixed in https://github.com/FeatureIDE/FeatureIDE/commit/fb2d13bfb718353d118651abc2a48e7bc7b23a9a
