### ISSUE TITLE
Improvements for the configuration editor

### ISSUE THREAD

**Issue by pinnecke** [FeatureIDE/FeatureIDE#183]
## Removing configurations needs to trigger computation of unused features

Not only adding and editing configurations can change the list of unused features, but also the removal. Make sure that all cases are updated correctly.

**Comment by tthuem** [comment]
Removed the following, as already implemented:

**Expand/Collapse all option**
see #15

**Comment by tthuem** [comment]
Already done in the meantime:

## XML format to store configuration decisions

Currently, we store all selected and deselected features including propagated features. The new format could only save manual selections, but would require to create the intermediate format for each composer.

**Comment by Kogoro** [comment]
Already solved in the meantime:
## Whether the configuration is valid or not disappears when the window width is too small

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/18326006/29066178-7544-11e6-9ef1-b21d2acde96e.png)

**Comment by tthuem** [comment]
All issues done
