### ISSUE TITLE
Replace LinkedList by ArrayList in Prop4J

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#188]
This will most probably speed up many calculations within FeatureIDE.

**Comment by tthuem** [comment]
see https://github.com/tthuem/FeatureIDE/tree/master/plugins/de.ovgu.featureide.fm.core/src/org/prop4j

**Comment by tthuem** [comment]
Furthermore, remove code clones introduced for the removal of hidden features (opposed to removal of abstract features)

**Comment by meinicke** [comment]
change had no measurarable effect.
