### ISSUE TITLE
Wrong counter examples when comparing feature models

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#191]
The following change from left to right feature model is indeed a generalization:

![generalization-bug](https://cloud.githubusercontent.com/assets/5330357/6037251/cb08f14c-ac51-11e4-8ab4-a64e1e104e49.png)

The first feature model is equivalent to (A) and the second is equivalent to (A or B). That is, newly added configurations/products are those that have B, but not A. However, the selection of abstract features is not correctly shown in the counter examples. The feature CNF is mandatory but not selected.

**Comment by skrieter** [comment]
How should abstract features be handled for this problem in general, since the view shows products and not variants?
Wouldn't it be best to hide unnecessary abstract features?

**Comment by tthuem** [comment]
It would be better to hide the icons or show at least valid selection values (instead of wrong ones). Hiding the features could be counter intuitive. That issue is not that important, go for the fastest solution.

**Comment by tthuem** [comment]
Seems to be related to #347 

@AlexanderKnueppel Can you check whether this is an instance of the same problem? Any ideas for resolving the issue?

**Comment by tthuem** [comment]
Could be related to #264

**Comment by tthuem** [comment]
@Subaro Why is it assigned to us?

**Comment by SundermannC** [comment]
This issue seems to be resolved. The added products that are displayed are now as expected.
