### ISSUE TITLE
Do not create src and bin folder for Feature Modeling projects

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#201]
As the projects created only for feature modeling do not have a Java nature, it makes no sense to me to create these folder for source code.

**Comment by anb0s** [comment]
I see the same in my "Feature Modeling Only" projects. Addionally folder "configs" is created in my project, although i've changed it to other folder in properties.

**Comment by tthuem** [comment]
Yes, but the folder "configs" is intentional, as you can create configurations in a feature model project. Or did I misunderstood you?

**Comment by anb0s** [comment]
Yes, but i've changed the name in project properties from default name "configs" to e.g. "CSI_Config/configurations/client_blocks". The folders "src" and "configs" are not used in my project (empty) but are created from FeatureIDE plugin:
![featureide-configs-folder](https://cloud.githubusercontent.com/assets/95811/6081046/aac04860-ae16-11e4-9987-2cdd1708593f.png)

**Comment by tthuem** [comment]
Indeed, that seems to be a related bug. Is that really a FeatureIDE project? If yes, which generator is used? (Can be seen in the statistics view.) If yes (again), I'm suprised that the FeatureIDE project decorator is not visible.

**Comment by anb0s** [comment]
I've just tried the nightly build and cannot reproduce my problem with created "configs" folder anymore.
The F-IDE nature was set but the icon was not there before, now after update it shows the "f" icon.

**Comment by anb0s** [comment]
The initial problem with creating bin and src folders for new projects for "Feature Modeling" only is still there.
