### ISSUE TITLE
[MPL] configurable path to interfaces

### ISSUE THREAD

**Issue by anb0s** [FeatureIDE/FeatureIDE#221]
See issue #220 too

All interfaces must be placed in folder "<project-root>\Interfaces". For our project i have to put it in subfolder, but then it cannot be found in mpl.velvet file, error message: "No interface for Chat could be found.".

It should be possible to define the path to the "interface" file (other included model file). May be directly in mpl.velvet file:

concept MPLChatTest : MPLChatTest
interface Chat("subfolder\Chat.velvet") chat, Chat chat2 {
	feature MPLChatTest.Base {
		use chat;
	}
	use chat2;
}

**Comment by tthuem** [comment]
I guess we do not aim to change the Velvet format in the near future.

@skrieter Is that still a problem or is there at least a workaround?

**Comment by RSchroeter** [comment]
In the commit da8dab4b5056a85544364eeea320dd9d40e20e7f, we changed the grammar of Velvet. Now it is possible to use an import for the reuse of a specific model (relative to the project root). In your case, you can write 
`import subfolder.Chat;`
`concept MPLChatTest ...`

**Comment by anb0s** [comment]
cool :) verified with nightly build version: Feature Modeling 3.0.1.201607200400

Thanks!

**Comment by tthuem** [comment]
Thank you, for your feedback!
