### ISSUE TITLE
[MPL] working with own project / migrating from one model to multiple

### ISSUE THREAD

**Issue by anb0s** [FeatureIDE/FeatureIDE#222]
See issues #220 and #221 too.

I'm trying to convert my "Feature Modeling Only" project to MPL project and split one big "project model" to many "component models". Then i want to use local constraints in components and global constraints in my project. So the main mpl.velvet project file should include (via reference or interface) all component models.

## Try to convert with described menue entry "FeatureIDE -> Convert to Multi Software Product Line" ##
I see only one entry in project menue "FeatureIDE -> Product Generator". My project has "de.ovgu.featureide.core.featureProjectNature" but there is no "FeatureIDE -> Convert to Multi Software Product Line" available. Just added "<nature>de.ovgu.featureide.core.mpl.MSPLNature</nature>" manually to .project and reloaded it.

## Converting old model.xml to velvet ##
Executed "FeatureIDE -> Export model to VELVET format" and saved the file to "Interfaces" folder.
Try to open the velvet file --> only "Source" can be see, not possible to switch to "Feature Order" or "Feature Diagram". There is an error in one description entry:
![featureide-mpl-velvet-export-description-error](https://cloud.githubusercontent.com/assets/95811/6466780/5a59bc5e-c1ca-11e4-984b-3606d21c7ca4.png)

Fixed the line ( changed internal " to ' ) and saved the file:
![featureide-mpl-velvet-export-description-error-fixed](https://cloud.githubusercontent.com/assets/95811/6466813/94fbe116-c1ca-11e4-9c94-1c021844ff8b.png)

Now the "Fature Diagram" and "Feature Order" editors are working!

Changed Layout to "Left To Right" and saved the file. Selected "Source" editor and surprise, surprise ;) it looks very small, empty:
..
concept MyVerySecureProject {
}
..
--> the same issue can reproduced if i change something other in the model. There is something wrong with "description fileds" !? Now exported again and removed all description fileds manually from velvet file (very long task, because i'm using it often). It looks better now...

**Comment by skrieter** [comment]
In the newest version of FeatureIDE there should be an entry to convert the project and add the MPL nature (It's not recommended to do this manually, because there are more changes necessary than just adding the nature).  
The problem with the " symbols should now be fixed with the last commit.  
Most actions within the UI editor for MPL feature models are not supported right now and should be avoided:
* For changes to the underlying model, you can normally edit the model.xml
* For changes to the velvet model, please use the text editor and edit the file manually

**Comment by anb0s** [comment]
Thanks. But there is no "FeatureIDE -> Convert to Multi Software Product Line" entry for my project. May be there is something missing, i've only this installed:

Eclipse Luna SR2 4.4.2 (32Bit)
Windows 7 (64Bit)
JDK / JRE 1.8.0_31 (32Bit)
FeatureIDE + Feature Modeling (only, no other FIDE plugins) 2.7.2.201503021452

**Comment by anb0s** [comment]
I've installed nightly build 2.7.3.201503120400 and FeatureHouse, now MPL menues are there ("FeatureIDE -> Convert to Multi Software Product Line"). Just converted the project to MPL and will report about my test. Thanks!

**Comment by tthuem** [comment]
Seems to be fixed. Please reopen, if there is still a problem.
