### ISSUE TITLE
Colligens doesn't generate executable based on given configuration

### ISSUE THREAD

**Issue by andykenner** [FeatureIDE/FeatureIDE#223]
We build a small example with the colligens composer. After introducing #ifdefs surrounding some simple printf(); calls, we selected some features randomly. After setting this configuration as "current configuration" using the context menu, the build process was executed an the .exe was generated successfully. The executable doesn't contain the expected behaviour. The console showed "test1 NOT", we expected something like test1test3, because those features were selected in the config.

```C
#include <stdio.h>
#include <stdlib.h>

int main(void) {
	
#ifdef test1
	printf("test1");
#else
	printf("test1 NOT");
#endif

#ifdef test2
	printf("test2");
#endif

#ifdef test3
	printf("test3");
#endif
	return EXIT_SUCCESS;
}
```

**Comment by tthuem** [comment]
Hi Thiago, can you have a look at this example and help to find the cause of that problem?

**Comment by andykenner** [comment]
Some additional details:

First try:

new-featureide-project->composer colligens, adding a test.c, adding some features to the model
--> this situation was given
![image](https://cloud.githubusercontent.com/assets/8641920/6506769/b0de7dba-c34d-11e4-8198-63a4e305cd2f.png)

after chosing set cofiguration as current nothing happens

using the product generator with the option all current products follwing error happend

![image](https://cloud.githubusercontent.com/assets/8641920/6506804/f461fbfc-c34d-11e4-8f79-47f4b337c47d.png)

but FIDE also said he generates all product successfully
after closing the error message and selecting the generated current config via context menu "set as current config" FIDE generates the executable and it works fine

**Comment by andykenner** [comment]
The second way:

Following the tutorial webcast from the colligens website:

First add a std c-project and added the FIDE IDE for the colligens composer, everything looks fine, no error makers

![image](https://cloud.githubusercontent.com/assets/8641920/6506974/2cc11b94-c34f-11e4-9929-2cc84b7ce115.png)

its the identically source code and feature model

chosing the shown config as current, the exe is generated but as said the issue description it doesn't contain the right feature code, it seems that all of the features are undefinied

a workaround was to generate the current variant with the help of the product generator, choosing the new config file as current. FIDE generates a preprocessed file and the executable seems to contain the correct feature code. For our example it prints the correct output to the console.

**Comment by tthuem** [comment]
I had similar problems with the Colligens hello world example in FeatureIDE 2.7.5. There is simply no output, independent of the configuration. It seems to me that all features are always deselected.

**Comment by andykenner** [comment]
The error is fixed now. The features selected in the configuration are passed correctly to the colligens composer.
Code branch:
**https://github.com/FeatureIDE/FeatureIDE/tree/issue_223**

**Comment by pinnecke** [comment]
Colligens composer is not listed in composer selection dropdown list in new feature project wizard. Please check

**Comment by ckruczek** [comment]
@pinnecke Not reproducable. I am able to select the Colligens composer properly
