### ISSUE TITLE
Current-configuration marker not set for configurations of generated product

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#241]
1. Generate products (e.g., all valid)
2. Set the configuration of on of these products to be the current configuration

-> the pen is not set to the selected configuration 1. Generate products (e.g., all valid)

**Comment by tthuem** [comment]
@meinicke Is this still reproduceble? What are your plans with this issue?

**Comment by meinicke** [comment]
works for me
