### ISSUE TITLE
Products returned by "calculateExample" of class "ModelComparator"

### ISSUE THREAD

**Issue by parcaini** [FeatureIDE/FeatureIDE#264]
Model

![altopt](https://cloud.githubusercontent.com/assets/12829806/8082725/8b21da6c-0f7f-11e5-8da3-d937f7a0030b.png)

is a generalization of model

![alt](https://cloud.githubusercontent.com/assets/12829806/8082729/950e7404-0f7f-11e5-809f-74f9c4b075ed.png)

In the first model, every configuration is a product, whereas in the second model only four configurations are products.

I need to obtain all the products added in the generalization. Method "calculateExample" of class ModelComparator seems suitable for obtaining them.
However, running the following test does not return all the added products, but only a subset. Indeed, I am expecting to retrieve 12 added products, but I get only 5 of them.

Is this the expected behaviour (i.e., I have wrongly understood the behaviour of "calculateExample"), or should it be considered a fault?

Thank you
Best regards,
PA

``` java
@Test
public void testForFeatureIDEaddedProducts() throws FileNotFoundException, UnsupportedModelException, TimeoutException {
    FeatureModel fm = read("alternative.xml");
    FeatureModel fmGen = read("optional.xml");
    ModelComparator comparator = new ModelComparator(1000000);
    Comparison comparison = comparator.compare(fm, fmGen);
    assertEquals(Comparison.GENERALIZATION, comparison);
    Set<String> addedProducts = new HashSet<String>();
    Configuration c;
    while((c = comparator.calculateExample(true)) != null) {
        System.out.println(c);
        addedProducts.add(c.toString());
    }
    assertEquals(12, addedProducts.size());
}

private static FeatureModel read(String path) throws FileNotFoundException, UnsupportedModelException {
    FeatureModel fm = new FeatureModel();
    AbstractFeatureModelReader reader = new XmlFeatureModelReader(fm);
    reader.readFromFile(new File(path));
    return fm;
}
```

**Comment by tthuem** [comment]
Thanks for your bug report. Could you please indicate the version of FeatureIDE and Sat4J installed on your system?

**Comment by parcaini** [comment]
FeatureIDE 2.7.3
Sat4J 2.3.5.v20130525

Best regards,
PA

**Comment by tthuem** [comment]
You are right, this is an incorrect output of FeatureIDE. I was able to reproduce it with the development version and SAT4J Core 2.3.5.v201308161310. As this functionality in FeatureIDE is just a wrapper for the SAT solver, we will investigate whether the cause is wrong usage of the Sat4J or a fault in Sat4J.

**Comment by SundermannC** [comment]
The method calculateExample works as intended. It is used to identify a generalization (or a specialization) and inherently computes some examples as a proof. It may be interesting to add a function that computes all added/removed configurations. We consider adding such a functionality later.

**Comment by tthuem** [comment]
That the list of returned configurations is not complete (i.e., only examples are computed) is likely due to the heuristics being used for a faster computation. In particular, a subset of all clauses is used to generate counter examples. More details on the heuristic can be found elsewhere: http://www.cs.utexas.edu/ftp/predator/ICSE2009.pdf
