### ISSUE TITLE
Configuration is indicated as invalid although it is valid

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#271]
A project that worked fine in FeatureIDE about five weeks ago illustrates a bug now:

https://github.com/TUBS-ISF/spl2015.benedicte.lagouge/tree/master/benedicte-lagouge-Task1

Just opened the project and all configurations are marked as invalid in Package Explorer. However, the configuration editor says they are valid and they were some weeks ago in both.

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/8252945/000864f6-168b-11e5-8843-85969f62daee.png)

**Comment by tthuem** [comment]
Same bug, other example:

https://github.com/TUBS-ISF/spl2015.stefan.muehlbauer/tree/master/Stefan-Muehlbauer-Task1

**Comment by meinicke** [comment]
seems to be related to https://github.com/tthuem/FeatureIDE/issues/296

**Comment by tthuem** [comment]
@skrieter Is that fixed already? Seems to be urgent for our tutorial at SPLC.

**Comment by Kogoro** [comment]
I checked the two examples with the latest nightly build, but the bug does not appear in my case. All configs are valid from the beginning.

**Comment by tthuem** [comment]
Seems to be fixed then, reopen if it still occurs.
