### ISSUE TITLE
Background colors for preprocessed Munge code

### ISSUE THREAD

**Issue by belkinot** [FeatureIDE/FeatureIDE#288]
Preprocessing Annotations and Highlighting needs to be implemented for the generated file.

**Comment by tthuem** [comment]
Please provide some more background on the problem and the envisioned solution. Generation of the current configuration? Generation of multiple products? What is the use case of annotations there?

**Comment by belkinot** [comment]
Annotations and Highlighting for the current configuration.

**Comment by tthuem** [comment]
Too few data provided on the use case of such functionality. Please feel free to reopen or comment, if this is still of interest. Thanks.
