### ISSUE TITLE
Implement support for runtime variability - New Composer Extension

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#294]
- how are variales handled? e.g., main() arguments, Configuration files
- check for inconsistent usage of configuration options
- background colors (+ further color support)
- testing (product based - variability-aware?)

**Comment by tthuem** [comment]
Milestone? Software project? Thesis?

**Comment by tthuem** [comment]
Some of this has been implemented already. Please create new issues or reopen if still necessary.
