### ISSUE TITLE
Color Scheme Switching does not automatically refresh and may lead to an infinity loop

### ISSUE THREAD

**Issue by pinnecke** [FeatureIDE/FeatureIDE#295]
#### Synopsis
Switching color schemes do not automatically refresh the feature model view and might lead to an infinity loop under certain circumstances. 
#### Environment
- **Eclipse Version**: Version: 4.4.2.v20150204-1700
- **FeatureIDE-Version** 2.7.4
- **Dev-Branch** christianJonasBranch_squashed
- **OS information** Apple OS X Yosemite 10.10.4
- **Java runtime used to run eclipse** 1.8.0_40, Java(TM) SE Runtime Environment (build 1.8.0_40-b25), Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode))
- **Java compiler**. Built-in Eclipse Java compiler, JDK 1.8

#### Details
If creating a or switching to color scheme in package explorer, a 
already opened model in feature diagram editor does not automatically refresh. FeatureIDE will run into an infinity loop (at least it seems so) when the following happen: 

**Reproduction  Refreshing:** Try opening a model.xml, create or switch color scheme in package explorer (ideally, let the desired scheme use other colors than the current). Changes in the profile won't
be reflected by the GUI.

**Reproduction  Infinity Loop:** Open a model.xml that has already a color scheme which colors at least one feature. I noticed that the color will not be automatically displayed although the scheme defined this. Then make a change to the model (e.g., add a feature below the root). Save the model and FeatureIDE will not response anymore.

**Comment by pinnecke** [comment]
Please review and reassign me afterwards.

**Comment by meinicke** [comment]
cannot be reproduced, 
report again if the error still happens and how, after next version

**Comment by pinnecke** [comment]
Was fixed by me with commit from Sep 22, 2015. If it is not reproducable, then the fix seems to be working.
