### ISSUE TITLE
Validity check of a configuration inconsistent

### ISSUE THREAD

**Issue by andykenner** [FeatureIDE/FeatureIDE#296]
starting with a new simple featureide modelling project i added some features to feature model and save it. 
this leads to an invalid config caused by having some mandatory features in the model.
after opening the invalid config, the feature selection is changed correctly by featureide itself, because the features are mandatory, but the errors doesn't disappear. 
I had to change something in the configuration addintionally and save it, to force featureide to check the configuration again and remove the error markers finally

**Comment by meinicke** [comment]
seems to be related to https://github.com/tthuem/FeatureIDE/issues/271

**Comment by tthuem** [comment]
@andykenner Can you still reproduce it?

**Comment by Kogoro** [comment]
Can't reproduce it with the latest nightly build.

**Comment by tthuem** [comment]
Seems to be fixed then, reopen if it still occurs.
