### ISSUE TITLE
Move "Add featureIDE Nature" @ projects menu to configure -> "Convert to FeatureIDE Project"

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#298]
The current entry of "Add featureIDE Nature" appears prominent at any project.

The default way is to have this entry at the "configure" sub menu. (e.g., see Convert to Maven Project, Convert to Plug-in Project, Convert to AspectJ Project)

**Comment by tthuem** [comment]
@meinicke Sounds like 5 minutes for you. That's why I assigned you for that. :)
