### ISSUE TITLE
Syntax errors in munge freezes featureide

### ISSUE THREAD

**Issue by andykenner** [FeatureIDE/FeatureIDE#299]
I'm using the munge composer for xml files preprocessing. If you produce a syntax error like a missing end statement or a wrongly used statement and start building the project to get the preprocessed output the build process is running and will never stop. featureide freezes completely

**Comment by andykenner** [comment]
Example for correct code, xml-file:

/*if[tax_eu_19_purchase_ust_skr04]*/

<record id="l10n_de.tax_ust_19_skr04" model="account.tax.template">
    <field name="price_include">1</field>
</record>
/*end[tax_eu_19_purchase_ust_skr04]*/

The descriped error may caused by different syntactical errors:
- using a missing/wrong spelled feature name
- using wrong preprocessor directives, link only /*end*/ instead of /*end[tax_eu_19_purchase_ust_skr04]*/ or similar syntax error in the rules of munge

**Comment by andykenner** [comment]
After some additional testing we found out, that small example don't cause the error of an never ending build-process, it seems to depend on the amount of features in the feature model

**Comment by tthuem** [comment]
It is known that certain analyses consume a considerable amount of time. Deactivating those should help as a workaround for really large models.
