### ISSUE TITLE
Implement support for jar files

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#3]
It should be able to include jars based on the configuration. The jars schould be located somewhere at the feature modules. Consider the support for both, compiling and running Java-programs. Can it be used for AHEAD and FeatureHouse? Is there a need for libraries for C/C++ or other languages?

**Comment by tthuem** [comment]
Not sure whether this is worth the effort as it is likely that it gives numerous conflicts with our reuse of classpath from JDT.
