### ISSUE TITLE
usability improvements - Constraint-Editor

### ISSUE THREAD

**Issue by andykenner** [FeatureIDE/FeatureIDE#300]
Here some suggestions to enhance the usability of the Constraint-Editor
* While the dialog proves the constraint editing/creating it, the "save anyway" is confusing, especially when you hit enter to confirm some input and hit it again to save it, but its not ready yet
* content assist should show the correct entry also, "base" is not shown if its typed in completly. the forecast list only shows base_xyz or similar, so you can't close the forecast popup.
* content assist only shows element that "beginswith" not contains, maybe a contains matching make sense, account_voucher -> i want use "vouch" as input to find account_voucher
* after choosing an entry out of the content assist list, additional to the command a white space should be added, to be able to go on easily
* error in syntax-highlighting: portal as feature-name --> "or" is highlighted, p"or"tal

**Comment by tthuem** [comment]
Merged into #178
