### ISSUE TITLE
usability-improvements Feature-Model-Editor

### ISSUE THREAD

**Issue by andykenner** [FeatureIDE/FeatureIDE#301]
Here some suggestions to enhance the usability of the Feature-Model-Editor
* move features in tree is only possible in the within the visible bounds, maybe we can move the screen when we reach the bounds or provide a mechanism to allow the creation of a new feature not a the end of the current layer
* CTRL-X and CTRL-V
* CTRL-Z after moving a selection of features moves every feature back stepwise not the whole group
* Search and Highlight in the Feature-Model, like CTRL-F or similar

**Comment by tthuem** [comment]
Search is available using the outline atm, but still it would be a nice improvement.

**Comment by tthuem** [comment]
Merged into #187
