### ISSUE TITLE
usability-improvements Configuration-Editor

### ISSUE THREAD

**Issue by andykenner** [FeatureIDE/FeatureIDE#302]
Here some suggestions to enhance the usability of the Configuration-Editor
* Integration of a search and highlight mechanism, to find features in a big configuration tree

**Comment by tthuem** [comment]
You mean just typing feature names is not enough and you want to filter only relevant features? Finding features is at least possible in the outline, haven't tried in the editor itself.

**Comment by tthuem** [comment]
Done
