### ISSUE TITLE
Tooltips of left editor bar sometimes show duplicate entries for ifdef annotations

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#305]
if Hello is the current ifdef condition of the line, but it is shown twice, see tooltip when the mouse is over the warning:

![duplicateentries](https://cloud.githubusercontent.com/assets/1482595/10725154/4150c954-7bca-11e5-8746-e5c2d69e7456.PNG)

**Comment by Subaro** [comment]
Does not happen anymore. I think I fixed it with  #445, but I am not sure.

@Kogoro could you also try it thanks 👍

**Comment by Kogoro** [comment]
I think commit a039f13136815679e49aa89ae90ea2a687d69e06 has solved it for now. It is still a to-do but I think it's a good solution to remove the text from colored annotations.

**Comment by tthuem** [comment]
@Kogoro Removing the text is not preferred as for long annotation the beginning may not be visible and the tooltip will then help to find out the feature name(s) for the colored annotation. I think this issue was only about avoiding duplicated entries, right?

**Comment by Subaro** [comment]
###Result:

<img width="355" alt="bbb" src="https://user-images.githubusercontent.com/6231523/28845939-ecef9c5e-7709-11e7-8424-08e011e83ea3.PNG">
