### ISSUE TITLE
Enable feature coloring from several places

### ISSUE THREAD

**Issue by pinnecke** [FeatureIDE/FeatureIDE#308]
Recently, the coloring of features over certain profiles were introduces. Currently, one has to create a profile in the package/project explorer but to change feature colors one has to do this in the feature dialog editor. However, to be more flexible the "Feature Coloring" popup menu entry from feature dialog editor should also be available in the pop menu of the feature model outline.

**Comment by tthuem** [comment]
Implemented in team project by Team 3.

**Comment by tthuem** [comment]
#437
