### ISSUE TITLE
FeatureCComposer - Enhancements

### ISSUE THREAD

**Issue by ckruczek** [FeatureIDE/FeatureIDE#311]
With e18d34c3f2b1ccc570e249d150f7a1af5859ee9e we introduced a first approach of the FeatureCComposer. There are several ehancements that need to be done later.

* Selection for prefered toolchain
  * simple gcc toolchain
  * make file toolchain
  * autotools toolchain
  * user defined toolchain

For autotools there are several things that need to be considered:

* automatically generate a so called 'autotools_default' file which represents the template for later generations(for manipulations of this file see the following bug we encountered and submitted at the eclipse bug tracker(https://bugs.eclipse.org/bugs/show_bug.cgi?id=481286) ). A possible template candidate could be:
```xml
<configurations>
<configuration id="org.eclipse.linuxtools.cdt.autotools.core.configuration.build.1967642192">
<option id="configure" value="configure"/>
<option id="configdir" value="dist"/>
<option id="cache-file" value=""/>
<option id="help" value="false"/>
<option id="no-create" value="false"/>
<option id="quiet" value="false"/>
<option id="version" value="false"/>
<option id="host" value=""/>
<option id="build" value=""/>
<option id="target" value=""/>
<option id="prefix" value=""/>
<option id="exec-prefix" value=""/>
<option id="libdir" value=""/>
<option id="bindir" value=""/>
<option id="sbindir" value=""/>
<option id="includedir" value=""/>
<option id="datadir" value=""/>
<option id="sysconfdir" value=""/>
<option id="infodir" value=""/>
<option id="mandir" value=""/>
<option id="srcdir" value=""/>
<option id="localstatedir" value=""/>
<option id="sharedstatedir" value=""/>
<option id="libexecdir" value=""/>
<option id="oldincludedir" value=""/>
<option id="program-prefix" value=""/>
<option id="program-suffix" value=""/>
<option id="program-transform-name" value=""/>
<option id="enable-maintainer-mode" value="false"/>
<flag id="CFLAGS">
<flagvalue id="cflags-debug" value="false"/>
<flagvalue id="cflags-gprof" value="false"/>
<flagvalue id="cflags-gcov" value="false"/>
</flag>
<option id="user" value="@@"/>
<option id="autogen" value="autogen.sh"/>
<option id="autogenOpts" value=""/>
</configuration>
</configurations>
  ```
* automatically generate a so called 'autotools_mappings' file that act as a mapper between features and possible preprocessor directives. A possible mapping candidate could be:

     HAVE_HASH;--enable-hash
     HAVE_HEAP;--enable-heap
     HAVE_QUEUE;--enable-queue
     HAVE_REPLICATION;--enable-replication

**Comment by tthuem** [comment]
Duplicate to #379
