### ISSUE TITLE
Inconsistent displaying of or-element in configuration editor

### ISSUE THREAD

**Issue by fheyden** [FeatureIDE/FeatureIDE#313]
When choosing Alternatives in an ANTENNA config-file the user sees that the configuration is invalid, but when more than one Alternative is not chosen yet the appropriate Alternatives are not visualized in green. (But they are if only one Alternative is not chosen.)

![antenna_config_incorrect](https://cloud.githubusercontent.com/assets/8309373/11588795/7348164c-9a83-11e5-9a2f-fedcbf7e5a0c.PNG)

**Comment by meinicke** [comment]
works for me
