### ISSUE TITLE
ColorAnnotation not working for Antenna

### ISSUE THREAD

**Issue by ghost** [FeatureIDE/FeatureIDE#317]
#### Prerequisitives
* **Eclipse Version:** Mars2
* **FeatureIDE-Version:** Current Develop Branch
* **Operating system:** Windows7
* **Java runtime used to run eclipse:** 1.7.0_71
* **FeatureIDE Composer:** de.ovgu.featureide.preprocessor.antenna

### Issue description
Highlighting in source editor does not work correct (see screenshots):

![antenna1](https://cloud.githubusercontent.com/assets/17700404/13946527/70cd7d2a-f015-11e5-8fbb-40e8d83aa63d.PNG)
![antenna2](https://cloud.githubusercontent.com/assets/17700404/13946526/70ccbee4-f015-11e5-97c8-9ca8f2bfd191.PNG)

[HelloWorld-Antenna.zip](https://github.com/FeatureIDE/FeatureIDE/files/183762/HelloWorld-Antenna.zip)

**Comment by pinnecke** [comment]
Can you please provide a description, or an image, on how it should work correctly?

**Comment by tthuem** [comment]
I think it is clear from the context. In first screenshot, Line 6 and 18 should be orange/red. In the second screenshot, Line 6, 7, and 18 should be colored orange/red.

**Comment by meinicke** [comment]
The problem is caused by the missing # in the endif directives.
I added the warning to be visible Line 1 (previously Line 0), unfortunately the exact line number is not given by antenna. (see: https://github.com/FeatureIDE/FeatureIDE/commit/9e979d6d73274208dfaa2f9d9bf9da0e3b39cbdb)
