### ISSUE TITLE
Problems in working with runtime parameters (runtime composer)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#320]
#### Prerequisitives
* **Eclipse Version:**  Standard 4.3.1
* **FeatureIDE-Version:** release branch, commit https://github.com/FeatureIDE/FeatureIDE/commit/d351678714c7be72d914e5ff1c0905535a84139b
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 1.8.0_77
* **FeatureIDE Composer:** Feature Modeling
* **Git branch/Commit-ID:**  release branch, commit d351678714c7be72d914e5ff1c0905535a84139b
* **Java compiler used to build the FeatureIDE plugin:** Java 1.8.0_77

### Issue description
P1. "Runtime Composer" should rather be called "Runtime Parameters". There is nothing composed.

P2. On my first attempt of creating a project, Eclipse freezed. The project was completely created already at that time. A second try seemed to work just fine.

![zwischenablage-7](https://cloud.githubusercontent.com/assets/5330357/14288520/4f564a80-fb57-11e5-90ac-e90ba4818cc3.jpg)

Similarly, Eclipse freezed when adding the example projects.

![zwischenablage-9](https://cloud.githubusercontent.com/assets/5330357/14288716/41ee0c60-fb58-11e5-8125-47a2255c3658.jpg)

 P3. The new file wizard does not work at all for this generator.

![zwischenablage-8](https://cloud.githubusercontent.com/assets/5330357/14288540/6cf9e290-fb57-11e5-941e-f823873b24d1.jpg)

 P4. It could be helpful to create a main class already to illustrate how to implement with that generator.

 P5. The HelloWorld-Properties contains a folder named "feature" which is not necessary.

**Comment by tthuem** [comment]
For the examples, I can even reproduce the freeze everytime.

![zwischenablage-10](https://cloud.githubusercontent.com/assets/5330357/14289157/e404cc18-fb59-11e5-95e1-cff129c57bb8.jpg)

**Comment by tthuem** [comment]
The property file is only created when changing the example configuration and the following output appears if run without changing the configuration before:

![zwischenablage-11](https://cloud.githubusercontent.com/assets/5330357/14289305/7bbd3f5e-fb5a-11e5-9880-0937e2bd4699.jpg)

**Comment by tthuem** [comment]
P7. I could not edit the run configuration that I just run in the properties. It was not even possible to create a new run configuration for Java applications.

![zwischenablage-12](https://cloud.githubusercontent.com/assets/5330357/14289473/3962a576-fb5b-11e5-9150-4c37e4a29502.jpg)

**Comment by tthuem** [comment]
P8. HelloWorld-Run Configuration did run but did not print anything to the console. Even after changing the configuration.

**Comment by meinicke** [comment]
All fixed.
P4: For explanation and usage we have the hello world examples
P8: cannot be reproduced, if it still happens please reopen or crate a new issue

**Comment by tthuem** [comment]
Great! P1-P8 are solved. :)
