### ISSUE TITLE
Generator for frameworks/plugins not intuitive

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#321]
#### Prerequisitives
- **Eclipse Version:**  Standard 4.3.1
- **FeatureIDE-Version:** release branch, commit https://github.com/FeatureIDE/FeatureIDE/commit/d351678714c7be72d914e5ff1c0905535a84139b
- **Operating system:** Windows 10
- **Java runtime used to run eclipse:** Java 1.8.0_77
- **FeatureIDE Composer:** Feature Modeling
- **Git branch/Commit-ID:**  release branch, commit d351678714c7be72d914e5ff1c0905535a84139b
- **Java compiler used to build the FeatureIDE plugin:** Java 1.8.0_77
### Issue description

P1. It is not clear whether source code of plugins need be altered in folder features or in the separate projects. Why do we need the projects? Why do we need the features folder?

![zwischenablage-14](https://cloud.githubusercontent.com/assets/5330357/14290566/cba59fc0-fb5f-11e5-9b77-4da02af5e2cb.jpg)

P2. Why are the jars stored in folders with the same name as the jars? Does not make sense to me.

P3. How to control the order in the example project? Currently, the output is not correct on my machine.

**Comment by tthuem** [comment]
I forgot to mention: Besides those minor things, the support for frameworks is great! Good job guys. :)

**Comment by meinicke** [comment]
P1: we also thought about several src paths in the main project for the project. However, the current solution explains the problems (e.g., visibility) of plugins much better, in the sense of a teaching purpose.

P2: you can also store multiple jars in the folder (i.e., per feature), the idea was to leave this more flexible. If there is only one jar per project (as currently) you are right.

P3: Thats the point of plugins. We could define an explicit order. However, an order is usually not possible for plugin systems.

**Comment by tthuem** [comment]
P1: Where are developers supposed to change the source code for plugins? In the separate projects? Or is both possible?

P2: I don't see any reason why one would want to do that and it is confusing to me. When do I need more than one jar?

P3: We need to fix the order for the example somehow, but I'm not quite sure how. Any ideas?

**Comment by meinicke** [comment]
P1: that should not matter as the files are the same
P2: that seems to be true, the additional folder seems to be redundant as we generate the jars automatically
P3: currently it seems that the jars are executed in alphabetical order, so we could change the names of the features accordingly

**Comment by tthuem** [comment]
P1: is ok.

P2: would be good, if we could fix that

P3: changing the names appears as a hack to me. why not allowing the order to be user-defined? should be not much effort, as the functionality is already there, right?

**Comment by tthuem** [comment]
@meinicke Are P2 and P3 useful in the context of a software project?

**Comment by tthuem** [comment]
I see the following open issues (others fixed in the meantime):

P1: Other projects should have the Framework projects name as a prefix, otherwise it is hard to see which projects are related, if several examples are imported into the workspace (or if we have several student submissions in the same workspace).

P2: Jars should all be added to a folder lib (instead of subfolders for features).

If possible, would be good to fix this for the book already.

**Comment by Kogoro** [comment]
Both tasks should be fixed with the two commits. Could you please check the fix for P2 as I may misunderstand it in some way.
If it is correct I will merge it.
