### ISSUE TITLE
Create a default color scheme if there is none and colors are assigned to features

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#323]
#### Prerequisitives
- **Eclipse Version:**  Standard 4.3.1
- **FeatureIDE-Version:** release branch, commit https://github.com/FeatureIDE/FeatureIDE/commit/d351678714c7be72d914e5ff1c0905535a84139b
- **Operating system:** Windows 10
- **Java runtime used to run eclipse:** Java 1.8.0_77
- **FeatureIDE Composer:** Feature Modeling
- **Git branch/Commit-ID:**  release branch, commit d351678714c7be72d914e5ff1c0905535a84139b
- **Java compiler used to build the FeatureIDE plugin:** Java 1.8.0_77
### Issue description

It took me a while to find out why I'm not allowed to assign colors to features. Though this is a bug. Would be more intuitive if we always allow to assign colors and create a default color scheme if there is none available so far.

![zwischenablage-16](https://cloud.githubusercontent.com/assets/5330357/14291109/3850e074-fb62-11e5-9229-7ad68abf2b8a.jpg)

**Comment by tthuem** [comment]
Furthermore, colors are not automatically updated in collaboration diagram.

![zwischenablage-17](https://cloud.githubusercontent.com/assets/5330357/14291176/924696dc-fb62-11e5-9fe2-5b72453bf2b0.jpg)

**Comment by tthuem** [comment]
Also noticed that colored features do not reveal whether they are abstract or concrete in their tool tip.

![zwischenablage-19](https://cloud.githubusercontent.com/assets/5330357/14291264/1fe5d25a-fb63-11e5-94ea-715b7d693446.jpg)

It would help also if abstract features cannot be colored. That this is currently possible does not make sense to me, their are no artifacts to trace anyway.

**Comment by tthuem** [comment]
Furthermore, we should add the project explorer to FeatureIDE perspective, as colors are not shown in package explorer. Maybe we should open both and make the project explorer the default (i.e., left tab).

![zwischenablage-7](https://cloud.githubusercontent.com/assets/5330357/14672136/2e9f8b80-06f6-11e6-8b87-697c016cb0e5.jpg)

**Comment by Kogoro** [comment]
Furthermore, the project explorer, the source view and the outline should be updated when the complete color scheme is removed by the user. Also, when assigning colors in the feature model the project explorer should be updated.

**Comment by tthuem** [comment]
Also, the color scheme is not updated in the editor accordingly. Just opened a new project without color scheme. Tried to assign a color to a feature, which was not possible (as stated above). Created a color scheme, but it was still not possible and necessary to close the feature model editor to be able to assign the color.

**Comment by tthuem** [comment]
Implemented in team project by Team 3.

**Comment by tthuem** [comment]
#437
