### ISSUE TITLE
Fix "show hidden features" in feature model editor

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#324]
#### Prerequisitives
* **FeatureIDE-Version:**  2.7.5

### Issue description
The action "show hidden features" in feature model editor does not work. 
I.e., the action is not applied correctly, the Legend is layouted, but the action is not propagated to the FeaturesEditParts.

After reopening of the editor, the features are hidden.

**Comment by tthuem** [comment]
Seems related to #389, as both are update problems.

**Comment by tthuem** [comment]
Jens, will you have a look at this or should I ask Alex?

**Comment by tthuem** [comment]
I think it worked more-or-less with Jens' revision and the rest comes with next release.
