### ISSUE TITLE
Remove dependency to eclipse SDK in fm.core

### ISSUE THREAD

**Issue by pinnecke** [FeatureIDE/FeatureIDE#328]
#### Prerequisitives
* **FeatureIDE-Version:** 3.0.0 (in develop)

### Issue description
Unfortunately, there is a dependency to eclipse SDK in fm.core. This is a barrier when one want to use the core functionally in custom projects (e.g., writing custom feature model to FeatureIDE-compatible xml files using IFeature, IFeatureModel and the related xml writer classes). Ideally, fm.core should depend only on the JDK plus core-required external dependencies (e.g., the sat solver).

**Comment by skrieter** [comment]
Done. See #392
