### ISSUE TITLE
Configuration Editor: possibility to automatically select sub-tree when parent is selected

### ISSUE THREAD

**Issue by pinnecke** [FeatureIDE/FeatureIDE#329]
### Enhancement description

In the configuration editor features are organized hierarchically depending on their parent-/child relationship. 
`--- (  ) A`
`---------|- (  ) B`
`---------|- (  ) C`

However, currently selecting a parent node will not lead to automatically ("manual") selection of the sub tree. 

`--- ( x ) A`
`---------|- (  ) B`
`---------|- (  ) C`

Although this is intended depending on the context, it would improve the usability a lot when one have the option to automatically select the child features by selecting the parent feature (instead of select each child feature ).

`--- ( x ) A`
`---------|- ([x]) B`
`---------|- ([x]) C`

**Comment by tthuem** [comment]
This is impossible in many cases due to diagram or cross-tree constraints. For example, if the child features are alternative, what will you choose? Personally, I think there are more interesting ways to speed up the configuration process. I vote for closing this issue.

**Comment by pinnecke** [comment]
In general you are right. In the specific case I have a feature model with a high number of optional features per parent only, and a huge amount of implies constraints. In this use-case selecting feature by feature is not reasonable.

**Comment by tthuem** [comment]
I still have doubts that this is the right way to go. If we have better ideas, this situation could indeed be improved.
