### ISSUE TITLE
FeatureIDE adds markers to non-FeatureIDE projects

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#334]
#### Prerequisitives
* **Eclipse Version:**  Eclipse 4.5.2 Platform 64bit
* **FeatureIDE-Version:**  FeatureIDE v3.0.0
* **Operating system:** Windows 10 
* **Java runtime used to run eclipse:** 1.8.0_77
* **FeatureIDE Composer:** none, not even a FeatureIDE project
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/b057fc0e87b112952a5e5037a10e6f6779b5ab1b

### Issue description
Feature model problem marker created for an XML file in a project that is not a FeatureIDE project. That's annoying and we should try not to interfere with other plugins. Further, FeatureIDE becomes the default editor for XML (which might be hard to change) and the tree is shown even if it is not a feature model at all.

![zwischenablage-3](https://cloud.githubusercontent.com/assets/5330357/14647384/caa2d4e0-065d-11e6-95a6-b1824f683a4d.jpg)

![zwischenablage-4](https://cloud.githubusercontent.com/assets/5330357/14647386/cc5f863e-065d-11e6-9338-c5d1bc7bc607.jpg)

**Comment by tthuem** [comment]
The marker was created when I opened the file with our feature model editor. Still, no marker should be created as it is not clear whether this is supposed to be a feature model.

**Comment by jabiercoding** [comment]
I was about to report this but I see that it was already reported. I confirm that this is a very annoying issue. I have other java projects that interact with the FeatureIDE project. Maybe try to make the feature model content type more accurate.

**Comment by Kogoro** [comment]
I checked it also with a normal java project, where I added a model.xml manually. I can reproduce the tree icon when the xml contains a complete feature model in xml (root tag featureModel exists), but I don't get a problem marker at all with the latest nightly build.

**Comment by tthuem** [comment]
It is fixed now.
