### ISSUE TITLE
Invalid configurations are not marked as invalid

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#335]
#### Prerequisitives
* **Eclipse Version:**  Eclipse 4.5.2 Platform 64bit
* **FeatureIDE-Version:**  FeatureIDE v3.0.0
* **Operating system:** Windows 10 
* **Java runtime used to run eclipse:** 1.8.0_77
* **FeatureIDE Composer:** none, not even a FeatureIDE project
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/51fc3c99bc44150b58fcf7c44caf77c6bea9f25f

### Issue description
Created an Eclipse with only FeatureIDE and Feature Modeling installed. Created a project with a mandatory and an optional feature. Selected both features in a configuration. Change both features to alternative and got no marker for invalid configuration. When opening the configuration editor it said the configuration is invalid, but when moving the window next to the diagram, even that warning disapeared and I can even select both features at the same time.

![zwischenablage-5](https://cloud.githubusercontent.com/assets/5330357/14648457/a5ca57ec-0662-11e6-8513-f75df0ee4f99.jpg)

**Comment by tthuem** [comment]
Due to the small width of the configuration editor, the statement "invalid" disappeared. That's unintuitive.

**Comment by meinicke** [comment]
fixed in https://github.com/FeatureIDE/FeatureIDE/commit/2c88b172275a2a4fe7a7190372fa5d085a727f04
