### ISSUE TITLE
Not able to compile hello world with runtime parameters

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#336]
#### Prerequisitives
* **Eclipse Version:**  Eclipse 4.5.2 Committers 32bit
* **FeatureIDE-Version:**  FeatureIDE v3.0.0
* **Operating system:** Windows 10 
* **Java runtime used to run eclipse:** 1.8.0_77
* **FeatureIDE Composer:** Runtime Parameters
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/51fc3c99bc44150b58fcf7c44caf77c6bea9f25f

### Issue description
Installed FeatureIDE over new update site, opened the property example, changed the project properties. Even after refresh and clean build, the PropertyManager cannot be found and the Main not be executed.

![zwischenablage-6](https://cloud.githubusercontent.com/assets/5330357/14649163/1a1f6512-0666-11e6-97d2-90bda1325177.jpg)

What does it mean for a file to be local?

**Comment by tthuem** [comment]
Run Configuration worked just fine.

**Comment by meinicke** [comment]
the PropertyManager file was not included in the build.properties
