### ISSUE TITLE
Eclipse freezes when importing all FeatureIDE examples

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#337]
#### Prerequisitives
* **Eclipse Version:**  Eclipse 4.5.2 Platform 64bit
* **FeatureIDE-Version:**  FeatureIDE v3.0.0
* **Operating system:** Windows 10 
* **Java runtime used to run eclipse:** 1.8.0_77
* **FeatureIDE Composer:** MPL-FH-Java?
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/d943a2e1e0e5bab1dd36d8f0992ef2fcf073fd15

### Issue description
Eclipse freezes when importing all FeatureIDE examples.

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/14669477/5787b52a-06e9-11e6-9241-247b8e7a280d.jpg)

Cancelling jobs did not help.

![zwischenablage-2](https://cloud.githubusercontent.com/assets/5330357/14669485/624eadd8-06e9-11e6-9bef-7255f082d6cc.jpg)

Not even possible to close Eclipse.

![zwischenablage-3](https://cloud.githubusercontent.com/assets/5330357/14669518/90ac58a6-06e9-11e6-9bf9-986a34a1e97a.jpg)

Killing and restarting Eclipse solved the problem. It took several minutes until all processes were finished, but it did not freeze again.

**Comment by pinnecke** [comment]
Can not reproduce the issue. Both importing all projects without having a "closed" copy on the workspace, and importing all project while some project are already "closed" in the workspace works fine. 

Version FeatureIDE on current release branch version on OS X, HotSpot using java "1.8.0_77", and Eclipse for RCP and RAP Developers (Version: Mars.2 Release (4.5.2), Build id: 20160218-0600). 

Might related to Windows environment since we both have the same eclipse version? I assigned Jens in order to check this.

**Comment by tthuem** [comment]
Tried to reproduce it myself. Run into the same problem but with different project this time.

![zwischenablage-8](https://cloud.githubusercontent.com/assets/5330357/14672469/5356709a-06f8-11e6-9c00-b3ba0f15530f.jpg)

**Comment by meinicke** [comment]
cannot be reproduced on Mars Win10 64bit
also MPL did not cause any problems.

Yes it takes a while until the projects are built. BerkelyDB-FH-Java takes some time, especially for propagation.

**Comment by tthuem** [comment]
I'm waiting for 2 hours now - nothing happens. We should invesigate this for the next version.

I also experienced that - after killing and restarting Eclipse - BerkeleyDB-FH-Java takes the most time.

**Comment by pinnecke** [comment]
Reviewed this issue again. Still, cannot reproduce it. Initially it through it might be related to "built automatically" option in Eclipse enabled when importing all examples. At my machine FeatureIDE is able to import all examples in a reasonable time independent of whenever "built automatically" is enabled or not. 

Please try to reproduce it again Thomas. When it still occurs, we should take a look during the meeting.

**Comment by tthuem** [comment]
Tested again on development branch, commit https://github.com/FeatureIDE/FeatureIDE/commit/d4d8a932034ffbaff2cd192f9a9a27b00f2e9b4b.

Took several minutes to load and build all examples, but Eclipse did not freeze again.
