### ISSUE TITLE
Use DefaultNewFeatureProjectWizardExtension by default

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#342]
### Issue description
This is a minor issue. While developing a composer, the de.ovgu.featureide.core.wizard extension point is mandatory even if it is not needed. If you remove this extension point, for example from the images composer plugin.xml, it is not possible for the user to create the project, the Finish button is enabled but nothing happens and the wizard remains open.
It will be nice to use by default de.ovgu.featureide.core.wizardextension.DefaultNewFeatureProjectWizardExtension if nothing has been registered for a composer so the developer does not need to add this.

I think that changing this will fix it:
https://github.com/jabiercoding/FeatureIDE/commit/f55eccdea9b35712f088449465c1dfd4553a0ce2

**Comment by tthuem** [comment]
Sounds fine to me. Jabier, can you send a pull request (for better keeping track that is your commit)?

**Comment by Kogoro** [comment]
I removed also the usages of the default implementations in all plugins under the plugins path.

**Comment by jabiercoding** [comment]
@Kogoro Nice! :) Regarding your last comment, I can still see that the default implementation is declared at plugins/de.ovgu.featureide.core.images/plugin.xml   The idea now is that we can remove the extension point="de.ovgu.featureide.core.wizard" when there is no need of a special project wizard.

**Comment by Kogoro** [comment]
@jabiercoding In the specific issue branch are two more commits which remove the de.ovgu.featureide.core.wizard extension's from the plugins under the plugin path. Also from the plugins/de.ovgu.featureide.core.images/plugin.xml. ;)

**Comment by jabiercoding** [comment]
@Kogoro :+1:

**Comment by tthuem** [comment]
Go ahead and merge into _release_.
