### ISSUE TITLE
Make feature model wizard accessible if only feature modeling is installed

### ISSUE THREAD

**Issue by skrieter** [FeatureIDE/FeatureIDE#343]
### Issue description

When only the feature modeling feature is installed in Eclipse, there is no easy way to create an empty feature model.
There should be 
- a context menu entry and/or 
- an extension to the "new file" wizard in Eclipse.

**Comment by meinicke** [comment]
The wizard exists, but seems not to be visible if only feature modeling is insalled

**Comment by tthuem** [comment]
Done with #649
