### ISSUE TITLE
Analysis marked features as dead falsely 

### ISSUE THREAD

**Issue by pinnecke** [FeatureIDE/FeatureIDE#344]
#### Prerequisitives
* **Eclipse Version:** 
* **FeatureIDE-Version:**  3.0.00 (Marketplace)
* **Operating system:** Windows 
* **Java runtime used to run eclipse:** 
* **FeatureIDE Composer:** Feature Modeling
* **Git branch/Commit-ID:**  
* **Java compiler used to build the FeatureIDE plugin:** 

### Issue description
Thomas Leich reported one of his students had a bug using FeatureIDE 3.0 from marketplace recently in Thomas' lecture. The model used by the student was marked with dead features. I was not able to reproduce this (MacOS) and it is currently unknown if the student is confronted with the bug when restarting Eclipse. 

### Note
We should note this in case it happens again, or one could reproduce it.

![screen_deadfeature](https://cloud.githubusercontent.com/assets/3775170/14740373/ac55814e-088e-11e6-8cb2-1d1da94adf60.png)

![bildschirmfoto 2016-04-22 um 13 34 27](https://cloud.githubusercontent.com/assets/3775170/14740399/e841d0d6-088e-11e6-81e0-7273811ac21e.png)

**Comment by andykenner** [comment]
i have tried to reproduce the error with a fresh dowloaded eclipse JavaEE Version (Eclipse Java EE IDE for Web Developers; Version: Kepler Service Release 2).
Except the fact that my project (FeatureModeling) structure differs from the one in the picture, i was not able to reproduce this error with a similar development environment

**Comment by andykenner** [comment]
![image](https://cloud.githubusercontent.com/assets/8641920/14742565/3d375fb2-089d-11e6-9dda-e818c71fad95.png)

different project structure in the package explorer. sure, they used a feature modelling project?

**Comment by tthuem** [comment]
@pinnecke Can you reproduce it?
