### ISSUE TITLE
Layout not saved for feature model

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#346]
#### Prerequisitives
* **Eclipse Version:**  All
* **FeatureIDE-Version:**  3.0.0
* **Operating system:** All
* **Java runtime used to run eclipse:** All
* **FeatureIDE Composer:** Feature Model
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/a5afd7e75b7ea9efc1e941e397b8fad27ac1dd33

### Issue description
Layout is not saved for feature model.

- change layout. 
- save model
- close and open editor
- still old layout is used

**Comment by tthuem** [comment]
What about manual layout? Does it work? If so, it is probably less critical.
