### ISSUE TITLE
Selecting features not possible in the top middle of a box

### ISSUE THREAD

**Issue by AlexanderKnueppel** [FeatureIDE/FeatureIDE#348]
#### Prerequisitives
* **Eclipse Version:**  `4.4.2`
* **FeatureIDE-Version:**  `2.7.5`
* **Operating system:** `Windows 7/10`
* **Java runtime used to run eclipse:** `1.8.0`
* **FeatureIDE Composer:** ``
* **Git branch/Commit-ID:**  `f67728363a22a4619b06c9624a4624afb1dfbd58`
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
Trying to select a feature by clicking at the top middle of a feature box doesn't work.

![selection](https://cloud.githubusercontent.com/assets/263321/14895537/78f9afb0-0d79-11e6-871c-dbb4947ab0d0.png)

If I click somewhere in those red boxes, I'm not able to select either A or B. The not-clicking-space is rather big.

**Comment by tthuem** [comment]
I also experienced this behavior and it is quite unintuitive why clicking on the features does not always work.

**Comment by tthuem** [comment]
It is almost impossible to use the current feature diagram. Selecting a feature is really a challenge!
