### ISSUE TITLE
Improve support for #condition in Antenna projects

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#352]
#### Prerequisitives
- **FeatureIDE Composer:** Antenna
### Issue description

Antenna allows to exclude complete files using #condition FEATURE
Currently the build process works, but not any additional support (colors, line numbers(should be all), analyses (e.g., dead code))

**Comment by meinicke** [comment]
fixed in https://github.com/FeatureIDE/FeatureIDE/commit/e39a912eb2262a792f4689bade2c265efd5d97b3

**Comment by tthuem** [comment]
We experienced a case were a condition is missing in the collaboration diagram. Reimar can give more details in the next days.

**Comment by tthuem** [comment]
Reimar, we need your input for that.

**Comment by RSchroeter** [comment]
The problem occurs if multiple classes exist in one file. The case is simply not yet supported .

**Comment by tthuem** [comment]
Hence, a possible task for a software project?

**Comment by RSchroeter** [comment]
Yes, why not? 

I found a second error with the same result. If a file name is a prefix of another file name, only one class is represented in the diagram.

**Comment by skrieter** [comment]
Could not reproduce. Seems to be fixed in the meantime.
