### ISSUE TITLE
Analysis marked dead features as false-optional 

### ISSUE THREAD

**Issue by SofiaAnanieva** [FeatureIDE/FeatureIDE#353]
#### Prerequisitives
* **Eclipse Version:**  `4.3.2`
* **FeatureIDE-Version:**  `V3.0.0`
* **Operating system:** `Apple OS X El Capitan 10.11.5`
* **Java runtime used to run eclipse:** `Java 1.8.0_73, Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)`
* **Git branch/Commit-ID:**  `master`

### Issue description
Optional child-features of dead features are analyzed to be both dead and false-optional, although they should be only dead. In the feature model blow, feature C is analyzed to be both dead and false-optional.

Debugging method **updateConstraints()** in class **FeatureModelAnalyzer** reveals that feature C is both in lists for dead features (_fmDeadFeatures_) and for false-optional features (_fmFalseOptionals_). 

![bildschirmfoto 2016-05-26 um 14 04 36](https://cloud.githubusercontent.com/assets/15520103/15575159/c1a0b75c-2351-11e6-9a66-3885dc4c88b4.png)

**Steps to reproduce:**
1)	Create a feature model with an optional parent and optional child feature
2)	Create a constraint which results in the optional parent feature to be dead, e.g. a mandatory feature which excludes the optional parent feature
3)	The optional child feature  is marked to be false optional whereas the tooltip for the respective constraint  indicates that both parent and child feature are dead

**Comment by tthuem** [comment]
Sebastian, I assigned you as I remember that you worked on a more efficient computation recently. There should be an easy fix as a feature can never be both dead and false-optional. Hence, it can just be marked as dead instead.
