### ISSUE TITLE
FeatureIDE prepacked version creates folders in users directory in windows

### ISSUE THREAD

**Issue by andykenner** [FeatureIDE/FeatureIDE#354]
#### Prerequisitives
* **Eclipse Version:**  4.5.2
* **FeatureIDE-Version:**  3.0.0
* **Operating system:** Windows 7
* **Java runtime used to run eclipse:** 
* **FeatureIDE Composer:** 
* **Git branch/Commit-ID:**  
* **Java compiler used to build the FeatureIDE plugin:** 
### Issue description

After using the prepacked versions (32, 64bit) i found a new user tthuem in my users folder. See screenshot for contents
![image](https://cloud.githubusercontent.com/assets/8641920/15651569/bb9cbf86-2680-11e6-8e6d-cf2833d99f88.png)

in complete the following structure is created:
C:\Users\tthuem\Tools\FeatureIDE\eclipse4.5.2committers-featureide3.0.0-win64\eclipse\.eclipseextension\features

**Comment by andykenner** [comment]
Tested it with the win32 version:
- unzip --> no
- first start of eclipse -> yes

the following path ist generated:
Users\tthuem\Tools\FeatureIDE\eclipse4.5.2committers-featureide3.0.0-win32\eclipse\.eclipseextension\features

based in the path its just a folder in folder in folder ...
the last folder "features" is empty, no files given

**Comment by andykenner** [comment]
here are the resulte of a search i have done, where you see the 

D:\000_testing\featureide_300_32\eclipse\configuration\org.eclipse.osgi\177\data\-958340017\artifacts.xml (1 hit)
	Line 3: <repository name='C:\Users\tthuem\Tools\FeatureIDE\eclipse4.5.2committers-featureide3.0.0-win32\eclipse\.eclipseextension' type='org.eclipse.equinox.p2.artifact.repository.simpleRepository' version='1.0.0'>
  D:\000_testing\featureide_300_32\eclipse\configuration\org.eclipse.osgi\197\data\724350240\artifacts.xml (1 hit)
	Line 3: <repository name='update site: file:/C:/Users/tthuem/Tools/FeatureIDE/eclipse4.5.2committers-featureide3.0.0-win32/eclipse/configuration/org.eclipse.osgi/185/data/listener_1925729951/' type='org.eclipse.equinox.p2.artifact.repository.simpleRepository' version='1'>
  D:\000_testing\featureide_300_32\eclipse\configuration\org.eclipse.osgi\197\data\724350240\content.xml (1 hit)
	Line 3: <repository name='update site: file:/C:/Users/tthuem/Tools/FeatureIDE/eclipse4.5.2committers-featureide3.0.0-win32/eclipse/configuration/org.eclipse.osgi/185/data/listener_1925729951/' type='org.eclipse.equinox.internal.p2.metadata.repository.LocalMetadataRepository' version='1'>
  D:\000_testing\featureide_300_64\eclipse\configuration\org.eclipse.osgi\177\data\200678382\artifacts.xml (1 hit)
	Line 3: <repository name='C:\Users\tthuem\Tools\FeatureIDE\eclipse4.5.2committers-featureide3.0.0-win64\eclipse\.eclipseextension' type='org.eclipse.equinox.p2.artifact.repository.simpleRepository' version='1.0.0'>
  D:\000_testing\featureide_300_64\eclipse\configuration\org.eclipse.osgi\197\data\1181782049\artifacts.xml (1 hit)
	Line 3: <repository name='update site: file:/C:/Users/tthuem/Tools/FeatureIDE/eclipse4.5.2committers-featureide3.0.0-win64/eclipse/configuration/org.eclipse.osgi/185/data/listener_1925729951/' type='org.eclipse.equinox.p2.artifact.repository.simpleRepository' version='1'>
  D:\000_testing\featureide_300_64\eclipse\configuration\org.eclipse.osgi\197\data\1181782049\content.xml (1 hit)
	Line 3: <repository name='update site: file:/C:/Users/tthuem/Tools/FeatureIDE/eclipse4.5.2committers-featureide3.0.0-win64/eclipse/configuration/org.eclipse.osgi/185/data/listener_1925729951/' type='org.eclipse.equinox.internal.p2.metadata.repository.LocalMetadataRepository' version='1'>

**Comment by tthuem** [comment]
Seems to be an issue of Eclipse, not FeatureIDE.
