### ISSUE TITLE
Documentation generation does not return expected results

### ISSUE THREAD

**Issue by ckruczek** [FeatureIDE/FeatureIDE#357]
#### Prerequisitives
- **Eclipse Version:**  `Luna`
- **FeatureIDE-Version:**  `2.7.4,2.7.5, 3.0.0`
- **Operating system:** `Linux`
- **Java runtime used to run eclipse:** ``
- **FeatureIDE Composer:** `FeatureHouse`
- **Git branch/Commit-ID:**  ``
- **Java compiler used to build the FeatureIDE plugin:** ``
### Issue description

With the Featurehouse composer the context menu-entries 
**Feature-IDE->Documentation->**\* do result in nothing. To be more precise, I used the HelloWorld-FH-Java example for FH and debugged the java doc generation. As a result - the `PrintDocumentationJob.java` line 96 returns null for the `.getProjectSignatures()` call. This happens regardless of the additional Fuji-Typecheck activation, as suggest by @skrieter. I also encountered the same behavior while using a annotation based composer like Antenna.
Stepping back to the versions 2.7.5 as well as 2.7.4 didn't changed the behavior.

**Comment by ckruczek** [comment]
The issue is not resolved with the featurehouse BerkeleyDB example. Steps to reproduce

1. Open featurehouse example for BerkeleyDB
2. Enable Fuji Type-Check on the project
3. Set a breakpoint at line 103 in `PrintDocumentationJob.java`
4. Call the *Documentation->Create Product Documentation* for the project
5. Returned `projectSignatures` are null

**Comment by tthuem** [comment]
@skrieter Can you confirm there is a problem?

**Comment by skrieter** [comment]
For this functionality, we currently rely on Fuji to generate an AST.
For FeatureHouse projects, Fuji Type Check must be enabled.
However, Fuji is not compatible with Java 1.8 or higher.
