### ISSUE TITLE
Analysis didn't detect redundant constraint

### ISSUE THREAD

**Issue by SofiaAnanieva** [FeatureIDE/FeatureIDE#358]
#### Prerequisitives
* **Eclipse Version:**  `4.3.2`
* **FeatureIDE-Version:**  `V3.00`
* **Operating system:** `Apple OS C El Capitan 10.11.5`
* **Java runtime used to run eclipse:** `Java 1.8.0_65, Java(TM) SE Runtime Environment (build 1.8.0_65-b17) Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)`
* **Git branch/Commit-ID:**  `explanations`

### Issue description

In the feature model below, Constraint B => H is redundant, because B implies a false-optional feature H. This redundancy is not detected.

![fofix](https://cloud.githubusercontent.com/assets/15520103/16190220/8387a584-36de-11e6-8bec-ac7bf7d08820.png)

This error is reproducible on the master branch. However, the false-optional feature H is detected but not colored on the master branch. This is fixed in branch _explanations, ConstraintFigure.java_ (fm.ui.editors.featuremodel.figures), _line 189_.

**Comment by tthuem** [comment]
Seems to be related to #347

**Comment by tthuem** [comment]
Also closed #318, as this seems to be a duplicate. Still, there are further examples of wrong behavior.
