### ISSUE TITLE
White color for features color

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#359]
#### Prerequisitives
* **FeatureIDE-Version:**  3.0.1

### Issue description
I think that in previous versions of FeatureIDE I was able to change the background of the features to white. When I export as image to create documentation I really prefer all the features to have white background and not the default light blue ones. Now it seems a predefined set of colors so I will have to go back to previous versions as far as I understand.

Could next versions of FeatureIDE allow to have white? This will be ok for me so I do not have to keep previous versions of FeatureIDE to export images.

I think that the enum at de.ovgu.featureide.fm.core.color.FeatureColor with this predefined set of 10 colors is maybe motivated by the Project Explorer view where we can visualise the colors used during the derivation... it seems that the white color means "unused" color in this view. If this is the problem for not to have white, maybe you can try to display only the involved colors...

**Comment by tthuem** [comment]
Indeed, we used to have a preferences page where all distances and colors could be adjusted arbitrarily. Why is that preference page not available anymore?

**Comment by meinicke** [comment]
The defined colors are used for highlightings and so, thats why we define only a small set of default colors.

Anyway, what you want is something different.
Just open the preferences of the feature model (i.e., right-click on a model.xml - properties - feature model editor)
There you can edit the all default colors:
![issue359](https://cloud.githubusercontent.com/assets/1482595/16373359/22b057a0-3c52-11e6-8e74-466f326e04c2.PNG)
.

**Comment by jabiercoding** [comment]
Thanks! I have seen this property page but I did not remember how to find it again.

**Comment by tthuem** [comment]
Me too. ;)
