### ISSUE TITLE
Add project explorer to the FeatureIDE perspective

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#360]

**Comment by Kogoro** [comment]
I can already add the project explorer view to the perspective. But it looks like in the image.
![projectexplorer](https://cloud.githubusercontent.com/assets/8019776/16570107/7b6e647a-423f-11e6-9e0d-bece4d358129.png)

**Comment by Kogoro** [comment]
The project explorer view is now as discussed the first tab on left side pane.
Implemented in https://github.com/FeatureIDE/FeatureIDE/commit/9a5ec2b83aa45dd10e95fb84214537fcedee7f28 in branch issue-360.
Maybe someone could also take a quick look at that.
