### ISSUE TITLE
Source code cannot be found in legacy FeatureHouse projects

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#362]
New examples work just fine, but I had old examples in my workspace which cannot be compiled anymore.

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/16579526/6087ffd4-42a0-11e6-850f-e24fe4824163.png)

Please check whether this problem also occurs with other FeatureHouse projects.

**Comment by meinicke** [comment]
this is due to the change that FH generates no longer into the src/"configuration" folder.

I could add an update of the classpath when initializing the project.

**Comment by tthuem** [comment]
I know. Sounds good. Christopher was only assigned to test whether this also occurs for other projects than those that I tested. If you can do it for this version, this would be best.
