### ISSUE TITLE
Root feature labeled as dead after adding a constraint

### ISSUE THREAD

**Issue by AlexanderKnueppel** [FeatureIDE/FeatureIDE#368]
#### Prerequisitives
* **Eclipse Version:**  `Mars.2 (4.5.2)`
* **Operating system:** `Windows 7`
* **Java runtime used to run eclipse:** `1.8`
* **FeatureIDE Composer:** `Feature modeling`
* **Git branch/Commit-ID:**  ` 9b6bcd3 (develop)`

### Issue description
I created a new modeling project and added features A,B,C below the root feature (as depicted in the attached image). After adding the constraint (A or B), the root feature  is colored in red. There is no entry in the legend though. This might be confusing, as red is usually used for dead features.
Reopen the file helps, as the analyzer is probably invoked again and has no issues anymore.

![image](https://cloud.githubusercontent.com/assets/263321/16829524/20cd5b96-4999-11e6-8973-e4058727428d.png)

**Comment by tthuem** [comment]
Jens, Sebastian, who can fix this?
