### ISSUE TITLE
cannot install FeatureIDE without JUnit and other Java IDE dependencies

### ISSUE THREAD

**Issue by anb0s** [FeatureIDE/FeatureIDE#369]
#### Prerequisitives
* **Eclipse Version:**  `Add text here (needed for best issue handling)`
Eclipse IDE for C/C++ Developers
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

* **FeatureIDE-Version:**  `Add text here (needed for best issue handling)`

* **Operating system:** `Add text here (needed for best issue handling)`
Windows 7 x64
* **Java runtime used to run eclipse:** `Add text here (needed for best issue handling)`
java.runtime.version=1.7.0_75-b13

* **FeatureIDE Composer:** `Add text here (optional, leave blank if not needed)`
* **Git branch/Commit-ID:**  `Add text here (optional, leave blank if not needed)`
* **Java compiler used to build the FeatureIDE plugin:** `Add text here (optional, leave blank if not needed)`

### Issue description
  Software being installed: FeatureIDE 3.0.1.201605191759 (de.ovgu.featureide.feature.group 3.0.1.201605191759)
  Missing requirement: FeatureIDE 3.0.1.201605191759 (de.ovgu.featureide.feature.group 3.0.1.201605191759) requires 'org.junit 0.0.0' but it could not be found

**Comment by anb0s** [comment]
looks like related to #326

**Comment by tthuem** [comment]
Did you try to install the unit tests? They are not designed for end-users, as they cannot be run anyway from the GUI.

Seems to be not related with issue #326.

Maybe we should remove it from the update site in future to avoid confusion.

**Comment by anb0s** [comment]
No, i have just selected "FeatureIDE" feature and then eclipse started to resolve the dependencies, but it's working very slow in our company via proxy and we do not want to have all (not needed) eclipse dependencies to have the IDE lean.

**Comment by tthuem** [comment]
Thanks for the pointer. We'll check that for the hotfix.

**Comment by tthuem** [comment]
Jens, is this fixed with #384?

**Comment by FeatureIDE** [comment]
No, I just removed the dependency to JUnit (at least it is now optional)
To remove the dependencies to JDT I dont see a good solution.

**Comment by meinicke** [comment]
No, I just removed the dependency to JUnit (at least it is now optional)
To remove the dependencies to JDT I dont see a good solution.

**Comment by tthuem** [comment]
Duplicate to #326
