### ISSUE TITLE
Improve performance of explanations for feature model anomalies

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#372]
#### Prerequisitives
- **Eclipse Version:**  All
- **FeatureIDE-Version:**  3.0.1
- **Operating system:** All
- **Java runtime used to run eclipse:** All
- **FeatureIDE Composer:** All
- **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/c708eecc1bc7f2805199fa38b139539a9254da48
- **Java compiler used to build the FeatureIDE plugin:** All
### Issue description

Improve performance of Feature Model fault explanations (currently increase overall calculation times by a factor of 3).

Currently performance tests fail (JUnit timeout), quick-fixed using option to disable explanations.
See: https://github.com/FeatureIDE/FeatureIDE/commit/6f7c254363f1da19282789ebc0a627f3f0a8b45b#diff-6782d44a0497aecf593b117d5ec49cda

**Comment by tthuem** [comment]
Done
