### ISSUE TITLE
Make FeatureC composer ready for the update site

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#379]
We code on FeatureC composer in the repository for a while now. Either make the code stable enough for releases of FeatureIDE or move it to experimental plug-ins.

**Comment by tthuem** [comment]
Or, is it already stable enough for the update site?

**Comment by ckruczek** [comment]
With #311, I already explained what additional work with FeatureC has to be done. My personal point of view is not to integrate FeatureC into FeatureIDE unless the described enhancements are implemented. So, I guess we could move it to the experimental plug-ins.

**Comment by tthuem** [comment]
Fine for all, to move it to experimental?
