### ISSUE TITLE
Error while generating all valid configurations in projects with java nature

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#384]
#### Prerequisitives
* **FeatureIDE-Version:**  3.1.0

### Issue description
Using the example Stack-FH-Java, click on Product Generator, generate all valid configurations, and do not select "Create new projects". We get an error window with NullPointerException and no output is generated.

**Debug:** In `de.ovgu.featureide.ui.actions.generator.Generator.Generator(int, ConfigurationBuilder)`
if the project has java nature, it creates an instance of `TestRunner` but then it cannot load the class `org.junit.runner.notification.RunListener`

**Fix:** Adding the required bundle `org.junit` in `/de.ovgu.featureide.ui/META-INF/MANIFEST.MF` fix the issue. But maybe you want to refactor.

**Comment by meinicke** [comment]
A) We can add junit to the dependencies,
or
B) We can check wheter junit is installed at the point is is required.

**Comment by jabiercoding** [comment]
Well, in this plugin it is only used in the method that I mentioned but it is a nice feature to be able to compile and launch junit tests for each generated configuration... In case that it is not natural to move this post-processing to another plugin I think that A is better (as workaround).  You can add another Issue for trying to refactor this, it will be nice to have an extension point for implementing generators to remove the "switch" "cases"  in ConfigurationBuilder.

**Comment by meinicke** [comment]
I quess it is a good idea to create extension points here to implement other compilers or analysis (e.g. static analysis)

For the moment I will just add the dependency and a new ticket for extension points

**Comment by meinicke** [comment]
I added a check whether the JUnit plugin is installed. 
The reference to JUnit is now optional.

**Comment by jabiercoding** [comment]
nice,
just a minor detail, if I am not missing something, probably you can replace
```
	private static boolean JUNIT_INSTALLED = false;
	static {
		final Bundle[] bundles = InternalPlatform.getDefault().getBundleContext().getBundles();
		for (Bundle bundle : bundles) {
			if ("org.junit".equals(bundle.getSymbolicName())) {
				JUNIT_INSTALLED = true;
				break;
			}
		}
	}
```
with 
`private static boolean JUNIT_INSTALLED = Platform.getBundle("org.junit")!=null;`

**Comment by meinicke** [comment]
you are right, thanks for the hint! 
I changed the code.
