### ISSUE TITLE
T-Wise variant generation with SPLCATool CASA is not working

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#387]
#### Prerequisitives
* **FeatureIDE-Version:**  3.1.0

### Issue description
Import the images_example, click on Product generation, select T-wise and the CASA algorithm.
Nothing is created.

**Debug:** `de.ovgu.featureide.ui.actions.generator.configuration.SPLCAToolConfigurationGenerator.runSPLCATool()` calls `generate(100, maxConfigs());` which is an empty method in `no.sintef.ict.splcatool.CoveringArrayCASA`

**Comment by tthuem** [comment]
Duplicate to #414
