### ISSUE TITLE
Generated dimacs file contains wrong number of clauses

### ISSUE THREAD

**Issue by joliebig** [FeatureIDE/FeatureIDE#388]
#### Prerequisitives
* **Eclipse Version:**  `Mars.2 Release (4.5.2)`
* **FeatureIDE-Version:**  `3.1.0`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `Java(TM) SE Runtime Environment (build 1.8.0_91-b15)`
* **FeatureIDE Composer:** `feature modelling`
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** `

### Issue description
The generated dimacs file for the model.xml (see [model.txt](https://github.com/FeatureIDE/FeatureIDE/files/398081/model.txt)) contains the wrong number of clauses (57 instead of 58). This may cause an error during t-wise product generation, which fails with an error (ICPL 2-wise, but all others fail too):
![2016-08-02 22_49_10-clipboard](https://cloud.githubusercontent.com/assets/380818/17344695/74013976-5903-11e6-8974-888df26b68a0.png)

![2016-08-02 22_51_29-window](https://cloud.githubusercontent.com/assets/380818/17344797/b6ea4642-5903-11e6-9836-4fc974f5f8df.png)

**Comment by jabiercoding** [comment]
This might be related to #384
I guess that @joliebig , you have the java nature in the .project file of your FeatureIDE project.
I tested with your feature model removing the java nature and it creates the t-wise configurations

**Comment by joliebig** [comment]
Yes, removing the java nature works. Thanks.
