### ISSUE TITLE
tooltip shows wrong name after changing a feature

### ISSUE THREAD

**Issue by joliebig** [FeatureIDE/FeatureIDE#389]
#### Prerequisitives
* **Eclipse Version:**  `Mars.2 Release (4.5.2)`
* **FeatureIDE-Version:**  `3.1.0`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `Java(TM) SE Runtime Environment (build 1.8.0_91-b15)`
* **FeatureIDE Composer:** `feature modelling`
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
When changing a feature name the tooltip of the feature still shows the old feature name. Saving the feature model does not change that. One way to get the right tooltip is to reopen the feature model.

![2016-08-02 22_56_33-window](https://cloud.githubusercontent.com/assets/380818/17345166/123eba18-5905-11e6-8d7c-933d5e2c6dab.png)

**Comment by meinicke** [comment]
I cannot reproduce the bug (tried it with current nightly build and with the last release 3.1.0).

works for me.
