### ISSUE TITLE
Antenna parsing does not fail on edge case

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#390]
#### Prerequisitives
* **Eclipse Version:**  `Mars.2 Release (4.5.2)`
* **FeatureIDE-Version:**  `3.1.0.201607211032`
* **FeatureIDE Composer:** `Antenna`

### Issue description
Antenna parsing should fail when entering '#(ä|ö|ü|ß)if', but accepts it and changes it to '#?if'.

Before:
![2016-08-16_21-42-13](https://cloud.githubusercontent.com/assets/8019776/17713422/242c94c4-63fb-11e6-8365-d82d0d103323.png)

After:
![2016-08-16_21-42-49](https://cloud.githubusercontent.com/assets/8019776/17713425/29f5ea72-63fb-11e6-9792-3e430d1caa5b.png)

**Comment by tthuem** [comment]
Don't see any problem here. Antenna seems to generate ? because of a wrong charset, but if Antenna is fine with it, why should FeatureIDE report a problem? Also, it seems to be a very unlikely case. Please reopen if this is still a problem.
