### ISSUE TITLE
Refactor non-Eclipse related code of FeatureIDE into a Java library

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#392]
Currently, FeatureIDE is only usable as an Eclipse plug-in. In future, we might want to support other IDEs such as IntelliJ or provide some of the functionality to other kind of Java development, including dynamic product lines.

Sebastian started with the implementation in a branch: https://github.com/FeatureIDE/FeatureIDE/tree/Core_Library

**Comment by skrieter** [comment]
Done.

**Comment by tthuem** [comment]
Where is documented how to create the Jar?

**Comment by skrieter** [comment]
Added `readme.txt` with instructions (and common errors) for building the jar file in f5577232a2bad0c94840ee919d8cea4bbca5da42.

**Comment by tthuem** [comment]
Thanks
