### ISSUE TITLE
Creating a new framework project leads to a compiler error

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#394]
#### Prerequisitives
- **Eclipse Version:**  4.5.2
- **FeatureIDE-Version:**  3.1.0
- **Operating system:** Windows 10
- **Java runtime used to run eclipse:** 8
- **FeatureIDE Composer:** Framework
### Issue description

After creating a new project, I encountered the following error marker. What does it mean that the file is not local?

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/17970970/0aca94b0-6ad9-11e6-9b1f-e27026f7b498.png)

This issue might not be relevant to the tutorial, but especially for team project, book, and upcomming lectures next term.

**Comment by tthuem** [comment]
In contrast, HelloWorld example worked just fine.

**Comment by tthuem** [comment]
Also, the first steps are rather unclear as not a single plug-in project is created in the first place.

**Comment by Subaro** [comment]
@tthuem I don't get the error message.

**Comment by tthuem** [comment]
Indeed, I also do not get any compiler error anymore.
