### ISSUE TITLE
Collaboration diagram shows boxes for propositional signs (e.g., |) and for deselected features in top left corner

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#395]
#### Prerequisitives
* **Eclipse Version:** Neon
* **FeatureIDE-Version:**  3.1.0
* **Operating system:** Win 10
* **Java runtime used to run eclipse:** 1.8
* **FeatureIDE Composer:** Antenna
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/069ba9fdca66c0552446d065b22e7a33d8452320

### Issue description

Collaboration diagram shows boxes for propositional signs (e.g., |) and for deselected features in top left corner see attachments

![fault](https://cloud.githubusercontent.com/assets/1482595/18036688/efff12be-6d3f-11e6-93f3-5d3fabca254d.JPG)

**Comment by tthuem** [comment]
I think I've seen this month ago, but hard to reproduce. Can you reproduce it?

**Comment by meinicke** [comment]
Yes it it reproducible, the example is shown in the picture.
The thing is that this happens for the Elevator example.

**Comment by tthuem** [comment]
Christopher, do you have time tomorrow to try to fix this?

**Comment by tthuem** [comment]
Alex, do you have time for this on Friday?

**Comment by AlexanderKnueppel** [comment]
Yes, I'll try to fix this on friday.

**Comment by AlexanderKnueppel** [comment]
I cannot reproduce this behaviour.

![image](https://cloud.githubusercontent.com/assets/263321/18204932/ace06df0-711f-11e6-9b8c-298c72d57581.png)

Tested with Mars and Neon on commit id 069ba9f. Another question: what does A | B mean for Antenna? I thought, Antenna recognizes only logical operators (e.g., ||) and not bitwise operations.

**Comment by tthuem** [comment]
Jens, we need your support on how to reproduce it and whether using the correct operators already solves the problem?

**Comment by meinicke** [comment]
activate show unselected features in the collaboration diagram.

it will either create an entry for "|" or for !AAAAAAAA

**Comment by tthuem** [comment]
Alex, can you reproduce it now?

**Comment by AlexanderKnueppel** [comment]
Yes, my fault. I'll try to fix it now.
