### ISSUE TITLE
Copy & Paste Partial Feature Model

### ISSUE THREAD

**Issue by TNO-ESI** [FeatureIDE/FeatureIDE#396]
#### Prerequisitives
* **Eclipse Version:**  4.5.1
* **FeatureIDE-Version:**   3.1.0.201607211032	
* **Operating system:**  Ubuntu
* **Java runtime used to run eclipse:** OpenJDK 1.7.0_111
* **FeatureIDE Composer:**
* **Git branch/Commit-ID:**
* **Java compiler used to build the FeatureIDE plugin:**

### Issue description
How can I copy a selected part of a feature model diagram as subtree and paste it as subtree below an existing feature in another feature model (in the same or a different project)? It seems that there is no copy function implemented, not even if a single feature is selected.

**Comment by tthuem** [comment]
Indeed. The easiest way to do this right now, is to switch to the source tab and copy and paste the according subtree in XML format directly. However, if you copy within the same model, you have to rename all identifiers.

**Comment by tthuem** [comment]
Hope this solves your problem. If not, it would be interesting to know more about the use case of copy and paste.

**Comment by TNO-ESI** [comment]
This is a solution that we had though of ourselves as well, but it is not a very user-friendly one, especially if the model is somewhat larger...

**Comment by tthuem** [comment]
Right. Still, I need more motivation for copy and paste, as we simply have not needed that before. Why do you need to clone parts? What should happen with names in the same model or are you just using it across models?

It could also indicate that copy and paste is not the right thing to do. For example, with Velvet, you can automatically include instances of complete feature models. However, that might depend on the use case, such that we need more input.
