### ISSUE TITLE
FSTModel contains separate entries for !Feature

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#397]
#### Prerequisitives
* **FeatureIDE-Version:**  3.1.0
* **FeatureIDE Composer:** Antennaneeded)`

### Issue description
The fst model contains separate entries for !Feature.
So the entry for Feature is not found.
This causes several issues for collor annotations in the editor, entries in the Collaboration diagram, and in the outline. see pic:

![fstmodelfault](https://cloud.githubusercontent.com/assets/1482595/18139197/5cf59736-6f7e-11e6-8349-13991e94a228.JPG)
)

**Comment by tthuem** [comment]
Besides that "!Hello" is not shown in the collaboration diagram, I cannot see any problems here. Also I'm not following what exactly is the problem. In particular, what do you mean by separate entries? "Not" missing in your explanation? Please clarify.

**Comment by meinicke** [comment]
look at the picture, the entry for !Hello is missing in the CD, the code and the outline entry is not highlighted.

seems to be fixed with commit  https://github.com/FeatureIDE/FeatureIDE/commit/c90a1c29797af6c6a7cba586dee616ffec3c40dd
