### ISSUE TITLE
Enable creation of new files in project explorer (as in package explorer)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#405]
The perspective-specific menu is simply not available even though the FeatureIDE perspective is active.

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/18328841/19539842-7551-11e6-9058-acc4067219df.png)

Works fine in package explorer, but as the color support is only available in the project explorer this is rather odd.

**Comment by tthuem** [comment]
Otherwise, project explorer should not be the first tab.

**Comment by tthuem** [comment]
Seems to be a known problem for the project explorer.

**Comment by Subaro** [comment]
<img width="475" alt="ccc" src="https://user-images.githubusercontent.com/6231523/28869655-b80bd0a6-777d-11e7-8c1b-1c88e0b92a56.PNG">

**Comment by Subaro** [comment]
<img width="321" alt="ddd" src="https://user-images.githubusercontent.com/6231523/28875655-91f7daa4-7796-11e7-9c12-e724a753d1cd.PNG">
