### ISSUE TITLE
Feature model edits view shows wrong data if features occuring in constraints are renamed

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#408]
![zwischenablage-4](https://cloud.githubusercontent.com/assets/5330357/18342921/62a2a69a-75b1-11e6-9603-d1aff6c0bbff.png)

**Comment by tthuem** [comment]
This does not seems to be an update problem, as switching to another editor does not help. Only closing the feature diagram and opening it again helps.

**Comment by tthuem** [comment]
Tried many other cases and always worked well. However, the actual cause seems to be that the edit view does seems to interact with the renaming of features. In the above example, I renamed feature Shortest_Path into ShortestPath, which is a refactoring, but marked as arbitrary edit!

![zwischenablage-5](https://cloud.githubusercontent.com/assets/5330357/18343094/34e0b02a-75b2-11e6-8c70-d2d2e29b382a.png)

**Comment by tthuem** [comment]
Seems that this only happens if features are contained in constraints. The renaming does not seem to be applied to constraints.

**Comment by tthuem** [comment]
@Subaro Why is it assigned to me?

**Comment by SundermannC** [comment]
This bug seems to not be reproducible anymore.
