### ISSUE TITLE
Product generator does not generate all valid configurations

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#413]
This bug is really critical for the tutorial and some of our recent evaluations.

Generated all valid configurations for http://git.iti.cs.ovgu.de/dbse-projects/featureide/tree/master/tutorials/2016-SPLC/projects/ImprovedElevator and was wondering why a bug that only occurs in one configuration is not found. It turned out that the number of configurations is correct, but some are identical and some are missing.

![zwischenablage-2](https://cloud.githubusercontent.com/assets/5330357/18363135/14f7be96-7609-11e6-899b-de79681b0af3.png)

**Comment by Enxhi04** [comment]
I tried the Product generator with a smaller model and have the same issue. Is the bug fixed? @meinicke

**Comment by tthuem** [comment]
Thanks for your report, we will have a look soon.

**Comment by PaulWestphal** [comment]
The product generator generates the correct number of configurations, but if you look at them, they're invalid and duplicates.

**Comment by tthuem** [comment]
@PaulWestphal This bug was fixed back then, it seems to be only related. Please create a new issue instead, as discussed in our last meetings.

**Comment by PaulWestphal** [comment]
https://github.com/FeatureIDE/FeatureIDE/issues/1066
