### ISSUE TITLE
Product generator finds only few random configurations even if there are more

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#415]
Started random product generation for a product line with 16 products and a maximum set to 20 products and the result was that only 4 products were generated.

**Comment by meinicke** [comment]
Use the Hello World model, it only creates 3 configurations.

**Comment by tthuem** [comment]
Not an issue for the tutorial, but it is weird that the generator cannot find all valid configurations using this option. In other words, some configurations are not computed as random configurations, which is a limitation of the random generation.

**Comment by meinicke** [comment]
The generator is actually broken.
Before the generator generated all configurations. 
However, the question is what a default behavior should produce.  (e.g., do we want to allow duplicate configs; should it be possible to generate more configs than defended in the model)

**Comment by skrieter** [comment]
Fixed in 29b94d0d0ace32b282742625eb1aeba08f63fde0.
