### ISSUE TITLE
Feature with or-group not recognized as false-optional in constraint dialog

### ISSUE THREAD

**Issue by AlexanderKnueppel** [FeatureIDE/FeatureIDE#418]
The constraint editor should recognize that constraint "Camera" would lead to feature "Media" beeing false-optional:
![image](https://cloud.githubusercontent.com/assets/263321/18388941/e9c3bd9c-76a3-11e6-8445-e9a58a1b610a.png)

Feature "Media" is declared as false-optional in the feature model editor though (after adding constraint "Camera"). The same happens for alternative groups.

Edit: `ConstraintTextValidator.java` in `de.ovgu.featureide.fm.ui.editors` should be refactored such that each analysis (void, false-optional, dead, redudant) relies on the `FeatureModelAnalyzer` rather than on a sole implementation (would probably also reduce unnecessary feature model cloning). This may already solve this issue.

**Comment by tthuem** [comment]
This behavior is intended, as there is no graphical representation of mandatory within a group. With several groups per feature this would somehow be possible, but these are not yet supported and it would require reordering, which might change the semantics of the product line for some composers. Hence, this is not considered a false-optional feature.
