### ISSUE TITLE
New notation for dead and false-optional features that does not interact with coloring of features

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#419]

**Comment by tthuem** [comment]
Problem seems to be related to color scheme.

**Comment by meinicke** [comment]
Works for me.
@tthuem Please give more information how to reproduce.

<img width="515" alt="falseoptionaldead" src="https://cloud.githubusercontent.com/assets/1482595/18617912/9e41589a-7da9-11e6-9205-9c0685f09289.PNG">

**Comment by meinicke** [comment]
<img width="217" alt="falseoptionaldead2" src="https://cloud.githubusercontent.com/assets/1482595/18617932/ebacd0aa-7da9-11e6-8ed5-acef3e3ac968.PNG">

**Comment by tthuem** [comment]
If the color scheme is activated, the dead and false-optional features are not colored in the feature diagram. This is unintuitive and took me quite some time to find out. We need an intuitive handling for that.

**Comment by tthuem** [comment]
Works now, but colors are still confusing together with assigned colors.

We could add error markers, warnings and infos instead. Similar to the problem view.

Related: Also there could be an entry for the current color scheme in the legend with the name of the color scheme.

**Comment by tthuem** [comment]
Done with #649
