### ISSUE TITLE
Left align layout does not contain connections in special cases

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#421]
#### Prerequisitives
* **Eclipse Version:**  LUNA
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/c982d12a253983ff7cc69240a597c4207bed851c

### Issue description
When opening a feature model that is left aligned then for some models the connections are not drawn (only happens after opening the file not after changing from another layout)

![bugleftlayout](https://cloud.githubusercontent.com/assets/1482595/18495466/266820a8-79ec-11e6-9504-7e29448d7566.JPG)

	<featureModel>
		<properties/>
		<struct>
			<and abstract="true" mandatory="true" name="HelloWorld">
				<description>
					
				</description>
				<feature name="L2Build">
					<description>
						
					</description>
				</feature>
				<feature mandatory="true" name="AAAAAA">
					<description>
						
					</description>
				</feature>
				<feature name="CCCCCCC">
					<description>
						
					</description>
				</feature>
			</and>
		</struct>
		<constraints/>
		<calculations Auto="true" Constraints="true" Features="true" Redundant="true" Tautology="true"/>
		<comments/>
		<featureOrder userDefined="false"/>
	</featureModel>

>

**Comment by tthuem** [comment]
Fixed for 3.2.0 (release) or 3.3.0 (develop)?

**Comment by skrieter** [comment]
Both.
Does the bug still occur for you?

**Comment by tthuem** [comment]
Where can I see in which branches a certain commit is in? It seems that Github is pointing to develop even it has been fixed in release.

**Comment by skrieter** [comment]
I don't see an easy way on github.
You can sort of tell from the branch network graph, but I find this rather confusing.

However, Eclipse shows you which branches contain a specific commit (in the commit view).
Other git clients can propably do the same.

**Comment by AlexanderKnueppel** [comment]
@tthuem release was merged into develop after  the commit, so the commit is essentially part of the history of both branches. Maybe github prefers the default? If you are using the git bash you can use **git branch -a --contains [sha1]**

**Comment by Kogoro** [comment]
Since this change, the layout seems to be broken when you delete a subtree and then undo the operation. The result looks like this:
![screenshot from 2016-10-12 15 27 26](https://cloud.githubusercontent.com/assets/8019776/19311942/a74576fc-9090-11e6-9229-e34cd6c984cb.png)

**Comment by skrieter** [comment]
@Kogoro I cannot reproduce this behavior.
Can you provide a small example with a feature model and all the steps you did?
(Perhaps it would be better to open a new issue :) )

**Comment by Kogoro** [comment]
Steps to reproduce the issues are:
1. Open a feature modeling example like E-Shop or FeatureIDE
2. Delete a feature, which has a subtree
3. Use undo
4. The feature model looks like the image above
Going back to the commit 76f6537146b70cb830551e0a2da4ebc1509efe07 removes the bug, so it must happened in the next commit.

**Comment by skrieter** [comment]
Thanks! (Apparently my model was too small)
I fixed it in c5debd2b9c3f21cea211f687b638cc0ffcc49a12
