### ISSUE TITLE
Quick fix for unused and "false optional" features is not triggering refresh

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#423]
![zwischenablage-2](https://cloud.githubusercontent.com/assets/5330357/18543541/aa1d5d60-7b30-11e6-8c9b-d677bae9c9c4.png)

![zwischenablage-3](https://cloud.githubusercontent.com/assets/5330357/18543542/ad03820c-7b30-11e6-8a0a-05ae75c5011a.png)

Manual refresh on complete project:

![zwischenablage-4](https://cloud.githubusercontent.com/assets/5330357/18543554/bb0b65e0-7b30-11e6-83ee-177d77b15364.png)

Without refresh, seems that the quick fix did not work and also the warnings/infos are not updated.

**Comment by Kogoro** [comment]
Refresh works now when a configuration is created, but a refresh is not triggered when you delete a configuration manually. Also, a comma is placed at the end of each infos which could be removed for a more polished look.
Maybe you could also create another quick-fix for false-optional to make the features mandatory. I think this could be really helpful too.

**Comment by Subaro** [comment]
@Kogoro 
I removed the comma at the end of each info. I also created another quick fix to change the false-optional features to mandantory, but it seems that the given feature model for the quick fix class is not the same than the feature model of the current feature diagram page. Altering the given feature model does nothing.
