### ISSUE TITLE
Warnings for unused features not updated when removing configurations

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#424]
"Check and generating markers is only triggered when a configuration file or the feature model changes. NOT when a project is reopened or imported, or when a configuration file is deleted."

see #402

**Comment by AlexanderKnueppel** [comment]
Reopening and importing should work now, as the check is triggered by project construction. Deleting a configuration file was not working in the first place I believe and should get fixed

**Comment by Subaro** [comment]
The warnings will now be updated when removing/deleting configurations
