### ISSUE TITLE
Manual layout completely broken

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#429]
This bug is very annoying for the current team project and a no-go for the next release. Positions of features are not saved at all and weird things happen in manual layout.

Opened a feature diagram and selected manual layout:
![fm1](https://cloud.githubusercontent.com/assets/5330357/19085515/db3882f0-8a6a-11e6-9567-2eebb652c3a8.PNG)
![fm2](https://cloud.githubusercontent.com/assets/5330357/19085521/dd4270e2-8a6a-11e6-8c23-0c146adabe96.PNG)

Moved features and saved the diagram:
![fm3](https://cloud.githubusercontent.com/assets/5330357/19085526/df7a54b0-8a6a-11e6-84e0-fc4e3dc54abf.PNG)

Closing and reopening the diagram results in the following:
![fm4](https://cloud.githubusercontent.com/assets/5330357/19085530/e1232d64-8a6a-11e6-8be8-d74ce799de54.PNG)

There are many further issues with the manual layout when working with it for a while.

@skrieter Seems to be related to your changes. Please fix in release and merge to develop afterwards. Sebastian, when can you fix this?

**Comment by tthuem** [comment]
@skrieter  Why in development branch?

**Comment by skrieter** [comment]
@tthuem Because _develop_ is the default branch and all fixes from _release_ should be merged back into it.
(Unless it is a quickfix, specifically made for the next verison)
