### ISSUE TITLE
FMEditor: Two Outlines - Two Implementations

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#430]
#### Prerequisitives
- **FeatureIDE-Version:**  `latest develop`
### Issue description

For the Feature Model Editor, there are two outlines, the original of eclipse and the FeatureIDE Outline. Both show nearly the same content, but they are different in the implementation and the package.

The customization of the normal outline for the feature model editor lies under package _de.ovgu.featureide.fm.ui.views.outline_ in form of _[FmOutlinePage.java](https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/views/outline/FmOutlinePage.java)_.
The other implementation is located at _[de.ovgu.featureide.ui.views.collaboration.outline.Outline.java](https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.ui/src/de/ovgu/featureide/ui/views/collaboration/outline/Outline.java)_ and is more functional e.g. in form of double-click to toggle mandatory status, but needs a refactoring I think.

I think it could be very confusing for users as I would expect the same behavior when they look alike.
So the FeatureIDE outline view for feature models should also be visible in the normal outline when the feature model editor is the active editor.

**Comment by tthuem** [comment]
Outline for feature models should also be available if only fm.core and fm.ui are installed.

**Comment by Kogoro** [comment]
Pushed a working version to the branch. Now the Outline is in the fm.ui package and will be extended if needed. 
To drawbacks until now:
- [ ] There is a bug that actions that are executed through the outline and should affect the feature model in the editor have no effect. On the other hand is the collapsed sync working very well. Seems also as a wrong feature model is used. Must investigate this further.
- [ ] Until now, the eclipse outline uses also a different implementation which will be corrected in the next commit

Nevertheless, someone maybe can take a look at this version for feedback on how the new outline is displaying actions?

**Comment by tthuem** [comment]
Can you give us a demo in next meeting?

**Comment by Kogoro** [comment]
Yes should be possible.
