### ISSUE TITLE
Save feature model expansion states in extra XML.

### ISSUE THREAD

**Issue by skrieter** [FeatureIDE/FeatureIDE#433]
#### Prerequisitives
- **FeatureIDE-Version:**  3.1.2
- **Git branch/Commit-ID:**  833b18b2ce1174232b13b1867df5a87526b1b3a4
### Issue description

The XML that saves the GUI information for the feature model editor is save by the class FeatureDiagramEditor:
Line 877, 955: `FileHandler.save(Paths.get(extraPath), graphicalFeatureModel, format);`

The information for feature model expansion states need to be saved in this file as well.

To save additional information they must to be available in the implementation of IGraphicalFeatureModel (parameter _graphicalFeatureModel_) and must be saved by the class GraphicalFeatureModelFormat (parameter _format_).

**Comment by tthuem** [comment]
Christopher, please decide whether this change is feasible within the team project or should be fixed afterwards. That was my fault, as I did not know about the second storage option for attributes.

**Comment by Kogoro** [comment]
I think we will make it and change the code from the IFeatureModel to the IGraphicalFeatureModel during this week.

**Comment by Kogoro** [comment]
The change from IFeatureModel to IGraphicalFeatureModel has a bigger impact as we thought. Since the GraphicalFeatures are often redrawn at various situations, keeping the collapsed state is more complicated and requires more work. So we will change the structure after the team project.

**Comment by tthuem** [comment]
@Kogoro Done?

**Comment by Kogoro** [comment]
Yeah that is done in team1 branch
