### ISSUE TITLE
Create a feature model with features when adding the FeatureIDE nature

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#44]
For AspectJ we have functionality that extracts the features from aspect files and creates a corresponding feature model automatically, if the FeatureIDE nature is added to an existing project, Maybe this functionality could be applied to other composition tools.

**Comment by tthuem** [comment]
Done by Team2.

**Comment by tthuem** [comment]
Should be used to add all FeatureHouse examples as FeatureIDE examples.

**Comment by tthuem** [comment]
Duplicate to #436

**Comment by tthuem** [comment]
Duplicate to #578
