### ISSUE TITLE
Generated dimacs file contains wrong number of clauses

### ISSUE THREAD

**Issue by joliebig** [FeatureIDE/FeatureIDE#440]
#### Prerequisitives
- **Eclipse Version:**  `Mars.2 Release (4.5.2)`
- **FeatureIDE-Version:**  `3.1.2`
- **Operating system:** `Windows 10`
- **Java runtime used to run eclipse:** `java version "1.8.0_102`
- **FeatureIDE Composer:** `feature.modelling`
- **Git branch/Commit-ID:**  ``
- **Java compiler used to build the FeatureIDE plugin:** ``
### Issue description

The generated dimacs file for the model.xml (see [model.txt](https://github.com/FeatureIDE/FeatureIDE/files/547360/model.txt)) contains the wrong number of clauses (57 instead of 58). As a result, the created dimacs file has to be fixed manually, before it can be processed by other tools.

This issue was reported earlier ([issue 388](https://github.com/FeatureIDE/FeatureIDE/issues/388)), but the proposed fix does not apply here.

**Comment by tthuem** [comment]
Can you please provide more details what is missing and why?

**Comment by joliebig** [comment]
The dimacs export creates a dimacs file with the wrong number of clauses: `p cnf 33 57`. The correct line is `p cnf 33 58`.

**Comment by tthuem** [comment]
Why fixed in develop? Delays the fix to be released by at least two months.
