### ISSUE TITLE
Make feature folders more accessible in FeatureHouse

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#443]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.1.2.201610250400`
* **FeatureIDE Composer:** `FeatureHouse`

### Issue description
Feature folders in FeatureHouse projects are at the moment like normal folders. You must double-click them to open the next level. This lead to some missing context menu entries like 'Source' and an inaccessibility (e.g. you can't format the files easily, refactoring does not work as you would think, etc.).
The enhancement could be a more 'src' like behavior. E.g. when you rename a file, then all other files in other feature folders are also renamed.

**Comment by tthuem** [comment]
Sounds all interesting and we've tried several of these things already in the past.

The short story: You basically have to reimplement JDT for FeatureHouse, which is infeasible at the moment. Same applies for any other technique than FeatureHouse and it is simply impractical to develop all this support for any composer. We've had several students implementing prototypes, but none of them made it into a release so far. Good luck if you want to try it too. :)
