### ISSUE TITLE
CNF is created for almost every analysis

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#449]
Currently, there is duplicated effort for analyses that consider the feature model, because the CNF is created several times. Instead, the FeatureModelAnalyzer could store the CNF once it is created and use it several times. If the feature model changes, the analyzer could remove the CNF and create it again once requested.

**Comment by TimoGuenther** [comment]
The CNF is cached as of https://github.com/FeatureIDE/FeatureIDE/commit/c898dc3030babf8746c52d560adbb4353b234918. The analyzer creates the CNF lazily when needed and resets it when the feature model changes, i.e., when the feature model fires specific events. I don't know if the event types `FEATURE_MODIFY` and `HIDDEN_CHANGED` have an impact on the feature model formula, though. Someone confirm this, please.

I also tried having other classes use the CNF cached by `FeatureModelAnalyzer` but soon realized that a CNF isn't the same as a CNF. There are a few dimensions in which the feature model formulas used by the various classes differ (whether the root feature should be included, whether it should be "compact" or "regular", whether Boolean variables should be included, etc.). Probably not worth the effort to cache all these different versions of the feature model formula.
