### ISSUE TITLE
Antenna jar requires Java 1.8 instead of Java 1.7

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#450]
FeatureIDE should work with Java 1.7 and thus the jar should be compiled with 1.7 if possible:

https://github.com/FeatureIDE/FeatureIDE/commit/f2d3cc66b42611531e5b6a65b174bf2d70338b25

**Comment by meinicke** [comment]
fixed in https://github.com/FeatureIDE/FeatureIDE/commit/19762248b265a0a45c4ce69a3704bb6bdaf94059

**Comment by meinicke** [comment]
see: https://github.com/FeatureIDE/FeatureIDE/commit/8dca461dad947039cef4ccfcaab8c019709d1a0e
