### ISSUE TITLE
FeatureHouse (Fuji jar) requires Java 1.8 instead of Java 1.7

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#451]
FeatureIDE should work with Java 1.7 and thus the jar should be compiled with 1.7 if possible:

https://github.com/FeatureIDE/FeatureIDE/commit/6a9f611813839c880a6da387fe57d1ea40119521

**Comment by meinicke** [comment]
works for me
all classes are at most compiled with Java 7

**Comment by meinicke** [comment]
see : https://github.com/FeatureIDE/FeatureIDE/commit/8dca461dad947039cef4ccfcaab8c019709d1a0e

**Comment by tthuem** [comment]
Problem seems to be rather Fuji.

**Comment by tthuem** [comment]
Jens, you broke it: https://github.com/FeatureIDE/FeatureIDE/commit/5b8705081681015c6fd6f048419f38c7c3d96028

**Comment by meinicke** [comment]
Why should that be my commit?

**Comment by tthuem** [comment]
Who has access to Fuji and can compile it with Java 1.7?

The wrong version was included by someone with wrong Github settings recently: https://github.com/FeatureIDE/FeatureIDE/commit/5b8705081681015c6fd6f048419f38c7c3d96028

**Comment by tthuem** [comment]
Am I correct that this commit is only in develop so far?

**Comment by tthuem** [comment]
Done for now, see #455
