### ISSUE TITLE
Undoing "collapse siblings" does not refresh properly

### ISSUE THREAD

**Issue by TimoGuenther** [FeatureIDE/FeatureIDE#452]
Steps to reproduce:
1. Create a feature model containing a feature with siblings and add children to a sibling.
2. Collapse the siblings of the feature using the "collapse siblings" context menu entry.
3. Undo the operation (Ctrl-Z).

Example:
![undo collapse siblings graphical](https://cloud.githubusercontent.com/assets/18397625/21074637/44397256-befe-11e6-9d79-97eebc42e26a.png)

Note how the Radio feature still shows the amount of collapsed children despite not being collapsed. Also, some of its children are missing some connection figures.

Only the undo operation is affected. Effectively undoing the operation by expanding each sibling or expanding everything is not affected.

**Comment by Subaro** [comment]
Is now fixed on branch bs_team1. 

@TimoGuenther please use the branch bs_team1 in future because the bs_team1_GraphficalRework will be removed.
