### ISSUE TITLE
Product generation of all valid configurations does not work if features contain whitespaces

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#453]
#### Prerequisitives
* **Eclipse Version:**  4.5.2
* **FeatureIDE-Version:**  3.1.0 and 3.1.2
* **Operating system:** Windows
* **FeatureIDE Composer:** Feature Modeling

### Issue description
In projects with feature modeling, product generation can only create configuration files. Still, this can also be used together with feature names like "A B". However, we found out that basically nothing happens for such feature models. Looks like something we could check in future with a new unit test.

**Comment by Subaro** [comment]
To create a test we need an IFeatureProject to create the Configuration Builder. Christopher and I didn´t find a way to get an IFeatureProject for the tests. Because of that, we skip the test. Is that ok?

**Comment by tthuem** [comment]
Fine.
