### ISSUE TITLE
Lines cross boxes for showing number of collapsed features

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#454]
Is it possible to draw collapse figures after connections (and giving those boxes background color)?

Right now it is hard to read some numbers if there are several connections on top of them.

**Comment by Subaro** [comment]
@tthuem Hello Thomas. I totally agree. I created my own GEF Editor to understand how GEF works.

**Comment by Subaro** [comment]
@tthuem Hello Thomas. I totally agree.  In the team project we didn´t found a solution to draw the decoration above the connection. So in the last days I created my own GEF Editor to understand how GEF works.

I found out that the connection are added to the connection layer and the other figures are added to the primary layer. By default GEF puts the connection layer to the highest level. Just refreshing the decoration after the connection won´t work this way. So i searched for a way to put a new layer(for the collapsed decoration) on top of the connection layer. It is possible but only if the ModelEditPart inheritances at least the FreeformGraphicalRootEditPart or ScalableRootEditPart, where you can organize your layer on your own.

Our current ModelEditPart uses AbstractEditPart. Switching to FreeformGraphicalRootEditPart or ScalableRootEditPart didn´t work.

**Comment by tthuem** [comment]
@Subaro Would it help to declare those boxes as connections instead of figures and make sure those are the last entries? Or is there no list with all connections?

Another option would be to adapt layout algorithms to incorporate those boxes, but this would involve a large effort, which is probably too large.

**Comment by Subaro** [comment]
@tthuem Yeah it helped. If the feature is collapsed it creates a connection to himself. Then I assigned the collapsed decoration as target decoration. 

This is what it look like:
![unbenannt](https://cloud.githubusercontent.com/assets/6231523/21314317/a5fd0418-c5f6-11e6-8f06-77d3abbe36f5.PNG)

Note: I switched the background color to white.

**Comment by tthuem** [comment]
Nice! If your done, please give it to @Kogoro for review.

**Comment by Kogoro** [comment]
Looks good to me.
Tested the bs_team1 branch and collapsed decoration is drawn above the connections.
