### ISSUE TITLE
Test Fuji with new FeatureIDE API

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#455]
Sebastian mentioned problems with current version of Fuji. Sebastian, anything more concrete? Which functionality is based on Fuji (must be tested)?

**Comment by tthuem** [comment]
@meinicke Sebastian said that it seems to work. Did you experience any problems? If not, go ahead an close this issue.

**Comment by wesleyxie** [comment]
Hi guys. I am now using FeatureIDE 3.2.0 it seems Java 1.7 is not supported yet. Could you point it out how to allow using Java 1.7 at the moment?

**Comment by tthuem** [comment]
@wesleyxie Could you please be more precise? What exactly is not working with release v3.2.0? Do you mean Java 1.7 for the JVM Eclipse is running at our for your code in a FeatureHouse project?

**Comment by wesleyxie** [comment]
@tthuem thanks a lot for the quick reply. Yes, it is the code. The JVM eclipse now is running on Java 1.7 and works well with fuji type checker enabled. But in FeatureHouse, the code now is not able to be compiled successfully when there is Java 1.7 features, e.g. Annotation.

**Comment by meinicke** [comment]
Can you give an code example, so we can reproduce it. 
I tried @Deprecated and LinkedList<Object> which are working.

**Comment by wesleyxie** [comment]
Thanks for the updates. @meinicke. Here is the code example:


List<String> aStringList = new ArrayList<>();
or
public @interface SomeAnnotation {
    ...
}

For above code, it will raise some compiling issue with 'token not expected' error message.

**Comment by tthuem** [comment]
The issue itself is too unspecific. If there are concrete compatibility problems, please report them.

@wesleyxie As you are refferering to the to-be-composed code, this is not related to this issue. As far as I know, FeatureHouse projects only support Java 1.5 for composition by now and I'm not aware that anyone is working on an extension to newer Java versions.
