### ISSUE TITLE
Collaboration diagram does not scale for preprocessor projects

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#461]
The collaboration diagram cannot be used as columns and rows consume too much space, such that only few features and files can be shown at the same time. There are two main problems:

1. Package names are always shown, which can lead to very wide column names. What about omitting package names at all? We could show them in a tool tip.

2. Showing the complete ifdef-structure for each ifdef does help to get an overview. We could replace that by simply printing the number of occurrences or by showing presence conditions instead of nested ifdefs. That is, instead of showing

```
ifdef A
    ifndef B
        ifdef C
```

we could print A && !B && C

Printing the number only would have the problem that we cannot jump to that ifdef anymore, as there might be several of them.

**Comment by tthuem** [comment]
Same for package names in FOP projects:

![fop-tracing-collaborationdiagram1](https://cloud.githubusercontent.com/assets/5330357/23365328/f8afd47c-fd02-11e6-84c2-dce76380bd91.png)

**Comment by Kogoro** [comment]
Can someone review the changes?

**Comment by tthuem** [comment]
Yes, I'll do it.

**Comment by tthuem** [comment]
Package names still too long. Also, I think that one presencondition in each line would be better to recognize where a precondition starts or ends.

![unbenannt](https://cloud.githubusercontent.com/assets/5330357/23601278/f43335b8-024a-11e7-9597-708e89c54753.PNG)

**Comment by Kogoro** [comment]
Will look into the long package names issue.
But I think, each presence condition in one line is not optimal as conditions grow easily and will not scale again.

**Comment by Kogoro** [comment]
As a compromise to longer lines in the collaboration diagram, only the specific directives for a feature and no hierarchy will be shown.

**Comment by Kogoro** [comment]
Looks now like this. It's more compact now. 
![unbenannt](https://cloud.githubusercontent.com/assets/8019776/23961128/437caea4-09aa-11e7-80f0-5bdac1c884f9.PNG)

**Comment by tthuem** [comment]
There is still a problem with package names of inner classes:

![packagenames](https://cloud.githubusercontent.com/assets/5330357/24549397/641e57d6-1619-11e7-8e73-d72080ffd1f2.PNG)

**Comment by tthuem** [comment]
Why does the branch still exist? And why does it have unmerged changes?

**Comment by Kogoro** [comment]
The branch will be used for #482, because this issue is not using presence conditions​ at all.

**Comment by tthuem** [comment]
Please rename the branch then (or create a new one and remove the old one).
