### ISSUE TITLE
If feature model is void, all features should be red instead of only the root feature

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#462]
Proposal by Gunter Saake. Is easier to recognize and also consistent as technically every feature is dead then.

**Comment by Subaro** [comment]
I created a feature model and added the constraint {not root}. That leads to NullPointerException and a ContradictionException. The Exception should be caught. I will also take a look at the exceptions.

**Comment by tthuem** [comment]
Please copy and paste the exceptions into that issue. Thanks.

**Comment by Subaro** [comment]
I can't reproduce the NullPointerException, but the ContradictionException always occur, when creating a constraint that leads to a void feature model. The Exception will be shown after saving.

![unbenannt](https://cloud.githubusercontent.com/assets/6231523/22396527/083c661c-e55c-11e6-85e7-959c977c0587.PNG)

**Comment by Subaro** [comment]
Is it needed to print out the ContradictionException? Or should we just skip the print?

**Comment by Subaro** [comment]
@skrieter Because the ContradictionException was caught but nothing was done in the catch-block I decided to not print out the Exception. The branch is ready for merging but I'm waiting for an answer.

**Comment by Subaro** [comment]
Apparently, the constraint that causes the void model will not be colored red.

![aaaaaaa](https://cloud.githubusercontent.com/assets/6231523/24519334/11793ef4-1585-11e7-8121-c498aeeffc91.JPG)

**Comment by tthuem** [comment]
That behavior is expected now, as we have explanations now. Still, the issues #484 is left to be done.
