### ISSUE TITLE
Statistics on feature models should be split into structural and semantical section

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#463]
In statistics view, there should be a subtree for all structural properties and one for all those that require a SAT solver to reason about valid combinations of features.

**Comment by tthuem** [comment]
Who can do this?

**Comment by Kogoro** [comment]
A suggestion for a new separation of structural and analytical information:
![unbenannt3](https://cloud.githubusercontent.com/assets/8019776/22296257/dfcadcfc-e319-11e6-8f8e-7ebc3522c243.PNG)
Does this fulfill the issue?

**Comment by tthuem** [comment]
1. The last two entries are structural information.

2. Please merge "Feature statistics" and "Structural informations" into "Syntactical statistics"

3. Please merge "Analytical informations" and "Valid configurations ..." into "Semantical statistics"

@RSchroeter Any other suggestions?

**Comment by Kogoro** [comment]
I changed it to the following tree:
![unbenannt4](https://cloud.githubusercontent.com/assets/8019776/22383547/8cc60ec0-e4ca-11e6-955c-aa9a35757ae3.PNG)
When this structure is good, I will merge it.

**Comment by tthuem** [comment]
Structure is fine, but I don't see a need that we dinstinguish between "expand to calculate" and "double-click to calculate. Can this be unified?
