### ISSUE TITLE
Content assist for preprocessor directives

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#464]
The content assist for prerpocessors currently shows the available features after typing for example //#if.

It would be nice to also propose the possible directives itself, i.e., #if, #else, #endif and so on depending on the used preprocessor.

It would also be nice to propose valid logical identifiers such as | for "or" in Antenna.
That would be helpfull as these identifiers differ across prepocessors and differ to the coresponding statement in Java.

**Comment by skrieter** [comment]
Implemented in [SP_MD_SoSe2018](https://github.com/FeatureIDE/FeatureIDE/tree/SP_MD_SoSe2018).
