### ISSUE TITLE
Antenna content assist does not work for #condition

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#467]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.2.0`
* **FeatureIDE Composer:** `Antenna`
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/92482c68917e5b592f22ea882b99fa951fce2e83

### Issue description
When typing '#condition', the content assist does not propose features to select.

**Comment by Subaro** [comment]
@meinicke Is did this a while ago for #elif. Just need to add a line here:

![unbenannt](https://cloud.githubusercontent.com/assets/6231523/22397016/9c6d9d46-e567-11e6-8f46-ccffcbf272ec.PNG)

Just thought it could save some time searching :)

**Comment by meinicke** [comment]
That actually seems somehow fishy as it is hard coded in the UI plugin; i.e., there should be a reference to the composer.

**Comment by tthuem** [comment]
Seems to be related to #352
