### ISSUE TITLE
Add new Class / Role does not work for packages

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#468]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.2.0`
* **FeatureIDE Composer:** `FeatureHouse`
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/92482c68917e5b592f22ea882b99fa951fce2e83

### Issue description
Whenusing the collaboration diagram to add a new role, the autocompletion for the new Class file wizard dies not work correctly if the selected Class has a package.
It will use the complete header of the class for the class name including the package name, and it does not fill the entry for the package. (cf. picture)

To reproduce it right-click on an empty role and select "Add new Class/Role"

![newclassrole](https://cloud.githubusercontent.com/assets/1482595/22435566/853182f4-e6ee-11e6-925f-d55261efe649.PNG)

**Comment by Kogoro** [comment]
@meinicke Can you check if it meets the desired behavior? I added the package name, if possible.

**Comment by meinicke** [comment]
can be merged
