### ISSUE TITLE
Convert to FeatureIDE Project freezes Eclipse

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#469]
#### Prerequisitives
* **Eclipse Version:**  `Neon.2`
* **FeatureIDE-Version:**  `3.2.0`
* **Operating system:** `Win 10`
* **Java runtime used to run eclipse:** `JDK 8`
* **FeatureIDE Composer:** `FeatureHouse`
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/92482c68917e5b592f22ea882b99fa951fce2e83

### Issue description
Converting a Java Project to a FeatureIDE project causes Eclipse to freeze after finishing the dialog with FeatureHouse as composer.
It works for Antenna though.

**Comment by Kogoro** [comment]
Joshua and I are testing it at the moment. Seems like a race condition when converting the project source files.
