### ISSUE TITLE
Cannot create Java Interfaces for FeatureHouse (FOP) with the new file wizard

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#472]
### Issue description
When using the new file wizard, we currently can only create Java classes but not Java Interfaces.

**Comment by Subaro** [comment]
As usually, the first one creates a class. The second one now creates an interface when the interface checkbox is set. Interface checkbox is only available for java languages. 

<img width="764" alt="unbenannt3" src="https://cloud.githubusercontent.com/assets/6231523/23470410/98f016d2-fea6-11e6-80d4-4ad76d78d28f.PNG">

**Comment by tthuem** [comment]
Nice!
