### ISSUE TITLE
AHEAD composer does not import correctly from other projects

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#474]
#### Prerequisitives
* **FeatureIDE Composer:** `AHEAD`
* **Git branch**  `develop`

### Issue description
AHEAD does not rename and delete the sources from pure Java projects correctly. After the conversion, the project has both .java and .jak files in the source folder.
Related to #469.

**Comment by tthuem** [comment]
That's true for every AHEAD project. Source folders contain temporary .jak files and then .java files. Only the feature folder should not contain any .java files.

Sure that there is something wrong?

**Comment by Subaro** [comment]
We were wrong and nothing is missing. Everything is right. The AHEAD composer works like @tthuem describes him.
