### ISSUE TITLE
Preprocessor content assist should insert features in the right place

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#475]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.3.0`
* **FeatureIDE Composer:** `Antenna`

### Issue description
When using content assits for preprocessors it is possible to introduce the proposed feature on wron places, e.g., before the `#if` to `FEATURE #if` ; or after `#if FEATURE` to `#if FEATURE FEATURE`.

Related to issue #464

**Comment by skrieter** [comment]
Implemented in [SP_MD_SoSe2018](https://github.com/FeatureIDE/FeatureIDE/tree/SP_MD_SoSe2018).
