### ISSUE TITLE
Content assist for annotations should be sensitive to the actual composer (e.g., Antenna or Munge)

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#476]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.2.0`
* **FeatureIDE Composer:** `All`

### Issue description
When using content assist in comments with `#if`, the features are proposed even if the composer is not Antenna.

![ppcontentassist](https://cloud.githubusercontent.com/assets/1482595/22560892/342b682c-e944-11e6-8f09-7810099f9444.PNG)

The content assist should be sensitive to the actual composer.
i.e., there should be a reference to the composer extension.

Related to #464 and #475

**Comment by skrieter** [comment]
Implemented in [SP_MD_SoSe2018](https://github.com/FeatureIDE/FeatureIDE/tree/SP_MD_SoSe2018).
