### ISSUE TITLE
Color bars shown in project explorer even if no color scheme is activated

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#477]
In addition, all color boxes are shown even if the respective color is not assigned. Both was fixed for preprocessor projects, but we need the same behavior for FOP projects. The following screenshot shows the bars in a FeatureHouse project.

![fop-projectexplorer](https://cloud.githubusercontent.com/assets/5330357/22593714/41ae8c4a-ea20-11e6-9912-8394f7125c81.PNG)

**Comment by tthuem** [comment]
Is it just because those changes from team project are not yet merged into develop?

**Comment by Subaro** [comment]
Yes it was but the configuration/color team project are now merged into develop.

**Comment by tthuem** [comment]
Color bars are shown now, but still not as intended. It is hard to recognize which color is missing in a certain package.

The idea was that all color bars have the same width, which is determined by the number of colors that are actually assigned to features. Then, each column stand for a single color (over all packages and classes), whereas only columns are hidden for which the color is not assigned to any feature.

![temp](https://cloud.githubusercontent.com/assets/5330357/23365621/f6938764-fd03-11e6-94c0-20c98ea01b92.PNG)

**Comment by Subaro** [comment]
Apparently, that behavior was implemented for each single package but not for all packages at all. Like you said every class inside a package has the same color width. Here is a screenshot from inside the package:

<img width="410" alt="sssss" src="https://cloud.githubusercontent.com/assets/6231523/23371498/912c5e36-fd18-11e6-8d3d-6817303b2729.png">

So the packages should behave the same?

**Comment by Subaro** [comment]
Now the packages also behave the same. For the project, every package and file now got the same width and you can now see easily if some feature is not inside a package.

<img width="422" alt="unbenannt3" src="https://cloud.githubusercontent.com/assets/6231523/23380803/80c8238a-fd3c-11e6-8f7f-42aa98ad5939.PNG">

**Comment by Subaro** [comment]
Commit should have been for #477 not #447. Sorry

**Comment by tthuem** [comment]
Does not work for me. Instead of omitting empty boxes, any box is omitted for generated source code:

![unbenannt](https://cloud.githubusercontent.com/assets/5330357/23600897/0fd5861a-0249-11e7-8ed6-85b5576f36b0.PNG)

**Comment by Subaro** [comment]
I think the color bars will only be drawn if there is no features folder. If that exists the package color bars are omitted. 

So even if there is a feature folder the packages should have also the color bars? I will see what I can do

**Comment by tthuem** [comment]
As you can see in my screenshot a week ago, it was working before your changes. For generated code, the packages and classes do also have those boxes. Why are they not there anymore?

**Comment by Subaro** [comment]
Now the generated files will show the color bars again :)
It is now possible to color the feature out of feature files and out of derived files.


![unbenannt](https://cloud.githubusercontent.com/assets/6231523/24363690/e0215600-1310-11e7-894b-792aaf876cc5.JPG)

**Comment by tthuem** [comment]
@Kogoro Can you please try to update the according screenshot in our manuscript? Please post it here, too.

**Comment by tthuem** [comment]
Seems to work now
