### ISSUE TITLE
Export menu for feature models not available for non-FeatureIDE projects

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#480]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.2.0`

### Issue description
The menu entry for feature models (right-click on a model.xml in the package explorer) is not available in non-FeatureIDE projects.
e.g., if I want to export the model as dimacs then its not possible.

**Comment by Kogoro** [comment]
Duplicate #563.
