### ISSUE TITLE
FeatureIDE Outline shows wrong content for FeatureHouse projects

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#481]
For the elevator product line, the outline shows wrong members. The inner classes UpComperator and DownComperator do not exist and the members do exist in another inner class RequestComperator:

![fop-tracing-outline-final](https://cloud.githubusercontent.com/assets/5330357/23366825/717f6390-fd08-11e6-99da-d531b38dce7e.png)

**Comment by Kogoro** [comment]
We should discuss if inner classes should be shown when they are defined in other features.
After the commit https://github.com/FeatureIDE/FeatureIDE/commit/639e9afab0ab0cd9f91e487d27f7268cfd2a9f6c the outline is now:
![unbenannt2](https://cloud.githubusercontent.com/assets/8019776/24175873/fff419e4-0e98-11e7-8caf-6ae34a367a62.PNG)
So it's visible that it's not defined in this file.

**Comment by tthuem** [comment]
Seems to be fine now. Thanks.
