### ISSUE TITLE
Required libraries for FeatureIDE library

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#483]
#### Prerequisitives
* **Eclipse Version:** Neon
* **FeatureIDE-Version:** 3.2.0, the library
* **Operating system:** Windows

### Issue description
When using the FeatureIDE library I got some exceptions at runtime.
I fixed by including the sat4j library and the org.antlr.runtime library version 3 (not 4).
This issue is just in case you consider adding them directly to the FeatureIDE library or document it for other users. Maybe I am missing more required libraries but with this I did not have exceptions at runtime for my task.

For example, with
`FeatureModel fm = new FeatureModel(DefaultFeatureModelFactory.ID);`
we have this exception
`java.lang.NoClassDefFoundError: org/sat4j/specs/TimeoutException
	at de.ovgu.featureide.fm.core.base.impl.FeatureModel.createAnalyser(FeatureModel.java:188)`

and with the format manager, there is this exception
`java.lang.NoClassDefFoundError: org/antlr/runtime/RecognitionException
	at de.ovgu.featureide.fm.core.base.impl.FMFormatManager.<init>(FMFormatManager.java:41)`

**Comment by tthuem** [comment]
Thanks for the hint. I added a link to possibly needed jars. Which jars are needed depends on the actual use case.

![unbenannt](https://cloud.githubusercontent.com/assets/5330357/24406051/43c18462-13c7-11e7-8af7-fc8c5b732d82.PNG)
