### ISSUE TITLE
New extension point for feature-model outline to avoid duplicated code

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#485]
Tried to build the new version for the update site, but it fails with the following error message:

![cycle](https://cloud.githubusercontent.com/assets/5330357/24548449/8cfbd81c-1615-11e7-8f0d-526a139a737f.PNG)

I already removed all unnecessary dependencies from all plug-ins. Furthermore, I checked for each plug-in, whether there are any cycles, but there are none. Any ideas how to fix that?

**Comment by tthuem** [comment]
In addition, I recomputed all dependencies of all features. Did not help with the above problem.

There will be no new version unless we find a solution.

Can someone please create the version on his machine?

**Comment by tthuem** [comment]
Could also be related to our problem with nightly builds.

**Comment by Subaro** [comment]
If you tell me how to build a version i could try it on my Laptop :)

**Comment by tthuem** [comment]
Checkout all plugins and all projects from deploy into your workspace. Open UpdateSite3/site.xml, add all 11 features to category 3.3, select them and press Build.

**Comment by skrieter** [comment]
fm.ui imports packages from core, hence the cycle

**Comment by Kogoro** [comment]
Looks like the cycle is created through the coloring action in the fm.ui outline. Removing the action should solve the issue.

**Comment by Subaro** [comment]
But the color action of the outline is also in the fm.ui package

**Comment by skrieter** [comment]
I managed to fix one of the two problematic classes (SetFeatureColorAction).

However, FmOutlinePageContextMenu needs more serve modifications.
The outline should use an extension point for additional content (such as the FST elements).
Maybe we should disable that functionality for this version?

**Comment by Kogoro** [comment]
Maybe duplicating FmOutlinePageContextMenu for the release would be better. So feature coloring works in the FeatureIDE outline. From the standard outline, we can then remove the FST elements.

**Comment by skrieter** [comment]
I implemented our suggestion.
For now, there are two context menu classes (one in ui and one in fm.ui).
I briefly tested it and it seems to work.
But I strongly recommend that someone else has a look as well.

@tthuem You should now be able to build the new version.
I'm not closing this issue as it was just a quick'n'dirty fix.
Like I said before, an extension point (or a similar solution) seems more appropriate.

**Comment by tthuem** [comment]
Nightly builds are working again, indeed caused the weird problem on Teamcity. :)

**Comment by Kogoro** [comment]
Also related to #430 and the outline_rework branch.

**Comment by tthuem** [comment]
Building the update site does also work now, just tested it.

**Comment by Kogoro** [comment]
Closing in favor of #430
