### ISSUE TITLE
Problem with orders in frameworks with plug-ins

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#486]
Although, FeatureIDE allows to configure an order for framework projects, it is simply ignored. In the end, we cannot even implement our hello world example properly (and students had the same issue in our SPL lecture):

![framework](https://cloud.githubusercontent.com/assets/5330357/24549462/a18ef8d2-1619-11e7-8331-6b7ad3a28389.PNG)

We either need to skip writing about framework support or need to somehow handle ordering. Isn't there an easy way to load plug-ins in the order as given by the feature model? Maybe by exporting the total order an then using it during plug-in loading?

**Comment by meinicke** [comment]
@tthuem That is the thing with frameworks, they are usually oblivious of each other, thus there is no useful order. See eclipse plugins.

**Comment by tthuem** [comment]
Fixed, except #494
