### ISSUE TITLE
There are several problems with our example projects

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#487]
1. Examples typically do not have the FeatureIDE header (but at least Elevator and HelloWorld projects should have it)
2. In HelloWorld projects the class should be called HelloWorld and not Main
3. Default configurations are not always valid (cf. beautiful vs Beautiful)
4. If Hello and World are optional, we need at least one further cross-tree constraint that all products are useful: Beautiful or Wonderful implies World
5. The message on System.err in framework is not confusing (use System.out or omit it)
6. The line breaks in HelloWorld examples are weird

![propertymanager-license](https://cloud.githubusercontent.com/assets/5330357/24549783/3c562092-161b-11e7-9018-bb61dfb63a03.PNG)

7. The TODO in HelloWorld-RuntimeProperties is simply wrong and should be removed

![properties](https://cloud.githubusercontent.com/assets/5330357/24549773/30f54a48-161b-11e7-8783-8a41f8985ef1.PNG)

**Comment by Subaro** [comment]
> 2. In HelloWorld projects, the class should be called HelloWorld and not Main

In the book, there is the following figure given.
![unbenannt](https://cloud.githubusercontent.com/assets/6231523/24587677/3073eb3c-17bb-11e7-808e-2d810ed5a737.JPG)

Should we now make a new picture where we renamed the Main.java to HelloWorld.java? Or will that issue at the time of the book's release not be implemented?

**Comment by tthuem** [comment]
Yes, that would be an improvement. Thanks!

**Comment by tthuem** [comment]
7. There is no AspectJ hello world example

8. Feature models and configuration files should be as consistent as possible (see Framework example as a reference)

**Comment by tthuem** [comment]
What is left to do after my revision:

1. Revise HelloWorldMPL-FH-Java

2. Revise HelloWorld-DeltaJ

3. All book examples should have the FeatureIDE header

**Comment by Kogoro** [comment]
Book Example "SPL_PP Sabbath and Service and FIFO":
Change config to Sabbath and Service -> `The import de.ovgu.featureide.examples.elevator.core.controller.Request cannot be resolved`

**Comment by Kogoro** [comment]
Also, the following examples are missing: 

- Elevator SPL_PP V5 (Finished version of the preprocessor version)
- Elevator SPL_FOP V5 (Finished version of the feature-oriented programming version)

(I will update this list if more examples are missing)

**Comment by tthuem** [comment]
Could you add here which Chapters are refering to those examples (maybe in brackets)?

**Comment by Kogoro** [comment]
Added the chapters

**Comment by Subaro** [comment]
> Revise HelloWorldMPL-FH-Java

WIP

> Revise HelloWorld-DeltaJ

WIP

>All book examples should have the FeatureIDE header

DONE
