### ISSUE TITLE
Configuration Editor initially opens source tab

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#496]
#### Prerequisitives
* **Eclipse Version:**  Neon.2
* **FeatureIDE-Version:** 3.2.0
* **Operating system:** Win 10
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/3864ea5a9ec1652f38fa8873184d3b064779db6a

### Issue description
Configuration Editor initially opens source tab instead of the first page.

**Comment by Kogoro** [comment]
See #492, it should be already fixed on the release branch.

**Comment by tthuem** [comment]
@meinicke Please reopen the other issue, if still occurs on release branch.
