### ISSUE TITLE
Missing package javax.xml.bind when starting second Eclipse

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#497]
#### Prerequisitives
* **Eclipse Version:**  4.6.3 Committers
* **Operating system:** Win 10

### Issue description
Since I downloaded and set-up Neon.3, I'm getting this error whenever starting the second Eclipse instance. Any ideas how to fix that? Am I just need to install any Eclipse plug-in?

![unbenannt](https://cloud.githubusercontent.com/assets/5330357/24697804/bc640b42-19ee-11e7-9165-cb636b739f87.PNG)

**Comment by tthuem** [comment]
That's a configuration problem of Neon.2 and Neon.3, which has nothing todo with FeatureIDE. We probably have to live with it. ;)

**Comment by Kogoro** [comment]
As further information, I have tested it also and it runs without any popup.
My version of the development instance:
```
Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500
```

**Comment by irinaMogi** [comment]
Hello,
It still exists in win 7 and 10:
Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500
And
Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600

**Comment by tthuem** [comment]
Thanks, but this is a general problem with Eclipse, not with FeatureIDE. We cannot fix it.

**Comment by irinaMogi** [comment]
Thanks for reply.

ср, 31 янв. 2018 г. в 15:55, Thomas Thüm <notifications@github.com>:
