### ISSUE TITLE
An empty configuration file is not marked as dirty even if core features are selected automatically

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#499]
Wanted to create a new configuration that only contains the core features. Saving the configuration was only possible after switching to the source tab.

![config](https://cloud.githubusercontent.com/assets/5330357/24700343/28f94922-19f7-11e7-9eeb-2d0962c48a12.PNG)

**Comment by Subaro** [comment]
@tthuem It is not happening when I try to reproduce the behavior. Which composer did you use? FeatureHouse?

**Comment by tthuem** [comment]
Yes, probably.
