### ISSUE TITLE
Double clicking the Mandatory/Optional circle does not changes its state when not at 100% zoom

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#507]
#### Prerequisitives
* **FeatureIDE-Version:** 3.3.0
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/f0b4387fbe23aef7aae28d0762035ba247827fbd

### Issue description
Double click on the Mandatory/Optional circle in the feature model changes the group type instead of the Mandatory/Optional state when not at 100% zoom.

1. Set the zoom to 110%.
2. Double click the circle.

This might be a bug in draw2D and its calculation of coordinates.

**Comment by tthuem** [comment]
Does double click work if at 100%? At least clicking on the feature is intended to _not_ change the mandatory/optional property.

**Comment by meinicke** [comment]
Yes, it works for 100%.
