### ISSUE TITLE
Memory leak in Configuration Map

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#508]
#### Prerequisitives
* **Eclipse Version:**  Neon.2
* **FeatureIDE-Version:**  3.3.0
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/f0b4387fbe23aef7aae28d0762035ba247827fbd

### Issue description
When opening the Configuration Map for GPL-FH-Java an "org.eclipse.swt.SWTError: No more handles" it thrown.
I guess the pictures are not cached.

This causes Eclipse to freeze.

**Comment by Subaro** [comment]
@meinicke I don´t get the error when opening the Configuration Map for the GPL_FH Java project. Not on release and not in the develop. Did you made anything before opening the configuration map that could trigger that behaviour?

**Comment by Subaro** [comment]
Okai when I refresh the view

**Comment by meinicke** [comment]
I guess that you create new Images at some point.
Just create them as static fieleds once.

instead of calling return FMUIPlugin.getImage(imgPath); every time just cache them. 
See ConfigurationMapLabelProvider.getColumnImage

The images might actually already exist somewhere.

We could also just rewrite the method FMUIPlugin.getImage to cache the images in a map.
