### ISSUE TITLE
Legend should be implemented in a non-static way

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#509]
With the current implementation of the legend, the legend will always be newly created.  Most of the old Legends won´t be removed at runtime. Over time that leads to a big amount of RAM that is blocked. Also, the only reference that the FeatureDiagramEditor has is a static one that leads to inconsistent behavior. 
Hiding the legend in instance A of a FeatureModelEditor will also hide the legend of instance B.

I think the legend should not be created every time and should be refreshed on change. That should happen in the EditPart via an Event. Then the movement of the legend could be handled with an event and the static reference could be removed.

**Comment by Kogoro** [comment]
I have tried the branch nonstatic_legend.
Overall it's a great refactoring, but when using hidden in the model the layout is still sometimes wrong.

### First
When hiding features, the layout is like this for both Top-Down layouts (ordered and centered)
![unbenannt](https://user-images.githubusercontent.com/8019776/27838422-d5d53572-60ea-11e7-9c42-61c9119127ab.PNG)
(Also the collapsed item in the legend figure is wrong)

### Second
When layouting with Top-Down (left-aligned) selected, the hidden features are not positioned again:
![unbenannt3](https://user-images.githubusercontent.com/8019776/27838518-8058fdf8-60eb-11e7-9e1a-59f9d3aef31f.PNG)

**Comment by Subaro** [comment]
Both issues above are not happening because of the new legend. Also, issues already exists for false layout of hidden features #546

**Comment by Subaro** [comment]
Is merged on develop
