### ISSUE TITLE
ConfigurationEditor possible configurations text

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#511]
#### Prerequisitives
* **Eclipse Version:**  `Neon.3`
* **FeatureIDE-Version:**  `3.3.0`

### Issue description
Text is not visible, but it should as there is space left.
![eclipse_2017-04-13_13-44-52](https://cloud.githubusercontent.com/assets/8019776/25003414/91ef3f96-204f-11e7-9bb8-b17aea4edb9a.png)

**Comment by Kogoro** [comment]
Changed to an always displayed info text and a minimizing search field.
Maybe we can shorten the text with icons for valid configurations and configuration numbers?

**Comment by tthuem** [comment]
Please add some screenshots how it looks now.

**Comment by Kogoro** [comment]
Here are some screenshots:
![unbenannt](https://cloud.githubusercontent.com/assets/8019776/26806310/74aeb8f0-4a50-11e7-949a-8107832adaff.PNG)
![unbenannt3](https://cloud.githubusercontent.com/assets/8019776/26806321/80aafdda-4a50-11e7-883f-249bc7447971.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/8019776/26806324/83c12346-4a50-11e7-8a48-48be356149c0.PNG)
