### ISSUE TITLE
The feature order button for default order does not work.

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#516]
#### Prerequisitives
* **FeatureIDE-Version:** 3.3.0
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/bfc7a5398255c402ac13e19b9ef1c07b244080ff

### Issue description
In the feature order tab in the feature model editor, pressing the button for default feature order does not do anything.

**Comment by Kogoro** [comment]
Works for me as intended with HelloWorld-FH-Java and GameOfLife-FH-Java models.

**Comment by tthuem** [comment]
@meinicke With which example did you face problems?

**Comment by meinicke** [comment]
Cannot reproduce it anymore

**Comment by skrieter** [comment]
Occurs for me.
E.g. for HelloWorld AHEAD and FH.
