### ISSUE TITLE
Confusing warning for book example without composer

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#519]
For the book, we included an example which is not a FeatureIDE project and therefore has no composer. However, the example wizard seems to assume that each project needs a composer. We either need to insert a dummy composer (e.g., No Composer) or need to rethink whether this warning is actually necessary.

![unbenannt](https://cloud.githubusercontent.com/assets/5330357/25233251/80860a66-25de-11e7-8a79-b75572d7b963.PNG)

**Comment by Kogoro** [comment]
I have modified the check for composers. When only the java nature is visible, we do not show any warnings about missing composers.
It may be good to add a hint that these projects are pure java projects, but we should discuss it as it may confuse more people.

**Comment by tthuem** [comment]
Think it is fine without a warning. Go ahead and merge it.
