### ISSUE TITLE
Incorrect export of feature diagrams to scalable vector graphics

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#520]
When exporting the feature model as scalable vector graphics (.svg) some names of the features won´t be recognized as a text. Affected are features that contain the underline character (_) between at least three big characters. 

Here is my testing picture.
![unbenannt](https://cloud.githubusercontent.com/assets/6231523/25252658/3b248174-261e-11e7-978e-f5e58a39690d.PNG)

If I will find more cases where that happen I will post them below.

**Comment by Subaro** [comment]
Most feature models of chapter 5 cannot be exported. Following happens:

![unbenannt](https://cloud.githubusercontent.com/assets/6231523/25253701/54e88c78-2622-11e7-922a-49b82315b6a0.PNG)

**Comment by Subaro** [comment]
Removed critical because it is possible to print the feature model as pdf. That works fine.

**Comment by tthuem** [comment]
I'm sceptical what we can do about it, as SVG export relies on an external library. In any case not critical to the hotfix release.

**Comment by Subaro** [comment]
It is also not possible to see any logical operator. Any logical operator in the constraints is replaced as ? after an export.

**Comment by tthuem** [comment]
Did you check whether the font used is installed on your machine? http://wwwiti.cs.uni-magdeburg.de/iti_db/research/featureide/#faq

**Comment by tthuem** [comment]
Seems to be an issue of Draw2D or SVG export.
