### ISSUE TITLE
Altering an imported example also alter the example template

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#521]
#### Prerequisitives
* **Eclipse Version:**  `Neon.3 (Java)`
* **FeatureIDE-Version:**  `3.3 (Nightly)`
* **Operating system:** `Windows 10`

### Issue description
Issue occur on the Java package of Neon.3. After installing FeatureIDE from update site and updating with the nightly builds. 

1. Import any project from the example wizard
2. Change by example any feature in the feature model editor
3. Save
4. Delete project from disk
5. Import the same project from step 1 again
6. Changes that were made in step 2 are now present

Deleting the project from disk removed the complete directory from my workspace. I tested that.

It´s not happening when starting FeatureIDE through Eclipse for RCP and RAP Developers.

**Comment by tthuem** [comment]
Do you have some sort of name clash? Is the workspace by any chance the same folder on your disk that is storing the examples anyway?

**Comment by Subaro** [comment]
@tthuem My workspace was named FeatureIDE. But I created a new workspace and tested again. There is still the same Issue.

The weird is that the altered example templates are restored on an eclipse restart.

**Comment by tthuem** [comment]
Really weird.

Sounds like the files are not actually copied but only linked into the workspace.

**Comment by meinicke** [comment]
It sound rather that the Feature Model is still inside FeatureIDE.

**Comment by Subaro** [comment]
@tthuem, @skrieter 
I just updated the plugins. I tested it and it was not working. Still the same.

**Comment by Subaro** [comment]
@tthuem , @skrieter 
Tested it now but it doesn't work. It is still happening like described in the issue description.

**Comment by tthuem** [comment]
Seems to work now
