### ISSUE TITLE
Function to add feature above is not working as intened

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#523]
#### Prerequisitives
* **Eclipse Version:**  `Neon.3`
* **FeatureIDE-Version:**  `3.3`
* **Operating system:** `Windows 10`

### Issue description
When adding a feature above, the created figure is not directly placed above the selected feature. Instead at the top left position. The renaming is also not available and the connection are wrong.

![unbenannt](https://cloud.githubusercontent.com/assets/6231523/25274291/a67386e8-268f-11e7-9c3c-bedf278c01e3.PNG)

**Comment by tthuem** [comment]
related to #427

**Comment by Kogoro** [comment]
Seems to be still present on the issue-427 branch, after another click the feature aligns correctly but the connection to the feature below is drawn above the feature and the legend is intercepting with the features.
![unbenannt](https://cloud.githubusercontent.com/assets/8019776/26287569/cd9e39c8-3e7e-11e7-96d3-14797e38fe3a.PNG)

**Comment by Subaro** [comment]
Closed with commit 88fa6d2
