### ISSUE TITLE
Cannot edit specific config elements

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#527]
#### Prerequisitives
* **Eclipse Version:**  `Neon.1`
* **FeatureIDE Composer:** `Antenna`
* **Git branch/Commit-ID:**  `develop`

### Issue description
I have opened Elevator-Antenna-v1.4 and colored some features (see screenshot). But I can't save any changes made to the sub-tree of Priorities.
It simply resets all selections. Can somebody else confirm this behavior?

![2017-04-24_14-05-02](https://cloud.githubusercontent.com/assets/8019776/25336678/e3889788-28f8-11e7-9ef1-6c98b5291891.png)

**Comment by tthuem** [comment]
Changes to colors are applied without saving. That's the same for all other editors. Does that explain the behavior to you? Does it work as intended?

**Comment by tthuem** [comment]
If not, does a refresh on the project exlorer help?

**Comment by Kogoro** [comment]
I have started the instance a second time. Still, I can't make any change in the tree of the configuration editor. Even if I don't color features. Looks like we reload the config file after a save, but the save never happens.

**Comment by tthuem** [comment]
Please clarify the following questions:

1. Can you edit and save configurations with the first tab of the configuration editor?
2. Can you edit and save configurations with the second tab of the configuration editor?
3. Can you edit and save configurations with the third tab of the configuration editor?

**Comment by Kogoro** [comment]
1. I can edit but the change is not saved
2. I can edit but the change is not saved
3. I can edit but the change is not saved
