### ISSUE TITLE
Feature Model Marker will not be updated when changing feature model

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#528]
#### Prerequisitives
* **Eclipse Version:**  `Neon.3 (Java)`
* **FeatureIDE-Version:**  `3.3 (Nightly Updates)`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `1.7`

### Issue description
After changing the feature model the current problem markers won´t be updated properly. 

We start with the feature Service to be abstract.

![bild](https://cloud.githubusercontent.com/assets/6231523/25381898/cabfe32e-29b5-11e7-8921-4104b0b743d4.PNG)

I changed Service to concrete and saved the model. Nothing happens the Marker didn´t go away.

![bild](https://cloud.githubusercontent.com/assets/6231523/25381964/0afdfdc2-29b6-11e7-8eb8-bfc2e127cf5a.PNG)

**Comment by tthuem** [comment]
@skrieter Is that related to your changes with respect to the loading of feature models? It worked in September at SPLC.

**Comment by Subaro** [comment]
When saving the java editor the feature module markers are updated, but in contrast, the builder problem marker like "missing semicolon" won´t.
