### ISSUE TITLE
Highlight Munge Source

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#529]
### Issue description
Munge source code should be highlighted in the project explorer.

![19-package-project-explorer](https://cloud.githubusercontent.com/assets/8019776/25401688/ad4fb30a-29f6-11e7-99aa-36f42833ecb9.png)

**Comment by tthuem** [comment]
Required for the screenshots or they need to be faked, if that is easier for now.

**Comment by Subaro** [comment]
@Kogoro Please also have a look at the branch issue-529. Should be working now.

Result:

<img width="411" alt="neue bitmap" src="https://cloud.githubusercontent.com/assets/6231523/26108160/f63191b4-3a4b-11e7-8fe7-fce342d47c01.png">

**Comment by tthuem** [comment]
nice! :)
