### ISSUE TITLE
When Saving at the Advanced Configuration Editor page, all the deselections get lost

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#532]
#### Prerequisitives
* **Eclipse Version:**  Neon.2
* **FeatureIDE-Version:**  3.3.0
* **Git branch/Commit-ID:** https://github.com/FeatureIDE/FeatureIDE/commit/d1692cbd3451a29b83964b403eba30750d0b610a

### Issue description
1. Deselect some features in the Advanced Configuration Editor page
2. Save the editor

If the deselections are not implied by some other selections they get lost because the whole configuration is loaded again.

**Comment by tthuem** [comment]
This is the normal behavior if you use the old configuration file format. Did you use the new one?

**Comment by meinicke** [comment]
No, I used the old format (i.e., the current default format).
Anyway, there is no reason that all my  changes get lost just because I save the editor.

**Comment by tthuem** [comment]
The reason is that deselections are not saved. Let's talk about this in our next meeting.

**Comment by skrieter** [comment]
Fixed.
