### ISSUE TITLE
Feature Model Outline view contains weird buttons

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#533]
The following buttons seem to make sense only for feature modules, but not for feature models. Depending on the context, only useful buttons should be shown.

Even the refresh button does not do anything, right?

![unbenannt](https://cloud.githubusercontent.com/assets/5330357/25540111/303d24e6-2c4a-11e7-9dd9-e79a904556be.PNG) ![unbenannt2](https://cloud.githubusercontent.com/assets/5330357/25540121/34276d46-2c4a-11e7-8675-67cae2accaea.PNG)
![unbenannt3](https://cloud.githubusercontent.com/assets/5330357/25540130/38270474-2c4a-11e7-9c8b-7c2e252dfe7f.PNG) ![unbenannt4](https://cloud.githubusercontent.com/assets/5330357/25540131/38400fbe-2c4a-11e7-8365-831031db76e8.PNG)
![unbenannt5](https://cloud.githubusercontent.com/assets/5330357/25540132/38431cea-2c4a-11e7-8d9a-8ccba1c8c185.PNG)

**Comment by Kogoro** [comment]
Maybe this should be a sub-task of the refactoring of the outline (#430) planned for the 3.4 release.

**Comment by tthuem** [comment]
Should be fixed with #430
