### ISSUE TITLE
No colors in project explorer for AHEAD projects

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#534]
![temp](https://cloud.githubusercontent.com/assets/5330357/25543457/e6fa3c26-2c56-11e7-9b39-acab3c4404e6.png)

At least feature models should be colored, as for FeatureC++ and FeatureHouse. Generated code could also work, as we have this data available in the FST. For FeatureC++, we also have an FST with that data for generated code.

**Comment by Subaro** [comment]
Result:

<img width="120" alt="unbenannt" src="https://user-images.githubusercontent.com/6231523/26943015-7591d55a-4c84-11e7-8c93-4136b7fa2fbf.PNG">
