### ISSUE TITLE
Legend size changes should triger layouting of legend

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#536]
Currently, the size of the legend changes dramatically if an explanation is shown. Then, the legend might overlay parts of the feature diagram and could profit from new layout (moving to another corner).

**Comment by Subaro** [comment]
Is fixed within the new nonstatic_legend branch. The branch is already in develop. When the Legend was moved manually to left of any feature or constraint and then an explanation is activated the legends is layouted only when the legend would intersect with any other element.
