### ISSUE TITLE
Feature model changed even if feature model editor was not saved

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#537]
#### Prerequisitives
* **Eclipse Version:**  Neon.2
* **FeatureIDE-Version:**  3.3.1
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/794be97cf9b5f573f1b6ba6dcbaac63c9e05a21e

### Issue description

After changing the feature model, and closing but not saving the feature model editor, the feature model changes are still present.

reproduce as follows:
1. change the model, e.g. remove a feature
2. close the editor without saving
3. open the editor

It seems that the internal feature model is somehow inconsistent

**Comment by tthuem** [comment]
Sounds indeed very critical.

Who can work on this?

**Comment by tthuem** [comment]
Happened to me again on current release branch.

**Comment by tthuem** [comment]
Seems to happen when switching between diagram and source while editing the model.

**Comment by tthuem** [comment]
@skrieter Any news on that? That seems to be the only issue critical to the upcoming release.

**Comment by tthuem** [comment]
Still needs to be merged into develop.
