### ISSUE TITLE
Avoiding computations when editing large feature models

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#542]
#### Prerequisitives
* **Eclipse Version:** Neon.2
* **FeatureIDE-Version:**  3.3.1

### Issue description
When editing large feature models, like Automotive, the edits where instant, especially if the model does not need to be layouted (e.g., change the group type, or change from mandatory to optional). 

The commit https://github.com/FeatureIDE/FeatureIDE/commit/000f7ad2d7b440df82966e755f2781fa5c174b07 adds a layout call to all operations (see FeatureDiagramEditor.propertyChange() ).

When removing the call it is still slow and freezes a bit.

**Comment by tthuem** [comment]
I'm not quite sure I can follow, but a freeze sounds like something we should fix within the hotfix release.

**Comment by meinicke** [comment]
An operation that was instant before takes now a minute or more, e.g., changing mandatory to optional in large feature models.
This just needs to refresh the decoration, but does to many unnecessary things (e.g., layout).

**Comment by tthuem** [comment]
Sounds like it would help if you collapse features, and there are further operations which actually require layouting. Hence, I agree that it is sufficient to consider performance for the next release.

**Comment by Subaro** [comment]
After the layout call was removed the mandatory change or group type change is instant again.

**Comment by tthuem** [comment]
Great!
