### ISSUE TITLE
Hidden property and constraints removed when saving feature diagram (sporadically)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#545]
The only difference of a hidden and a non-hidden feature is that only non-hidden features can/need to be configured by the user. Besides that, the attribute hidden has no further use case.

However, in the current simple and advanced configuration editor these hidden features are shown. Hence, all computations with respect to indeterminate hidden features are useless and hidden features cannot be used.

**Comment by tthuem** [comment]
Seems that the problem was that the hidden property was not stored correctly. Found out after closing and opening the feature diagram.

**Comment by tthuem** [comment]
Also found out that the editor removed all my cross-tree constraints with hidden features.

**Comment by Kogoro** [comment]
I tried to reproduce the issue on the develop branch with adding 3 new features to a feature modeling project, marking 2 features hidden and creating two constraints as pictured below, but it does work correctly for me. Also, further random changes do not lead to a wrong state.
![unbenannt](https://cloud.githubusercontent.com/assets/8019776/26288190/dd4127f6-3e8c-11e7-88ea-6d8575b896c0.PNG)

Do you have a minimal example as this is sporadic?

**Comment by tthuem** [comment]
Indeed, it is sporadic. Tried it several times to reproduce it myself, without luck. Nevertheless, does not mean there is no bug. ;)
