### ISSUE TITLE
Feature declared as false-optional which is not optional

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#547]
For some reason the group type can be other than AND if there is only one child. This used to be forbidden as it involves numerous problems. One is that we cannot distinguish alternative from or groups if there is no arc at all.

While this seems to be possible in the current version, it gets even worse: a feature that is not optional (according to the graphical representation of the feature diagram) is declared as false-optional, which does not make sense at all. Even if it would be an optional feature in this example, there is no constraint which could make it into an false-optional feature.

To make long story short, it seems the actual reason is that the same feature is treated as optional in some parts of the code and non-optional in other parts. This needs to be consistent.

![falseoptional](https://cloud.githubusercontent.com/assets/5330357/26219355/f6802eae-3c0e-11e7-928c-1bfc80557f43.PNG)

**Comment by Subaro** [comment]
@tthuem I think you changed the group type of EVEFI to OR. The child feature Method Treatment can be optional, but because there is only one child it is declared as false-optional. When only one child is present the group type won´t be displayed in the legend or in the diagram. That is the cause you are confused. It is a changed group type but it is not diplayed

**Comment by tthuem** [comment]
1. The set of false-optional features must be a subset of optional features, whereas features in alternative and or groups are not considered optional.

2. The group type should always be AND, if there is only one child. A while ago, we had the rule that this is simply display and written into XML that way. It would have the advantage that the group type does not change when removing and adding a feature in an or/alternative group with two children.

**Comment by Subaro** [comment]
Now the group type can only be changed when the feature has more than one child.

**Comment by Subaro** [comment]
@tthuem In the feature model analysis even feature from group type or and alternative are added to a possibleFO(false optional) list. I changed the condition so that only non-mandatory feature which has ta parent with group type AND are added to the list.

**Comment by tthuem** [comment]
As discussed in our meeting:

1. We agreed that false-optional features should also be highlighted for features in alternative and or groups (against what I've written above).

2. Whenever a group happens to have only one child, the group type will automatically be changed to AND.
