### ISSUE TITLE
Children of alternative and or-groups are mandatory with our XML format writer

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#550]
Matthias Tichy just reported that features grouped in or-groups or alternative-groups are marked as mandatory, which is quite confusing:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
	<featureModel>
		<properties/>
		<struct>
			<and abstract="true" mandatory="true" name="HelloWorld">
				<feature mandatory="true" name="Hello"/>
				<alt abstract="true" name="Feature">
					<feature mandatory="true" name="Wonderful"/>
					<feature mandatory="true" name="Beautiful"/>
				</alt>
				<feature name="World"/>
			</and>
		</struct>
```

1. Check that the writer for feature models does only output the mandatory/optional relationship if the feature is within an and-group.
2. Write a unit test to check that this does not happen anymore.
3. Load and store all our example feature models and compare the diff to make sure that exactly those relationships are omitted.

**Comment by Subaro** [comment]
1. done 
2. done
3. WIP
