### ISSUE TITLE
Color bars cover "changed"-marker from EGit.

### ISSUE THREAD

**Issue by skrieter** [FeatureIDE/FeatureIDE#551]
#### Prerequisitives
* **Eclipse Version:**  Neon.2
* **FeatureIDE-Version:**  3.3.1
* **Operating system:** Windows
* **Java runtime used to run eclipse:** 1.8
* **FeatureIDE Composer:** -
* **Git branch/Commit-ID:**  develop
* **Java compiler used to build the FeatureIDE plugin:** -

### Issue description
![issue](https://cloud.githubusercontent.com/assets/5803674/26361874/924eba32-3fdc-11e7-9279-2f054696f10b.png)

In both marked color bars, you can see the ">" symbol, which EGit uses to indicate a changed file.
The spaces for the color bars should be printed before the ">".

**Comment by tthuem** [comment]
Rather looks like a problem that should be fixed within EGit. I don't think it can be fixed in FeatureIDE's code.
