### ISSUE TITLE
Positioning of new constraints in manual layout

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#555]
#### Prerequisitives
* **Eclipse Version:**  `Neon.3`
* **FeatureIDE-Version:**  `3.3.1`
* **Git branch/Commit-ID:**  `develop`

### Issue description
Constraints are created in the upper left corner and can't be moved when using manual layout. Also, the legend should not move by itself.
![unbenannt](https://cloud.githubusercontent.com/assets/8019776/26548001/1a398500-4472-11e7-808a-cb4bac01715d.PNG)

**Comment by tthuem** [comment]
The legend has an own option for automatic layouting independent of the manual layout. Did you experience any problems with that?

If not, we probably need to think of something smarter than putting all new constraints in the left top corner. But this sounds as an enhancement suitable for a team project.

**Comment by Kogoro** [comment]
The legend shouldn't move in my opinion as well as all other features because when I manually move the legend I want it to stay there.
The constraints, on the other hand, should be movable to any location. To move new constraints to the upper left is not a problem for me.

**Comment by tthuem** [comment]
Let's discuss this issue tomorrow.

**Comment by Subaro** [comment]
Constraints in manual layout can now be moved freely. Was implemented in commit 2d8b82e8f602a8c4ae6caca921d9c87813d01f4a
