### ISSUE TITLE
An explanation is not removed correctly after using collapse operation.

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#572]
#### Prerequisitives
* **Eclipse Version:**  `Eclipse Neon`
* **FeatureIDE-Version:**  `develop`
* **Operating system:** `Win 10`

### Issue description
An explanation is not removed when doing following steps:

1. Load Example: BerkeleyDB-FH-Java
2. Open the model.xml
3. Change group type of feature "generatedSPL" to 'Alternative'
4. Click on the feature "DERIVATIVES" to show an explanation
5. Collapse "DERIVATIVES" now the explanation is not removed and still remains

**Comment by TimoGuenther** [comment]
Fixed as of https://github.com/FeatureIDE/FeatureIDE/commit/cf794d2d9657ecf08cab5af0a6a429c30fe32fdb.
