### ISSUE TITLE
Feature modeling plug-ins reference FeatureIDE's functionality

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#582]
The commit 80510ed371ead77e3c0ba8bf5e12fff16587a589 introduced imports that are not allowed. See detailed comments on this commit. Nightly builds do not work for that reason and we cannot build a new version before this is fixed.

**Comment by Kogoro** [comment]
Seems like some old refactoring artefacts. The filters should be in UI, that's right. Also I think the fst model is not used anywhere and can be easily removed. I will commit a patch as soon as possible.

**Comment by Kogoro** [comment]
Seems still to be broken. Can someone provide the Teamcity error?

**Comment by Kogoro** [comment]
Update: With my local repository, I can build all features without problems.

**Comment by tthuem** [comment]
```
31. ERROR in /home/itidbrun/TeamCity/buildAgent/work/featureide/artifacts/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/views/outline/custom/providers/FMTreeContentProvider.java (at line 50)
[04:00:51][java]     [javac] 	public class FMTreeContentProvider extends OutlineTreeContentProvider {
[04:00:51][java]     [javac] 	             ^^^^^^^^^^^^^^^^^^^^^
[04:00:51][java]     [javac] The type FMTreeContentProvider must implement the inherited abstract method IContentProvider.dispose()
```

**Comment by tthuem** [comment]
@Kogoro Can you also build fm.core and fm.ui separately (that was the problem before)? But now, there seems to be a new problem which is most likely an issue of compatibility to older Eclipse versions.

**Comment by Kogoro** [comment]
With oxygen and the actual develop, I can build de.ovgu.featureide.featuremodeling without any issues. So it can be an eclipse version issue.

**Comment by tthuem** [comment]
Please try to compile FeatureIDE with Eclipse 3.7 on your machine. The error message above did not help?

It would be good if we could create the new version of FeatureIDE tomorrow or Wednesday.

@Kogoro do you need help by @Subaro?

**Comment by Kogoro** [comment]
Okay, I will test it with Eclipse 3.7. It is worth to note that it is the 2011 version of eclipse. 
I will give an update how it goes.

**Comment by Kogoro** [comment]
Update 1:
I don't have a required JRE with support from 1.4 .-1.7 which has already arrived eol for support which makes finding executables very difficult. Maybe the better way could be to go one step up to Juno from 2012.

**Comment by Kogoro** [comment]
Seems that the Eclipse outline page needed the dispose method implemented and so the error occurs.

**Comment by tthuem** [comment]
Build and tests pass now! The build server seems to have only a problem in publishing the update site. So I guess we can close this issue.
