### ISSUE TITLE
Recompute dependencies of features

### ISSUE THREAD

**Issue by FeatureIDE** [FeatureIDE/FeatureIDE#584]
With the current build, Feature Modeling depends on FeatureIDE.

**Comment by Subaro** [comment]
<img width="296" alt="unbenannt" src="https://user-images.githubusercontent.com/6231523/31179823-48893dfa-a91d-11e7-9939-76e091e3360b.PNG">

**Comment by tthuem** [comment]
Initial issue is fixed by https://github.com/FeatureIDE/FeatureIDE/commit/f979333386e8ec99670b4876dc73bdd985dcd4a6

However, the cycle dependency between plug-ins is still there.

**Comment by Subaro** [comment]
Build all plugins without problems so like discussed I´m closing the issue now.
