### ISSUE TITLE
Antenna color bar shows not all colors in Project Explorer

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#593]
Elevator example 1.4 shows not all colors in src folder, but has large whitespaces.

![pe](https://user-images.githubusercontent.com/8019776/35297291-d83ea88c-007e-11e8-8568-c78f14e4627a.PNG)

**Comment by Subaro** [comment]
I changed it now. For every preprocessor composer, all the colors are shown, including antenna.

**Comment by tthuem** [comment]
"All colors" was probably misleading. Only assigned colors should be shown. That was on purpose.

@Subaro Please add a screenshot.

@Kogoro Please give an example which colors where missing before.

**Comment by Kogoro** [comment]
Example made with 3.4.2 added. First I checked out 3.3 which was correct so I checked out 3.4.2. Seems to be introduced between 3.3 and 3.4.2.

**Comment by tthuem** [comment]
Screenshots above looks fine (although it is confusing that it is added next to the initial bug report, while not showing the bug).
