### ISSUE TITLE
Invalid names for FeatureHouse and Antenna projects not checked

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#594]
I've seen many weird errors from Antenna not preprocessing a file over arbitrary exceptions in the error log.

**Comment by tthuem** [comment]
Please check whether spaces can be used with any other composer. Also, it would be good to have GUI tests for this functionality checking allowed and disallowed renamings for all composers. It is probably possible to create such a test for one composer and then copy and adapt it to other composers by basically changing the project on which the feature model is opened.

**Comment by Kogoro** [comment]
The following composers do not have a FMComposer extension:
- [ ] AHEAD
- [ ] FeatureCpp
- [ ] Images

The following pattern are applied to the following composers:
- Antenna: `^[a-zA-Z][\\w\\.\\-]*$`
- AspectJ: `^[a-zA-Z]\\w*$`
- FeatureHouse: `^[a-zA-Z][\\w\\.\\-]*$` -> Change to isValidJavaIdentifier
- Framework: FM constraints
- Munge: `^[a-zA-Z]\\w*$`
- Munge Android: FM constraints (complete empty file) -> Remove?
- Runtime: FM constraints

**Comment by tthuem** [comment]
Munge Android = Munge (try to use the same class)
AHEAD = FeatureHouse = AspectJ = Framework = Runtime = isValidJavaIdentifier
FeatureCpp = valid C identifier (or something simpler and more restrictive)
Images ??? @jabiercoding What restrictions do you have on names for features?

**Comment by jabiercoding** [comment]
I would say that Images composer has no restrictions on feature names

**Comment by tthuem** [comment]
@jabiercoding Thanks for the fast response. :)
