### ISSUE TITLE
Multi-composition: how can we combine several composers

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#6]
What if we have a project which is composed with FeatureHouse and we want to extend it by an AspectJ file?

What if want to write a delta-oriented extension to a feature-oriented program?

Think of other combinations and how the multi-composition process can be realized in FeatureIDE.

See HelloWorld?-FH-AspectJ for a simple example.

**Comment by tthuem** [comment]
Still interesting, but unlikely to produce any useful insights, whereas a large engineering effort is involved.
