### ISSUE TITLE
German translation of legend is incomplete

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#600]
![screenshot from 2017-09-25 14-21-14](https://user-images.githubusercontent.com/32126695/30808088-e8c6aad2-a1fc-11e7-9b60-35c4a8b7bcff.png)

**Comment by TimoGuenther** [comment]
Fixed as of https://github.com/FeatureIDE/FeatureIDE/commit/891fc38b61306f0f254bf3645010df8b8de48e36.
