### ISSUE TITLE
Legend should avoid mentioning abstract/concrete if all features have that property

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#603]
If a diagram contains only abstract or only concrete features, the legend is supposed to display "Feature" rather than "Concrete Feature" or "Abstract Feature". This is necessary for many applications (e.g., in publications) where the distinction between abstract and concrete is not needed.

This worked before, but seems to be messed up in cycles of years. Maybe the change to the code should incorporate the above comment.

**Comment by tthuem** [comment]
Similarly, the legend should not contain entries for collapsed features:

![legend](https://user-images.githubusercontent.com/5330357/31310007-7d1e8316-ab90-11e7-977e-764afb27a67b.png)

**Comment by tthuem** [comment]
Additionally, all words should be capitalized.

**Comment by PaulWestphal** [comment]
This is implemented as of 3edc9532878e7b281c1a328923c86f0d5dcdcaf7, except for

>Similarly, the legend should not contain entries for collapsed features:

Which is issue #784
