### ISSUE TITLE
When renaming a feature its connections are not always moved accordingly

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#604]
Experienced with alternative group in manual layout. Only connection to first child is updated.

**Comment by Kogoro** [comment]
In version 3.2 (on issue_461 branch) this also happens and can lead to this:
![fm](https://user-images.githubusercontent.com/8019776/37676368-0ac411f0-2c78-11e8-99dc-7faf82b207ee.png)

**Comment by PaulWestphal** [comment]
This works, but I'm not sure why it doesn't fix #612 as well.

**Comment by Kogoro** [comment]
#612 will now correctly updated the connections as well.
