### ISSUE TITLE
Make users aware that not all properties can be stored in all formats

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#616]
#### Prerequisitives
* **Git branch/Commit-ID:**  `develop`

### Issue description
GUIDSL and probably all other formats other than the internal XML are not saving analysis settings. 
Therefore the analysis cannot be disabled for them. If they can support the functionalities, the settings should be saved.
Attributes and other functionalities should also be considered.

Example: PROFilE examples on branch `profile_examples`

**Comment by tthuem** [comment]
We are not going to change other formats (except for Velvet). However, it seems that the GUI should only make available what can be configured (which is likely to get overly complex) or there should be a warning what cannot be stored persistently.

**Comment by tthuem** [comment]
Please convert the PROFilE example before adding it.

**Comment by tthuem** [comment]
Examples seem to be in our format now.

Any kind of handling to let users know what can be stored and what not would be nice. Maybe if the users is about to change something that is not supported in the format. But this would require very fine-grained levels of support in extension points and thus heavy changes.

**Comment by tthuem** [comment]
Duplication to #843
