### ISSUE TITLE
Check for signatures of methods

### ISSUE THREAD

**Issue by christophlsa** [FeatureIDE/FeatureIDE#62]
Enhancement:
1. If signature of one method is changed (e.g. new parameter, return value changed, method name changed, ...) the "overwritten" methods of the other roles should be checked (set marker) or also changed.
2. Check if all (overwritten) methods of the same class have the same signature.

It is very hard to identify the source of the error if the signatures of the methods are not equal.

**Comment by tthuem** [comment]
Interesting idea, but probably too much effort for this rather specific use case.
