### ISSUE TITLE
Since 7 years numerous tests compare identical feature models 

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#620]
For example:

https://github.com/FeatureIDE/FeatureIDE/blob/718a56db28b87283bc3a1a99d50bb56d70ed8a47/tests/de.ovgu.featureide.fm.core-test/src/de/ovgu/featureide/fm/core/io/TAbstractFeatureModelReaderWriter.java#L231-L250

[Edit Christopher:]
Tasks to do:

- [x] Check each test regarding feature models used.
- [x] When a feature model cannot be parsed the test should fail.
- [ ] Check if a comparison of the constraint id is currently enough. When it's not, improve constraint comparison and adapt tests.

**Comment by tthuem** [comment]
Also it seems that many of those tests in that class do not fail if the feature model cannot even be parsed in the first place. If our test models cannot be loaded, tests should fail.

**Comment by tthuem** [comment]
Furthermore, constraints are currently only compared by their ID, which does not seem to work well with the above test code. However, I'm not sure whether we should implement another equals-Method for Constraints or whether the test code needs to be updated.

**Comment by Subaro** [comment]
| Valid | Testclass | Add. Information |
| ------------- | ------------- | ---------  |
|  | **fm.core** | |
| √  | BFeatureModelAnalyzer  | |
| √ | ConstraintToStringTest  | |
| √ | TFeatureModel | |
| √ | TFeatureModelAnalyzer  | |
|  | **fm.core.base** | |
| √ | CustomFeaturesCustomPropertiesTest | |
| √ | CustomPropertiesTest | |
| √ | FalseOptionalAndOrAlternativeAnalyserTest | |
| √ | TFeatureUtils | |
|  | **fm.core.configuration** | |
| √ | TConfigurationReader| |
| √ | TConfigurationSelection| |
| √ | THiddenFeaturesConfiguration | |
| √ | TNumberOfConfigurations | |
|  | **fm.core.conversion** | |
| √ | TComplexConstraintConverter | |
|  | **fm.core.editing** | |
| √ | TModelComparator | |
|  | **fm.core.experimental** | |
| √ | BFeatureModelAnalyzerWithRuntimeConstraints | |
|  | **fm.core.explanations.fm** | |
| √ | DeadFeatureExplanationCreatorTests | |
| √ | FalseOptionalFeatureExplanationCreatorTests | |
| √ | RedundantConstraintExplanationCreatorTests | |
|  | **fm.core.io** | |
| INVALID | TAbstractFeatureModelReaderWriter | 3 Invalid Tests |
|  | **fm.core.io.guidsl** | |
| √ | TGuidslReader | |
| INVALID | TGuidslReaderWriter | Description not copied |
|  | **fm.core.io.sxfm** | |
| INVALID | Experiment_ConvertSPLOTmodels| Not active //@Test |
| √ | TSXFMReaderWriter | empty test cases |
|  | **fm.core.io.xml** | |
| √ | TXmlReaderWriter | |
| √ | XMLMandatoryOmitTest | |
|  | **runtimetest** | |
| √ | RuntimeTest| |
|  | **prop4j** | |
| √ | NodeWriterTests | |
| √ | Prop4JTest | |
|  | **prop4j.explain.solvers** | |
| √ | MusExtractorTests | |
| √ | MutableSatSolverTests | |
| √ | SatSolverTests | |
|  | **prop4j.explain.solvers.impl.sat4j** | 
| √ | Sat4jMusExtractorTests | |
| √ | Sat4jMutableSatSolverTests | |
| √ | Sat4jSatSolverTests | |
|  | **prop4j.transform** | |
| √ | DimacsReaderTests | |
| √ | DimacsWriterTests | |

**Comment by Subaro** [comment]
@tthuem The current build fails because of the SXFMReaderWriter and GUIDSL GuidslReaderWriter.

**Comment by tthuem** [comment]
Is everything done already?

I remember that we talked about checking equality of models, which, however, rather sounds like a new issue.

**Comment by Subaro** [comment]
For the new tests regarding the comparison of the constraint, a new issue was opened.

**Comment by tthuem** [comment]
see #718
