### ISSUE TITLE
If a configuration is changed outside of Eclipse it cannot be opened with our editor

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#626]
It seems that we need to apply a refresh before checking the format (i.e., if the context menu is build). Same could also happen for feature models (not tried). Also, it would probably be good to refresh files anyway before opening them in our editors.

**Comment by skrieter** [comment]
This is a general problem for Eclipse. If a resource is out of sync with the workspace our editors or content type descriptors are not even called. Thus, we cannot refresh the resource from within FeatureIDE.

[Here](https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-52.htm) is a possible solution for users that experience this problem.
