### ISSUE TITLE
Markers for invalid configurations are not created when feature model changes

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#627]

**Comment by PaulWestphal** [comment]
I need some more pointers to solve this. Where in the code are the markers for invalid configuration created right now?

**Comment by tthuem** [comment]
It used to be implemented here: https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.core/src/de/ovgu/featureide/core/internal/FeatureProject.java

@skrieter Was this functionality moved to the feature model analyzer?

**Comment by Kogoro** [comment]
These lines should be responsible for this:
https://github.com/FeatureIDE/FeatureIDE/blob/323c1b2d9df1bfaa0573735736e0c8c33398f3fd/plugins/de.ovgu.featureide.core/src/de/ovgu/featureide/core/internal/FeatureProject.java#L1060-L1110

**Comment by tthuem** [comment]
@PaulWestphal Any news on that issue?

**Comment by PaulWestphal** [comment]
I get weird conflicts in FocusOnExplanationAction.java and FeatureDiagramEditor.java unrelated to my commit when trying to merge this into develop.

**Comment by tthuem** [comment]
@Subaro @Kogoro Can someone review the changes and test it in both branches?

**Comment by Kogoro** [comment]
Markers are created, but I think these are wrong. With the antenna elevator v1.4, I get these markers for the feature model without changing the configurations (only changed the alternatives to and`s) and also the configuration also says they are valid. The last error marker is also confusing.
![fm](https://user-images.githubusercontent.com/8019776/34204199-1a015f06-e57e-11e7-845b-48ceb34d0c8d.PNG)
![config](https://user-images.githubusercontent.com/8019776/34204203-1b558b5c-e57e-11e7-8228-422cb218bb81.PNG)

**Comment by Kogoro** [comment]
On release, there is also one error marker for Ultimate configuration but it can be traced back to the configuration propagator(Returns false). Maybe @skrieter can have a look at this.
Steps to reproduce:
Load antenna elevator example v1.4 and set a breakpoint at ConfigurationPropagator$IsValidMethod [line: 104] - execute(IMonitor). When checking the ultimate configuration the propagator returns false, but the configuration editor says it is valid.
