### ISSUE TITLE
Top Down (Centered) Layout ignores all features.

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#633]
#### Prerequisitives
* **Eclipse Version:**  `Eclipse Oxygen 4.7`
* **FeatureIDE-Version:**  `develop (`abe44b99fd6b288ab6746bc57ab9edc68e8cfda0`)`
* **Operating system:** `Win 10`
* **Java runtime used to run eclipse:** `Java 1.7`

### Issue description
No features are layout when setting the layout to Top Down (Centered)

**Comment by Subaro** [comment]
The current problem does not exist anymore on the develop. @Kogoro Could you also test it.

**Comment by Kogoro** [comment]
Seems also good to me.
