### ISSUE TITLE
Integrate further support for contracts into FeatureIDE

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#64]
Project includes:
-Automated Analysis:
   -Metaproduct analysis
   -RAC
   -Testing
   -Analysis of all products
   -Mutation-"testing"
   -Arbitrary analysis

**Comment by tthuem** [comment]
@meinicke What is left open to be done?

**Comment by tthuem** [comment]
@meinicke This issue is too imprecise and the experimental development seems to be stale. Please provide more concrete proposals if you still think it is important.
