### ISSUE TITLE
Create Signature doesn't generate a document.

### ISSUE THREAD

**Issue by Adarsh-g-s** [FeatureIDE/FeatureIDE#642]
Prerequisites

Eclipse Version: Eclipse Neon
FeatureIDE-Version: develop
Operating system: Win 10
Java runtime used to run eclipse: Java 1.8
Issue Description

Run Munge composer
Choose corresponding FeatureIDE Example
FeatureIDE ->Munge -> Create Signature
No document gets generated

**Comment by skrieter** [comment]
Works as intended, but the name might be confusing.
The command enables the creation of the intenral signature structure, which is used for the extended outline.

I renamed the command in d6b4fa3646a243b1b9609b743dd92074ea6c6ac4.
