### ISSUE TITLE
Revise and merge development by Team 1 on feature-diagram actions

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#648]
![img_20171016_154919](https://user-images.githubusercontent.com/5330357/31618728-0c8f4054-b293-11e7-9840-7febffd95b0d.jpg)

![img_20171016_154936](https://user-images.githubusercontent.com/5330357/31618637-c53a1b34-b292-11e7-8923-8e149325c375.jpg)

**Comment by tthuem** [comment]
What is not yet implemented?

- Implement a new extension point to let other plug-ins add their actions and use it for the Feature Relations Graph
- Provide new implementation for the removal of features that uses feature-model slicing

What is merged into main fork?

- [ ] Store and load descriptions for cross-tree constraints in XML
- [ ] Show descriptions in tool tip and extend constraint dialog to edit descriptions
- [ ] Restructure actions in feature diagram for better usability
- [ ] Make actions available to multiple selections of features and constraints
- [ ] Make feature model wizard accessible if only feature modeling is installed
- [ ] Make configuration wizard accessible if only feature modeling is installed
- [ ] GUI tests for feature diagram editor
- [ ] Extension point for configuration wizard

What is ready for merge?

- [ ] Store and load descriptions for cross-tree constraints in XML
- [ ] Show descriptions in tool tip and extend constraint dialog to edit descriptions
- [ ] Restructure actions in feature diagram for better usability
- [ ] Make actions available to multiple selections of features and constraints
- [ ] Make feature model wizard accessible if only feature modeling is installed
- [ ] Make configuration wizard accessible if only feature modeling is installed
- [ ] GUI tests for feature diagram editor
- [ ] Extension point for configuration wizard

**Comment by tthuem** [comment]
For the record, everything was implemtend in the following fork originally: https://github.com/DawidSA2017/FeatureIDE

**Comment by Subaro** [comment]
The branch is now merged into develop

**Comment by tthuem** [comment]
@Subaro Did you also merge the Wiki and adapted all absolute paths in links?

**Comment by Subaro** [comment]
@tthuem I did merge the wiki. GitHub automatically adapted all paths.

**Comment by tthuem** [comment]
GUI tests fail as several actions are not available when multiple features are selected. It works for some selections, but not all. The GUI tests give numerous examples (e.g., DeleteIncludingSubfeaturesInFeatureDiagram).

**Comment by tthuem** [comment]
Seems to work now.
