### ISSUE TITLE
Revise and merge development by Team 3 on feature attributes

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#650]
![img_20171016_165001](https://user-images.githubusercontent.com/5330357/31618847-5a7bcdd2-b293-11e7-93ec-71c4c1d9b06f.jpg)

![img_20171016_165137](https://user-images.githubusercontent.com/5330357/31618852-5da9644c-b293-11e7-8dbc-4640280c294a.jpg)

**Comment by tthuem** [comment]
- Store and load attributes in XML format for feature models, whereas attributes have
   * name
   * type (i.e., Long, Double, String, Boolean, Enum)
   * unit (e.g., EUR or kg)
   * can be recursive (apply to all subfeatures) or not
   * can be configurable (changes allowed during configuration) or not
   * have a value (even if recursively defined for an ancestor)
- Create an action and a dialog with a Table Tree View to show and edit attributes
- Enable filtering for rows based on keywords (e.g., feature names, attribute names, values) that are automatically filled based on the selected feature
-  Create an outline view for configurations showing statistics, such as number of manually/automatically (de)selected and undecided features and a list of those features sorted by name providing navigation to features in editor
- Compute aggregated values for numerical and boolean attributes shared by at least two features
- Compute possible ranges for those attributes for the current partial configuration and without any decisions at all

**Comment by tthuem** [comment]
For the record, everything was implemtend in the following fork originally: https://github.com/madateamprojekt/Team317

**Comment by tthuem** [comment]
First part of this functionality will be released in v3.5.0 and the remaining parts in upcomming releases.

The following fork was used for prototypical development: https://github.com/Subaro/BachelorThesis_Sprey_Sundermann

**Comment by LeDominik** [comment]
@tthuem -- it seems that the Wiki-Page from https://github.com/madateamprojekt/Team317/wiki/Feature-Attributes was not moved over to the core wiki...

**Comment by Kogoro** [comment]
@LeDominik The wiki page was not moved as the fork under https://github.com/Subaro/BachelorThesis_Sprey_Sundermann reimplemented the functionality in a different way. Maybe @Subaro can enhance and update the wiki with the current view etc.

**Comment by tthuem** [comment]
@LeDominik Thanks for the comment. See #756.
