### ISSUE TITLE
Quick fix for missing configurations creates configurations in wrong format

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#657]
Deleted a configuration from one of our example projects to provoke warnings:

![qf](https://user-images.githubusercontent.com/5330357/32534510-49e3d260-c456-11e7-8a59-ebdd2eb28bc2.PNG)

Used the quick fix to generate configurations:

![qf-dialog](https://user-images.githubusercontent.com/5330357/32534512-4b6837fc-c456-11e7-90ab-6afcc95f06e8.PNG)

The above dialog does not allow to specify the configuration format. Hence, I would expect it to use the default format, but .config is used instead:

![format](https://user-images.githubusercontent.com/5330357/32534507-47a698c0-c456-11e7-9e7b-61112c00fb79.PNG)

This issue would be good to fix before the FeatureIDE tutorial planned in February.

**Comment by skrieter** [comment]
Fixed in c55d03a619f2f2e442a9680a01b739f166ae1403.
