### ISSUE TITLE
FeatureIDE manipulates feature models accidentially

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#662]
#### Prerequisitives
* **FeatureIDE-Version:** v3.3.0 for feature model creation (writing) and v3.3.2 or newer for reading

### Issue description
Created the following feature model with v3.3.0 (or v3.3.1):

![before](https://user-images.githubusercontent.com/5330357/32800488-c1fa3de2-c97a-11e7-9813-0a8d1711022d.png)

Loading the feature model with v3.3.2 or newer versions leads to the following result:

![after](https://user-images.githubusercontent.com/5330357/32800543-e79006e0-c97a-11e7-840e-fe09ce90ad3e.png)

FeatureIDE seems to misinterpret or-groups if one of their child features is a non-terminal feature (i.e., has further features). This only happens when creating the model with a different version that loading it, but it is quite critical, as those changes may stay unnoticed.

The feature model in XML format:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
	<featureModel>
		<properties/>
		<struct>
			<or mandatory="true" name="A">
				<or mandatory="true" name="B">
					<feature mandatory="true" name="D"/>
					<feature mandatory="true" name="E"/>
				</or>
				<feature mandatory="true" name="C"/>
			</or>
		</struct>
		<constraints/>
		<calculations Auto="true" Constraints="true" Features="true" Redundant="true" Tautology="true"/>
		<comments/>
		<featureOrder userDefined="false"/>
	</featureModel>
```

Who can have a look at this soon?

**Comment by Kogoro** [comment]
I traced it back to the following lines in the XML format. Seems that the getChildrenCount method does not work as expected here.

https://github.com/FeatureIDE/FeatureIDE/blob/5bf1ffe28eb37b5b093e7b752e3ded9d2d1fe1f3/plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java#L598-L603

**Comment by tthuem** [comment]
There are numerous mistakes with this piece of code. First, this should not be handled at the import, but in getters for the structure, as the same should happen when changing the feature diagram and we don't want to have code clones for this. Second, this code translates only Or and not alternative. Finally, this method is way too long.

**Comment by tthuem** [comment]
This issue is very critical. Numerous of our example projects cannot be used anymore, especially those from the book:

![void](https://user-images.githubusercontent.com/5330357/32927068-d7fe02dc-cb4a-11e7-9a8d-694324b045da.png)

**Comment by Kogoro** [comment]
Can someone please also test it on the release branch, so that we can make sure that this issue is solved correctly with no other errors appearing?

**Comment by tthuem** [comment]
It seems that the problem is fixed.

@Subaro Please do the code review as discussed.

**Comment by Subaro** [comment]
@Kogoro I do not see a problem with your changes.

**Comment by tthuem** [comment]
Seems that this problem still occurs on develop.

**Comment by tthuem** [comment]
Interestingly, the slight modifications to a feature model led to anomalies which are hard-to-explain.

For an industrial model with 712 features and 1141 constraints, the bug changed three or-groups into and-groups with mandatory child features. Those three changes led to an anomaly making the feature model void. While FeatureIDE can explain which constraints make the feature model void, not only those three parts were selected, but many more. 56 features and their respective connection to their parent were marked in the feature model as a cause of the anomaly (i.e., 56 tree constraints). Furthermore, 35 cross-tree constraints were involved in making the feature model void. When using FeatureIDE's functionality to collapse all features that are not involved in the explanation, a total number of 92 of all 712 features was shown. That is, while the actual cause of the void feature model were only related to three changed groups, a user has to inspect an explanation with 91 constraints and 92 involved features to identify the cause.

![model](https://user-images.githubusercontent.com/5330357/41845053-6e258a76-7872-11e8-8253-8e2c5e7ea881.png)

**Comment by tthuem** [comment]
Update on the long explanations: Even with the new and more detailed explanations with v3.5.0, the situation is not much better. The explanations show more detailed which tree constraint is involved in the explanation (i.e., whether a particular mandatory feature, an or-group, an alternative-group, or the parent-child-relationship is the cause).

![model_manipulated_3 5 0](https://user-images.githubusercontent.com/5330357/41845846-2d12a4a8-7875-11e8-855a-1ce6d100d29c.png)
