### ISSUE TITLE
Source tab should be the last tab in feature model editor

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#666]
Currently, the feature order tab has this position. First, this change should be reverted as it is rather unintuitive to people who have used FeatureIDE for a while. Second, it is common in Eclipse that multi page editors use the last tab for a source view.

![order](https://user-images.githubusercontent.com/5330357/32926957-5326f0aa-cb4a-11e7-9dd7-300ee5d39d08.PNG)

This occured in develop, but should be fixed in release, if necessary. Change milestone if only a change in develop is sufficient.

**Comment by skrieter** [comment]
Fixed in develop. Issue didn't occur in 3.4.2 release.
