### ISSUE TITLE
Feature name obfuscator

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#667]
FeatureIDE is more and more used in industrial applications for feature modeling. However, as feature models often contain confidential domain knowledge, feature models are typically not shared. Sharing, however, is necessary for numerous applications, including bug reports or reproduceability of research. Examples for obfuscated models are already in FeatureIDE: Automotive1 and Automotive2.

https://github.com/FeatureIDE/FeatureIDE/tree/develop/plugins/de.ovgu.featureide.examples/featureide_examples/FeatureModels

The goal is to write an obfuscator for feature names, as publishing the structure of a feature model is typically not a problem. Each feature name should be consistently replaced by unique identifier. Ideally, such a replacement would be stable over the evolution of a feature model. That is, when obfuscating the feature model again after a month of evolution, same feature names should lead to the same identifier.

The easiest thing to start with, would be an exporter into the FeatureIDE format, but with obfuscated names. Besides this, it would be nice to clone complete FeatureIDE projects and use the renaming functionality to replace all occurrences of a feature. In particular, features would be renamed in feature diagram, cross-tree constraints, feature diagram layout, configurations, color schemes, and source code.

**Comment by tthuem** [comment]
That was faster than expected. :)

I'll test it and will do a code review.

**Comment by tthuem** [comment]
Please revert the changes on develop, as they are not working. Then, create a branch for that changes for review.

Current implementation seems to dismiss many properties of feature diagrams:

![step1](https://user-images.githubusercontent.com/5330357/33166172-9be20afc-d039-11e7-8913-ab2a33cdbe88.png)
![step2](https://user-images.githubusercontent.com/5330357/33166175-9d8d7a58-d039-11e7-81eb-d1974156e78a.png)

**Comment by skrieter** [comment]
Should be working now.
Colors and key-value properties are not copied.
Could be a further enhancement.

**Comment by tthuem** [comment]
What is model.xml.salt good for?

**Comment by tthuem** [comment]
Seems to work well. Colors, layout and so one is not so important for now.

Is the model.xml.salt to be kept confidential? In other words, is it possible to recompute original feature names with that file?

**Comment by skrieter** [comment]
Since the obfuscator uses a hash function, in theory, it is possible to reengineer the original feature names by using a brute-force or dictonary attack on each individual feature.
The salt is used to make this attack unfeasible in practice.
It consists of a random string that is attached to each feature name before appling SHA-256.

The salt is stored in the salt file to be able to apply the same obfuscation again when the feature model evolves (i.e., computing the same identifiers).
Without this file (and probably even with) it is virtually impossible to reengineer the original feature names.

**Comment by tthuem** [comment]
Thanks for the explanation.
