### ISSUE TITLE
Open a second .xml configuration at the same time not possible

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#670]
#### Prerequisitives
* **Git branch/Commit-ID:**  `develop/release`

### Issue description
Steps to reproduce:
1. Open a .xml configuration
2. Try to open another .xml configuration with double-click

We can open the editor by manually select the configuration editor in the "Open With .." context menu entry. Also, .configs work fine.

**Comment by skrieter** [comment]
I think this is a general problem with the project explorer.
We experienced this problem before with serval other files (including model.xml).

I just found a related thread, maybe this can help:
https://stackoverflow.com/questions/31142547/double-clicking-a-resource-in-eclipse-project-explorer-does-not-open-the-second

**Comment by Subaro** [comment]
@Kogoro I tried but when double-clicking a .xml configuration it opens in another Configuration Editor. How can I reproduce? Which project did you use?

**Comment by tthuem** [comment]
@Kogoro What's left to be done here?
