### ISSUE TITLE
After editing a feature model in diagram and source, weird things happen

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#671]
The following behavior can be reproduced on release branch:

![step1](https://user-images.githubusercontent.com/5330357/33165585-ac1c5bfe-d037-11e7-94d5-6ead957376d6.png)
![step2](https://user-images.githubusercontent.com/5330357/33165588-adfdbcce-d037-11e7-9498-ff1686448b80.png)
![step3](https://user-images.githubusercontent.com/5330357/33165592-afd49202-d037-11e7-8e99-085e6d1015d9.png)
![step4](https://user-images.githubusercontent.com/5330357/33165596-b1b5573c-d037-11e7-8f46-1f32bbdbb942.png)
![step5](https://user-images.githubusercontent.com/5330357/33165597-b33a5454-d037-11e7-8e1f-1e81935f03b9.png)

**Comment by Kogoro** [comment]
Maybe related to the undo stack?
There are entries made by the text editor (DocumentUndoManager) which do the same as the SourceChangedOperation. I don't know if this is the problem but seems to be a bit suspicious.
![stack](https://user-images.githubusercontent.com/8019776/35915052-c90edc46-0c05-11e8-8bca-fc24b99ce285.PNG)

The selected entry prints the following:
```
Typing(org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument@79781e77)
org.eclipse.text.undo.DocumentUndoManager$UndoableTextChange undo modification stamp: 21 redo modification stamp: 22 start: 678, end: 678, text: '3', preservedText: ''
```

**Comment by tthuem** [comment]
@Kaemmelot Thanks for the report.

**Comment by Kogoro** [comment]
As purposed in the meeting, we change the manual layout to automatic when switching from the source to the diagram tab.
This should also resolve the problem mentioned by Paul in #776.
@PaulWestphal can you test this again? It is also on the branch issues_773_776.
