### ISSUE TITLE
Configuration propagator does not work correctly with abstract features

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#675]
#### Prerequisitives
* **Git branch/Commit-ID:**  `develop`, `release`
* **Formats checked**: `.config`,`.xml`

### Issue description

1. Import Hello World Antenna
2. Change Feature to `And`
3. Edit a configuration to use both features (`Wonderful` and `Beautiful`)
4. Change Feature back to `Alternative`
4. Open the edited configuration and you will get this configuration: 
![unbenannt](https://user-images.githubusercontent.com/8019776/33609346-08b325ac-d9c8-11e7-9eb8-8e86d7589e88.PNG)

**Comment by tthuem** [comment]
This is probably not specific to abstract features. It is an instance of a particular mode (in case we have such a mode) that allows you to fix configurations that have been invalidated by changing the feature model.

**Comment by tthuem** [comment]
Closed in favor of #678
