### ISSUE TITLE
Impossible to switch between tabs in the configuration editor after making the configuration invalid in the feature model editor.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#676]
### Issue description
1. Load the HelloWorld-Antenna example.
2. Open the configuration BeautifulWorld.xml in configuration editor, switch to source tab.
3. Make the configuration invalid by setting the Feature/World group to "alternative" and save.
4. In the configuration editor, try switching back to another tab. It doesn't work.

This bug exists in both release and develop right now. It seems like only .xml configurations are affected.

**Comment by tthuem** [comment]
Closed in favor of #678
