### ISSUE TITLE
Repairing invalid configurations interactively

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#678]
The configuration editor aims to avoid inconsistencies up-front. This behavior is impossible if a feature model is changed in a particular manner. Then, we have quite different behavior depending on whether the configuration editor is open or not and in which tab.

1. If the configuration is closed while saving the feature model, then it can somehow be fixed when opening the configuration. (Not sure whether this works in all cases already.)
2. If the configuration tree is open, then the configuration is fixed automatically, which can lead to counter intuitive results.
3. If the source tab is open, we cannot switch back to the tree without fixing the problem in XML (or the format being used).

**Comment by skrieter** [comment]
Fixed in branch issue_793. Close when merged.
