### ISSUE TITLE
When features are renamed in configurations their selection status is lost

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#685]
Before renaming, the feature ShortestPaht is selected:

![renaming](https://user-images.githubusercontent.com/5330357/34418536-e7bac398-ebfe-11e7-9191-c3be3c2211be.png)

After renaming, it is undefined rendering the configuration invalid:

![renaming2](https://user-images.githubusercontent.com/5330357/34418537-e90a9f98-ebfe-11e7-8947-48ff8932f3be.png)

This is rather critical as it is likely to remain unnoticed in many cases.

**Comment by tthuem** [comment]
This issues causes many weird error markers besides that certain configurations are invalid:

![problem-view](https://user-images.githubusercontent.com/5330357/34418737-ded3889a-ebff-11e7-9b94-96e668deb779.PNG)

**Comment by Kogoro** [comment]
The main problem is solved as features are now checked for renamings.
There is still a problem as configurations are checked twice. First, the current feature model (with the renaming) is used, while on the second run the old feature model (without the renaming) is used.
Also, the file content is correct but, when opening the editor, the configuration is changed to a state where the feature is not selected.

**Comment by Kogoro** [comment]
@skrieter 
Maybe one problem lies within the AFileManager
Seems to work better when changing emptyObject to variableObject in this line:
https://github.com/FeatureIDE/FeatureIDE/blob/2a4cefaf44c11f9cdf54f778632820c0569207b1/plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/manager/AFileManager.java#L305
We should check the FileManager occurrences for editObject() and getObject(). Maybe also renaming getObject to getPersistentObject or something like this could avoid confusion.

**Comment by tthuem** [comment]
Discussion is not yet finished.

**Comment by tthuem** [comment]
@PaulWestphal Please check, whether the renaming works in the tutorial.

**Comment by PaulWestphal** [comment]
It works. ShortestPath is still selected after renaming it.
