### ISSUE TITLE
Review error handling in NodeReader

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#690]
Should we really create a FALSE Literal at this point? This can lead to problems with features named FALSE. The question is if we break something when removing this code.

https://github.com/FeatureIDE/FeatureIDE/blob/f9c04038d02f2ca79e696873f9537bd27c7da52f/plugins/de.ovgu.featureide.fm.core/src/org/prop4j/NodeReader.java#L237-L247

**Comment by tthuem** [comment]
@skrieter intentionally added this in commit https://github.com/FeatureIDE/FeatureIDE/commit/53a41abfa8724c5ba0a2f002e2a2efdd8d163784. Simply removing it is likely to break anything.
