### ISSUE TITLE
Whether certain actions are added to the feature model context menu depends on the .isEnabled() status of one of the actions.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#691]
https://github.com/FeatureIDE/FeatureIDE/blob/1490be8611d509c72785f1d1f2b1126194b99526/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/FeatureDiagramEditor.java#L1128

Someone could write a method that determines what kind of context menu is being built.

This was part of #648 and the intended design for feature model context menus for 3.5.0 is outlined here: https://www.youtube.com/watch?v=9yksuffXv1s

**Comment by PaulWestphal** [comment]
It's not 100% done yet, connectionEntrys() still uses some .isEnabled() methods.

**Comment by PaulWestphal** [comment]
On second thought using methods of the connection type actions actually makes sense in the connectionEntries method, so I'll leave it largely unchanged for now.

**Comment by tthuem** [comment]
@Kogoro Can you review the changes?

**Comment by tthuem** [comment]
@PaulWestphal Why is it already merged when there was no code review?

**Comment by Kogoro** [comment]
![unbenannt2](https://user-images.githubusercontent.com/8019776/37218770-c5d76aec-23c1-11e8-84d6-5b9213e36365.PNG)
The collapse menus seems a bit off, or?

**Comment by PaulWestphal** [comment]
@Kogoro What do you mean by that?

**Comment by Kogoro** [comment]
Okay. After a talk with Paul, there seems to be no issues and I only get it wrong. So it's fine by me.
