### ISSUE TITLE
Statistics view won't reference a feature model, that was not automatically created

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#693]
#### Prerequisitives
* **FeatureIDE-Version:**  `release, develop`
* **Operating system:** `windows`

### Issue description
Steps to reproduce:
1. Create new featureIDE Project
2. Add a few features to the feature Model to see the effect later
3. Take a look at the Statistics View
4. Delete the feature Model (model.xml)
5. Create a new one
6. Take a look at the Statistics view

However, I am not entirely sure, whether I am just doing something wrong here.

Result:
The statistics of the automatically created model is correctly displayed.
![releaseautomaticallycreated](https://user-images.githubusercontent.com/24757266/35348015-17eb7614-0137-11e8-817a-0b559f428f9a.PNG)

Still showing the statistics of the deleted model(even after a refresh) :
![releaseselfcreated](https://user-images.githubusercontent.com/24757266/35348018-1acf0fc6-0137-11e8-9f7c-fe5df39491d5.PNG)

After closing and opening again:
![releaseafterexit](https://user-images.githubusercontent.com/24757266/35348624-d692977c-0138-11e8-9f18-594081a3b597.PNG)

**Comment by Kogoro** [comment]
Added a quick fix to a separate branch. 
We should discuss, how we want to handle model changes on the file system (removing and adding a new one under another name etc.)
The problem is that the feature model editor does not have access to the IFeatureProject.

**Comment by Kogoro** [comment]
We discussed this problem and decided that the statistics view will only be project-related, so the normal feature model must be named model.xml.
For information about the feature model in the editor, you can use the model edits view.
