### ISSUE TITLE
New extension point whenever code base changes for collaboration diagram, fuji markers, statistics view

### ISSUE THREAD

**Issue by kruegers** [FeatureIDE/FeatureIDE#70]

**Comment by tthuem** [comment]
In addition, make sure that Fuji error markers will also be deleted once they are not valid anymore (e.g., when saving some source code files again, saving the feature model).

**Comment by tthuem** [comment]
Similarly, a new listener is needed for updates of the feature model (only updates when a new version is saved). It is needed in the feature model edits view, the statistics view and for Fuji.

**Comment by tthuem** [comment]
@meinicke @skrieter Could you please report to which extent this is still open or already fixed? I remember that we've had numerous update problem, of which I have not seen much in the last time.

**Comment by tthuem** [comment]
Does not make sense to work on to many issues once and there is no overview what is left to be done of that above. Hence, I'm closing this issue and propose that we create new issues once we have seen further update problems, such as #424.
