### ISSUE TITLE
When changing the feature model, markers are not updated.

### ISSUE THREAD

**Issue by skrieter** [FeatureIDE/FeatureIDE#700]
#### Prerequisitives
* **Eclipse Version:**  Neon.2
* **FeatureIDE-Version:**  3.4
* **Operating system:** Windows
* **Java runtime used to run eclipse:** 1.8
* **FeatureIDE Composer:** all
* **Git branch/Commit-ID:**  develop
* **Java compiler used to build the FeatureIDE plugin:** 

### Issue description
Changing a feature model (e.g., removing a void constraint) does not clear the respective error markers.
Eclipse should perform a clean and (maybe) a build after saving a modified feature model.

**Comment by tthuem** [comment]
@skrieter Do we need this for the tutorial?

**Comment by Kogoro** [comment]
@tthuem We checked the issue and these were the only markers:
![fm5](https://user-images.githubusercontent.com/8019776/35988803-c808474c-0cff-11e8-85d6-a9983b8b1250.PNG)
Even after a build, this does not change.

**Comment by tthuem** [comment]
The change in the code does not look right. Also, why do those markers not appear anymore?

@PaulWestphal Paul, could you please check whether it works for the tutorial now? (i.e., there are only markers that we need for the tutorial)

**Comment by PaulWestphal** [comment]
Hands On II problems:

Occasionally when loading Elevator v1.0, I don't get the "The feature model is void" marker. It happens maybe once in two times.

The "Configuration 'x' is invalid" markers don't show up at all when the feature model is void unless I make a change in the feature model without fixing it.

Info markers still appear up to three times.

![tutorial1](https://user-images.githubusercontent.com/32126695/36030780-c99411d2-0da8-11e8-947e-84fe0c7f1d4e.png)

**Comment by tthuem** [comment]
Note sure what is going on here, but we are not getting closer to the version for the tutorial.

@Kogoro @Subaro Would be good if you could test the complete tutorial, too.

@skrieter We might need you help to get a stable version in time.

**Comment by Kogoro** [comment]
Regarding the not showing void marker: The sat solver delivers true as a result of the isValid() call. Then the marker is not created.
We will take a look at the configuration markers.

**Comment by Kogoro** [comment]
I made a quick fix for the markers. On build, there will be called a method for checking the most common problems.
@PaulWestphal @Subaro Please test on the quickfix branch.

**Comment by PaulWestphal** [comment]
When loading Elevator v1.0 on the quickfix branch "building workspace" never stops. That makes it impossible to run the elevator.

**Comment by Kogoro** [comment]
This does not happen for me. @Subaro: Does this occur for you as well?

**Comment by Kogoro** [comment]
5366e896ac04ae1e7ad6c28201a0ce5b31c3f99e should solve the rebuild issue. It appeared only sometimes when the feature model was overridden.
