### ISSUE TITLE
Problem with eporting model as svg

### ISSUE THREAD

**Issue by manojkeshava** [FeatureIDE/FeatureIDE#702]
[delta_features.pdf](https://github.com/FeatureIDE/FeatureIDE/files/1695403/delta_features.pdf)
#### Prerequisitives
* **Eclipse Version:**  eclipse neon2
* **FeatureIDE-Version:**  3.3.2
* **Operating system:** windows 10
* **Java runtime used to run eclipse:** jdk1.8
* **FeatureIDE Composer:** `Add text here (optional, leave blank if not needed)`
* **Git branch/Commit-ID:**  `Add text here (optional, leave blank if not needed)`
* **Java compiler used to build the FeatureIDE plugin:** `Add text here (optional, leave blank if not needed)`

### Issue description

I am using feature IDE for building feature models for my thesis. When I export the model as svg the "or" clause which has a filled arc looses its color. I am attaching it for your reference.

Thanks,
Manoj

**Comment by tthuem** [comment]
@manojkeshava Was not able to reproduce the problem. Did you have the same problem with the latest release 3.4.2?

**Comment by tthuem** [comment]
Can someone reproduce this problem? If so, does it still occur for branch release3.5?

**Comment by tthuem** [comment]
Can someone reproduce this problem? If so, does it still occur for branch release3.5?

**Comment by PaulWestphal** [comment]
It does not occur for me. But the legend isn't complete and special characters seem to be missing.

![svgbug](https://user-images.githubusercontent.com/32126695/37242082-bc4a7a62-2463-11e8-8602-6034a8145c3d.png)

**Comment by manojkeshava** [comment]
The problem for which I created the issue has occurred in the screenshot by PaulWestphal. I have also marked the places which I see the problem again in the attachment.

 

Regards,

Manoj

**Comment by tthuem** [comment]
The problem is likely to be caused by the SVG plug-in rather than by FeatureIDE. We have had numerous problems in the past with the SVG plug-in.

@manojkeshava We recommend to use the the export to PDF instead (i.e., print to PDF or any other printer you install). Please let us know, if that gives trouble too.
