### ISSUE TITLE
Marker for dead features is missing.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#705]
1. Load Antenna Elevator v1.0
2. Delete Modes=>Overloaded

Overloaded is now a dead feature, but there's no marker for it. There *is* a marker for false-optional feature Permission, however, so this seems like an inconsistency.

**Comment by tthuem** [comment]
A question is, whether we need markers at all, if this is already visible in the feature diagram. Markers for false-optional features are definitely not needed. Void feature models are necessary, as this is a severe inconsistency and such models cannot at all be used for configuration. Not sure whether we want to have markers for dead features or not. What are your opinions?

**Comment by Subaro** [comment]
@tthuem and @PaulWestphal The markers for the false-optional features only refer to the configuration that are currently available in the project workspace. As an example:

1) Load any feature model. 
2) Create a new feature 'test' under the root feature.
3) Open every configuration in the project and select 'test'

Now the feature 'test' is marked as false-optional in the Problem view. Therefore, we use two different definitions of false-optional. The first used inside the feature diagram means that there exists no configuration where the parent is selected while the feature is not selected. 

The second definition refers only to the configurations in the project making a feature 'false-optional' if it is selected in every available configuration.

In my opinion we should change the marker for 'false-optional' features to prevent the user of begin confused.

Current text:
`False optional: 2 features are optional but used in all configurations: CallButtons, test `

to just:
`2 features are optional but used in all configurations: CallButtons, test `

Besides we also have markers for unused features with the following text:
`Unused: 5 features are not used: PersonPriority, PermissionControl, RushHour, FloorPriority, Sabbath`

Maybe we could change both 'false-optional' and unused to:
`Configurations: 2 features are optional but used in all configurations: CallButtons, test `
and
`Configurations: 5 features are not used: PersonPriority, PermissionControl, RushHour, FloorPriority, Sabbath`

With that the user still got the overview tile 'Configurations' to know the markers has something to do with the configurations and the description of the proper problem.

What are your opinions?

**Comment by tthuem** [comment]
I agree with that confusion and like your proposals. Nevertheless, I think that we should come up with concrete names for unused and false-optional features in configurations.

**Comment by Subaro** [comment]
@tthuem I think we can still call unused features 'unused'. As for the 'false-optional' feature we could call them:
* false-elective features or
* false-arbitrary features
* predetermined features
* false-selected features

**Comment by tthuem** [comment]
always-selected and never-selected features

unused and undead features (I think the latter term has already another meaning in the community)

**Comment by Subaro** [comment]
Result: 
<img width="396" alt="aaa" src="https://user-images.githubusercontent.com/6231523/41530433-84b83e5a-72f0-11e8-8e2c-9623df0316c2.png">
