### ISSUE TITLE
Cannot open extended feature model if model with same name existed before

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#710]
Created a new feature modeling project. Exported the feature model into an extended feature model. Replaced model.xml with the extended feature model. The resulting feature model cannot be opened with the feature model editor.

![grafik](https://user-images.githubusercontent.com/5330357/37018631-586036a0-2115-11e8-80d4-80adec7846ef.png)

**Comment by tthuem** [comment]
Seems that this problem always occurs if a feature model with the same name has been there before, which was not an extended feature model. It just happened to me again, when I exported the model to the standard FeatureIDE feature model (by accident) and then exported an extended model with the same name.

**Comment by Subaro** [comment]
That does not only happen for extended feature models. 

1. Import two different examples A and B of feature models. 
2. Rename model.xml of example B to modelB.xml and move it to example A. 
3. Now delete model.xml for example A. 
4. Rename modelB.xml to model.xml
5. Open model.xml 

But know not the model of example B is shown instead of the model of example A shows which were deleted.

**Comment by SundermannC** [comment]
Same behavior for deleting and creating a model with the name of the deleted one
1. Create model.xml and add a few features
![samenamestep1](https://user-images.githubusercontent.com/24757266/37088949-45c6d96e-21ff-11e8-9a59-f58bb47ab8ac.PNG)
2. Delete model.xml 
3. Create new model with the same name: "model"
4.Result:
![samenamestep2](https://user-images.githubusercontent.com/24757266/37088951-4749e114-21ff-11e8-838b-c68368d8c49b.PNG)

**Comment by Kogoro** [comment]
The problem seems to be that the AFileManager does not check the content when looking for an already existing instance. I have tried some ways to check it but this leads to a need for improving the equals method of feature models (and of course all other classes which uses the AFileManager) and a change to the getInstance method. 
The methods could look like this:
```
        @SuppressWarnings("unchecked")
        @CheckForNull
	public static final <T, R extends IFileManager<T>> R newTempInstance(Path path, ObjectCreator<T> objectCreator) {
		final SimpleFileHandler<T> fileHandler = getFileHandler(path, objectCreator);
		if (fileHandler.getObject() != null) {
			try {
				final String absolutePath = constructAbsolutePath(path);
				final Constructor<? extends IFileManager<T>> constructor =
					objectCreator.fileManagerClass.getDeclaredConstructor(objectCreator.objectClass, String.class, IPersistentFormat.class);
				constructor.setAccessible(true);
				final IFileManager<?> instance = constructor.newInstance(fileHandler.getObject(), absolutePath, fileHandler.getFormat());
				instance.getLastProblems().addAll(fileHandler.getLastProblems());
				return (R) objectCreator.fileManagerClass.cast(instance);
			} catch (ReflectiveOperationException | SecurityException | IllegalArgumentException e) {
				Logger.logError(e);
			}
		}
		return null;
	}

	@SuppressWarnings("unchecked")
	@CheckForNull
	public static final <T, R extends IFileManager<T>> R getInstance(Path path, ObjectCreator<T> objectCreator) {
		final IFileManager<?> instance = getInstance(path);
		if (instance == null) {
			return newInstance(path, objectCreator);
		} else {
			final R castedInstance = (R) objectCreator.fileManagerClass.cast(instance);
			final R readInstance = newTempInstance(path, objectCreator);
			if (!castedInstance.editObject().equals(readInstance.editObject())) {
				return newInstance(path, objectCreator);
			}
			if (objectCreator.fileManagerClass.isInstance(instance)) {
				return castedInstance;
			} else {
				return null;
			}
		}
	}
```
```
@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if ((obj == null) || (getClass() != obj.getClass())) {
			return false;
		}
		final FeatureModel other = (FeatureModel) obj;
		if (getNumberOfFeatures() != other.getNumberOfFeatures()) {
			return false;
		}
		if (getConstraintCount() != other.getConstraintCount()) {
			return false;
		}
		for (final IFeature feature : getFeatures()) {
			boolean test = false;
			for (final IFeature otherFeature : other.getFeatures()) {
				if (feature.equals(otherFeature)) {
					test = true;
				}
			}
			if (!test) {
				return false;
			}
		}
		for (final IConstraint constraint : getConstraints()) {
			boolean test = false;
			for (final IConstraint otherConstraint : other.getConstraints()) {
				if (constraint.equals(otherConstraint)) {
					test = true;
				}
			}
			if (!test) {
				return false;
			}
		}
		return true;
	}
```
Negative effect: A file will be read more often.
Another approach could be a resource change event which creates a new instance for every change of the feature model, which is nevertheless quite often.
