### ISSUE TITLE
After accidentially clicking on recursive, all attribute values are lost

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#711]
Not sure how to solve this problem, but this can be frustrating if all attribute values are lost this way.

![grafik](https://user-images.githubusercontent.com/5330357/37019873-310f2570-211a-11e8-837f-393f439f17f4.png)

**Comment by SundermannC** [comment]
My solution would be saving the values non-persistent after removing the recursive tag. So they are available until the .xml is closed. Do you have suggestions ?

Start:
![recursivestep1](https://user-images.githubusercontent.com/24757266/37088452-b348ad20-21fd-11e8-8424-45691cd32000.PNG)
First click on recursive
![recursivestep2](https://user-images.githubusercontent.com/24757266/37088457-b4941e62-21fd-11e8-9527-05ee85c7a6d8.PNG)
Second click on recursive
![recursivestep3](https://user-images.githubusercontent.com/24757266/37088460-b60776c2-21fd-11e8-9335-7472d89c13d6.PNG)
