### ISSUE TITLE
Make feature attributes available using a Java library

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#714]
Similar to the existing FeatureIDE library, we need to make the attributes available using a jar. Either by including the sources into the existing jar or by means of a separate jar.

@skrieter Sebastian, which option do you prefer?

**Comment by Subaro** [comment]
The scripts to generate the java library for the attributes are pushed on develop. (09b590d46cf27e18b174c17cb75c993e0f6f5949)
