### ISSUE TITLE
Exporting product-equivalent model with only simple constraints does not work anymore

### ISSUE THREAD

**Issue by AlexanderKnueppel** [FeatureIDE/FeatureIDE#719]
#### Prerequisitives
* **FeatureIDE-Version:**  3.4.3

### Issue description
Get a feature model with complex constraints (i.e., a constraint that is neither a requires nor a excludes constraint). I used the GPL-medium example.

Right-click on model.xml and choose FeatureIDE->"Product-equivalent model with simple constraints"
The problem is that complex constraints are not recognized anymore, and, thus, the transformation is disabled:

![image](https://user-images.githubusercontent.com/263321/37277163-36b1386e-25e4-11e8-8cab-0b787aafaf24.png)

The respective classes are under fm.core.conversion. In "ComplexConstraintConverter.java" there are methods for identifying whether a constraint is simple or complex. I assume something happened with the constraint or node classes, which invalidated the rightfulness of these methods.

**Comment by tthuem** [comment]
Thanks for the report.

**Comment by tthuem** [comment]
Seems to work partially now. Removing redundant constraints, however, does not work. When translating our example axTLS, I'm still getting numerous redundant constraints.

**Comment by AlexanderKnueppel** [comment]
Agree, the option to remove redundant constraints is quite misleading. This option removes redundant constraints prior to conversion (so they do not have to be converted). New redundant constraints can emerge in the conversion process when constraints are not minimized (at least that is the reason I can think of). 
Maybe the option should cover both cases, but removing redundant constraints can take a while. 

Another enhancement I can thank of would be to always use the combined approach, as speed was never an issue.

**Comment by tthuem** [comment]
Oh ok. Then I misunderstood this configuration option.

@AlexanderKnueppel Could you simply change the label to make that clear? I think the rest can stay as-is.
