### ISSUE TITLE
Can't save a Feature Diagrams initial state.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#733]
Steps to reproduce:
1. Load any feature model.
![speicherbug1](https://user-images.githubusercontent.com/32126695/37922489-f580c716-312c-11e8-8b6b-1aa0e957d6e3.png)
2. Create a new Feature below a feature (NewFeature1) and save the Feature Model.
![speicherbug2](https://user-images.githubusercontent.com/32126695/37922493-f6cfd940-312c-11e8-8f38-9c7ce0f25f3f.png)
3. Delete the Feature you just created (thus going back to the state when you first loaded the feature model). Even though you just changed the feature model, there is no dirty flag. Try to save (you can't).
![speicherbug3](https://user-images.githubusercontent.com/32126695/37922495-f83fe50e-312c-11e8-9342-06dab49a4763.png)

You can still go back to the initial state by creating two features instead of one and deleting both of them. This bug appears in both develop and release3.5 and may be related to #677.

**Comment by Kogoro** [comment]
@PaulWestphal Can you check if it works as expected now? It should be only savable when it is different to the persistent model. See AFileManager.hasChanged(). Now it is also not savable after making multiple operations and reverting them.
