### ISSUE TITLE
Analyses in constraint dialog take longer than in feature model

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#736]
#### Prerequisitives
* **FeatureIDE-Version:**  3.4.2

### Issue description
For certain very long constraints of the form `A or B or C or ... or Y implies Z` the constraint dialog takes up-to 8 minutes for a feature model with about 400 features and 1000 constraints. For the same model, the complete analysis in the feature diagram was finished within 10 seconds. However, as the constraint dialog even needs to check fewer properties, it should even be faster.

I might be able to share the feature model somewhen in April.

**Comment by skrieter** [comment]
@tthuem Can you please checkout the branch `fix_constraint_dialog_performance` and test whether the performance improved for your example?

**Comment by tthuem** [comment]
@skrieter The speed-up is amazing. I tried the largest constraints and computations were finished in each case within a second, often even in milliseconds. Before your changes, I found cases where analyses needed up-to three minutes. That's a speed-up of 2 to 3 orders of magnitude.

Please go ahead and merge it into the release branch.

For the record, what of your changes lead to the speed-up?

**Comment by skrieter** [comment]
Merged.

The speed-up comes mostly from caching of intermediate results. Before, there were lots of redundant operations such as cloning the feature model, creating CNFs and new solver objects, and re-analysing the complete feature model after adding/deleting/modifing a constraint.
I also reused our existing and optimised analyses where ever possible.
