### ISSUE TITLE
Calculation of program variants for EPL-AHEAD model is wrong

### ISSUE THREAD

**Issue by ec0github** [FeatureIDE/FeatureIDE#741]
#### Prerequisitives
* **Eclipse Version:**  `Oxygen.3 (4.7.3)`
* **FeatureIDE-Version:**  `3.5.0`
* **Operating system:** `CentOS Linux release 7.4.1708 (Core) `
* **Java runtime used to run eclipse:** `openjdk version "1.8.0_161"
* **FeatureIDE Composer:** `AHEAD`
* **Git branch/Commit-ID:**  `Add text here (optional, leave blank if not needed)`
* **Java compiler used to build the FeatureIDE plugin:** `openjdk version "1.8.0_161`

### Issue description
Calculation of program variants for EPL-AHEAD is wrong. The number of configuration is 16 and number of program variants is 1. It should be 16.

![image](https://user-images.githubusercontent.com/10429223/38498626-9f5b41d4-3c37-11e8-8be0-b1ac6081bf75.png)

**Comment by tthuem** [comment]
@ec0github Thanks for your report. This is a very intersting example and there is no easy solution.

The difference when computing the number of configurations and number of variants is that we ignore abstract features for the number of variants. That is, we slice a feature model such that all abstract features are removed, while keeping transitive constraints.

Right now, we did the same for hidden features, as their selection status cannot be influenced by the user during configuration. However, slicing out all abstract AND all hidden features is certainly wrong, as illustrated in the example above.

An easy fix is to treat hidden features as any other feature (not slice them out). The resulting number of variants/configurations is then exact, if there are no indeterminate hidden features. However, if there are indeterminate hidden features (as in the example above) the computed number might be larger than actually possible during the configuration process.

As we are not aware of any algorithm to compute the exact number in presence of indeterminate hidden features, we will most probably go for the fix stated above and mention the inaccuracy in the tool tip.

**Comment by ec0github** [comment]
I just have an idea and correct me if it is not working. As there is no problem in the calculation of number of valid configurations, can we have the set of valid configurations and filter out the abstract features from each configuration. There are some filtered configurations are identified. Then, we filter the resulting configurations for distinct result. The result set should be valid variants. Thank you.

**Comment by tthuem** [comment]
Indeed, that's an option but requires quadratic effort in the number of returned configurations. We would only need to do that if there are (indeterminate) hidden features.

@skrieter What do you think?

**Comment by skrieter** [comment]
I made a quickfix in 0babb90b05e7447a27bfde36b2715d8f296a04c9.
Hidden features can now be considered in the calculation of the number of possible configurations.

For counting the number of program variants they are now included. However this could still lead to inaccurate results when the hidden features are indetermined. Nevertheless, the results are still much better than before.

@ec0github  Indeed your solution should also work and in addition ignores the indetermined state of the hidden features. However, it would require some restructuring of our current code. As @tthuem mentioned it introduces quite some overhead for larger models and thus we only want to apply this in case there are indetermined hidden features. Probably, we will included this in the next release (3.6).

**Comment by ec0github** [comment]
@skrieter thank you for your prompt action and understand that it need sometime to plan for a long term solution

**Comment by tthuem** [comment]
We decided to make users aware (in the statistics view) that indeterminate hidden features can make the computation inaccurate.
