### ISSUE TITLE
Conversion of feature models not working

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#744]
Not sure why, but there are two ways to convert a feature model. Using the context menu on a project and using the context menu on a feature model. The former is not working, at least for conversions into the extended feature model format:

![image001](https://user-images.githubusercontent.com/5330357/38729280-c31d9738-3f12-11e8-8d9b-cbe3a4d346c6.jpg)

![image002](https://user-images.githubusercontent.com/5330357/38729281-c5390f66-3f12-11e8-98aa-8f65ff2f55bb.jpg)

**Comment by skrieter** [comment]
The one that appears for projects and folder was intended to export all feature models in this folder to another one and convert the file format accordingly.
I revised the code so that it is now in accordance with the other export function and works properly.

**Comment by skrieter** [comment]
The current label is _Export All Feature Models_.
I'd like to avoid an overly long label text.
Any suggestions?

**Comment by tthuem** [comment]
The title is fine.
