### ISSUE TITLE
Fix JavaDoc problems in FeatureIDE source code

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#748]
To add FeatureIDE to the Maven Central Repository it is necessary that the source code is accepted by JavaDoc compiler. Currently, there are numerous problems with JavaDoc comments.

@hfenske33 is preparing a new branch that checks all violations on Jenkins. Nevertheless, it might be better to work with Eclipse Support on these violations and then use Jenkins to check validity.

**Comment by Subaro** [comment]
@tthuem Is would manually check every plugin for their java docs. In the process i generate the javadoc into the folder 'doc' for every plugin.

**Comment by Subaro** [comment]
| Plugin                                                | Status | Errors |
|-------------------------------------------------------|--------|--------|
| de.ovgu.featureide.core                               |        |        |
| de.ovgu.featureide.core.ahead                         |        |        |
| de.ovgu.featureide.core.antenna                       |        |        |
| de.ovgu.featureide.core.aspectj                       |        |        |
| de.ovgu.featureide.core.conversion.ahead-featurehouse |        |        |
| de.ovgu.featureide.core.featurecpp                    |        |        |
| de.ovgu.featureide.core.featurehouse                  |        |        |
| de.ovgu.featureide.core.framework                     |        |        |
| de.ovgu.featureide.core.images                        |        |        |
| de.ovgu.featureide.core.mpl                           |        |        |
| de.ovgu.featureide.core.munge                         |        |        |
| de.ovgu.featureide.core.munge.android                 |        |        |
| de.ovgu.featureide.core.runtime                       |        |        |
| de.ovgu.featureide.examples                           |        |        |
| de.ovgu.featureide.fm.attributes                      |        |        |
| de.ovgu.featureide.fm.core                            |        |        |
| de.ovgu.featureide.fm.ui                              |        |        |
| de.ovgu.featureide.migration                          |        |        |
| de.ovgu.featureide.ui                                 |        |        |
| de.ovgu.featureide.ui.android                         |        |        |
| de.ovgu.featureide.ui.mpl                             |        |        |
| de.ovgu.featureide.Cloneanalysis                      |        |        |
| br.ufal.ic.colligens                                  |        |        |

**Comment by Subaro** [comment]
Current overview:

| Plugin                                                | Status  | Errors                   |
|-------------------------------------------------------|---------|--------------------------|
| de.ovgu.featureide.core                               | Failure | 14 errors, 56 warnings   |
| de.ovgu.featureide.core.ahead                         | Success | 13 warnings              |
| de.ovgu.featureide.core.antenna                       | Success | 3 warnings               |
| de.ovgu.featureide.core.aspectj                       | Success | 0                        |
| de.ovgu.featureide.core.conversion.ahead-featurehouse | Success | 2 warnings               |
| de.ovgu.featureide.core.featurecpp                    | Success | 1 warning                |
| de.ovgu.featureide.core.featurehouse                  | Failure | 8 errors, 21 warnings    |
| de.ovgu.featureide.core.framework                     | Success | 14 warnings              |
| de.ovgu.featureide.core.images                        | Failure | 2 errors, 5 warnings     |
| de.ovgu.featureide.core.mpl                           | Success | 0                        |
| de.ovgu.featureide.core.munge                         | Failure | 2 errors, 2 warnings     |
| de.ovgu.featureide.core.munge.android                 | Success | 5 warnings               |
| de.ovgu.featureide.core.runtime                       | Success | 0                        |
| de.ovgu.featureide.examples                           | Failure | 3 errors, 5 warnings     |
| de.ovgu.featureide.fm.attributes                      | Failure | 1 error                  |
| de.ovgu.featureide.fm.core                            | Failure | 100 errors, 100 warnings |
| de.ovgu.featureide.fm.ui                              | Failure | 59 errors, 100 warnings  |
| de.ovgu.featureide.migration                          | Failure | 2 errors, 17 warnings    |
| de.ovgu.featureide.ui                                 | Failure | 22 errors, 80 warnings   |
| de.ovgu.featureide.ui.android                         | Success | 0                        |
| de.ovgu.featureide.ui.mpl                             | Success | 0                        |
| de.ovgu.featureide.Cloneanalysis                      | Success | 0   |
| br.ufal.ic.colligens                                  | Failure | 3 errors, 60 warnings    |

**Comment by Subaro** [comment]
@SundermannC @PaulWestphal The current java doc fixes were only commited to the branch FeatureIDEDocs

**Comment by Subaro** [comment]
The javadocs on release3.5 are up to date an can be compiled without any error. The same goes for develop.
