### ISSUE TITLE
Feature Model editor allows invalid names for renaming.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#752]
This has been happening since FeatureIDE 3.1

**Comment by tthuem** [comment]
Please provide more details. What do you consider an invalid name? Which composer are you referring to?

**Comment by PaulWestphal** [comment]
Any name without quote signs and brackets is accepted. Special characters, spaces, only numbers, etc. Even though the "invalid name" popup appears, it doesn't stop me from pressing enter to apply the invalid name. 

I've tried Antenna and FeatureC++.

![invalidnames](https://user-images.githubusercontent.com/32126695/39188877-27058da2-47d1-11e8-831e-8d3226ed37ee.png)

**Comment by tthuem** [comment]
That's scary.
