### ISSUE TITLE
NullPointerException when trying to access Color Scheme Menu in non-FeatureIDE project.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#755]
How to reproduce:

1. Create Java Project in Eclipse
2. Right-click the Project
3. Open the FeatureIDE menu
4. Try to open the Color Scheme Menu

This happens in the current develop branch and in release 3.5.0.

**Comment by tthuem** [comment]
Why is the FeatureIDE menu available for non-FeatureIDE projects at all?

**Comment by Kogoro** [comment]
@skrieter Does your commit 7ec1803bb24b16def71f86cd01c44d3874e6ad37 solve this issue?

**Comment by skrieter** [comment]
@Kogoro I didn't look at the concrete problem I here. I just fixed the menu in the GUI. Maybe it prevents users from getting this particular NullPointer, but I'm not sure.
