### ISSUE TITLE
Font size in features

### ISSUE THREAD

**Issue by vsmiari** [FeatureIDE/FeatureIDE#758]
Is there a way to change the font size of the text of the features?

**Comment by tthuem** [comment]
The font size can be changed by adapting the zoom level:

![font-size](https://user-images.githubusercontent.com/5330357/40046739-ffa317a8-582d-11e8-9178-63db02cade23.PNG)

Other properties of the feature diagram can be specified in the properties page:

![properties](https://user-images.githubusercontent.com/5330357/40046793-1bc7453a-582e-11e8-8fcd-28aece12ee9c.PNG)

![properties-dialog](https://user-images.githubusercontent.com/5330357/40046801-1dd3d29e-582e-11e8-9641-dcb30c3e45c2.PNG)

Hope this answers your question. If not, feel free to comment on this issue again.

**Comment by vsmiari** [comment]
I'm sorry I wasn't more specific. Yes zooming in does work at runtime but what I meant was increasing the font size in the exported image also. The .png file has the same font size whether I am zoomed in 100% or 200%.

**Comment by tthuem** [comment]
@vsmiari Have you tried to print the diagram to a PDF or any other file printer? Does it not help either?
