### ISSUE TITLE
Feature Model source editor page allows invalid names for renaming.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#759]
Similiar to #752.

**Comment by PaulWestphal** [comment]
Okay this could be fixed by inserting something like this:


```
if (!FMComposerManager.getFMComposerExtension(ResourcesPlugin.getWorkspace().getRoot().findFilesForLocationURI(object.getSourceFile().toUri())[0].getProject()).isValidFeatureName(name)) {
    throwError(name + " is not a valid feature name", e);
}
```
here

https://github.com/FeatureIDE/FeatureIDE/blob/03225c14fb716b498964612716727f68dd13e892/plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java#L551-L558

However, that would only cover the default .xml feature model format. So I'd have to paste this into the eight other feature model formats. Can anyone think of a less clunky way to do this? @Kogoro @Subaro

**Comment by Subaro** [comment]
@PaulWestphal Did you consider the XMLExtendedFeatureModelFormat?

**Comment by PaulWestphal** [comment]
Yes, check the commit 64349fff3a09098b448c0f878b1e04c77f57d4a7.
