### ISSUE TITLE
Make the FeatureIDE Outline read-only.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#760]
It's supposed to be a view, not an editor. Thus, edit actions should be removed from it. Currently the context menu for features looks like this:

![kontextmenu](https://user-images.githubusercontent.com/32126695/40381550-45ebc808-5dfc-11e8-93e0-419a5ac820c4.png)

And like this for constraints:

![kontextmenu2](https://user-images.githubusercontent.com/32126695/40381566-4d829a42-5dfc-11e8-9b1c-794bf0f2d762.png)

Should both of these context menus be removed entirely or are there any actions in there that make sense in the Outline view? I could see an argument being made for keeping Feature Color.

**Comment by tthuem** [comment]
@SundermannC What is the status here? In which branch is it developed?

**Comment by PaulWestphal** [comment]
0ee063526913776f53b45c44c311998eaa64b671
