### ISSUE TITLE
Collapsing or expanding a feature does not set a dirty flag.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#761]
1. Open any Feature Model
2. Collapse or expand a feature without changing anything else
3. Try to save (you can't)

If you close and reopen the editor now, the collapse status will be back to it's previous state.

**Comment by tthuem** [comment]
Same applies for positions of features in manual layout.

**Comment by Kogoro** [comment]
Related to #776. I will check if it is also solved in the branch issue_773_776.

**Comment by Kogoro** [comment]
Is also done with #773 and #776. @Subaro and @PaulWestphal please also verify this when checking the other two issues.

**Comment by Subaro** [comment]
@Kogoro Yes, it worked.
