### ISSUE TITLE
Unintuitive behaviour when moving between features using the arrow keys in left-aligned layout.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#763]
Example:

When pressing the right arrow key, you'd expect to jump to "Service".

![arrowkeys](https://user-images.githubusercontent.com/32126695/40384784-e0697814-5e04-11e8-82d9-4bba1421adfe.png)

However, you'll select "FIFO" instead.

![arrowkeys2](https://user-images.githubusercontent.com/32126695/40384871-2096af1a-5e05-11e8-850a-5b52af95e722.png)

**Comment by tthuem** [comment]
Same for left-to-right layout.

**Comment by Subaro** [comment]
related to #765,
