### ISSUE TITLE
Can't save a configuration after it was automatically fixed in the configuration editor.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#764]
1. Load the HelloWorld-Antenna example
2. Create the constraint "World implies Wonderful" and save
3. Open BeautifulWorld.xml

Wonderful is now selected, but it can't be saved because there's no dirty flag.

**Comment by PaulWestphal** [comment]
This is not a bug. The changes to the configuration are already saved when you enter the configuration editor.

**Comment by tthuem** [comment]
It is not intuitive that opening an editor changes a file.

Or is the configuration updated when saving the feature model?

**Comment by tthuem** [comment]
We need to discuss this issue with Sebastian.

**Comment by skrieter** [comment]
Fixed in branch issue_793. Close, when merged.
