### ISSUE TITLE
False warning that the feature model has been changed outside of Eclipse

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#770]
I edited a feature model and during this process I switched to the source tab. When saving the feature model, I am asked to load the contents from disk, which is essentially the old, unchanged state of the feature model. Clicking on yes resets all changes that have been applied to the feature model.

![feature-model-loaded](https://user-images.githubusercontent.com/5330357/40476099-7c12a9ae-5f43-11e8-919d-fe66d14c4d23.png)

**Comment by Subaro** [comment]
@tthuem I tried to reproduce but it does not occur. I did the following:
```
1) Open feature model
2) Did some changes 
3) Switched to the source tab
4) Saved the feature model without any problem
```
Also did:
```
1) Open feature model
2) Did some changes 
3) Switched to the source tab
4) Changed something in the source
5) Saved the feature model without any problem
```
And also:
```
1) Open feature model
2) Did some changes 
3) Switched to the source tab
4) Changed something in the source
5) Switched to the feature diagram editor
6) Did some changes
7) Switched to the source tab
8) Saved the feature model without any problem
```

**Comment by Subaro** [comment]
After discussing this issue we agreed to delay it because it seems to be a running condition.

**Comment by PaulWestphal** [comment]
We can't reproduce this bug right now.
