### ISSUE TITLE
Manual layout information not loaded correctly

### ISSUE THREAD

**Issue by rene-schoene** [FeatureIDE/FeatureIDE#773]
#### Prerequisitives
* **Eclipse Version:**  `Oxygen.3 (4.7.3)`
* **FeatureIDE-Version:**  `Release 3.5.0 (April 2018)`
* **Operating system:** `Fedora 27 x64`
* **Java runtime used to run eclipse:** `1.8.0_121`
* **FeatureIDE Composer:**
* **Git branch/Commit-ID:**
* **Java compiler used to build the FeatureIDE plugin:** 

### Issue description

The manual layout information is not loaded correctly after saving and closing the model file.

### Steps to reproduce

1) Create a new FeatureIDE project, leave everything to defaults except the name.
2) *Optional: Create a new feature in the model.*
3) Set the layout to `Manual layout`.
4) Move around some of the features.
5) Save and close the model.

Here the layout information is saved correctly in the file `model.xml.xml`.

6) Open the model again.

Now the layout is back to the layout selected before using manual layout, thus all manual editing is discarded. Additionally the model is marked to have changes (marked with the `*`).

**Comment by tthuem** [comment]
Thanks for the report. We will hopefully have a fix until the next release.

**Comment by rene-schoene** [comment]
Great. As a remark: It works, if (before saving the model), one selects in the context menu: Set Layout -> Auto Layout Constraints.
Then apparently the model is loaded correctly.

**Comment by Subaro** [comment]
@Kogoro I reviewed your changes. They seem very good and it is working.
