### ISSUE TITLE
Connections of features created with "Create Feature Above" do not show up in left-aligned or left-to-right layout.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#774]
This appears to happen every time. When another change to the Feature Model occurs, the connection is visible again.

![connectionslefttoright1](https://user-images.githubusercontent.com/32126695/40677609-6c1dba04-637e-11e8-9345-d4124907365b.png)

![connectionslefttoright2](https://user-images.githubusercontent.com/32126695/40677614-6d9aaffe-637e-11e8-9022-6c60eb591adf.png)

**Comment by tthuem** [comment]
Thanks for reporting it. This is rather a major issue, as the left-to-right layout is the only one that scales to large feature models.

**Comment by Subaro** [comment]
The edit parts were not refreshed which lead to the missing connections. After all it is still suspicious because it only happened for left -> right layouts. Now it is fixed.
