### ISSUE TITLE
Legends auto-layout moves all features to (0,0)

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#775]
#### Prerequisitives
* **Git branch/Commit-ID:**  `release3.5`

### Issue description
Change the layout to manual and move the legend freely to any point.
Click "Auto-Layout Legend" in the legend context menu and all positions are set to (0,0) which makes the complete diagram unusable. 
![unbenannt](https://user-images.githubusercontent.com/8019776/40715752-e827175c-6406-11e8-9116-2f2886470777.JPG)

**Comment by Subaro** [comment]
@Kogoro I could not reproduce this behavior ;)

**Comment by Kogoro** [comment]
Seems to be a problem on my side.
