### ISSUE TITLE
Legend movement should make the diagram dirty

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#776]
#### Prerequisitives
* **Git branch/Commit-ID:**  `release3.5`

### Issue description
I think that when the legend is moved freely, the editor should be in the dirty state.
Also, the legends position could be saved along with other settings of the FeatureModelLayout class in the graphical feature model.

**Comment by PaulWestphal** [comment]
The legend's position is not saved, therefore there shouldn't be a dirty flag if you move it. It's not a bug.

**Comment by Subaro** [comment]
@Kogoro I reviewed your changes. They seem very good and it is working.

**Comment by PaulWestphal** [comment]
Issues #776 and #761 are fixed, but it looks like the model.xml.xml doesn't update when you edit the Feature Model in the Source Tab. Try this:

1. Open new HelloWorld-Antenna
2. Open the Feature Model Editor and set manual layout
3. Open model.xml.xml
4. Go to Feature Model Source Tab
5. Delete lines 7 and 8
6. Save

**Comment by Subaro** [comment]
@Kogoro after changing the layout, no dirty flag appears ;) I think it is because of your work
