### ISSUE TITLE
Annoying runtime exception when right clicking things (e.g., eGit repository)

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#778]
#### Prerequisitives
* **Eclipse Version:** Oxygen
* **FeatureIDE-Version:**  3.5.0
* **Operating system:** Windows

### Issue description
The class DynamicProfileMenu throws exceptions that make Eclipse to add an Error and to force to open the Errors view. For example, if you use eGit and you have cloned a repository, this is the error caused by the exception when you right click the repo.

```
java.lang.RuntimeException: element RepositoryNode[REPO, Repository[C:\git\x\.git]](class org.eclipse.egit.ui.internal.repository.tree.RepositoryNode) not coveredd
	at de.ovgu.featureide.ui.actions.DynamicProfileMenu.getCurrentFeatureProject(DynamicProfileMenu.java:192)
	at de.ovgu.featureide.ui.actions.DynamicProfileMenu.<init>(DynamicProfileMenu.java:68)```

**Comment by tthuem** [comment]
Thanks for the report, sounds indeed annoying. We'll investigate this soon.
