### ISSUE TITLE
Autocompletion in constraint dialog for features starting with "

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#781]
Constraints use "" for features that have spaces in their name. Example:

To use a feature called New Feature in a constraint, you have to type "New Feature".

How it should work:

1. Create a new project using a composer that allows spaces in feature names

2. Create a feature with a space in its name

3. Create a new constraint

4. Type a ", there should be auto complete options for features that contain a space

**Comment by Rahel12342** [comment]
A few small functionalities related to the issue are not correctly implemented yet (e.g. only show "and" as autocompletion if the last word was a feature) and will be adapted with this issue since their way of working is related and similar
