### ISSUE TITLE
Content assist in constraint dialog should support brackets

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#782]
1. Open the constraint dialog

2. Type a bracket: (

![klammer1](https://user-images.githubusercontent.com/32126695/41301812-396f136e-6e69-11e8-84ee-460c4e2d2009.png)

3. Use auto-complete to add a keyword or feature name

![klammer2](https://user-images.githubusercontent.com/32126695/41301824-3fbcb8b6-6e69-11e8-852c-e371b6bc383a.png)

4. The bracket disappears

![klammer3](https://user-images.githubusercontent.com/32126695/41301830-4335bc86-6e69-11e8-9ef7-626e3f1ef8b5.png)

**Comment by skrieter** [comment]
Fixed in [SP_MD_SoSe2018](https://github.com/FeatureIDE/FeatureIDE/tree/SP_MD_SoSe2018).
