### ISSUE TITLE
No generation of code after changes in feature files

### ISSUE THREAD

**Issue by nioerd** [FeatureIDE/FeatureIDE#789]
#### Prerequisitives
* **Eclipse Version:**  4.7.3a
* **FeatureIDE-Version:**  3.5
* **Operating system:** MacOS 10.11.6
* **Java runtime used to run eclipse:** 1.8
* **FeatureIDE Composer:** FeatureHouse
* **Git branch/Commit-ID:**
* **Java compiler used to build the FeatureIDE plugin:**

### Issue description
The main code in "src" of a project is not created after code in "features" is created or changed. To make the IDE generate the code the user needs to manually uncheck, then check an other feature and save inside a config-xml file or click on the config and select "FeatureIDE" > "Set as current configuration".

Is this behavior planed?
If not, it would be nice, if changes in the feature-src files would make its way into the main-src files automatically.

**Comment by tthuem** [comment]
Thanks for the report. We will investigate why this does not work with FeatureHouse (anymore).

**Comment by Subaro** [comment]
Duplicate to #794 number 1
