### ISSUE TITLE
Add tests for extended feature models and add them to CI

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#792]
There are tests available, but not yet running on Jenkins and Travis.

**Comment by Kogoro** [comment]
Currently, we only have tests for the standard feature model. The tests in the attributes-test project are commented out.
The attributes-test project can be included with `<module>tests/de.ovgu.featureide.fm.attributes-test</module>` under test-modules.
Therefore, I would choose to wait until proper tests are written.

**Comment by Subaro** [comment]
Tests for extended feature models are committed on release3.5. More functionality which is currently not available on release3.5 needs testing and, thus, we should postpone the issue.

- [x] Tests for extended feature models and the new format
- [ ] Tests for extended configurations
