### ISSUE TITLE
Issues for the FeatureHouse composer

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#794]
#### Prerequisitives
* **Eclipse Version:**  `Photon Release (4.8.0)`
* **FeatureIDE-Version:**  `release3.5`
* **Operating system:** `Win10`

### Issue description
As developing my program I realized that the feature house composer does contain a lot of annoying things. 

1) As a user, it is not clear when the features are composed to the source code. It only happens when changing the configuration (I think so, I found no other way). That is very annoying because you always need to switch configuration and so on. I think for testing the program more often it is beneficial to add a small composer toolbar containing the essential operations. Like "Generate source for current configuration", "Create feature folders if necessary".

2) Apparently adding a feature and saving the model leads to eclipse waiting for some operation:
![unbenannt](https://user-images.githubusercontent.com/6231523/42734434-0bbbe538-8844-11e8-87fe-39a4405e170e.PNG)

3) Somestimes the feature folders are not generated corretly. Somtimes some folders are missing and somtimes unused folders are not removed automatically. But they should.

**Comment by tthuem** [comment]
1. We rather need to react on changes to source files and then build automatically. That's the default behavior in Eclipse (unless deactivated).

2. Seems to be related to #146 and #251.

3. Feature folders should only be removed if they are empty.

**Comment by tthuem** [comment]
Users reported that 1. is not only an issue for FeatureHouse, but also for other composers! Please make sure that generation works for all composers whenever a source file changes.

**Comment by Subaro** [comment]
Number 1 is fixed now. The feature project works with a list of all selected features in the current configuration. To do so the complete file was scanned and returned. Because of the changed configuration format, the returned content was wrong. Reading the configuration with the specific file reader and returning the list of all selected features fixed the build behavior for feature-based composers.

**Comment by Subaro** [comment]
Number 3 is also working fine now. Could be related to the changed I did with Paul regarding the generation of markers. But IDK

**Comment by Subaro** [comment]
Number 3 is outsourced into issue #826
