### ISSUE TITLE
Feature names incomplete when zooming in the feature diagram

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#795]
![image2](https://user-images.githubusercontent.com/5330357/42992845-100b9772-8c0a-11e8-92e5-64229bdd32df.png)

![image](https://user-images.githubusercontent.com/5330357/42992813-f6c7547c-8c09-11e8-961e-10827860f93f.png)

Thanks to Don Batory for the report.

**Comment by Subaro** [comment]
Sadly the zooming and the scaling is part of eclipse. We could provide more space in advance to prevent the incompletes names.

**Comment by tthuem** [comment]
Sounds like a reasonable workaround.

**Comment by tthuem** [comment]
Could you add screenshots here for different zoom levels? Would be good to document here how it is supposed to look like.
