### ISSUE TITLE
The selection in the project explorer is broken when using the java perspective

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#800]
In the Package Explorer, the selection is completely broken. Selecting an element is not possible, because the selection jumps to another object. Mostly the latest used element. 

Reproduce:
1. Create a new project (we took FeatureHouse)
2. Switch to Java Perspective
3. Right-click 'Base' folder and select 'New -> Class'
4. Instead of creating the class in the 'Base' folder it is created in the 'src' folder. Additionally, the focus issue appears.

Sometimes only step 1 & 2 are needed. After switching to the FeatureIDE perspective the issue still persists.

**Comment by tthuem** [comment]
Please check whether this can still be reproduced.

**Comment by PaulWestphal** [comment]
This was an eclipse proton bug, it's fixed with eclipse 2018-09.
