### ISSUE TITLE
Automatically adjust FM to editor size when opening if no layout information is available

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#809]
Now that the automatic collapsing (i.e., adjusting to editor size) works (cf. #621), we can use that function if no layout information is available when opening a feature model. This happens in various cases. For instance, when creating a new feature model (but then it is typically small enough to display) but also when exporting a feature model or when sending a feature model to someone else (when not including the whole project).

**Comment by PaulWestphal** [comment]
I removed this functionality because it no longer worked correctly (adjusted model to editor size every time a model was opened).

The old implementation relied on the model.xml.xml file, which is no longer being used.
