### ISSUE TITLE
Team 1 "Legend and Collapsing" (Team Project in Braunschweig 2018)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#810]
Tentative tasks for Team 1 "Legend and Collapsing"

* Legend should avoid mentioning abstract/concrete if all features have that property #603
* Legend should only show entries for visible (not collapsed) model elements #784
* Unintentional group type change on collapsed features #806
* Search for features should work for substrings and collapsed features #787
* Layouting of legend should incorporate boxes for collapsed features #660
* Boxes for collapsed features are crossed by feature connections #659
* Automatically adjust FM to editor size when opening if no layout information is available #809

Related tasks

* Quickfix for unused concrete features / used abstract features #699

**Comment by tthuem** [comment]
This project will be implemented by Ajeeth Kularajan, Insansa Michel, Lennart Kontny, Malek Badeer

**Comment by Indycate** [comment]
https://github.com/Indycate/FeatureIDE/tree/tubs18-team1

**Comment by tthuem** [comment]
The screencast is available online https://youtu.be/lfdJTSZI0-Q

**Comment by PaulWestphal** [comment]
#603 the legend correctly hides "abstract", "concrete" and "hidden" when those elements are collapsed. However "intermediate hidden" and the group types still show up.

**Comment by PaulWestphal** [comment]
#660 the boxes of collapsed features are incorporated for legend layouting, but only if you click an additional time after collapsing a feature. It seems like the legend is layouted _before_ the collapsed boxes are created.

**Comment by PaulWestphal** [comment]
#659 Boxes for collapsed features are still crossed by feature connections. I'm not sure why we accepted this in the first place, maybe it works in Linux, but not in Windows?
