### ISSUE TITLE
Team 3 "View for Constraints" (Team Project in Braunschweig 2018)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#812]
Tentative tasks for Team 3 "View for Constraints"

* Create a new view showing a table with all cross-tree constraints and their descriptions (part of #737)
* Add the view to the FeatureIDE perspective (part of #737)
* Let the view show only constraints that contain at least one (or all?) of the feature selected in the feature diagram (part of #737 and #178)
* Implement a free text filter to show only constraints that contain the search string in formula or description (part of #737 and #178)
* Respond to changes of the active editor and changes in the feature diagram (part of #737)
* Let users edit constraints with the same dialog as in the feature diagram (part of #737)
* Hide constraints in the diagram if the view is visible (part of #737)

Related tasks

*  Autocompletion in constraint dialog for features starting with " #781

**Comment by oliviia12** [comment]
https://github.com/oliviia12/FeatureIDE

**Comment by tthuem** [comment]
This project will be implemented by Domenik Eichhorn, Kamil Rosiak, Rahel Arens, Thomas Graave

**Comment by tthuem** [comment]
Further tasks that could be useful for users:
* Selection of a constraint should highlight the features in the feature diagram (as possible without the view).
* Explanations for dead features, false-optional features, void feature models, and redundant constraints should work as without the view.
* Hotkeys for all operations on constraints. Ideally, it would be possible to filter and remove constraints without using the mouse at all.
* Ask users whether they want to open the view if they open a feature diagram (and the view is closed).
* Add icons/buttons to the top of the view for context menu entries, such as whether collapsed constraints are shown.
* Allow reordering of constraints by means of drag and drop. How to handle drag and drop if only a subset of all constraints is shown? - alternatively - Enable sorting of the constraints based on different criteria.

**Comment by ksmallros** [comment]
> Ask users whether they want to open the view if they open a feature diagram (and the view is closed).

When implementing this it would probably be a good idea to add allow the user to check a "Do not show this windows again" option.
Is there a global properties file we can use for this? If not should we rather implement our own properties file or save this option per project in already existing configs?

**Comment by tthuem** [comment]
@skrieter Could you comment on the questions raised above?

**Comment by skrieter** [comment]
For this, you can use the class de.ovgu.featureide.fm.core.Preferences and the corresponding de.ovgu.featureide.fm.ui.preferences.FeatureIDEPreferencePage.

**Comment by tthuem** [comment]
The screencast is available on online: https://youtu.be/HTtfu5MevPU

**Comment by tthuem** [comment]
An open issue is that the preferences right now have only one boolean option deactivating or activating the dialog, but there should be two options: one for the dialog and one for the choice done in the dialog.

**Comment by PaulWestphal** [comment]
Additional enhancement for the future:

https://github.com/FeatureIDE/FeatureIDE/issues/849

**Comment by PaulWestphal** [comment]
b2b590028cb8a3e16e24432914dbf7d5c8cb521a

Preferences now have two booleans. One for activating the popup when starting FeatureIDE and one for opening the Constraint View when starting FeatureIDE.
