### ISSUE TITLE
vanishing connections when clicking the "show collapsed constraints" button

### ISSUE THREAD

**Issue by oliviia12** [FeatureIDE/FeatureIDE#821]
When a feature model is open and the button "show collapsed constraints" (right click in feature model > show collapsed constraints) is clicked, some connections between the features vanish.
When you collapse the features and and open them again, the connections are visible again.

**Comment by PaulWestphal** [comment]
The same problem occurs with "show hidden features".

**Comment by tthuem** [comment]
I understood that this happens on branch develop. Does it happen on release3.5 too? If so, we should fix it there.

**Comment by koalamitice** [comment]
just tested it on release 3.5 and it seems to work there :)

**Comment by Subaro** [comment]
Tested again on release 3.5 and it worked.
