### ISSUE TITLE
Connection is not displayed when creating a new feature with the "Create Feature Above" action in horizontal layouts.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#822]
After making another change to the Feature Model, it is rendered correctly.

**Comment by PaulWestphal** [comment]
May be related to #821

**Comment by Subaro** [comment]
@PaulWestphal 
I tested all layouts and it seems fine. Can you reproduce the issue and provide more information on how to do so?

**Comment by Subaro** [comment]
@PaulWestphal Thanks. Now it does appear. Kinda strange because the layout should not mess with the connections :/

**Comment by Subaro** [comment]
@PaulWestphal hmm I just tested again and now it seems to work fine. Could you test again?
