### ISSUE TITLE
When trying to edit or create a Constraint when the FeatureModel is void there is an error occurring with the Constraint Dialog.

### ISSUE THREAD

**Issue by oliviia12** [FeatureIDE/FeatureIDE#823]
![screenshot from 2018-09-28 16-20-11](https://user-images.githubusercontent.com/43337532/46214227-f2926500-c33a-11e8-963d-287ae31c0fb1.png)

**Comment by tthuem** [comment]
Thanks for the report.

**Comment by Subaro** [comment]
An identical but different error also appears when saving a void feature model. 
The actuator is also "Creating Empty clause?". Occurs while the configurations are checked and if the model is void.

**Comment by Subaro** [comment]
@skrieter 

I created a small examples regarding this problem. 
<img width="370" alt="home and professtional" src="https://user-images.githubusercontent.com/6231523/47073700-26093680-d1f9-11e8-8823-a25b3af031a9.PNG">

The CNF is as followed:
```(Test) & (Test | -Base) & (Base | -Test) & (-Base)```

When adding the last clause `-Base` to the solver it throws a contradiction exception.

Now I catch the ContradictionException and imply that the feature model is void. 

Now the error does not longer appear and the constraint editor works as intended.
<img width="247" alt="home and professtional" src="https://user-images.githubusercontent.com/6231523/47074056-e4c55680-d1f9-11e8-91ae-5f077ce2c922.PNG">

**Comment by Subaro** [comment]
Sames goes for the error appearing when checking configurations while the feature model is void.
