### ISSUE TITLE
Endless building the workspace job for Eclipse Photon

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#826]
#### Prerequisitives
* **Eclipse Version:**  `Photon`
* **FeatureIDE-Version:**  `release3.5`
* **Operating system:** `Win10`
* **Java runtime used to run eclipse:** `1.8`

### Issue description
When editing the feature model and saving the changes the job named "building workspace" is started. Unfortunately, the job never terminates and cannot be canceled leading to severe usability problems.

It seems that the problem is occurring for all composers. We got some reports describing the same behavior. 

### Workaround
It is possible to not use the Photon release.

### Reproduce
1. Import HelloWorld example for the framework composer.
2. Change model and save.

### Result
![](https://user-images.githubusercontent.com/6231523/42734434-0bbbe538-8844-11e8-87fe-39a4405e170e.PNG)

**Comment by tthuem** [comment]
A question whether this is fixed by new Eclipse version.

**Comment by PaulWestphal** [comment]
I've just tested every composer with eclipse 2019-03.

Framework and AspectJ seem to still have this problem. The other composers work.

**Comment by SundermannC** [comment]
The endless loop could be prevented by changing the build type to CLEAN_BUILD. The previous type FULL_BUILD caused the build manager to restart the building process each time. For now, we tolerate potential additional effort to build a CLEAN_BUILD.
