### ISSUE TITLE
Dirty flag does not disappear after a single save in the Source tab of the Feature Diagram Editor.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#828]
This currently happens on the develop branch. (and only on the develop branch, not in release3.5)

1. Make any change in the Feature Diagram Editor and hit save.

The changes are applied to the .xml file on the first save. However, you need to save again to get the dirty flag to disappear.

**Comment by Subaro** [comment]
@PaulWestphal could you provide more information. I imported the antenna example and changed something in the source tab. After pressing save the feature model saved accordingly and the dirty flag disappeared. Tested on release3.5.

You wrote that it appeared on the develop branch. Maybe it only happens on develop. Then we should modify the milestone.

**Comment by PaulWestphal** [comment]
This used to happen all the time, but I can't reproduce it anymore.

**Comment by tthuem** [comment]
I've seen this again on release 3.5 branch for commit https://github.com/FeatureIDE/FeatureIDE/commit/2e06190ff2ea8c380d4f386048522e1619d43c3f. It is seldom, but it still happens from time to time. I've seen this after making changes to the source tab.
