### ISSUE TITLE
Feature models cannot be opened again after restarting Eclipse

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#833]
Seems that we are too restrictive when loading feature models now. Cannot work with numerous models for that reasons. For example, if the first character of the name is a number in an extended feature model, the feature diagram cannot be opened anymore.

**Comment by Subaro** [comment]
@tthuem Could you send me the corrupted feature model via E-Mail?

I could not reproduce the issue on the newest release3.5. It worked fine with features starting with numerical characters.

**Comment by tthuem** [comment]
Indeed it only seems to happen in some weird situations, such that simply sending the model probably does not help. It happens reproducible when I create a FeatureIDE project in the first Eclipse instance (with 3.5.2 installed) and import that project into the second instances workspace (current release3.5 branch). A reason then could be that the feature model is not in the path of the workspace.

However, I also found cases where a project was created in a workspace and also has this problem. Still struggling to find out why. So far, I found nothing special within the feature models and within the FeatureIDE projects. Hence, it could be some sort of settings file in the workspace or so.

**Comment by tthuem** [comment]
Steps to reproduce: Create an extended feature modeling project. Rename feature Base into 1Base. Restart Eclipse and try to open the feature diagram.

For newly created projects you can correctly manipulate names. However, once Eclipse is restarted is only permits valid Java identifiers.

**Comment by tthuem** [comment]
Found out that this also happens to standard feature models.

There is also a problem that sliced feature models cannot be opened at all as they introduce names not supported anymore.

**Comment by tthuem** [comment]
@Subaro When can you investigate this issue? I'm considering to wait for the next release for this to be fixed.

**Comment by Subaro** [comment]
@tthuem 
Still can't reproduce for standard feature models. We will discuss this issue at the meeting.

**Comment by Subaro** [comment]
We concluded that the slicing process generates invalid names for some composers. Therefore, we rename the features introduced by the slicing process from "__root__" to "root" and "__abstract__" to "abstract"
