### ISSUE TITLE
Focus on all anomalies in a feature model

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#834]
We have a menu entry to focus on an explanation or a single constraint. In this case, all parts of the feature diagram not relevant are collapsed automatically.

Would be great to have something similar for: all dead features, all false-optional features, all redundant constraints, or all anomalies alltogether. These four options could be entries in a submenu.

**Comment by tthuem** [comment]
Similarly, it would be great to show not only a single explanation, but to show all explanations alltogether on demand and focus on those. Here, a constraint causing numerous anomalies would be easily visible.

**Comment by bjthehun** [comment]
When Automated Calculations are disabled for the Feature Model, and no manually calculated analysis results are available (i.e. what features are dead), should those options still be active, and trigger the required Feature Model Analyses then?

**Comment by bjthehun** [comment]
Also, constraints cannot be collapsed, so the entry for redundant constraints should expand the features they contain, right?

**Comment by SundermannC** [comment]
> When Automated Calculations are disabled for the Feature Model, and no manually calculated analysis results are available (i.e. what features are dead), should those options still be active, and trigger the required Feature Model Analyses then?

I think its more intuitive to compute the results in this case just as you suggested.

> Also, constraints cannot be collapsed, so the entry for redundant constraints should expand the features they contain, right?

Yes, the features should be expanded in this case.

**Comment by bjthehun** [comment]
> Similarly, it would be great to show not only a single explanation, but to show all explanations all together on demand and focus on those. Here, a constraint causing numerous anomalies would be easily visible.

Perhaps it might be useful to show all anomalies whenever the user selects the root feature, in addition to an action that focuses on them (ans shows them, too). Also, instead of listing the single explanations with their reasons, one could also list the reasons and then the explanations they are part of, i.e.:
```
Constraint A => B is involved in these anomalies:
* Anomaly 1
* Anomaly 2
* ...
Child Relation C => B is involved in these anomalies:
...
```
Would that make sense?
