### ISSUE TITLE
Integrate extended configuration and computation of attribute ranges into develop

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#835]
As far as I know, this is currently only available on the FeatureModel_Attributes branch (see #255 for more details).

**Comment by Subaro** [comment]
The FMOutline for (extended) configuration is now merged into develop.

**Comment by cpwnd** [comment]
Hi, are the configurable attributes already usable via the user interface (configuration editor)?
I don't see it in my local version of FeatureIDE 3.6.2 and 3.7 either. Also I made sure using the ExtendedFeatureModel-Format and ExtendedXML.

Specifically I expect the xml in the source tab to contain the configured attribute values, which I put in via configuration or extended configuration view with the feature attributes tab open below it.

I can give you my steps to reproduce it, if needed.

Also the [wiki] states it's still only usable with a special branch.

[wiki]: https://github.com/FeatureIDE/FeatureIDE/wiki/Feature%20Attributes#24-configurable-attributes-and-extended-configurations
