### ISSUE TITLE
ExtendedFeatureModel performance of attribute view, especially when values are changed

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#837]
#### Prerequisitives
* **Eclipse Version:**  `4.7.3.a`
* **FeatureIDE-Version:**  `3.5.2`
* **Operating system:** `Win 7 64`
* **Java runtime used to run eclipse:** `Build 1.8.0_161-b12`

### Issue description

When creating or changing feature attributes within the feature attribute view, every time a change of a field is made (e.g. attribute name, attribute value), the view refreshes its contents and therefore is blocked for further interaction. It surely depends on the model and the machine, but when using models with a decent size (>800 features) it takes >10s on my machine (i5 6300 2,4GHz, 8gb ram).

Maybe the feature attribute view is only refreshed/validated, when the model is saved. So a user can make all inputs without a blocked view and when finished save the model file and trigger the validation (the ui blocking operation).

However I don't think this is in any sense urgent (at least for me), but would improve the usability of the attribute view.

**Comment by tthuem** [comment]
Refreshing the attribute view only when the model is saved is counter intuitive. We should nevertheless inspect what is the source of the performance problems and whether there is a connection to the attributes view or extended feature models.

**Comment by Subaro** [comment]
We slightly reworked the FeatureAttributeView to display the attributes more efficiently and to reduce the amount of effort required to refresh the attributes. Changes to attributes and their creation should now proceed instantaneously. The changes are not directly referenced to this issue, thus, I will close the issue manually
