### ISSUE TITLE
Drop-down menu for boolean attributes in the FeatureAttributeView

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#847]
In the FeatureAttributeView it is possible to manage boolean attributes. To set their values you need to type exactly "false" or "true" to set their value. A drop-down menu or checkbox would increase the usability a lot.

**Comment by tthuem** [comment]
The problem of a checkbox is that the value undefined is not possible anymore (unless we find a checkbox supporting three values). This could be problematic especially for recursive attributes that are supposed to be undefined for subfeatures on creation.

**Comment by Subaro** [comment]
Result:
![grafik](https://user-images.githubusercontent.com/6231523/51112506-c837bb00-17f6-11e9-8953-0ce9ba468b16.png)
