### ISSUE TITLE
FeatureIDE cannot be compiled with Eclipse 2018-12 due to access to internal API

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#852]
#### Prerequisitives
* **Eclipse Version:**  Eclipse Committers 2018-12
* **FeatureIDE-Version:**  Release Branch 3.5
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 172/201
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/2e06190ff2ea8c380d4f386048522e1619d43c3f
* **Java compiler used to build the FeatureIDE plugin:** Java 8 Update 172/201

### Issue description
![image](https://user-images.githubusercontent.com/5330357/51598919-d1174380-1efe-11e9-93b4-55cc0a81a15b.png)

**Comment by alkalinan** [comment]
I had the same problem, my solution was to change the severity in Eclipse from _Error_ if _Forbidden restriction_  to _Warning_. (see picture below from the proprieties windows of the plugin)
![capture d ecran 2019-01-23 a 11 46 07](https://user-images.githubusercontent.com/19858911/51601390-7bde3080-1f04-11e9-9cb5-d2537135407e.png)

**Comment by tthuem** [comment]
@alkalinan Thanks, good to know!

**Comment by tthuem** [comment]
Just tested and it does compile with Eclipse 2018-09 and probably also earlier versions.

**Comment by Subaro** [comment]
Eclipse assumes that CompilationUnitEditor is not part of the public API. The message was only a warning before. With the new eclipse version, they switched to an error. 

Another way to fix is to add an access-rule to the project and allowing us to use the class without an error message.

**Comment by Subaro** [comment]
As we decided, I created an access rule for the CompilationUnitEditor. Now we don't have any more problems using/compiling FeatureIDE within newer Eclipse versions.
