### ISSUE TITLE
The attributes view does not show newly created attributes

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#853]
#### Prerequisitives
* **Eclipse Version:**  2018-09
* **FeatureIDE-Version:**  release 3.5 branch
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** JDK8
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/2e06190ff2ea8c380d4f386048522e1619d43c3f
* **Java compiler used to build the FeatureIDE plugin:** JDK8

### Issue description
When adding feature attributes, nothing happens in the feature attributes view. They seem to be created in background but the view does not show them.

**Comment by tthuem** [comment]
Furthermore, removing an attribute uncollapses all entries in the view.

**Comment by tthuem** [comment]
The fix is reverted? Is it fixed then?

**Comment by Subaro** [comment]
Yeah, I accidentally pushed to develop first. Therefore, I reverted and committed to release3.5. After that, I merged to develop. It is fixed. The merged commit wasn`t referenced as we can see.
