### ISSUE TITLE
Inefficient encoding of recursive feature attributes in XML format

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#855]
#### Prerequisitives
* **Eclipse Version:**  2018-09
* **FeatureIDE-Version:**  release 3.5 branch
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** JDK8
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/2e06190ff2ea8c380d4f386048522e1619d43c3f
* **Java compiler used to build the FeatureIDE plugin:** JDK8

### Issue description
The storage consumed for recursive attributes is considerable. When an recursive attributes is added to the root of a feature model, the same line is added to each feature (i.e., potentially thousand times).

```        <and mandatory="true" name="A">
            <attribute name="X" recursive="true" type="long" unit="sec"/>
            <attribute name="Y" recursive="true" type="long" unit=""/>
            <attribute name="Z" recursive="true" configurable="true" type="long" unit=""/>
            <alt mandatory="true" name="B">
                <attribute name="X" recursive="true" type="long" unit="sec"/>
                <attribute name="Y" recursive="true" type="long" unit="" value="2"/>
                <attribute name="Z" recursive="true" configurable="true" type="long" unit=""/>
```

1. The signature of the attribute does only need to be stored once, which includes the tags recursive, configurable, type and unit.
2. As recursive and configurable, unit should have a default value that is not stored (i.e., the empty string).
3. The whole line containing the attribute only makes sense if the value is different from null.

So the example above would be simplified to:

```
        <and mandatory="true" name="A">
            <attribute name="X" recursive="true" type="long" unit="sec"/>
            <attribute name="Y" recursive="true" type="long"/>
            <attribute name="Z" recursive="true" configurable="true" type="long"/>
            <alt mandatory="true" name="B">
                <attribute name="Y" value="2"/>
```

This also helps to avoid inconsistencies. Imagine I would like to change the type or unit of an recursive attribute in XML for a large feature model. This is rather impossible.

**Comment by tthuem** [comment]
For this change, please make sure that old models can still be opened. So parsing a model that contains more information should be no problem at all.

**Comment by tthuem** [comment]
By the way, when adding value="" in an inherited attribute, the attribute simply disappears and is never restored. That is, even though the attribute is supposed to be recursive, it is easy to introduce inconsistencies, in which some of the subfeatures do not have the attribute. The implementation should also be more robust against those inconsistencies when fewer data is stored.

**Comment by tthuem** [comment]
An open question is still what to do when the property recursive is deactivated. I guess the user should be warned that this will automatically remove all inherited attributes and their values in subfeatures. The current handling makes it hard to remove recursive attributes as it needs to be removed in every feature in which a value has been defined.

**Comment by SundermannC** [comment]
Removed redundant properties of recursive features. The xml elements of recursive attributes now look like this:
```
                    <attribute name="X" value="313"/>
                    <attribute name="Y" value="1.79"/>
                    <attribute name="Z" value="false"/>
```
If no value was defined for a recursive attribute, the entry in the xml-file is omitted.

**Comment by SundermannC** [comment]
The old  XML-format is still readable, but saving the feature model will change the format to the new one.
