### ISSUE TITLE
Show colors assigned to features in attributes view

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#857]
Currently, colors assigned to features in the feature diagram are ignored in the attributes view (i.e., not yet supported). Furthermore, the green background color is confusing.

![image](https://user-images.githubusercontent.com/5330357/52114847-6dcb9680-260d-11e9-9a9e-32d2af25c93b.png)

**Comment by tthuem** [comment]
A related improvement would be if the attributes view shows attributes even if the selection in the feature diagram contains elements that are not features (e.g., legend or constraints). It could simply ignore every selection not being a feature.

**Comment by Subaro** [comment]
As we discussed before, we only show the currently selected features in the diagram editor. Additionally, I already removed the green and gray background. It currently looks like this:

![grafik](https://user-images.githubusercontent.com/6231523/64601483-8c1c2080-d3ac-11e9-9ff2-6b97ed6cbe14.png)

**Comment by Subaro** [comment]
I also implemented the behaviour that elements selected besides features, like connection, are omitted in the feature attribute view. This allows the user to show the attributes of all features by pressing STRG+A in the diagramm editor. 

Example:

![grafik](https://user-images.githubusercontent.com/6231523/64602112-b02c3180-d3ad-11e9-8264-7406ffa81e75.png)
