### ISSUE TITLE
Changes to the constraints of a cloned feature model also are also applied to the original one

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#859]
#### Prerequisitives
* **Eclipse Version:**  `Eclipse Photon`
* **FeatureIDE-Version:**  `release 3.5 branch`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `JDK8`

### Issue description
After renaming a feature in a cloned feature model that contains constraints. The new name is also applied to constraints of the original. The original feature keeps the old name. 

Setup:
- Feature model with constraints

Reproduce error:
1. Create a clone of the model : IFeatureModel issueCopy = featureModel.clone();
2. Change the name of a feature that appears in a constraint: 
		for (String oldName : issueCopy.getFeatureOrderList()) {
			issueCopy.getRenamingsManager().renameFeature(oldName, "Copy_" + oldName);
		}

Expected Result:
- No changes are applied to the orignal feature Model
- Features are renamed in the copy

Actual Result:
- Expected results for the copy
- Feature names are changed (only) within constraints for the original
- Original model is not legal

**Comment by SundermannC** [comment]
#860

**Comment by tthuem** [comment]
Merged the pull request.
