### ISSUE TITLE
Missing horizontal scrollbar in configuration map

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#861]
#### Prerequisitives
* **Eclipse Version:**  `Eclipse Photon`
* **FeatureIDE-Version:**  `Release 3.5 Branch`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `JDK8`

### Issue description
The configuration map cannot be scrolled horizontally.
It is not possible to see configurations that exceed the screen in the configuration map.

**Comment by Subaro** [comment]
Now it is possible to scroll the complete view horizontally to show the columns for the different configurations and to scroll the tree vertically to show the selection of the respective feature without scrolling the headers. Result:

<img width="150" alt="Unbekannt" src="https://user-images.githubusercontent.com/6231523/56576276-7356ce00-65b7-11e9-9e1b-7df9cb15a965.PNG">
