### ISSUE TITLE
Feature attribute view shows nothing if a non-feature is included in the selection

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#862]
#### Prerequisitives
* **Eclipse Version:**  `Eclipse Photon`
* **FeatureIDE-Version:**  `Release 3.5 branch`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `JDK8`

### Issue description
Current behavior:
- If a non-feature (Constraint/Legend) is part of a selection, the attribute view does not show the selected features

This is inconvenient when it is necessary to select all features of a large model. 

Desired behavior:
- Ignore elements that are no features in the selection instead of ignoring the entire selection

**Comment by tthuem** [comment]
I mentioned this already in #857.

**Comment by Subaro** [comment]
Fixed with #857
