### ISSUE TITLE
Advanced Filters for Configuration Map

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#867]
The configuration map can filter out certain features. It would be great if it would also be possible to hide all features being selected in all configurations or being deselected in all configurations. That would help when comparing configurations with each other for large configuration spaces (i.e., many features or many predefined configurations).

![image](https://user-images.githubusercontent.com/5330357/53574620-3a2e4e80-3b70-11e9-9cad-29545eab8f06.png)

**Comment by Subaro** [comment]
<img width="500" alt="1" src="https://user-images.githubusercontent.com/6231523/58867743-8a0a3d80-86aa-11e9-8b14-02c499ae78d8.PNG">


<img width="500" alt="2" src="https://user-images.githubusercontent.com/6231523/58867757-8e365b00-86aa-11e9-9f30-0bb1ed15febf.PNG">
