### ISSUE TITLE
Constraints view updated multiple times when opening a feature model

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#874]
#### Prerequisitives
* **Eclipse Version:** 2019-03
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8
* **Git branch/Commit-ID:**  develop 52970006e188ae37e494688ddd1740edbe54b788
* **Java compiler used to build the FeatureIDE plugin:** Java 8

### Issue description
When opening a large feature model, the constraints view is filled with constraints multiple times. I recognized this by the scrollbar which it larger, shrink, getting larger, shrinks... The constraint view seems to be updated when there are changes in the feature diagram representation even though it is independent of those changes.

For reproduction, take a large feature model (e.g., FinancialServices01) and copy model.xml into a new file. Then open the constraints view and then the copied model. You may even try to expand all features once they have been automatically collapsed and reopen it again. I counted that the constraint view is updated 5 times before the diagram is opened and 10 times afterwards.

Also, I'm not quite sure why simply showing the constraints (i.e., a single update) takes so long. It seems that the view is updated after every constraint (otherwise the scrollbar would probably not be updated all the time).

**Comment by PaulWestphal** [comment]
related: dd7af6e31026d2c94a4c74085a39c8373d06a5c6
