### ISSUE TITLE
"Show Hidden Dependencies of Submodel" action is missing in the feature diagram

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#875]
#### Prerequisitives
* **Eclipse Version:** 2019-03
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8
* **Git branch/Commit-ID:**  develop 52970006e188ae37e494688ddd1740edbe54b788 as well as release 3.5.4
* **Java compiler used to build the FeatureIDE plugin:** Java 8

### Issue description
The action was opening a window showing a sliced feature model and emphasizing implicit constraints. It is likely that this functionality disappeared as of release 3.5.0, but not sure when exactly. Even though

**Comment by tthuem** [comment]
@PaulWestphal Can you investigate this?

**Comment by PaulWestphal** [comment]
It was accidentally removed in this commit: 32e3c8b09139f06a9028b0557ad24eb0886f5a79

Now it's back. I double-checked and it was the only action that was accidentally removed in that change.
