### ISSUE TITLE
Runtime error loading extended feature models

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#876]
#### Prerequisitives
* **FeatureIDE-Version:**  3.5.4

### Issue description
I am using the standalone libs to load an extended feature model. Lets say that content is a String with the Sandwich model.xml content, and then I do

`		IFeatureModel featureModel = new ExtendedFeatureModel(ExtendedFeatureModelFactory.ID);
		FileHandler.loadFromString(content, featureModel, new XmlExtendedFeatureModelFormat());`

I get 
`java.lang.ClassCastException: de.ovgu.featureide.fm.core.base.impl.ExtendedFeature cannot be cast to de.ovgu.featureide.fm.attributes.base.impl.ExtendedFeature
	at de.ovgu.featureide.fm.attributes.format.XmlExtendedFeatureModelFormat.parseFeatures(XmlExtendedFeatureModelFormat.java:593)`

Having ExtendedFeature and ExtendedFeatureModel in both standalone jars is weird. I have both in the classpath. What I am doing wrong? Thanks!

**Comment by tthuem** [comment]
@PaulWestphal @Subaro Who can help here?

**Comment by jabiercoding** [comment]
I do not understand why ExtendedFeature, ExtendedFeatureModel and ExtendedFeatureModelFactory are present in both jars... Anyway, maybe the fix is changing 

`de.ovgu.featureide.fm.attributes.base.impl.ExtendedFeatureModel`
and make public this constructor that is currently protected?

`protected ExtendedFeatureModel(String factoryID)`

**Comment by jabiercoding** [comment]
I tried to export a jar with the change from protected to public and using it, but I have the same casting exception...

**Comment by Subaro** [comment]
@jabiercoding Hello, at first there exists an old an a new implementation for extended feature models. The old implementation is in package `de.ovgu.featureide.fm.core` and the new is inside the package `de.ovgu.featureide.fm.attributes`. 

In your example:
`IFeatureModel featureModel = new ExtendedFeatureModel(ExtendedFeatureModelFactory.ID);
 FileHandler.loadFromString(content, featureModel, new XmlExtendedFeatureModelFormat());`
I assume that you import the ExtendedFeatureModel and the ExtendedFeatureModelFactory from the core package. In the second line you use the format of the attributes package to load an extended feature model from the attributes implementation. 

To use the extended feature model with the attributes view you just need to import both classes from the attributes package. I will discuss the ambiguous names for the different implementation with the rest of the team. Hope I could help :)

**Comment by jabiercoding** [comment]
@Subaro As I mentioned, if I import the ExtendedFeatureModel from the attributes package, the constructor is protected de.ovgu.featureide.fm.attributes.base.impl.ExtendedFeatureModel.ExtendedFeatureModel(String) so I cannot create an instance from my external program. So maybe you need to change from protected to public. But even if you change this, you can check that we still have the mentioned casting exception when trying with Sandwich model.xml

**Comment by tthuem** [comment]
@skrieter is planning to rename the format into MultiFeatureModel to avoid confusion with extended feature models having attributes.

**Comment by skrieter** [comment]
Fixed.
