### ISSUE TITLE
Quickfix for Never-Selected features doesn't work.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#878]
I noticed this while testing the tutorial on the release3.5 branch using Photon June 2018.

How to reproduce:

1. load example Elevator-Antenna-v1.1

2. Create a new configuration called Professional via menu File > New > Configuration File

3. Select the features FIFO, DirectedCall, and FloorPermission; save and close the editor

4. Open feature model; use context menu to change group type below feature Modes to an alternative; save the model

5. Open the invalid configuration Professional; deselect feature FIFO; save the configuration

6. Problem view indicates never-selected features; try to use Quick Fix in context menu to create  configuration with feature Sabbath;

**Comment by Subaro** [comment]
@PaulWestphal I just tested it on Eclipse2018_12 and it worked without any problems. With QuickFix a new configuration named `Configuration0` was created and only the feature Sabbath was selected. The Never-Selected marker disappeared after running the QuickFix.

**Comment by PaulWestphal** [comment]
Oops, I thought you used the quick fix by double-clicking (the way you go to the relevant code for warnings), not by right-clicking and using the context menu. My bad.
