### ISSUE TITLE
Configuration Diagrams doesn't work with selected features from the configuration 

### ISSUE THREAD

**Issue by MuhammadShehzadbhatti** [FeatureIDE/FeatureIDE#884]
#### Prerequisitives
* **eclipse4.9.0:**  `Add text here (needed for best issue handling)`
* **committers-featureide3.5.4:**  `Add text here (needed for best issue handling)`
* **-win64:** `Add text here (needed for best issue handling)`
* **JDK 1.8.0:** `Add text here (needed for best issue handling)`
* **AHEAD:** `Add text here (optional, leave blank if not needed)`
* **master/3812ebc :**  `Add text here (optional, leave blank if not needed)`
* **Java compiler used to build the FeatureIDE plugin:** `Add text here (optional, leave blank if not needed)`

### Issue description
I am working on Graph Product Line to evaluate the composers. My first goal is to evaluate AHEAD composer. I have facing problem in feature collaboration diagram that is not viewing under feature collaboration diagram, but as I open a jak file then it shows its configuration file name but here I need all selected features collaboration diagram that I selected in config, unfortunately, it doesn't show, but it shows all feature collaborations of all unselected features. Moreover, I think it could be an issue relates to eclipse version that I have downloaded with the whole package from FeatureIDE.GitHub

**Comment by tthuem** [comment]
@PaulWestphal Can you have a look? If you have a fix soon, we could also add this to release 3.5.5. Let me know.

**Comment by PaulWestphal** [comment]
The CollaborationModelBuilder was not updated to properly scan the new configuration file format.
