### ISSUE TITLE
Configuration Diagrams doesn't work with selected features from the configuration 

### ISSUE THREAD

**Issue by MuhammadShehzadbhatti** [FeatureIDE/FeatureIDE#885]
#### Prerequisitives
* **eclipse4.9.0:**  
* **committers-featureide3.5.4:** 
* **-win64:** 
* **JDK 1.8.0:** 
* **AHEAD:** 
* **master/3812ebc :**

### Issue description
I am working on Graph Product Line to evaluate the composers. My first goal is to evaluate AHEAD composer. I have facing problem in feature collaboration diagram that is not viewing under feature collaboration diagram, but as I open a jak file then it shows its configuration file name but here I need all selected features collaboration diagram that I selected in config, unfortunately, it doesn't show, but it shows all feature collaborations of all unselected features. Moreover, I think it could be an issue relates to eclipse version that I have downloaded with the whole package from FeatureIDE.GitHub

**Comment by tthuem** [comment]
Duplication to #884
