### ISSUE TITLE
Make long descriptions with linebreaks readable in Constraint View. 

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#887]
![linebreaks](https://user-images.githubusercontent.com/32126695/59188856-eec90a80-8b78-11e9-82bb-d6480e3251fd.png)

Right now linebreaks are replaced by whitespaces. This is fine to make the View usable with long descriptions, but there should be an option that allows you to read the whole description without having to click the constraint.

This could be achieved by adding an option to show the whole constraint description directly in the View.

There should at least be a popup text showing the whole description when you hover over the constraint description column entries with the cursor.

**Comment by h3ssto** [comment]
Was fixed in #1065.
