### ISSUE TITLE
Runtime Parameters: Eclipse New-Project-Creation Build Error

### ISSUE THREAD

**Issue by gusschwto** [FeatureIDE/FeatureIDE#893]
#### Prerequisitives
* **Eclipse Version:**  2019-06 (4.12.0)
* **FeatureIDE-Version:**  3.5.5.201906282321
* **Operating system:** Microsoft Windows 10 Home Version 10.0.17763 Build 17763
* **Java runtime used to run eclipse:** jdk-12.0.1
* **FeatureIDE Composer:** n.a.
* **Git branch/Commit-ID:**  n.a.
* **Java compiler used to build the FeatureIDE plugin:** n.a.

### Issue description
Hello FeatureIDE team,

**I'm facing the following issue:**
I would like to create a SPL Configuration with Runtime Parameters, based on a "runtime.properties" Files. Creating such a project with the Eclipse build in "new project" functionality causes an "Errors running builder" to me. I'm using for this the above mentioned setup.
I checked some different version of FeatureIDE+Java+Eclipse  to create such an SPL and found that 
- Eclipse-2019-03 with Java 1.8 is working (with above mentioned FeatureIDE version).

Details to what I've done:
    Eclipse -> New -> FeatureIDE Project
    Select Composer="Runtime Parameters" -> Next
    Add any Project name: e.g. "testFeatureIDE" -> Finish
    Error pop-up appears:
![FeatureIDE_Error](https://user-images.githubusercontent.com/50327606/62773278-0b62bf80-baa2-11e9-919e-fd3c47f2e401.png)
Text: "Errors occurred during the build.
Errors running builder 'Extensible Feature Project Builder' on project 'testFeatureIDE'.class de.ovgu.featureide.core.runtime.RuntimeParameters tried to access private method org.eclipse.jdt.internal.corext.callhierarchy.CallHierarchy.<init>()V (de.ovgu.featureide.core.runtime.RuntimeParameters is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7075ef91; org.eclipse.jdt.internal.corext.callhierarchy.CallHierarchy is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @4f4b7a2e)"

I can ignore the problem and work with FeatureIDE, but as soon as I save the error appears again.

I've seen that in Git you've a FeatureIDE version 3.6 available. Currently this one is missing to me in the Eclipse archive:
![2019-08-09_11h38_46](https://user-images.githubusercontent.com/50327606/62773665-05211300-baa3-11e9-9a80-43af8a770b3f.png)

Thanks and best regards

**Comment by tthuem** [comment]
@PaulWestphal Can you please try to reproduce this bug with Eclipse 2019-06 and FeatureIDE 3.5.5.201906282321. If you can reproduce it, it would be nice to check whether this is fixed on release 3.6 branch.

**Comment by tthuem** [comment]
@gusschwto FeatureIDE 3.6 has not been released yet, but is likely to be released soon.

**Comment by PaulWestphal** [comment]
The bug is reproducible with Eclipse 2019-06 and FeatureIDE 3.5.5, but it's fixed on the release 3.6 branch with Eclipse 2019-06.
