### ISSUE TITLE
Runtime Parameters: Generation of runtime.properties into different folder

### ISSUE THREAD

**Issue by gusschwto** [FeatureIDE/FeatureIDE#894]
#### Prerequisitives
-     Eclipse Version: 2019-06 (4.12.0)
-     FeatureIDE-Version: 3.5.5.201906282321
-     Operating system: Microsoft Windows 10 Home Version 10.0.17763 Build 17763
-     Java runtime used to run eclipse: jdk-12.0.1
-     FeatureIDE Composer: n.a.
-     Git branch/Commit-ID: n.a.
-     Java compiler used to build the FeatureIDE plugin: n.a. 

### Issue description
I'm working on an university project where several Java Sub-classes shall be created via FeatureIDE and used inside a bigger Java framework. The FeatureIDE option to create these sub-classes is the Runtime-Parameters (Properties) configuration.
My used Java framework is very strickt with its implementation of the Security-Manager. Therefore the generated product can only access data inside its bin-folder. But, the standard place for the "runtime.properties" is the Eclipse project main folder and can't be accessed therefore. Currently I've to copy this by hand into the /src (copied to /bin while building) or /bin folder directly.

Is there a possibility to configure FeatureIDE in Eclipse in a way, that the file "runtime.properties" is generated into /src or /bin ?

**Comment by Subaro** [comment]
@gusschwto 
The runtime.properties will now also be generated inside the build path of the composer.
