### ISSUE TITLE
Constraints not shown in feature model editor.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#896]
Currently on the release3.6 branch there is a bug which causes constraints not to show up. The only way to reproduce this bug that I have found so far (edit: check my comment below to see how to reproduce the bug) is running any GUI test using the context Elevator-FeatureModeling followed by the GUI test ExplainingAnomaliesInFeatureDiagram which uses the context ElevatorWithAnomalies. 

Elevator-FeatureModeling and ElevatorWithAnomalies are very similar contexts (all same file names). It has three additional constraints "Behavior=>Service", "Service=>Behavior", and "Behavior=>not FloorPriority". These constraints don't show up until you make an edit in the feature model.

It's a very minor bug, but it causes the GUI test ExplainingAnomaliesInFeatureDiagram to fail, which is very annoying.

**Comment by tthuem** [comment]
I assume the new Constraints View is opened in the GUI test? We could close it in the test for now and investigate this problem for release 3.6.1.

@PaulWestphal What do you think?

**Comment by PaulWestphal** [comment]
No, it's closed for all GUI tests. There is no GUI test for the constraint view yet.

**Comment by tthuem** [comment]
OK, please comment out the tests and we'll investigate the issue for v3.6.1.

**Comment by PaulWestphal** [comment]
How to reproduce:

1. Load example HelloWorld-Antenna
2. Create Feature Below "Feature" and save.
3. Delete the project "HelloWorld-Antenna", check the box "Delete project contents on disk"
4. Load example HelloWorld-Antenna again.
5. Open the feature model. "NewFeature1" will be in the top left corner. Also the legend placement will be wrong.

Refreshing the feature model by making any change in it will make the feature model editor work as intended again.
