### ISSUE TITLE
Cross-tree constraints are shown below the feature diagram even if constraints view is open

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#898]
#### Prerequisitives
* **Eclipse Version:**  2019-03
* **FeatureIDE-Version:**  3.6.0
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 201
* **Git branch/Commit-ID:** release 3.6 https://github.com/FeatureIDE/FeatureIDE/commit/04eb097507f6b1634133fd44b6ce3ed7b78c0195

### Issue description
Imported Elevator-Antenna-v1.1 and opened the feature model. The constraints are shown below the diagram even though the constraint view is opened:

![image](https://user-images.githubusercontent.com/5330357/64018018-67fa4d00-cb2b-11e9-916f-9c652c2b8f39.png)

I was able to reproduce this with several models and only activating/deactivating the constraint view seems to help. Then, the constraints disappear in the feature diagram as desired.

**Comment by tthuem** [comment]
The behavior is also correct once the user selects any element in the feature diagram.

**Comment by Subaro** [comment]
The view does not hide the constraint after starting eclipse because it is only executed when the ConstraintsView is changed from hidden to visible. Therefore, an additional check is required when opening a feature diagram editor. Then it works fine.
