### ISSUE TITLE
Implement incremental composer functionality

### ISSUE THREAD

**Issue by fbenduhn** [FeatureIDE/FeatureIDE#9]
case 1 "a file changed":

```
1)move changed file and related selected files into a temporary folder(also create feature folders)
2)remove old composed file
3)perform composition on the files at the temporary folder
```

also: do only change the related FSTClass at the FSTModel

this should work for all composition tools with a feature folder(AHEAD,FH,FC++,Munge)
the compiler will also do an incremental build

case 2 "configuration changed":

```
do only compose effected files
```

**Comment by tthuem** [comment]
@meinicke Not quite sure whether I could follow completely, but do you think this is still useful?

**Comment by tthuem** [comment]
Unlikely to give a large speed-up and there are more time consuming tasks in FeatureIDE.
