### ISSUE TITLE
Runtime Config: New Java file cause Error featureIDE.core.runtime.RuntimeParameters

### ISSUE THREAD

**Issue by gusschwto** [FeatureIDE/FeatureIDE#901]
#### Prerequisitives
* **Eclipse Version:**  2019-06 (4.12.0)
* **FeatureIDE-Version:**    3.6.0.201908302227
* **Operating system:** Microsoft Windows 10 Home Version 1903 Build 18362.295
* **Java runtime used to run eclipse:** jdk-12.0.2
* **FeatureIDE Composer:** n.a.
* **Git branch/Commit-ID:**  n.a.
* **Java compiler used to build the FeatureIDE plugin:** n.a.

### Issue description
After creating a new FeatureIDE project, based on "Runtime Parameters", I want to create a Java class which should contain my Main-function and further actions.
Creating this new Java file cause a FeatureIDE-Error: ... featureIDE.core.runtime.RuntimeParameters ...

Screenshot:
![2019-09-04_21h31_34](https://user-images.githubusercontent.com/50327606/64286770-6fbc5600-cf5e-11e9-8431-ff2a70d0059f.png)

Beside that a similar error is created when I delete the Error Log in Eclipse and save a change in the created file:
![grafik](https://user-images.githubusercontent.com/50327606/64286993-d772a100-cf5e-11e9-97b5-10dc0865905a.png)

**Hint:**
**Eclipse 2019-03** throws also errors while creating a file and deleting the Error Log. But the error message is about "An error has occurred. See error log for more details. java.lang.NullPointerException"
![grafik](https://user-images.githubusercontent.com/50327606/64287280-844d1e00-cf5f-11e9-81ed-4fb34d7aa022.png)

**Comment by PaulWestphal** [comment]
A possible workaround is using eclipse 2018-09, the error doesn't occur there.

**Comment by tthuem** [comment]
@gusschwto Does it work for you with Eclipse 2018-09, too?
