### ISSUE TITLE
Compatibility problems with Eclipse 2019-09

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#908]
Following these steps outlined in the wiki page (https://github.com/FeatureIDE/FeatureIDE/wiki/Preparing-Eclipse) works perfectly fine for eclipse 2018-09.

However, when using Eclipse 2019-09, you get thousands of errors in the following packages:

```
de.ovgu.featureide.core.runtime
de.ovgu.featureide.fm.core
de.ovgu.featureide.fm.ui
de.ovgu.featureide.ui
de.ovgu.featureide.ui.mpl
```

![thousands_of_errors](https://user-images.githubusercontent.com/32126695/66390289-b290a400-e9ca-11e9-8d86-188db0f0dcda.png)

Eclipse 2019-09 seems to be unable to get the bundles specified in the MANIFEST.MF files?

![manifest](https://user-images.githubusercontent.com/32126695/66390654-685bf280-e9cb-11e9-8bae-46b83c0ace78.png)

This is an issue with the release3.6 branch, there are very similar issues with release3.5.

**Comment by PaulWestphal** [comment]
The plugins org.apache.commons.math, org.eclipse.draw2d, and org.eclipse.gef have been removed from the Eclipse for Committers package.

I have not yet found a way to find all of these plugins independently from eclipse, but copy+pasting the .jar files from an eclipse photon plugin folder into the new eclipse version works.

**Comment by tthuem** [comment]
This step is not yet documented in the wiki: https://github.com/FeatureIDE/FeatureIDE/wiki/Eclipse-for-Committers

**Comment by PaulWestphal** [comment]
The wiki tells you to get a prepackaged version of eclipse, which has FeatureIDE installed.
