### ISSUE TITLE
Weird behavior when creating a new project while the constraint view is closed

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#912]
#### Prerequisitives
* **Eclipse Version:** 2019-03
* **Operating system:** Windows 10
* **Git branch/Commit-ID:**  release3.6 https://github.com/FeatureIDE/FeatureIDE/commit/6173d671966b5824f4beff3748b8cb7b1e306dd4

### Issue description
Closed the constraints view and tried to create a new feature modeling project. When pressing finish, there is a popup as for the newly created project the feature model is opened.

Pressing abort seems to do nothing. Pressing no seems to work fine. Pressing yes results in some weird behavior that I first need to press finish again in the project creation wizard and then need to answer the other dialog. Maybe it would help to first close the old dialog before proceed opening the feature model.

**Comment by PaulWestphal** [comment]
We are now at FeatureIDE 3.6.x, isn't it time to remove the message entirely?

**Comment by tthuem** [comment]
When updating an old Eclipse or when the FeatureIDE perspective is not used, this message is still needed.

**Comment by h3ssto** [comment]
The origin of this behavior lies in the way a new project is generated (on press of _Finish_ in the context of the wizard). As part of the creation, the FeatureDiagramViewer is started, launching the "Do you want to open the Constraint View?"-dialog, which then blocks the dispose of the wizard.

**Comment by h3ssto** [comment]
Note to future devs: Do not create ne Shell-Objects, but use `Display.getCurrent().getActiveShell()`. 

Also the wheel has been invented, no need to do it again.
