### ISSUE TITLE
How to execute the code source 

### ISSUE THREAD

**Issue by Maouaheb** [FeatureIDE/FeatureIDE#919]
#### Prerequisitives
* **Eclipse Version:**  `Add text here (needed for best issue handling)`
* **FeatureIDE-Version:**  `Add text here (needed for best issue handling)`
* **Operating system:** `Add text here (needed for best issue handling)`
* **Java runtime used to run eclipse:** `Add text here (needed for best issue handling)`
* **FeatureIDE Composer:** `Add text here (optional, leave blank if not needed)`
* **Git branch/Commit-ID:**  `Add text here (optional, leave blank if not needed)`
* **Java compiler used to build the FeatureIDE plugin:** `Add text here (optional, leave blank if not needed)`

### Issue description
Add text here
 Hi everyone, i am looking for how executing code source on eclipse environment 
Thanks

**Comment by tthuem** [comment]
Here is a how to for installing Eclipse plug-ins: https://www.youtube.com/watch?v=dNc1uJxsJqM

You may also just download the pre-configured Eclipse installations with FeatureIDE installed: https://featureide.github.io/#download

**Comment by Maouaheb** [comment]
Dear Sir,
thank you for your response. However, i am looking for compiling and executing the all source code files of featureIDE in eclipse not to use it as a plugin. Hence i didn't find any information in read me file to guide me for this purpose for example the main class to run, and to compile.
I hope you would help
Thank you so much 
Best regards





Le Mercredi, Novembre 20, 2019 16:54 GMT, Thomas Thüm <notifications@github.com> a écrit:
 
Here is a how to for installing Eclipse plug-ins: https://www.youtube.com/watch?v=dNc1uJxsJqM
You may also just download the pre-configured Eclipse installations with FeatureIDE installed: https://featureide.github.io/#download

**Comment by tthuem** [comment]
Please have a look at our wiki: https://github.com/FeatureIDE/FeatureIDE/wiki/Preparing-Eclipse
