### ISSUE TITLE
"Show Hidden Dependencies of Submodel" throws NullPointerException

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#920]
#### Prerequisitives

Fresh install of https://github.com/FeatureIDE/FeatureIDE/releases/download/v3.6.1/eclipse4.13.0committers-featureide3.6.1-win64.zip on Windows 10. Created a FeatureIDE project `test` with "Feature Modeling" as composer.

### Issue description

In the feature model created by default (with root feature `test` and child `Base`), right clicking `Base` and choosing `Show Hidden Dependencies of Submodel` leads to a NullPointerException ('' has encountered a problem):

![grafik](https://user-images.githubusercontent.com/4258713/69362275-81281b00-0c8e-11ea-9bfb-668663f884e2.png)

**Comment by tthuem** [comment]
I also just encountered this bug:

![image](https://user-images.githubusercontent.com/5330357/69672229-f2edd380-1097-11ea-87c5-8b127acac640.png)

It seems to work with v3.5.5:

![image](https://user-images.githubusercontent.com/5330357/69672336-2fb9ca80-1098-11ea-80c6-82203c10a777.png)

Another bug is that implicit constraints are not highlighted anymore as such (see legend).

**Comment by tthuem** [comment]
Who can check whether this worked with v3.6.0?

**Comment by ekuiter** [comment]
This bug also occurs in v3.6.0. I can confirm it works in v3.5.5.

**Comment by skrieter** [comment]
Bug was introduced in v3.6.0.

**Comment by Subaro** [comment]
Tested and works with the fix.

**Comment by Subaro** [comment]
The NullPointer is fixed. However, the shown submodel does still not show implicit constraints. Also, false-optional and dead features are not marked.

Current result with release3.6:
![grafik](https://user-images.githubusercontent.com/6231523/70439453-f9148480-1a87-11ea-9486-f4bf80450bf2.png)

**Comment by tthuem** [comment]
Created a separate issue for the remaining problem: #946
