### ISSUE TITLE
Feature Model Editor shows Features that don't exist anymore. 

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#921]
This bug currently exists in the release3.6 branch.

1. Load example HelloWorld-Antenna
2. Create Feature Below "Feature" and save.
3. Delete the project "HelloWorld-Antenna", check the box "Delete project contents on disk"
4. Load example HelloWorld-Antenna again.
5. Open the feature model. "NewFeature1" will be in the top left corner. Also the legend placement will be wrong.

Refreshing the feature model by making any change in it will make the feature model editor work as intended again.

**Comment by tthuem** [comment]
@PaulWestphal Please comment why you have closed this issue without linking any commits to it.

**Comment by PaulWestphal** [comment]
because i realized that it was the same bug as this: 

https://github.com/FeatureIDE/FeatureIDE/issues/896
