### ISSUE TITLE
Opening feature models with GUIDSL does not work anymore

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#922]
#### Prerequisitives
* **Eclipse Version:**  see release packages
* **FeatureIDE-Version:**  v3.6.1 and v3.5.5 and v3.4.3 and v3.3.2 and v3.2.0 and v3.1.2 and v3.0.1
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 201

### Issue description
Imported the Car example. Pressing the button does create a model.m file but GUIDSL does not open.

![image](https://user-images.githubusercontent.com/5330357/69660323-5cfa7e80-1080-11ea-9b72-687611e2e271.png)

**Comment by Subaro** [comment]
Could not reproduce on release3.6. When clicking `Open with GUIDSL` the GUIDSL java application starts and everything seems to work fine:

<img width="667" alt="Annotation 2020-05-10 172231" src="https://user-images.githubusercontent.com/6231523/81503280-419fca80-92d2-11ea-881c-debd6c4f92dc.png">

The model.m was created accordingly when closing GUIDSL

**Comment by Subaro** [comment]
Tested again on release packages. Simply importing Car and opening it afterwards works. However, When I add a feature below USB or CD then the GUIDSL cannot open because of the following message:
```
Cannot have a production USB as a simple pattern
multiple definitions of USB
multiple definitions of _USB
3 error(s) found
Processing terminated
```

`model.m`:
```
Car : Carbody [Radio] Gearbox GearboxTest :: _Car ;

Radio : Ports* [Navigation] [Bluetooth] :: _Radio ;

Ports : USB
	| CD ;

USB : [NewFeature] :: _USB ;

Navigation : [DigitalCards] GPSAntenna :: _Navigation ;

DigitalCards : Europe
	| USA ;

Gearbox : Manual
	| Automatic ;

%%

Navigation implies USB ;
Europe implies Gearbox ;
GPSAntenna implies USB ;
Carbody and Gearbox ;
Gearbox and Radio implies Navigation ;
Carbody implies Automatic and not Bluetooth ;
```

Model:

![grafik](https://user-images.githubusercontent.com/6231523/82200329-5f7eb800-98ee-11ea-9935-4dd552b35ba2.png)

**Comment by h3ssto** [comment]
CNR on *release 3.6`
OS: `5.6.12-arch1-1`
Eclipse: 4.13 (Prepackaged version)
Java: 1.8 (latest)

**Comment by tthuem** [comment]
Cannot reproduce this either. Maybe this was an interaction with my antivirus software on my old PC (which I don't have anymore).
