### ISSUE TITLE
Creation wizard for configurations does not work if configuration folder does not exist

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#926]
#### Prerequisitives
* **Eclipse Version:**  see release packages
* **FeatureIDE-Version:**  v3.6.1
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 201

### Issue description
The wizard does not select the project automatically based on the selected context. Also, pressing finish is impossible. Tested with Automotive02_V4.

The wizard should create the folder, if necessary. Also, all examples should use consistent names for those folders (i.e., configs).

**Comment by skrieter** [comment]
Bug was introduced in v3.6.0.
