### ISSUE TITLE
Feature model editor is not closed if the opened file is deleted

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#927]
#### Prerequisitives
* **Eclipse Version:**  see release packages
* **FeatureIDE-Version:**  v3.6.1
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 201

### Issue description
Opened multiple interfaces and submodels in example Automotive02_V4. When I deleted those, the editor was not closed as common in Eclipse. This has worked in older versions.

**Comment by Subaro** [comment]
The editor will now be closed after the input model is deleted. However, I could not determine whether the functionality was implemented before. The implementation only handled when a project was removed.

**Comment by Subaro** [comment]
Eclipse handles the project and it's files differently. Therefore, merging both blocks seems unreasonable. Closing the issue now.
