### ISSUE TITLE
Export of feature dependency information does not work anymore

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#931]
#### Prerequisitives
* **Eclipse Version:**  see release packages
* **FeatureIDE-Version:**  v3.6.1 (works with v3.5.5)
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 201

### Issue description
![image](https://user-images.githubusercontent.com/5330357/69676514-3436b100-10a1-11ea-99d3-60161bb51333.png)

results in

```
de.ovgu.featureide.fm.core.analysis.mig.ModalImplicationGraph@32d8123b
```

but expected was

```
X ALWAYS Y := If X is selected then Y is selected in every valid configuration.
X MAYBE  Y := If X is selected then Y is selected in at least one but not all valid configurations. 
X NEVER  Y := If X is selected then Y cannot be selected in any valid configuration.

CD ALWAYS Car
CD ALWAYS GPSAntenna
[...]
```

**Comment by skrieter** [comment]
Bug was introduced in v3.6.0.
