### ISSUE TITLE
Plug-In "de.ovgu.featureide.visualisation" is redundant

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#933]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.6`

### Issue description
All classes and functionality of the Plug-In `de.ovgu.featureide.visualisation` are already present in `de.ovgu.featureide.ui`. Both add a menu entry. However, only the menu entry of the `de.ovgu.featureide.ui` works. Thus, we should remove `de.ovgu.featureide.visualisation`.

**Comment by tthuem** [comment]
@jabiercoding Any idea why your functionality is added twice?

**Comment by jabiercoding** [comment]
Hi, no idea. I am quite sure that I did not move it to ``de.ovgu.featureide.ui``. I am more into splitting things in plugins (I use to end up with a lot of them...). Someone probably refactored it. If ``de.ovgu.featureide.ui`` is fine for you then we can remove ``de.ovgu.featureide.visualisation``.

**Comment by Subaro** [comment]
We decided to leave everything in its own plug-in. I fixed the issue that prevented the generation of graphs and removed the redundant code from the `fm.ui` plug-in.
