### ISSUE TITLE
Export of configurations as LaTeX with TikZ

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#934]
### Issue description
Extend the configuration export as LaTeX with new template.

Template for advanced export:
![grafik](https://user-images.githubusercontent.com/6231523/70054052-a857e400-15ce-11ea-8c9e-ac0b8eed66ad.png)

**Comment by tthuem** [comment]
Already implemented:

![image](https://user-images.githubusercontent.com/5330357/71885857-83a9db80-313b-11ea-85a6-0843a9676d13.png)

Still not clear to me why the export is only available in the advanced editor. It should be available in every configurator tab and also in the package and project explorer.
