### ISSUE TITLE
Remove Fuji Support

### ISSUE THREAD

**Issue by skrieter** [FeatureIDE/FeatureIDE#936]
### Issue description
Fuji is not able to run with Java 1.8 or higher. Since FeatureIDE now requires Java 1.8 or higher to run, it is not possible to use Fuji at all. Thus, we should remove support for Fuji all together in the next version to avoid confusion and to clean up the code.

**Comment by skrieter** [comment]
Issues exists since version 3.6.
Related to #928.

**Comment by ekuiter** [comment]
As of v3.8.0, Fuji is removed, so we can close this.
