### ISSUE TITLE
Constraints view does not show constraints for an explanation after a defect was selected.

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#937]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.6`

### Issue description

The constraints view should show all constraints that contain the currently selected feature. In addition, it should show all constraint related to an explanation for the currently selected feature. However, such constraints are omitted.

### Reproduce

1. Import `Car` example and open `model.xml`.
2. Check that the constraints view is open and shows all constraints for the model.
3. Select dead feature `Manual`
4. Constraints view shows not the constraints that make `Manual` void.

### Result

![grafik](https://user-images.githubusercontent.com/6231523/70529275-0e50e800-1b48-11ea-933f-38de1ffc9522.png)

**Comment by PaulWestphal** [comment]
https://github.com/FeatureIDE/FeatureIDE/blob/cd1ad4e173cde398ca6d90d58daf595b054b7f8f/plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/views/constraintview/ConstraintViewController.java#L265-L268

We had decided on showing all constraints that are part of the explanation in the constraint view.
