### ISSUE TITLE
Files in release branch and release jar differ

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#941]
### Issue description

If I download the release jars for version 3.6.0 the java files in the jar differ to the files in the repository under the v3.6.0 tag.
https://featureide.github.io/#download

Exemplarily at file Configuration.java, for example there is in line 200 a clear difference.
https://github.com/FeatureIDE/FeatureIDE/blob/v3.6.0/plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/configuration/Configuration.java

**Comment by SundermannC** [comment]
@tthuem 
The uploaded .jars for release 3.6.0 at https://featureide.github.io/#download and https://github.com/FeatureIDE/FeatureIDE/releases/tag/v3.6.0 are both actually for release 3.5.5 and need to get updated.

**Comment by tthuem** [comment]
@cpwnd Thanks for the report. Something went wrong during the creation of the Jars.

Updated Jars are now available here: https://github.com/FeatureIDE/FeatureIDE/releases/tag/v3.6.0

However, as there is a newer version already available, we decided to not publish an updated version of FeatureIDE v3.6.0. Hence, examples in this version still contain the wrong Jar.
