### ISSUE TITLE
Features show up in feature model editor multiple times.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#943]
This bug is currently in the release3.6 branch. It does not seem to be 100% reproducible but still very common.

1. Load example HelloWorld-Antenna
2. Create new feature below "Beautiful"
3. Save changes
4. Close the feature model editor
5. Reopen the feature model editor

![doublefeature](https://user-images.githubusercontent.com/32126695/71824064-f746dc80-3098-11ea-852d-02bd51cd6b80.png)

Any change to the model will make the feature model editor display it correctly again.

This bug was introduced in FeatureIDE 3.6.0

**Comment by tthuem** [comment]
Several members of the team were not able to reproduce this.
