### ISSUE TITLE
'Calculate Features' and 'Calculate Constraint Errors' checkmarks have no impact 

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#944]
#### Prerequisitives
* **Eclipse Version:**  `2018-09 (4.9)`
* **FeatureIDE-Version:**  `3.6.1 branch`
* **Operating system:** `Ubuntu 18.04`

### Issue description
When analyzing the feature model in the feature model editor, the entire model is always analyzed. 

Reproduction:
1. Create feature model
2. Open feature model editor
3. Deselect 'Calculate Features' and/or 'Calculate Constraint Errors' 
4. Perform change in editor

Expected behavior: For example constraint defects are not computed/shown.
Actual behavior: Entire model is analyzed independent of the selections in 3.

**Comment by Subaro** [comment]
related to #942
