### ISSUE TITLE
Implicit constraints not highlighted when computing hidden dependencies

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#946]
Implicit constraints, dead features, and false-optional features not highlighted when computing hidden dependencies of submodels:

![image](https://user-images.githubusercontent.com/5330357/71885130-0336ab00-313a-11ea-90c1-56aac19d434c.png)

See #920

**Comment by Subaro** [comment]
Fixed the issue. Result:

![grafik](https://user-images.githubusercontent.com/6231523/81505229-4c139180-92dd-11ea-9968-c618b1fca444.png)
