### ISSUE TITLE
Collapse boxes with 10 or more children don't show the number of children.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#947]
This bug is currently on the release3.6 branch.

before collapsing:

![collapsebox1](https://user-images.githubusercontent.com/32126695/71896659-ab596d80-3154-11ea-95b4-4d2694487d7f.png)

after collapsing:

![collapsebox2](https://user-images.githubusercontent.com/32126695/71896676-bb714d00-3154-11ea-94f4-7e7810c39994.png)

This bug was introduced in FeatureIDE 3.6.0

**Comment by PaulWestphal** [comment]
This bug occurs for me every time. Also for features with 100 or more children, while @Subaro does not seem to get the bug at all.

**Comment by Subaro** [comment]
Testes again and can still not reproduce:

![grafik](https://user-images.githubusercontent.com/6231523/81503360-ba9f2200-92d2-11ea-9851-09b9e78e1489.png)

**Comment by PaulWestphal** [comment]
I've tried the following:

- Checked the decorator text of the CollapsedDecoration, it's set correctly.

- Changed the size of the CollapsedDecoration box.

- Changed the font.

But the bug still occured, so I don't know how to continue from here.

**Comment by tthuem** [comment]
Closed as it could not be reproduced
