### ISSUE TITLE
Overlapping feature boxes after introducing new defects

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#951]
#### Prerequisitives
* **Eclipse Version:**  `4.12`
* **FeatureIDE-Version:**  `Release 3.6.0 & release3.6 branch`
* **Operating system:** `Windows 10`

### Issue description
![grafik](https://user-images.githubusercontent.com/24757266/72347394-59769180-36d8-11ea-925f-7396fdcd4c52.png)

The features are not layouted right after the defect flags are set but after another action that forces  re-layouting (e.g. introducing a new feature).

**Comment by h3ssto** [comment]
Is there a "Relayout"-Button / Shortcut (F5?), if not, why not?

**Comment by h3ssto** [comment]
CNR under __OS:__ `Arch Linux 5.4.8-arch1-1`

**Comment by Subaro** [comment]
CNR under OS: Win 10, Eclipse 4.8.0

Steps:
    Imported "Sandwich" Example Model
    Added Constraint "Bread & Toast"

Gui was updated as expected

**Comment by h3ssto** [comment]
@FeatureIDE Could you please also try to reproduce the phenomena at hand, since neither of us could reproduce it.

**Comment by SundermannC** [comment]
@h3ssto @Subaro 
I cannot reproduce it on Eclipse 4.8, but it happens everytime on Eclipse 4.12 with the same procedure as described by @Subaro. Did you test the issue on Eclipse 4. 12?

**Comment by h3ssto** [comment]
> Did you test the issue on Eclipse `4.12`?

Tested it on `4.8` and `4.12`, CNR in both, updated my original comment.

**Comment by SundermannC** [comment]
I cannot reproduce this issue anymore, even on Eclipse 4.12.
