### ISSUE TITLE
"Show Hidden Features" flag cannot be removed

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#961]
#### Prerequisitives
* **Eclipse Version:**  `4.8 and 4.12`
* **FeatureIDE-Version:**  `Release 3.6 branch`
* **Operating system:** `Windows 10`

### Issue description
Clicking "Show Hidden Features" in the feature model editor context menu does nothing.
It does not seem to matter whether there is a hidden feature in the feature model.

![image](https://user-images.githubusercontent.com/24757266/72806805-3870ec00-3c56-11ea-9130-998e093927ff.png)

**Comment by tthuem** [comment]
We decided that this menu entry including all related code should be removed. Hiding features in the configuration should still be possible.

**Comment by PaulWestphal** [comment]
Due to the large amount of code removed, we decided to push these changes to the develop branch for now. 

see 

8fedf4a8d8a29554345995b313f4cd2b783e4f60 

and following commits.

**Comment by PaulWestphal** [comment]
The GUI test verifications had to be changed and caused merge conflicts between the release branch and the develop branch, so I decided to merge this into release3.6 for 3.6.3, as previously planned.
