### ISSUE TITLE
Feature Attributes View not working as intended for Extended Configurations

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#978]
#### Prerequisitives
* **Eclipse Version:**  `4.12`
* **FeatureIDE-Version:**  `Release3.6 Branch`
* **Operating system:** `Windows 10`

### Issue description
![grafik](https://user-images.githubusercontent.com/24757266/75110535-99ae2580-562f-11ea-84a2-ca6d61d2f665.png)
This is always shown when using the feature attribute view while working with an extended configuration.
Expected Behavior:
The attributes of some/all features with the "Configurable"-flag are shown. 
Viable options to decide which features to display I can think of:
(A) all features
(B) all features included in the configuration
(C) only the feature marked by the last click

**Comment by Subaro** [comment]
We found more problems with the attribute view. We refactored the filtering and content provider so that the usage of the configuration editors is intuitive and shows respective messages. We fixed the saving of configurable attributes in extended configurations.
