### ISSUE TITLE
Allow slicing for a selection of multiple features

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#984]
### Issue description
Currently slicing is only allowed for the subtree of one selected feature in the feature model editor.
![grafik](https://user-images.githubusercontent.com/24757266/75165263-66988e80-5722-11ea-8338-3bafd2da1f5c.png)
It makes sense to also allow selecting an arbitrary number of features and create a sliced model with those.

**Comment by tthuem** [comment]
In addition, it would be nice if the slicing criterion (i.e., the selection of features to remain in the model) could be saved somehow. As a simple solution, we could store the selection of such features in a new file format. Another solution would be to let users slice based on attributes defined for an extended feature model. However, then the solution would only be applicable to extended feature models. Ideas and comments are welcome.

**Comment by f105** [comment]
Store the selections in a file sounds good to me. Because we do different slicings: can I store different selections in different files? Upon the next slicing, I would like to either retrieve the selections from one of these files, or make a new selection. Retrieving selections from a file should tolerate missing features (in case they were deleted or renamed in the meantime).

**Comment by tthuem** [comment]
We are planning to allow a selection based on a search. That is, different keywords or hashtags could be added in the description and then the selection can be restored easily. This even works for renamings of features.

**Comment by f105** [comment]
If I understand that correctly, the checkboxes in the slicing dialog can be initialized with the result of a keyword/hashtag search? That's good.
Will it also be possible to save a new selection by providing a keyword/hashtag which would then be added to the descriptions of the selected features?

**Comment by tthuem** [comment]
@f105 Thanks for your feedback.

> If I understand that correctly, the checkboxes in the slicing dialog can be initialized with the result of a keyword/hashtag search? That's good.

We aim to get rid of this extra dialog by integrating the slicing into the feature diagram editor. Indeed, there will be two steps involved: First, automatic selection based on a keyword/hashtag search. Second, selected features can be removed by means of slicing.

> Will it also be possible to save a new selection by providing a keyword/hashtag which would then be added to the descriptions of the selected features?

So far, this was not yet planned, but could be an interesting extension. We'll discuss this new feature in our regular meeting.

**Comment by h3ssto** [comment]
Original issue is fixed by #1087, the enhancements / extensions requested in the comments above will be tracked in #1088.
