### ISSUE TITLE
Export of feature model ignores chosen file option

### ISSUE THREAD

**Issue by h3ssto** [FeatureIDE/FeatureIDE#988]
#### Prerequisitives
Tested on develop, 3.6.2 and on current prepackaged Eclipse.

### Issue description
Open Feature Model (eg. Sandwich / Berkley db)
model.xml -> FeatureIDE > Export Feature Model > eg. DIMACS
File content is XML.

The functionality is working as intended under Release 3.5.5

**Comment by Subaro** [comment]
CNR under __OS:__ `Windows 10`
**Eclipse Versions**: `4.8`

Steps:
1. Imported example "Sandwich"
2. Export feature model as DIMACS via `Export Feature Model`
3. model.dimacs is created with appropriate content

1. Imported example "BerkeleyDB"
2. Export feature model as DIMACS via `Export Feature Model`
3. model.dimacs is created with appropriate content

**Comment by h3ssto** [comment]
This is _not_ a bug in FeatureIDE but a Regression in the GTK called in by Eclipse in FileDialog. Eclipse 4.9.0 is working as intended. This is not an issue under Windows.

### `computeResultChooserDialog()` from Eclipse 4.9.0 (same as in current versions):
```java
String computeResultChooserDialog () {
	//[..]
	filterIndex = -1;
	long /*int*/ filter = GTK.gtk_file_chooser_get_filter (handle);
	if (filter != 0) {
		long /*int*/ filterNamePtr = GTK.gtk_file_filter_get_name (filter);
		if (filterNamePtr != 0) {
			int length = C.strlen (filterNamePtr);
			byte[] buffer = new byte [length];
			C.memmove (buffer, filterNamePtr, length);
			//OS.g_free (filterNamePtr); //GTK owns this pointer - do not free
			String filterName = new String (Converter.mbcsToWcs (buffer));
			for (int i = 0; i < filterExtensions.length; i++) {
				if (filterNames.length > 0) {
					if (filterNames[i].equals(filterName)) {
						filterIndex = i;
						break;
					}
				} else {
					if (filterExtensions[i].equals(filterName)) {
						filterIndex = i;
						break;
					}
				}
			}
		}
       }

//[..]
}
```

**Comment by h3ssto** [comment]
@Subaro Could you please verify if this also is a problem under Windows for Eclipse 4.12/4.13

**Comment by h3ssto** [comment]
We filed a bug in the Eclipse bug tracker https://bugs.eclipse.org/bugs/show_bug.cgi?id=562395
