### ISSUE TITLE
Slicing produces feature model with invalid names.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#997]
The name  "\_\_root\_\_" that is created when slicing a feature model is invalid for the Antenna composer (and most liekly others as well!). You have to change the name of that feature before it can be used.

Is there any particular reason why slicing can't use feature names that are compatible with all composers?

Only this line would have to be changed to ensure compatibility:

https://github.com/FeatureIDE/FeatureIDE/blob/1ec4bbe97e4e13049a0ddcb48a582e302276725f/plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/job/SliceFeatureModel.java#L109

**Comment by tthuem** [comment]
Let's call it "NewRootFeature". Add numbers if possible.

**Comment by PaulWestphal** [comment]
I've moved the getFeatureName method to add numbers from a ui package to a core package. Also both "NewFeature" and "NewRootFeature" now only have a number appended if neccessary.
